; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_cloud=music_data_cloud
.endif

music_data_cloud:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Cloud
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 317,264

.export music_data_cloud
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env6,@env5,@env7,@env0 ; 00 : Noise short
	.word @env1,@env5,@env7,@env0 ; 01 : Noise long
	.word @env13,@env2,@env11,@env0 ; 02 : SqWoobble
	.word @env3,@env5,@env8,@env0 ; 03 : Instrumental 2
	.word @env10,@env4,@env8,@env0 ; 04 : Death effect
	.word @env9,@env5,@env12,@env0 ; 05 : Long instrumental

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cc,$04,$c0,$00,$03
@env2:
	.byte $cc,$cc,$c0,$c0,$00,$00
@env3:
	.byte $00,$cc,$02,$ca,$c3,$c3,$c2,$c0,$00,$07
@env4:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$0a
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $00,$cc,$c0,$00,$02
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $c2,$7f,$00,$00
@env9:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env10:
	.byte $00,$ce,$cc,$cb,$ca,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$0b
@env11:
	.byte $c1,$7f,$00,$00
@env12:
	.byte $c0,$c2,$00,$01
@env13:
	.byte $0c,$ca,$c6,$c7,$c7,$c5,$c7,$c2,$04,$c1,$00,$09,$c1,$c0,$0f,$c0,$00,$0f
@env14:
	.byte $00,$c1,$7f,$00,$02

@samples:
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 00 PERCUSSION 4.dmc (Pitch:15)

@song0ch0:
	.byte $46, $03
@song0ch0loop:
	.byte $7b, $84
@song0ref6:
	.byte $20, $89, $20, $89, $20, $89, $1d, $83, $20, $89, $20, $89, $1d, $83, $20, $83, $1d, $83, $20, $89, $20, $89, $20, $89
	.byte $20, $89, $1b, $83, $20, $89, $20, $89, $1b, $83, $20, $83, $1b, $83, $20, $89
	.byte $41, $28
	.word @song0ref6
@song0ref49:
	.byte $8b, $00, $85, $76, $86
@song0ref54:
	.byte $27, $83, $29, $83, $2c, $83, $00, $83, $2c, $81, $00, $9d, $27, $81, $2c, $83, $00, $83, $a3, $72, $88, $38, $89, $74
	.byte $84, $14, $ad
	.byte $41, $1a
	.word @song0ref49
	.byte $41, $1a
	.word @song0ref49
	.byte $41, $1a
	.word @song0ref49
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $7b, $84
@song0ref96:
	.byte $25, $89, $25, $89, $25, $8f, $27, $83, $00, $83, $27, $8f, $27, $89, $27, $89, $24, $89, $24, $89, $24, $8f, $24, $83
	.byte $00, $83, $24, $8f, $24, $89, $24, $89
	.byte $41, $20
	.word @song0ref96
	.byte $8b, $00, $85, $79
	.byte $41, $12
	.word @song0ref54
@song0ref138:
	.byte $33, $83, $2e, $83, $00, $83, $30, $83, $00, $89, $72, $1b
@song0ref150:
	.byte $73, $81, $81, $74, $81, $81, $75, $81, $81, $76, $81, $81, $77, $81, $81, $78, $81, $81, $79, $81, $81, $78, $8d, $77
	.byte $81, $76, $81, $81, $75, $81, $81, $74, $81, $81, $73, $81, $8b, $00, $85, $79
	.byte $41, $12
	.word @song0ref54
	.byte $2c, $83, $00, $9b, $72, $18
	.byte $41, $1a
	.word @song0ref150
	.byte $79
	.byte $41, $12
	.word @song0ref54
	.byte $41, $25
	.word @song0ref138
	.byte $79
	.byte $41, $12
	.word @song0ref54
	.byte $2c, $83, $00, $9b, $72, $18
	.byte $41, $17
	.word @song0ref150
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $8a
@song0ref227:
	.byte $0d, $89, $25, $89, $0d, $89, $25, $89, $0f, $89, $27, $89, $0f, $89, $27, $89, $14, $89, $20, $89, $14, $89, $20, $89
	.byte $14, $89, $20, $89, $14, $89, $20, $89
	.byte $41, $20
	.word @song0ref227
	.byte $41, $20
	.word @song0ref227
	.byte $41, $20
	.word @song0ref227
	.byte $41, $20
	.word @song0ref227
	.byte $41, $20
	.word @song0ref227
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $7f, $80
@song0ref280:
	.byte $15, $89, $79, $1e, $85, $1e, $81, $76, $82, $1e, $89, $78, $80, $1e, $85, $1e, $81, $7f, $15, $89, $79, $1e, $85, $1e
	.byte $81, $76, $82, $1e, $89, $78, $80, $1e, $85, $1e, $81, $7f
	.byte $41, $18
	.word @song0ref280
	.byte $7f
	.byte $41, $18
	.word @song0ref280
	.byte $7f
	.byte $41, $18
	.word @song0ref280
	.byte $7f
	.byte $41, $18
	.word @song0ref280
	.byte $7f
	.byte $41, $18
	.word @song0ref280
	.byte $7f
	.byte $41, $18
	.word @song0ref280
@song0ref339:
	.byte $15, $89, $1e, $85, $1e, $81, $79, $82, $1e, $89, $7f, $80, $1e, $85, $1e, $81, $15, $89, $1e, $85, $1e, $81, $79, $82
	.byte $1e, $89, $7f, $80, $1e, $85, $1e, $81
	.byte $41, $18
	.word @song0ref280
	.byte $7f
	.byte $41, $18
	.word @song0ref280
	.byte $7f
	.byte $41, $18
	.word @song0ref280
	.byte $41, $18
	.word @song0ref339
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $df, $df, $df, $df
@song0ref393:
	.byte $97, $01, $ad, $01, $95, $97, $01, $ad, $01, $95, $97, $01, $ad, $01, $95, $97, $01, $ad, $01, $95
	.byte $41, $14
	.word @song0ref393
	.byte $42
	.word @song0ch4loop
