; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_enter_in_a_pipe=music_data_enter_in_a_pipe
.endif

music_data_enter_in_a_pipe:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Enter in a pipe
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 325,271

.export music_data_enter_in_a_pipe
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env4,@env7,@env0 ; 00 : Instrumental
	.word @env3,@env4,@env6,@env0 ; 01 : Blank
	.word @env5,@env4,@env6,@env0 ; 02 : Noise short
	.word @env2,@env4,@env6,@env0 ; 03 : Drums Sus

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c8,$c8,$c7,$c6,$c5,$c5,$c4,$c3,$c0,$00,$09
@env2:
	.byte $00,$ce,$cc,$ca,$c8,$c6,$c3,$c2,$00,$07
@env3:
	.byte $00,$cf,$7f,$00,$02
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $00,$cc,$c0,$00,$02
@env6:
	.byte $7f,$00,$00
@env7:
	.byte $c2,$7f,$00,$00
@env8:
	.byte $00,$c1,$7f,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$68,$0f,$40 ; 00 kickcki1.dmc (Pitch:15)

@song0ch0:
	.byte $46, $03, $7c, $80, $1e, $83, $1e, $89, $1e, $89, $1e, $83, $1e, $89, $23, $95, $7d, $24, $95, $26, $95, $7f, $2b, $95
@song0ch0loop:
	.byte $00, $95, $42
	.word @song0ch0loop
@song0ch1:
	.byte $7b, $80, $28, $83, $28, $89, $28, $89, $24, $83, $28, $89, $7c, $2b, $95, $7d, $1f, $95, $23, $95, $7f, $26, $95
@song0ch1loop:
	.byte $00, $95, $42
	.word @song0ch1loop
@song0ch2:
	.byte $82, $0e, $89, $1a, $89, $0e, $89, $1a, $89, $13, $89, $1f, $89, $15, $89, $21, $89, $17, $89, $23, $89, $1a, $89, $26
	.byte $89
@song0ch2loop:
	.byte $00, $95, $42
	.word @song0ch2loop
@song0ch3:
	.byte $84, $20, $89, $20, $83, $20, $89, $20, $83, $20, $89, $86, $21, $00, $81, $74, $1a, $83, $75, $19, $83, $74, $19, $83
	.byte $19, $83, $73, $17, $83, $17, $83, $74, $17, $83, $75, $17, $83, $17, $83, $76, $17, $83, $7a, $17, $83, $7f, $1b, $81
	.byte $00, $1c, $81, $00, $1c, $81, $00, $1c, $81, $00
@song0ch3loop:
	.byte $00, $95, $42
	.word @song0ch3loop
@song0ch4:
	.byte $df, $01, $89, $01, $89, $01, $83, $01, $83, $01, $83, $01, $83
@song0ch4loop:
	.byte $00, $95, $42
	.word @song0ch4loop
