; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_game_over=music_data_game_over
.endif

music_data_game_over:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Game Over
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 296,247

.export music_data_game_over
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env1,@env4,@env0 ; 00 : Long instrumental

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$7f,$00,$01
@env2:
	.byte $7f,$00,$00
@env3:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env4:
	.byte $c0,$c2,$00,$01
@env5:
	.byte $00,$c1,$7f,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$68,$0f,$40 ; 00 kickcki1.dmc (Pitch:15)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 01 PERCUSSION 4.dmc (Pitch:15)

@song0ch0:
	.byte $46, $03, $7c, $80, $1d, $83, $00, $89, $19, $83, $00, $89, $14, $89, $1e, $95, $1b, $95, $1d, $83, $1b, $83, $1d, $a1
	.byte $00, $89
@song0ch0loop:
	.byte $97, $42
	.word @song0ch0loop
@song0ch1:
@song0ref32:
	.byte $7c, $80, $25, $83, $00, $89, $20, $83, $00, $89, $1d, $89, $21, $85, $23, $85, $21, $85, $20, $85, $22, $85, $20, $85
	.byte $20, $b9
@song0ch1loop:
	.byte $97, $42
	.word @song0ch1loop
@song0ch2:
	.byte $41, $0b
	.word @song0ref32
	.byte $95, $23, $95, $25, $b9
@song0ch2loop:
	.byte $97, $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $9b
@song0ch3loop:
	.byte $97, $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $87, $01, $83, $01, $83, $02, $85
@song0ch4loop:
	.byte $97, $42
	.word @song0ch4loop
