; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_in_an_other_castle=music_data_in_an_other_castle
.endif

music_data_in_an_other_castle:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : In an other castle
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 294,245

.export music_data_in_an_other_castle
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env5,@env2,@env6,@env0 ; 00 : Long instrumental
	.word @env3,@env2,@env4,@env0 ; 01 : Noise short
	.word @env1,@env2,@env4,@env0 ; 02 : Drums Sus

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$ce,$cc,$ca,$c8,$c6,$c3,$c2,$00,$07
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $00,$cc,$c0,$00,$02
@env4:
	.byte $7f,$00,$00
@env5:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env6:
	.byte $c0,$c2,$00,$01
@env7:
	.byte $00,$c1,$7f,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$68,$0f,$40 ; 00 kickcki1.dmc (Pitch:15)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 01 PERCUSSION 4.dmc (Pitch:15)

@song0ch0:
	.byte $46, $03, $7c, $80, $1d, $83, $00, $89, $19, $83, $00, $89, $14, $89, $1e, $95, $1b, $95, $1d, $83, $1b, $83, $1d, $a1
	.byte $00, $ff
@song0ch0loop:
	.byte $97, $42
	.word @song0ch0loop
@song0ch1:
	.byte $7c, $80, $25, $83, $00, $89, $20, $83, $00, $89, $1d, $89, $21, $85, $23, $85, $21, $85, $20, $85, $22, $85, $20, $85
	.byte $20, $ff, $af
@song0ch1loop:
	.byte $97, $42
	.word @song0ch1loop
@song0ch2:
	.byte $80, $0d, $89, $19, $89, $0d, $89, $19, $89, $15, $89, $21, $89, $17, $89, $23, $89, $25, $ff, $af
@song0ch2loop:
	.byte $97, $42
	.word @song0ch2loop
@song0ch3:
	.byte $82
@song0ref90:
	.byte $20, $89, $20, $83, $20, $89, $20, $83, $20, $89, $7b, $84, $1a, $81, $00, $81, $74, $1a, $85, $75, $19, $74, $00, $83
	.byte $19, $83, $73, $17, $83, $17, $83, $74, $17, $83, $7f, $82, $20, $89, $20, $83, $20, $89, $20, $83, $20, $83, $20, $83
	.byte $41, $20
	.word @song0ref90
	.byte $8d
@song0ch3loop:
	.byte $97, $42
	.word @song0ch3loop
@song0ch4:
@song0ref147:
	.byte $01, $95, $02, $95, $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $0b
	.word @song0ref147
	.byte $87
@song0ch4loop:
	.byte $97, $42
	.word @song0ch4loop
