; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_waterworld=music_data_waterworld
.endif

music_data_waterworld:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Waterworld
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 325,271

.export music_data_waterworld
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env10,@env5,@env13,@env0 ; 00 : Long instrumental
	.word @env11,@env4,@env9,@env0 ; 01 : Death effect
	.word @env6,@env5,@env8,@env0 ; 02 : Noise short
	.word @env14,@env1,@env12,@env0 ; 03 : SqWoobble
	.word @env3,@env5,@env8,@env0 ; 04 : Blank
	.word @env2,@env7,@env8,@env0 ; 05 : bass1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $cc,$cc,$c0,$c0,$00,$00
@env2:
	.byte $00,$c8,$c8,$c7,$c6,$c5,$c5,$c4,$c3,$c0,$00,$09
@env3:
	.byte $00,$cf,$7f,$00,$02
@env4:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$0a
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $00,$cc,$c0,$00,$02
@env7:
	.byte $bd,$ba,$b7,$b4,$00,$03
@env8:
	.byte $7f,$00,$00
@env9:
	.byte $c2,$7f,$00,$00
@env10:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env11:
	.byte $00,$ce,$cc,$cb,$ca,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$0b
@env12:
	.byte $c1,$7f,$00,$00
@env13:
	.byte $c0,$c2,$00,$01
@env14:
	.byte $0c,$ca,$c6,$c7,$c7,$c5,$c7,$c2,$04,$c1,$00,$09,$c1,$c0,$0f,$c0,$00,$0f
@env15:
	.byte $00,$c1,$7f,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$68,$0f,$40 ; 00 kickcki1.dmc (Pitch:15)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 01 PERCUSSION 4.dmc (Pitch:15)

@song0ch0:
	.byte $46, $03, $80
@song0ref4:
	.byte $19, $85, $18, $85, $17, $85, $16, $85, $17, $85, $18, $85, $19, $81, $19, $81, $19, $81, $00, $81, $1b, $81, $00, $81
	.byte $1c, $91, $00, $81
@song0ch0loop:
	.byte $1e, $95, $1d, $95, $1e, $ad, $1e, $95, $1d, $8d, $20, $85, $1e, $ad, $1c, $95, $1b, $95, $1c, $ad, $1c, $95, $16, $8d
	.byte $20, $85, $1e, $ad, $27, $89, $76, $82, $25, $89, $7f, $80, $25, $89, $76, $82, $25, $89, $7f, $80, $24, $89, $75, $82
	.byte $24, $89, $80, $36, $85, $38, $81, $00, $85, $36, $81, $7f, $25, $89, $75, $82, $25, $89, $7f, $80, $24, $89, $75, $82
	.byte $24, $89, $7f, $80, $23, $89, $75, $82, $23, $89, $80, $34, $85, $36, $81, $00, $85, $34, $81, $7f, $17, $95, $1c, $85
	.byte $1e, $85, $22, $85, $22, $81, $22, $81, $22, $89, $1c, $81, $1b, $95
	.byte $41, $1c
	.word @song0ref4
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $80
@song0ref150:
	.byte $19, $85, $1b, $85, $1d, $85, $1e, $85, $20, $85, $21, $85, $22, $81, $22, $81, $22, $81, $00, $81, $22, $81, $00, $81
	.byte $22, $8d, $1e, $85
@song0ch1loop:
	.byte $27, $95, $26, $95, $27
@song0ref184:
	.byte $99, $1e, $81, $20, $81, $22, $81, $23, $81, $25, $81, $27, $95, $26, $8d, $28, $85, $27, $a9, $1e, $81, $25, $95, $24
	.byte $95, $25
	.byte $41, $09
	.word @song0ref184
	.byte $24, $81, $25, $95, $1e, $8d, $28, $85, $27, $a9, $1e, $81, $2a, $89, $7a, $82, $2a, $89, $7f, $80, $2a, $89, $7a, $82
	.byte $2a, $89, $7f, $80, $2a, $89, $7b, $82, $2a, $89, $7f, $80, $2a, $85, $2c, $81, $00, $85, $2a, $81, $28, $89, $7b, $82
	.byte $28, $89, $7f, $80, $28, $89, $7b, $82, $28, $89, $7f, $80, $28, $89, $7b, $82, $28, $89, $7f, $80, $28, $85, $2a, $81
	.byte $00, $85, $28, $81, $27, $95, $20, $85, $22, $85, $28, $85, $27, $81, $27, $81, $27, $89, $22, $81, $23, $95
	.byte $41, $1c
	.word @song0ref150
	.byte $42
	.word @song0ch1loop
@song0ch2:
	.byte $df
@song0ch2loop:
	.byte $88
@song0ref316:
	.byte $17, $89, $23, $89, $12, $89, $1e, $89, $14, $89, $20, $89, $16, $89, $22, $89
	.byte $41, $10
	.word @song0ref316
@song0ref335:
	.byte $19, $89, $25, $89, $12, $89, $1e, $89
	.byte $41, $08
	.word @song0ref335
	.byte $41, $08
	.word @song0ref335
	.byte $17, $89, $23, $89, $19, $89, $25
@song0ref356:
	.byte $89, $17, $89, $23, $89, $16, $89, $22, $89, $15, $89, $21, $89, $14, $89, $20, $89, $19, $89, $25, $89, $18, $89, $24
	.byte $41, $09
	.word @song0ref356
@song0ref383:
	.byte $0b, $89, $17, $89, $0b, $89, $17, $89
	.byte $41, $08
	.word @song0ref383
	.byte $0d, $89, $19, $89, $11, $89, $1d, $89, $12, $89, $1e, $89, $16, $89, $22, $89, $42
	.word @song0ch2loop
@song0ch3:
	.byte $76, $8a, $1d, $77, $81, $71, $23, $81, $81, $72, $81, $81, $81, $73, $81, $81, $81, $74, $81, $81, $81, $75, $81, $81
	.byte $81, $76, $81, $81, $81, $77, $81, $81, $76, $81, $81, $81, $75, $81, $74, $81, $81, $73, $81, $81, $72, $81, $81, $71
	.byte $81, $81, $81, $93, $70, $85
@song0ch3loop:
	.byte $79, $84
@song0ref470:
	.byte $20, $89, $20, $95, $20, $89, $20
@song0ref477:
	.byte $89, $20, $89, $20, $89, $20, $89, $20, $89, $20, $95, $20, $89, $20, $83, $20, $83, $20, $83, $20, $83, $20, $89, $20
	.byte $83, $20, $83
	.byte $41, $22
	.word @song0ref470
	.byte $41, $15
	.word @song0ref470
	.byte $41, $0e
	.word @song0ref477
	.byte $89, $20, $89, $20, $89, $20, $89, $86, $19, $95, $84, $20, $95, $86, $18, $95, $84, $20, $95, $42
	.word @song0ch3loop
@song0ch4:
	.byte $97, $02, $ad, $02, $85, $02, $85, $02, $85
@song0ch4loop:
@song0ref545:
	.byte $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $08
	.word @song0ref545
	.byte $41, $08
	.word @song0ref545
	.byte $41, $08
	.word @song0ref545
	.byte $41, $08
	.word @song0ref545
	.byte $41, $08
	.word @song0ref545
	.byte $41, $08
	.word @song0ref545
	.byte $01, $95, $02, $95, $01, $95, $02, $85, $02, $85, $02, $85, $42
	.word @song0ch4loop
