; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_disco_mario=music_data_disco_mario
.endif

music_data_disco_mario:
	.byte 14
	.word @instruments
	.word @samples-4
; 00 : Overworld
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 358,298
; 01 : Underworld
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 307,256
; 02 : Waterworld
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word 325,271
; 03 : Castleworld
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word 313,261
; 04 : Cloud
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word 317,264
; 05 : Enter in a pipe
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.word 325,271
; 06 : Starman
	.word @song6ch0
	.word @song6ch1
	.word @song6ch2
	.word @song6ch3
	.word @song6ch4
	.word 266,221
; 07 : Death
	.word @song7ch0
	.word @song7ch1
	.word @song7ch2
	.word @song7ch3
	.word @song7ch4
	.word 307,256
; 08 : Game Over
	.word @song8ch0
	.word @song8ch1
	.word @song8ch2
	.word @song8ch3
	.word @song8ch4
	.word 296,247
; 09 : You saved the princess
	.word @song9ch0
	.word @song9ch1
	.word @song9ch2
	.word @song9ch3
	.word @song9ch4
	.word 313,261
; 0a : In an other castle
	.word @song10ch0
	.word @song10ch1
	.word @song10ch2
	.word @song10ch3
	.word @song10ch4
	.word 294,245
; 0b : Victory
	.word @song11ch0
	.word @song11ch1
	.word @song11ch2
	.word @song11ch3
	.word @song11ch4
	.word 378,315
; 0c : Hurry up
	.word @song12ch0
	.word @song12ch1
	.word @song12ch2
	.word @song12ch3
	.word @song12ch4
	.word 319,266
; 0d : New song
	.word @song13ch0
	.word @song13ch1
	.word @song13ch2
	.word @song13ch3
	.word @song13ch4
	.word 385,320

.export music_data_disco_mario
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env10,@env9,@env13,@env0 ; 00 : Noise short
	.word @env1,@env9,@env13,@env0 ; 01 : Noise long
	.word @env4,@env9,@env13,@env0 ; 02 : Drums Sus
	.word @env15,@env9,@env18,@env0 ; 03 : Long instrumental
	.word @env16,@env8,@env14,@env0 ; 04 : Death effect
	.word @env19,@env2,@env17,@env0 ; 05 : SqWoobble
	.word @env3,@env9,@env14,@env0 ; 06 : Instrumental
	.word @env6,@env9,@env13,@env0 ; 07 : Blank
	.word @env7,@env9,@env14,@env0 ; 08 : Instrumental 2
	.word @env5,@env9,@env13,@env0 ; 09 : Triangle
	.word @env21,@env9,@env14,@env0 ; 0a : Death instrument
	.word @env3,@env11,@env13,@env0 ; 0b : bass1
	.word @env20,@env9,@env13,@env0 ; 0c : Sample Kick
	.word @env12,@env8,@env14,@env0 ; 0d : Death effect 2

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cc,$04,$c0,$00,$03
@env2:
	.byte $cc,$cc,$c0,$c0,$00,$00
@env3:
	.byte $00,$c8,$c8,$c7,$c6,$c5,$c5,$c4,$c3,$c0,$00,$09
@env4:
	.byte $00,$ce,$cc,$ca,$c8,$c6,$c3,$c2,$00,$07
@env5:
	.byte $00,$cf,$07,$c0,$00,$03
@env6:
	.byte $00,$cf,$7f,$00,$02
@env7:
	.byte $00,$cc,$02,$ca,$c3,$c3,$c2,$c0,$00,$07
@env8:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$0a
@env9:
	.byte $c0,$7f,$00,$01
@env10:
	.byte $00,$cc,$c0,$00,$02
@env11:
	.byte $bd,$ba,$b7,$b4,$00,$03
@env12:
	.byte $00,$c8,$c4,$c0,$00,$03
@env13:
	.byte $7f,$00,$00
@env14:
	.byte $c2,$7f,$00,$00
@env15:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env16:
	.byte $00,$ce,$cc,$cb,$ca,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$0b
@env17:
	.byte $c1,$7f,$00,$00
@env18:
	.byte $c0,$c2,$00,$01
@env19:
	.byte $0c,$ca,$c6,$c7,$c7,$c5,$c7,$c2,$04,$c1,$00,$09,$c1,$c0,$0f,$c0,$00,$0f
@env20:
	.byte $00,$c1,$7f,$00,$02
@env21:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c6,$c5,$c3,$c2,$c1,$c0,$00,$0c

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$68,$0f,$40 ; 00 kickcki1.dmc (Pitch:15)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 01 PERCUSSION 4.dmc (Pitch:15)

@song0ch0:
	.byte $46, $03
@song0ch0loop:
	.byte $7c, $8c
@song0ref6:
	.byte $1f, $83, $1f, $89, $1f, $89, $1f, $83, $1f, $89, $24, $95, $7d, $25, $95, $27, $95, $7f, $2c, $95
@song0ref26:
	.byte $1d, $8f, $19, $8f, $14, $8f, $19, $89, $1b, $89, $1a, $83, $19, $89, $19, $85, $20, $85, $24, $85, $25, $89, $22, $83
	.byte $24, $89, $22, $89, $1d, $83, $1e, $83, $1b, $8f
	.byte $41, $22
	.word @song0ref26
@song0ref63:
	.byte $8b, $29, $83, $28, $83, $27, $83, $24, $89, $25, $89, $1d, $83, $1e, $83, $20, $89, $19, $83, $1d, $83, $1e, $83
	.byte $41, $0b
	.word @song0ref63
	.byte $2a, $89, $2a, $83, $2a, $95
	.byte $41, $17
	.word @song0ref63
	.byte $8b, $21, $8f, $1e, $8f, $1d, $ad, $8b, $21, $8f, $1e, $8f, $1d, $ad, $8b, $21, $8f, $1e, $8f, $8a, $1d, $ad, $8c
@song0ref121:
	.byte $21, $83, $21, $89, $21, $89, $21, $83, $23, $89, $20, $83, $1d, $89, $1d, $83, $19, $95, $21, $83, $21, $89, $21, $89
	.byte $21, $83, $23, $83, $20, $b3
	.byte $41, $12
	.word @song0ref121
	.byte $7c
	.byte $41, $12
	.word @song0ref6
@song0ref158:
	.byte $25, $83, $22, $89, $1d, $8f, $1d, $89, $1e, $83, $25, $89, $25, $83, $1e, $95, $20, $85, $2a, $85, $2a, $85, $2a, $85
	.byte $29, $85, $27, $85, $25, $83, $22, $89, $1e, $83, $1d, $95
	.byte $41, $12
	.word @song0ref158
@song0ref197:
	.byte $27, $85, $27, $83, $27, $85, $25, $85, $24, $85, $20, $83, $1d, $89, $1d, $83, $19, $97
	.byte $41, $24
	.word @song0ref158
	.byte $41, $12
	.word @song0ref158
	.byte $41, $12
	.word @song0ref197
	.byte $41, $1e
	.word @song0ref121
	.byte $41, $12
	.word @song0ref121
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref234:
	.byte $7b, $8c, $29, $83, $29, $89, $29, $89, $25, $83, $29, $89, $7c, $2c, $95, $7d, $20, $95, $24, $95, $7f, $27, $95, $8a
@song0ref258:
	.byte $19, $8f, $14, $8f, $11, $8f, $16, $89, $18, $89, $17, $83, $16, $89, $14, $85, $1d, $85, $20, $85, $22, $89, $1e, $83
	.byte $20, $89, $1d, $89, $19, $83, $1b, $83, $18, $8f
	.byte $41, $22
	.word @song0ref258
@song0ref295:
	.byte $8b, $20, $83, $1f, $83, $1e, $83, $1c, $89, $1d, $89, $15, $83, $16, $83, $19, $89, $16, $83, $19, $83, $1b, $83
	.byte $41, $0b
	.word @song0ref295
	.byte $25, $89, $25, $83, $25, $89, $00, $89
	.byte $41, $17
	.word @song0ref295
	.byte $8b, $1c, $8f, $1b, $8f, $19, $8d, $00, $9d, $8b, $1c, $8f, $1b, $8f, $19, $8d, $00, $9d, $8b, $28, $8f, $27, $8f, $25
	.byte $ad
@song0ref357:
	.byte $25, $83, $25, $89, $25, $89, $25, $83, $27, $89, $29, $83, $25, $89, $22, $83, $20, $95, $25, $83, $25, $89, $25, $89
	.byte $25, $83, $27, $83, $29, $b3
	.byte $41, $12
	.word @song0ref357
	.byte $41, $12
	.word @song0ref234
	.byte $8a
@song0ref394:
	.byte $29, $83, $25, $89, $20, $8f, $21, $89, $22, $83, $2a, $89, $2a, $83, $22, $95, $24, $85, $2e, $85, $2e, $85, $2e, $85
	.byte $2c, $85, $2a, $85, $29, $83, $25, $89, $22, $83, $20, $95
	.byte $41, $12
	.word @song0ref394
@song0ref433:
	.byte $2a, $85, $2a, $83, $2a, $85, $29, $85, $27, $85, $25, $af
	.byte $41, $24
	.word @song0ref394
	.byte $41, $12
	.word @song0ref394
	.byte $41, $0c
	.word @song0ref433
	.byte $41, $1e
	.word @song0ref357
	.byte $41, $12
	.word @song0ref357
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $8e
@song0ref465:
	.byte $0f, $89, $1b, $89, $0f, $89, $1b, $89, $14, $89, $20, $89, $16, $89, $22, $89, $18, $89, $24, $89, $1b, $89, $27
@song0ref488:
	.byte $89
@song0ref489:
	.byte $0d, $89, $19, $89, $0d, $89, $19, $89, $0d, $89, $19, $89, $0d, $89, $19, $89, $0d, $89, $19, $89, $11, $89, $1d, $89
	.byte $12, $89, $1e, $89, $13, $89, $20
	.byte $41, $20
	.word @song0ref488
@song0ref523:
	.byte $89, $0d, $89, $19, $89, $0d, $89, $19, $89, $12, $89, $1e, $89, $14, $89, $20, $89, $0d, $89, $19, $89, $0d, $89, $19
	.byte $89, $12, $83, $00, $89, $14, $83, $20, $89, $14
	.byte $41, $11
	.word @song0ref523
@song0ref560:
	.byte $15, $89, $21, $89, $17, $89, $23, $89, $19, $89, $25, $89, $19, $89, $25, $89
	.byte $41, $10
	.word @song0ref560
	.byte $41, $10
	.word @song0ref560
@song0ref582:
	.byte $15, $89, $21, $89, $15, $89, $21, $89, $0d, $89, $19, $89, $0d, $89, $19, $89
	.byte $41, $10
	.word @song0ref582
	.byte $41, $10
	.word @song0ref582
	.byte $41, $18
	.word @song0ref465
	.byte $84
	.byte $41, $14
	.word @song0ref489
	.byte $41, $14
	.word @song0ref489
@song0ref614:
	.byte $0d, $89, $19, $89, $0d, $89, $19, $89, $14, $89, $20, $89, $16, $89, $24, $89, $19, $89, $25, $89, $19, $89, $25
	.byte $41, $15
	.word @song0ref488
	.byte $41, $14
	.word @song0ref489
	.byte $41, $17
	.word @song0ref614
	.byte $89, $8e
	.byte $41, $10
	.word @song0ref582
	.byte $41, $10
	.word @song0ref582
	.byte $41, $10
	.word @song0ref582
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $7f, $80
@song0ref663:
	.byte $20, $89, $20, $83, $20, $89, $20, $83, $20, $89, $84, $21, $00, $81, $74, $1a, $83, $75, $19, $83, $74, $19, $83, $19
	.byte $83, $73, $17, $83, $17, $83, $74, $17, $83, $75
@song0ref697:
	.byte $17, $83, $17, $83, $76, $17, $83, $7a
@song0ref705:
	.byte $17, $83, $7f, $1b, $81, $00, $1c, $81, $00, $1c, $81, $00, $1c, $81, $00
@song0ref720:
	.byte $82, $14, $00, $87, $80, $20, $85, $20, $81, $82, $20, $89, $80, $20, $85, $20, $81
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
@song0ref758:
	.byte $82, $14, $00
@song0ref761:
	.byte $81, $80, $20, $83, $20, $83, $20, $83, $7b, $84, $19, $83, $7f, $80, $20, $83, $20, $83, $20, $83
	.byte $41, $11
	.word @song0ref758
	.byte $41, $11
	.word @song0ref758
@song0ref787:
	.byte $82, $14, $00, $81, $14, $00, $81, $80, $20, $83, $82, $14, $00, $81, $7b, $84, $19, $83, $7f, $80, $20, $83, $20, $83
	.byte $20, $83
	.byte $41, $11
	.word @song0ref758
	.byte $41, $11
	.word @song0ref758
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $84, $21, $83, $74, $18, $83, $75, $18, $83, $74, $18, $83, $18, $83, $73, $17, $83, $17, $83, $74, $17, $83, $7f, $82
	.byte $14, $00, $81, $75, $84, $17, $83, $17, $83, $76
	.byte $41, $10
	.word @song0ref705
	.byte $41, $0f
	.word @song0ref761
	.byte $41, $13
	.word @song0ref787
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $41, $31
	.word @song0ref663
	.byte $41, $0f
	.word @song0ref761
	.byte $41, $13
	.word @song0ref787
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $41, $11
	.word @song0ref758
	.byte $41, $11
	.word @song0ref758
	.byte $41, $11
	.word @song0ref758
	.byte $41, $11
	.word @song0ref758
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $75, $84
	.byte $41, $16
	.word @song0ref697
	.byte $41, $0f
	.word @song0ref761
@song0ref939:
	.byte $82, $14, $00, $81, $80, $20, $83, $20, $83, $20, $83, $84, $18, $81, $00, $85, $80, $20, $83, $20, $83
	.byte $41, $0c
	.word @song0ref939
	.byte $80, $20, $83, $20, $83, $20, $83
	.byte $41, $11
	.word @song0ref939
	.byte $41, $0c
	.word @song0ref939
	.byte $80, $20, $83, $20, $83, $20, $83
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref993:
	.byte $01, $89, $00, $89, $01, $89, $00, $89
@song0ref1001:
	.byte $01, $95, $01, $95, $01, $89, $01, $89, $01, $83, $01, $83, $01, $83, $01, $83
@song0ref1017:
	.byte $01, $95, $01, $95, $01, $95, $01, $95, $01, $95, $01, $95
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $01, $95, $01, $95, $01, $95, $01, $95
	.byte $41, $24
	.word @song0ref993
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $01, $95, $01, $95
	.byte $41, $1c
	.word @song0ref1001
	.byte $41, $0c
	.word @song0ref1017
	.byte $01, $95, $01, $95, $42
	.word @song0ch4loop
@song1ch0:
	.byte $46, $04
@song1ch0loop:
@song1ref4:
	.byte $76, $92
@song1ref6:
	.byte $01, $83, $0d, $83, $40, $0a, $83, $0a, $83, $40, $0b, $83, $0b, $bf
	.byte $41, $0c
	.word @song1ref6
@song1ref23:
	.byte $06, $83, $12, $83, $03, $83, $0f, $83, $04, $83, $10, $bf
	.byte $41, $0c
	.word @song1ref23
	.byte $41, $0b
	.word @song1ref6
	.byte $83, $71, $88, $1f, $83, $8a, $1f
@song1ref48:
	.byte $81, $83, $73, $83, $74, $83, $75, $83, $76, $83, $7a, $83, $7b, $83, $7c, $83, $7d, $83, $7f, $83, $74, $83, $70, $83
	.byte $81
	.byte $41, $0b
	.word @song1ref4
	.byte $83, $71, $88, $23, $83, $8a, $23
	.byte $41, $0e
	.word @song1ref48
	.byte $76, $92
	.byte $41, $0b
	.word @song1ref23
	.byte $83, $71, $88, $2f, $83, $8a, $15
	.byte $41, $0e
	.word @song1ref48
	.byte $76, $92
	.byte $41, $0b
	.word @song1ref23
	.byte $83, $71, $88, $2f, $83, $8a, $21
	.byte $41, $0a
	.word @song1ref48
	.byte $7f, $81, $7a, $8c, $1c, $81, $1b, $81, $1a, $81, $19, $89, $1c, $89, $1b, $89, $15, $89, $14, $89, $1a, $89, $19, $81
	.byte $1f, $81, $1e, $81, $1d, $81, $23, $81, $22, $81, $21, $85, $1c, $85, $18, $85, $17, $85, $16, $85, $15, $85, $71, $8a
	.byte $1b
	.byte $41, $0a
	.word @song1ref48
	.byte $7f, $87, $70, $af, $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
@song1ref176:
	.byte $7f, $8c
@song1ref178:
	.byte $19, $83, $25
@song1ref181:
	.byte $83, $16, $83, $22, $83, $17, $83, $23, $bf
	.byte $41, $0c
	.word @song1ref178
@song1ref193:
	.byte $12, $83, $1e, $83, $0f, $83, $1b, $83, $10, $83, $1c, $bf
	.byte $41, $0c
	.word @song1ref193
	.byte $41, $0b
	.word @song1ref178
	.byte $83, $71, $88, $28, $83, $8a, $28
@song1ref218:
	.byte $81, $83, $73, $83, $74, $83, $75, $83, $76, $83, $79, $83, $7a, $83, $7c, $83, $7d, $83, $7f, $83, $74, $83, $71, $83
	.byte $70, $81
	.byte $41, $0b
	.word @song1ref176
	.byte $83, $71, $88, $2c, $83, $8a, $2c
	.byte $41, $0e
	.word @song1ref218
	.byte $78, $8c
	.byte $41, $0b
	.word @song1ref193
	.byte $83, $71, $88, $2c, $83, $8a, $1e
	.byte $41, $0e
	.word @song1ref218
	.byte $79, $8c
	.byte $41, $0b
	.word @song1ref193
	.byte $83, $71, $88, $2c, $83, $8a, $1e
	.byte $41, $0a
	.word @song1ref218
	.byte $7f, $81, $7b, $8c, $28, $81, $27, $81, $26, $81, $25, $89, $28, $89, $27, $89, $21, $89, $20, $89, $26, $89, $25, $81
	.byte $2b, $81, $2a, $81, $29, $81, $2f, $81, $2e, $81, $2d, $85, $28, $85, $24, $85, $23, $85, $22, $85, $21, $85, $71, $8a
	.byte $20
	.byte $41, $0a
	.word @song1ref218
	.byte $7f, $87, $70, $af, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $86
	.byte $41, $0b
	.word @song1ref178
	.byte $83, $18, $83, $19, $83
	.byte $41, $0b
	.word @song1ref178
	.byte $83, $18, $83, $24, $83
	.byte $41, $0b
	.word @song1ref178
	.byte $83, $18, $83, $19, $83
	.byte $41, $0b
	.word @song1ref178
	.byte $83, $18, $83, $24, $83
	.byte $41, $0b
	.word @song1ref193
	.byte $83, $11, $83, $12, $83
	.byte $41, $0b
	.word @song1ref193
	.byte $83, $11, $83, $1d, $83
	.byte $41, $0b
	.word @song1ref193
	.byte $83, $11, $83, $12, $83
	.byte $41, $0b
	.word @song1ref193
	.byte $83, $11, $83, $1d, $83
	.byte $41, $0b
	.word @song1ref178
	.byte $83, $18, $83, $19, $83
	.byte $41, $0b
	.word @song1ref178
	.byte $83, $18, $83, $24, $83
	.byte $41, $0b
	.word @song1ref178
	.byte $83, $18, $83, $19, $83
	.byte $41, $0b
	.word @song1ref178
	.byte $83, $18, $83, $24, $83
	.byte $41, $0b
	.word @song1ref193
	.byte $83, $11, $83, $12, $83
	.byte $41, $0b
	.word @song1ref193
	.byte $83, $11, $83, $1d, $83
	.byte $41, $0b
	.word @song1ref193
	.byte $83, $11, $83, $12, $83
	.byte $41, $0b
	.word @song1ref193
	.byte $83, $1b, $83, $1a, $83, $19, $83, $25, $83, $19, $83, $25, $83, $17, $83, $23, $83, $17, $83, $23, $83, $16, $83, $22
	.byte $83, $16, $83, $22, $83, $15, $83, $21, $83, $15, $83, $21, $83, $14, $83, $20, $83, $14, $83, $20, $83, $14, $83, $20
	.byte $83, $14, $83, $14, $83, $14, $83, $20, $83, $11, $83, $1d, $83, $12, $83, $1e, $83, $13, $83, $14, $83, $14, $83, $20
	.byte $41, $08
	.word @song1ref181
	.byte $83, $18, $83, $24, $83, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $7f, $80
@song1ref557:
	.byte $14
@song1ref558:
	.byte $00, $81, $73, $1f, $83
@song1ref563:
	.byte $1f, $83
@song1ref565:
	.byte $1f, $83, $7f, $1d, $83, $73, $1f, $83, $1f, $83, $1f, $83, $7f, $14, $83, $7d, $15, $00, $81, $7f, $14, $83, $73
	.byte $41, $0b
	.word @song1ref565
	.byte $41, $17
	.word @song1ref558
	.byte $73
	.byte $41, $0b
	.word @song1ref565
	.byte $41, $17
	.word @song1ref558
	.byte $73
	.byte $41, $0b
	.word @song1ref565
	.byte $41, $17
	.word @song1ref558
	.byte $73
	.byte $41, $0c
	.word @song1ref565
	.byte $73, $1f, $1f, $81
	.byte $41, $0a
	.word @song1ref563
@song1ref619:
	.byte $7f, $14, $83, $74, $1f, $83, $7d, $15, $00, $81, $7f, $14, $83, $73
	.byte $41, $0c
	.word @song1ref565
	.byte $73, $1f, $1f, $81
	.byte $41, $0a
	.word @song1ref563
	.byte $41, $09
	.word @song1ref619
	.byte $73
	.byte $41, $0b
	.word @song1ref565
	.byte $41, $17
	.word @song1ref558
	.byte $73
	.byte $41, $0b
	.word @song1ref565
	.byte $41, $17
	.word @song1ref558
	.byte $73
	.byte $41, $0b
	.word @song1ref565
	.byte $41, $17
	.word @song1ref558
	.byte $73, $1f, $83, $7b, $1d, $81, $1d, $81, $1d, $81, $1d, $81, $1d, $81, $7f, $1d, $81
	.byte $41, $18
	.word @song1ref557
	.byte $73
	.byte $41, $0b
	.word @song1ref565
	.byte $41, $10
	.word @song1ref558
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref698:
	.byte $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $08
	.word @song1ref698
	.byte $41, $08
	.word @song1ref698
	.byte $41, $08
	.word @song1ref698
@song1ref715:
	.byte $01, $89, $00, $89, $02, $95, $01, $89, $00, $89, $02, $95
	.byte $41, $0c
	.word @song1ref715
	.byte $41, $0c
	.word @song1ref715
	.byte $41, $0c
	.word @song1ref715
@song1ref736:
	.byte $01, $89, $02, $89, $01, $89, $02, $89
	.byte $41, $08
	.word @song1ref736
	.byte $41, $08
	.word @song1ref736
	.byte $41, $08
	.word @song1ref736
	.byte $41, $08
	.word @song1ref736
	.byte $42
	.word @song1ch4loop
@song2ch0:
	.byte $46, $03, $86
@song2ref4:
	.byte $19, $85, $18, $85, $17, $85, $16, $85, $17, $85, $18, $85, $19, $81, $19, $81, $19, $81, $00, $81, $1b, $81, $00, $81
	.byte $1c, $91, $00, $81
@song2ch0loop:
	.byte $1e, $95, $1d, $95, $1e, $ad, $1e, $95, $1d, $8d, $20, $85, $1e, $ad, $1c, $95, $1b, $95, $1c, $ad, $1c, $95, $16, $8d
	.byte $20, $85, $1e, $ad, $27, $89, $76, $88, $25, $89, $7f, $86, $25, $89, $76, $88, $25, $89, $7f, $86, $24, $89, $75, $88
	.byte $24, $89, $86, $36, $85, $38, $81, $00, $85, $36, $81, $7f, $25, $89, $75, $88, $25, $89, $7f, $86, $24, $89, $75, $88
	.byte $24, $89, $7f, $86, $23, $89, $75, $88, $23, $89, $86, $34, $85, $36, $81, $00, $85, $34, $81, $7f, $17, $95, $1c, $85
	.byte $1e, $85, $22, $85, $22, $81, $22, $81, $22, $89, $1c, $81, $1b, $95
	.byte $41, $1c
	.word @song2ref4
	.byte $42
	.word @song2ch0loop
@song2ch1:
	.byte $86
@song2ref150:
	.byte $19, $85, $1b, $85, $1d, $85, $1e, $85, $20, $85, $21, $85, $22, $81, $22, $81, $22, $81, $00, $81, $22, $81, $00, $81
	.byte $22, $8d, $1e, $85
@song2ch1loop:
	.byte $27, $95, $26, $95, $27
@song2ref184:
	.byte $99, $1e, $81, $20, $81, $22, $81, $23, $81, $25, $81, $27, $95, $26, $8d, $28, $85, $27, $a9, $1e, $81, $25, $95, $24
	.byte $95, $25
	.byte $41, $09
	.word @song2ref184
	.byte $24, $81, $25, $95, $1e, $8d, $28, $85, $27, $a9, $1e, $81, $2a, $89, $7a, $88, $2a, $89, $7f, $86, $2a, $89, $7a, $88
	.byte $2a, $89, $7f, $86, $2a, $89, $7b, $88, $2a, $89, $7f, $86, $2a, $85, $2c, $81, $00, $85, $2a, $81, $28, $89, $7b, $88
	.byte $28, $89, $7f, $86, $28, $89, $7b, $88, $28, $89, $7f, $86, $28, $89, $7b, $88, $28, $89, $7f, $86, $28, $85, $2a, $81
	.byte $00, $85, $28, $81, $27, $95, $20, $85, $22, $85, $28, $85, $27, $81, $27, $81, $27, $89, $22, $81, $23, $95
	.byte $41, $1c
	.word @song2ref150
	.byte $42
	.word @song2ch1loop
@song2ch2:
	.byte $df
@song2ch2loop:
	.byte $8e
@song2ref316:
	.byte $17, $89, $23, $89, $12, $89, $1e, $89, $14, $89, $20, $89, $16, $89, $22, $89
	.byte $41, $10
	.word @song2ref316
@song2ref335:
	.byte $19, $89, $25, $89, $12, $89, $1e, $89
	.byte $41, $08
	.word @song2ref335
	.byte $41, $08
	.word @song2ref335
	.byte $17, $89, $23, $89, $19, $89, $25
@song2ref356:
	.byte $89, $17, $89, $23, $89, $16, $89, $22, $89, $15, $89, $21, $89, $14, $89, $20, $89, $19, $89, $25, $89, $18, $89, $24
	.byte $41, $09
	.word @song2ref356
@song2ref383:
	.byte $0b, $89, $17, $89, $0b, $89, $17, $89
	.byte $41, $08
	.word @song2ref383
	.byte $0d, $89, $19, $89, $11, $89, $1d, $89, $12, $89, $1e, $89, $16, $89, $22, $89, $42
	.word @song2ch2loop
@song2ch3:
	.byte $76, $96, $1d, $77, $81, $71, $23, $81, $81, $72, $81, $81, $81, $73, $81, $81, $81, $74, $81, $81, $81, $75, $81, $81
	.byte $81, $76, $81, $81, $81, $77, $81, $81, $76, $81, $81, $81, $75, $81, $74, $81, $81, $73, $81, $81, $72, $81, $81, $71
	.byte $81, $81, $81, $93, $70, $85
@song2ch3loop:
	.byte $79, $80
@song2ref470:
	.byte $20, $89, $20, $95, $20, $89, $20
@song2ref477:
	.byte $89, $20, $89, $20, $89, $20, $89, $20, $89, $20, $95, $20, $89, $20, $83, $20, $83, $20, $83, $20, $83, $20, $89, $20
	.byte $83, $20, $83
	.byte $41, $22
	.word @song2ref470
	.byte $41, $15
	.word @song2ref470
	.byte $41, $0e
	.word @song2ref477
	.byte $89, $20, $89, $20, $89, $20, $89, $8a, $19, $95, $80, $20, $95, $8a, $18, $95, $80, $20, $95, $42
	.word @song2ch3loop
@song2ch4:
	.byte $97, $02, $ad, $02, $85, $02, $85, $02, $85
@song2ch4loop:
@song2ref545:
	.byte $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $08
	.word @song2ref545
	.byte $41, $08
	.word @song2ref545
	.byte $41, $08
	.word @song2ref545
	.byte $41, $08
	.word @song2ref545
	.byte $41, $08
	.word @song2ref545
	.byte $41, $08
	.word @song2ref545
	.byte $01, $95, $02, $95, $01, $95, $02, $85, $02, $85, $02, $85, $42
	.word @song2ch4loop
@song3ch0:
	.byte $46, $05
@song3ch0loop:
	.byte $81, $76, $8c
@song3ref7:
	.byte $1b, $81, $1a, $81, $19, $81, $1a, $81, $1b, $81, $1c, $81, $1b, $81, $1a, $81
	.byte $41, $10
	.word @song3ref7
	.byte $74
@song3ref27:
	.byte $27, $81, $26, $81, $25, $81, $26, $81, $27, $81, $28, $81, $27, $81, $26, $81
	.byte $41, $10
	.word @song3ref27
	.byte $77
	.byte $41, $10
	.word @song3ref7
	.byte $41, $10
	.word @song3ref7
@song3ref53:
	.byte $1a, $81, $19, $81, $1a, $81, $1b, $81, $1a, $81, $1b, $81, $1a, $81, $19, $81
	.byte $41, $10
	.word @song3ref53
	.byte $98
@song3ref73:
	.byte $1e, $81, $1f, $81, $1e, $81, $1d, $81, $1e, $81, $1d, $81, $1c, $81, $1d, $81
	.byte $41, $0f
	.word @song3ref73
	.byte $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $76, $94
	.byte $41, $10
	.word @song3ref7
	.byte $41, $10
	.word @song3ref7
	.byte $78
	.byte $41, $10
	.word @song3ref7
	.byte $41, $10
	.word @song3ref7
	.byte $79
	.byte $41, $10
	.word @song3ref7
	.byte $41, $10
	.word @song3ref7
	.byte $41, $10
	.word @song3ref53
	.byte $41, $10
	.word @song3ref53
	.byte $41, $10
	.word @song3ref73
	.byte $41, $10
	.word @song3ref73
	.byte $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $00, $bd, $bf, $8e, $10, $9d, $0f, $8d, $13, $8d, $12, $9d, $11, $8d, $17, $8d, $16, $8d, $11, $8d, $10, $8d, $11, $8d
	.byte $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
	.byte $7f, $84, $14, $00, $8b, $79, $1d, $81, $00, $89, $7f, $14, $00, $8b, $79, $1d, $81, $00, $89, $78, $14, $00, $14, $00
	.byte $1b, $81, $1b, $81, $14, $00, $79, $14, $00, $1b, $7a, $81, $1b, $81, $7b, $14, $00, $14, $7c, $00, $1b, $81, $1b, $81
	.byte $7f, $1b, $81, $1b, $81, $1b, $81, $1b, $81
@song3ref219:
	.byte $14, $00, $83, $76, $1b, $81, $1b, $81, $79, $1d, $81, $00, $81, $1b, $85, $7f, $14, $00, $83, $77, $1b, $81, $00, $81
	.byte $1d, $85, $1b, $85, $7f
	.byte $41, $18
	.word @song3ref219
	.byte $7f
	.byte $41, $18
	.word @song3ref219
	.byte $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $bf, $01, $8d, $01, $8d, $01, $81, $01, $81, $01, $81, $01, $81, $01, $81, $01, $81, $01, $81, $01, $81
@song3ref280:
	.byte $01, $8d, $01, $8d, $01, $8d, $01, $8d, $01, $8d, $01, $8d
	.byte $41, $0c
	.word @song3ref280
	.byte $42
	.word @song3ch4loop
@song4ch0:
	.byte $46, $03
@song4ch0loop:
	.byte $7b, $8a
@song4ref6:
	.byte $20, $89, $20, $89, $20, $89, $1d, $83, $20, $89, $20, $89, $1d, $83, $20, $83, $1d, $83, $20, $89, $20, $89, $20, $89
	.byte $20, $89, $1b, $83, $20, $89, $20, $89, $1b, $83, $20, $83, $1b, $83, $20, $89
	.byte $41, $28
	.word @song4ref6
@song4ref49:
	.byte $8b, $00, $85, $76, $90
@song4ref54:
	.byte $27, $83, $29, $83, $2c, $83, $00, $83, $2c, $81, $00, $9d, $27, $81, $2c, $83, $00, $83, $a3, $72, $88, $38, $89, $74
	.byte $8a, $14, $ad
	.byte $41, $1a
	.word @song4ref49
	.byte $41, $1a
	.word @song4ref49
	.byte $41, $1a
	.word @song4ref49
	.byte $42
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $7b, $8a
@song4ref96:
	.byte $25, $89, $25, $89, $25, $8f, $27, $83, $00, $83, $27, $8f, $27, $89, $27, $89, $24, $89, $24, $89, $24, $8f, $24, $83
	.byte $00, $83, $24, $8f, $24, $89, $24, $89
	.byte $41, $20
	.word @song4ref96
	.byte $8b, $00, $85, $79
	.byte $41, $12
	.word @song4ref54
@song4ref138:
	.byte $33, $83, $2e, $83, $00, $83, $30, $83, $00, $89, $72, $1b
@song4ref150:
	.byte $73, $81, $81, $74, $81, $81, $75, $81, $81, $76, $81, $81, $77, $81, $81, $78, $81, $81, $79, $81, $81, $78, $8d, $77
	.byte $81, $76, $81, $81, $75, $81, $81, $74, $81, $81, $73, $81, $8b, $00, $85, $79
	.byte $41, $12
	.word @song4ref54
	.byte $2c, $83, $00, $9b, $72, $18
	.byte $41, $1a
	.word @song4ref150
	.byte $79
	.byte $41, $12
	.word @song4ref54
	.byte $41, $25
	.word @song4ref138
	.byte $79
	.byte $41, $12
	.word @song4ref54
	.byte $2c, $83, $00, $9b, $72, $18
	.byte $41, $17
	.word @song4ref150
	.byte $42
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $86
@song4ref227:
	.byte $0d, $89, $25, $89, $0d, $89, $25, $89, $0f, $89, $27, $89, $0f, $89, $27, $89, $14, $89, $20, $89, $14, $89, $20, $89
	.byte $14, $89, $20, $89, $14, $89, $20, $89
	.byte $41, $20
	.word @song4ref227
	.byte $41, $20
	.word @song4ref227
	.byte $41, $20
	.word @song4ref227
	.byte $41, $20
	.word @song4ref227
	.byte $41, $20
	.word @song4ref227
	.byte $42
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
	.byte $7f, $80
@song4ref280:
	.byte $15, $89, $79, $1e, $85, $1e, $81, $76, $82, $1e, $89, $78, $80, $1e, $85, $1e, $81, $7f, $15, $89, $79, $1e, $85, $1e
	.byte $81, $76, $82, $1e, $89, $78, $80, $1e, $85, $1e, $81, $7f
	.byte $41, $18
	.word @song4ref280
	.byte $7f
	.byte $41, $18
	.word @song4ref280
	.byte $7f
	.byte $41, $18
	.word @song4ref280
	.byte $7f
	.byte $41, $18
	.word @song4ref280
	.byte $7f
	.byte $41, $18
	.word @song4ref280
	.byte $7f
	.byte $41, $18
	.word @song4ref280
@song4ref339:
	.byte $15, $89, $1e, $85, $1e, $81, $79, $82, $1e, $89, $7f, $80, $1e, $85, $1e, $81, $15, $89, $1e, $85, $1e, $81, $79, $82
	.byte $1e, $89, $7f, $80, $1e, $85, $1e, $81
	.byte $41, $18
	.word @song4ref280
	.byte $7f
	.byte $41, $18
	.word @song4ref280
	.byte $7f
	.byte $41, $18
	.word @song4ref280
	.byte $41, $18
	.word @song4ref339
	.byte $42
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
	.byte $df, $df, $df, $df
@song4ref393:
	.byte $97, $02, $ad, $02, $95, $97, $02, $ad, $02, $95, $97, $02, $ad, $02, $95, $97, $02, $ad, $02, $95
	.byte $41, $14
	.word @song4ref393
	.byte $42
	.word @song4ch4loop
@song5ch0:
	.byte $46, $03, $7c, $8c, $1e, $83, $1e, $89, $1e, $89, $1e, $83, $1e, $89, $23, $95, $7d, $24, $95, $26, $95, $7f, $2b, $95
@song5ch0loop:
	.byte $00, $95, $42
	.word @song5ch0loop
@song5ch1:
	.byte $7b, $8c, $28, $83, $28, $89, $28, $89, $24, $83, $28, $89, $7c, $2b, $95, $7d, $1f, $95, $23, $95, $7f, $26, $95
@song5ch1loop:
	.byte $00, $95, $42
	.word @song5ch1loop
@song5ch2:
	.byte $8e, $0e, $89, $1a, $89, $0e, $89, $1a, $89, $13, $89, $1f, $89, $15, $89, $21, $89, $17, $89, $23, $89, $1a, $89, $26
	.byte $89
@song5ch2loop:
	.byte $00, $95, $42
	.word @song5ch2loop
@song5ch3:
	.byte $80, $20, $89, $20, $83, $20, $89, $20, $83, $20, $89, $84, $21, $00, $81, $74, $1a, $83, $75, $19, $83, $74, $19, $83
	.byte $19, $83, $73, $17, $83, $17, $83, $74, $17, $83, $75, $17, $83, $17, $83, $76, $17, $83, $7a, $17, $83, $7f, $1b, $81
	.byte $00, $1c, $81, $00, $1c, $81, $00, $1c, $81, $00
@song5ch3loop:
	.byte $00, $95, $42
	.word @song5ch3loop
@song5ch4:
	.byte $df, $01, $89, $01, $89, $01, $83, $01, $83, $01, $83, $01, $83
@song5ch4loop:
	.byte $00, $95, $42
	.word @song5ch4loop
@song6ch0:
	.byte $46, $02
@song6ch0loop:
	.byte $7a, $8a
@song6ref6:
	.byte $21, $89, $21, $89, $21, $89, $1e, $83, $21, $89, $21, $89, $1e, $83, $21, $83, $1e, $83, $21, $89, $21, $89, $21, $89
	.byte $21, $89, $1c, $83, $21, $89, $21, $89, $1c, $83, $21, $83, $1c, $83, $21, $89
	.byte $41, $28
	.word @song6ref6
	.byte $42
	.word @song6ch0loop
@song6ch1:
@song6ch1loop:
	.byte $7d, $8a
@song6ref55:
	.byte $1a, $89, $1a, $89, $1a, $8f, $1c, $83, $00, $83, $1c, $8f, $1c, $89, $1c, $89, $19, $89, $19, $89, $19, $8f, $19, $83
	.byte $00, $83, $19, $8f, $19, $89, $19, $89
	.byte $41, $20
	.word @song6ref55
	.byte $42
	.word @song6ch1loop
@song6ch2:
@song6ch2loop:
	.byte $86
@song6ref95:
	.byte $0e, $89, $26, $89, $0e, $89, $26, $89, $10, $89, $28, $89, $10, $89, $28, $89, $15, $89, $21, $89, $15, $89, $21, $89
	.byte $15, $89, $21, $89, $15, $89, $21, $89
	.byte $41, $20
	.word @song6ref95
	.byte $42
	.word @song6ch2loop
@song6ch3:
@song6ch3loop:
	.byte $7f, $80
@song6ref136:
	.byte $15, $89, $79, $1e, $85, $1e, $81, $76, $82, $1e, $89, $78, $80, $1e, $85, $1e, $81, $7f, $15, $89, $79, $1e, $85, $1e
	.byte $81, $76, $82, $1e, $89, $78, $80, $1e, $85, $1e, $81, $7f
	.byte $41, $18
	.word @song6ref136
	.byte $7f
	.byte $41, $18
	.word @song6ref136
	.byte $7f
	.byte $41, $18
	.word @song6ref136
	.byte $42
	.word @song6ch3loop
@song6ch4:
@song6ch4loop:
	.byte $df, $df, $df, $df, $42
	.word @song6ch4loop
@song7ch0:
	.byte $46, $03, $7a, $88, $22, $23, $24, $9a, $21, $8f, $7b, $90, $1b, $83, $22, $89, $22, $83, $22, $85, $20, $85, $1b, $85
	.byte $88, $1f, $83, $1c, $89, $1c, $83, $18, $8f
@song7ch0loop:
	.byte $97, $42
	.word @song7ch0loop
@song7ch1:
	.byte $97, $7b, $94, $24, $83, $2a, $89, $2a, $83, $2a, $85, $29, $85, $27, $85, $25, $a7
@song7ch1loop:
	.byte $97, $42
	.word @song7ch1loop
@song7ch2:
	.byte $97, $86, $14, $89, $20, $89, $14, $89, $20, $89, $0d, $89, $19, $89, $0d, $85, $00, $87
@song7ch2loop:
	.byte $97, $42
	.word @song7ch2loop
@song7ch3:
	.byte $97, $d9
@song7ch3loop:
	.byte $97, $42
	.word @song7ch3loop
@song7ch4:
	.byte $97, $01, $95, $02, $95, $01, $95, $02, $8f
@song7ch4loop:
	.byte $97, $42
	.word @song7ch4loop
@song8ch0:
	.byte $46, $03, $7c, $86, $1d, $83, $00, $89, $19, $83, $00, $89, $14, $89, $1e, $95, $1b, $95, $1d, $83, $1b, $83, $1d, $a1
	.byte $00, $89
@song8ch0loop:
	.byte $97, $42
	.word @song8ch0loop
@song8ch1:
@song8ref32:
	.byte $7c, $86, $25, $83, $00, $89, $20, $83, $00, $89, $1d, $89, $21, $85, $23, $85, $21, $85, $20, $85, $22, $85, $20, $85
	.byte $20, $b9
@song8ch1loop:
	.byte $97, $42
	.word @song8ch1loop
@song8ch2:
	.byte $41, $0b
	.word @song8ref32
	.byte $95, $23, $95, $25, $b9
@song8ch2loop:
	.byte $97, $42
	.word @song8ch2loop
@song8ch3:
	.byte $ff, $9b
@song8ch3loop:
	.byte $97, $42
	.word @song8ch3loop
@song8ch4:
	.byte $ff, $87, $01, $83, $01, $83, $02, $85
@song8ch4loop:
	.byte $97, $42
	.word @song8ch4loop
@song9ch0:
	.byte $46, $03, $86, $20, $85, $1f, $85, $20, $85
@song9ch0loop:
@song9ref11:
	.byte $1d, $ad, $1e, $95, $1f, $95, $20, $ad, $25, $95, $29, $8f, $29, $83, $27, $95, $29, $95, $2a, $95, $24, $95, $27, $ad
	.byte $25, $95, $20, $85, $1f, $85, $20, $85
	.byte $41, $20
	.word @song9ref11
	.byte $42
	.word @song9ch0loop
@song9ch1:
	.byte $97
@song9ch1loop:
	.byte $86
@song9ref52:
	.byte $14, $ad, $16, $95, $17, $95, $18, $ad, $1d, $95, $20, $95, $1e, $95, $20, $95, $22, $95, $1b, $95, $1e, $95, $00, $95
	.byte $1d, $95, $00, $95
	.byte $41, $1c
	.word @song9ref52
	.byte $42
	.word @song9ch1loop
@song9ch2:
	.byte $86, $14, $95
@song9ch2loop:
	.byte $94
@song9ref91:
	.byte $19, $89, $25, $89, $19, $89, $25, $89, $19, $89, $25, $89
	.byte $41, $0c
	.word @song9ref91
	.byte $1d, $89, $29, $89, $1d, $89, $29, $89, $86, $1e, $89, $2a, $89, $1e, $89, $2a, $89, $20, $89, $2c, $89, $20, $89, $2c
	.byte $89, $19, $89, $25, $89, $14, $89, $20, $89, $16, $89, $22, $89, $18, $89, $24, $89, $94
@song9ref148:
	.byte $0d, $89, $19, $89, $0d, $89, $19, $89, $0d, $89, $19, $89
	.byte $41, $0c
	.word @song9ref148
	.byte $11, $89, $1d, $89, $11, $89, $1d, $89, $86, $12, $89, $1e, $89, $12, $89, $1e, $89, $14, $89, $20, $89, $14, $89, $20
	.byte $89, $0d, $89, $19, $89, $0a, $89, $16, $89, $0b, $89, $17, $89, $0c, $89, $18, $89, $42
	.word @song9ch2loop
@song9ch3:
	.byte $97
@song9ch3loop:
	.byte $75
@song9ref210:
	.byte $82, $14, $00, $87, $80, $20, $85, $20, $81, $82, $20, $89, $80, $20, $85, $20, $81
	.byte $41, $0d
	.word @song9ref210
	.byte $41, $0d
	.word @song9ref210
	.byte $41, $0d
	.word @song9ref210
	.byte $77
@song9ref237:
	.byte $82, $14, $00, $81, $14, $00, $81, $80, $20, $85, $20, $81, $82, $20, $89, $80, $20, $85, $20, $81
	.byte $41, $0d
	.word @song9ref210
	.byte $41, $10
	.word @song9ref237
	.byte $41, $0d
	.word @song9ref210
	.byte $41, $10
	.word @song9ref237
	.byte $41, $0d
	.word @song9ref210
	.byte $41, $10
	.word @song9ref237
	.byte $41, $0d
	.word @song9ref210
	.byte $41, $10
	.word @song9ref237
	.byte $41, $0d
	.word @song9ref210
	.byte $41, $10
	.word @song9ref237
	.byte $41, $0d
	.word @song9ref210
	.byte $42
	.word @song9ch3loop
@song9ch4:
	.byte $97
@song9ch4loop:
@song9ref295:
	.byte $01, $95, $02, $95, $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $0c
	.word @song9ref295
	.byte $41, $0c
	.word @song9ref295
	.byte $41, $0c
	.word @song9ref295
	.byte $41, $0c
	.word @song9ref295
	.byte $01, $95, $02, $95, $42
	.word @song9ch4loop
@song10ch0:
	.byte $46, $03, $7c, $86, $1d, $83, $00, $89, $19, $83, $00, $89, $14, $89, $1e, $95, $1b, $95, $1d, $83, $1b, $83, $1d, $a1
	.byte $00, $ff
@song10ch0loop:
	.byte $97, $42
	.word @song10ch0loop
@song10ch1:
	.byte $7c, $86, $25, $83, $00, $89, $20, $83, $00, $89, $1d, $89, $21, $85, $23, $85, $21, $85, $20, $85, $22, $85, $20, $85
	.byte $20, $ff, $af
@song10ch1loop:
	.byte $97, $42
	.word @song10ch1loop
@song10ch2:
	.byte $86, $0d, $89, $19, $89, $0d, $89, $19, $89, $15, $89, $21, $89, $17, $89, $23, $89, $25, $ff, $af
@song10ch2loop:
	.byte $97, $42
	.word @song10ch2loop
@song10ch3:
	.byte $80
@song10ref90:
	.byte $20, $89, $20, $83, $20, $89, $20, $83, $20, $89, $7b, $84, $1a, $81, $00, $81, $74, $1a, $85, $75, $19, $74, $00, $83
	.byte $19, $83, $73, $17, $83, $17, $83, $74, $17, $83, $7f, $80, $20, $89, $20, $83, $20, $89, $20, $83, $20, $83, $20, $83
	.byte $41, $20
	.word @song10ref90
	.byte $8d
@song10ch3loop:
	.byte $97, $42
	.word @song10ch3loop
@song10ch4:
@song10ref147:
	.byte $01, $95, $02, $95, $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $0b
	.word @song10ref147
	.byte $87
@song10ch4loop:
	.byte $97, $42
	.word @song10ch4loop
@song11ch0:
	.byte $46, $04, $86
@song11ref4:
	.byte $14, $81, $19, $81, $1d, $81, $20, $81, $25, $81, $29, $81, $2c, $89, $29, $89
@song11ref20:
	.byte $15, $81, $19, $81, $1c, $81, $21, $81, $25, $81, $28, $81, $2d, $89, $28, $89
@song11ref36:
	.byte $17, $81, $1b, $81, $1e, $81, $23, $81, $27, $81, $2a, $81, $2f, $89, $2f, $81, $2f, $81, $2f, $81, $29, $8f, $00, $9b
@song11ch0loop:
	.byte $af, $42
	.word @song11ch0loop
@song11ch1:
	.byte $83, $86, $11, $81
	.byte $41, $09
	.word @song11ref4
	.byte $89, $20, $89, $00, $81, $10, $81
	.byte $41, $09
	.word @song11ref20
	.byte $89, $21, $89, $00, $81, $12, $81
	.byte $41, $09
	.word @song11ref36
	.byte $89, $27, $89, $31, $8f, $00, $9b
@song11ch1loop:
	.byte $af, $42
	.word @song11ch1loop
@song11ch2:
	.byte $94, $0d, $89, $19, $89, $0d, $89, $19, $89, $09, $89, $15, $89, $09, $89, $15, $89, $17, $89, $23, $89, $17, $89, $23
	.byte $89, $86, $0d, $95, $00, $95
@song11ch2loop:
	.byte $af, $42
	.word @song11ch2loop
@song11ch3:
	.byte $df, $df
@song11ch3loop:
	.byte $af, $42
	.word @song11ch3loop
@song11ch4:
@song11ref146:
	.byte $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $08
	.word @song11ref146
@song11ch4loop:
	.byte $af, $42
	.word @song11ch4loop
@song12ch0:
	.byte $46, $03, $86, $11, $00, $21, $81, $00, $81, $21, $81, $21, $81, $00, $81, $12, $81, $22, $81, $00, $81, $22, $81, $22
	.byte $81, $00, $81, $13, $81, $23, $81, $00, $81, $23, $81, $23, $81, $00, $81, $24, $81, $00, $81, $24, $9d
@song12ch0loop:
	.byte $00, $81, $42
	.word @song12ch0loop
@song12ch1:
	.byte $86, $1d, $81, $27, $85, $27, $81, $27, $85, $1e, $81, $28, $85, $28, $81, $28, $85, $1f, $81, $29, $85, $29, $81, $29
	.byte $85, $2a, $85, $2a, $9d
@song12ch1loop:
	.byte $00, $81, $42
	.word @song12ch1loop
@song12ch2:
	.byte $92, $24, $81, $30, $85, $30, $81, $30, $85, $25, $81, $31, $85, $31, $81, $31, $85, $26, $81, $32, $85, $32, $81, $32
	.byte $85, $20, $85, $8e, $20, $9d
@song12ch2loop:
	.byte $00, $81, $42
	.word @song12ch2loop
@song12ch3:
	.byte $ef
@song12ch3loop:
	.byte $83, $42
	.word @song12ch3loop
@song12ch4:
	.byte $ef
@song12ch4loop:
	.byte $83, $42
	.word @song12ch4loop
@song13ch0:
	.byte $46, $05
@song13ch0loop:
	.byte $8c, $19, $83, $0d, $83, $20, $83, $1c, $83, $10, $83, $23, $83, $1c, $83, $1e, $83, $12, $83, $25, $83, $1e, $83, $1c
	.byte $83, $86, $31, $83, $31, $9b, $00, $91, $ff, $42
	.word @song13ch0loop
@song13ch1:
@song13ch1loop:
	.byte $8c, $25, $83, $31, $83, $31, $83, $25, $83, $2f, $83, $2f, $83, $2f, $83, $23, $83, $2d, $83, $2d, $83, $2d, $83, $2c
	.byte $83, $86, $29, $83, $29, $af, $ff, $42
	.word @song13ch1loop
@song13ch2:
@song13ch2loop:
	.byte $90, $0d, $83, $19, $81, $19, $0d, $83, $19, $83, $10, $83, $1c, $81, $1c, $10, $83, $1c, $83, $12, $83, $1e, $81, $1e
	.byte $12, $83, $1e, $81, $1e, $19, $83, $86, $19, $9b, $00, $91, $ff, $42
	.word @song13ch2loop
@song13ch3:
@song13ch3loop:
	.byte $80, $20, $83, $8e, $23, $23, $00
@song13ref124:
	.byte $80, $20, $83, $20, $83, $20, $83, $86, $1f, $00, $81
	.byte $41, $09
	.word @song13ref124
	.byte $80, $20, $83, $20, $83, $20, $83, $86, $1f, $83, $00, $a9, $ff, $42
	.word @song13ch3loop
@song13ch4:
@song13ch4loop:
@song13ref155:
	.byte $01, $83, $00, $83, $02, $89, $01, $83, $00, $83, $02, $89
	.byte $41, $0b
	.word @song13ref155
	.byte $a9, $ff, $42
	.word @song13ch4loop
