; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_overworld=music_data_overworld
.endif

music_data_overworld:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Overworld
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 358,298

.export music_data_overworld
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env7,@env6,@env8,@env0 ; 00 : Noise short
	.word @env1,@env6,@env8,@env0 ; 01 : Noise long
	.word @env4,@env6,@env8,@env0 ; 02 : Drums Sus
	.word @env3,@env6,@env9,@env0 ; 03 : Instrumental
	.word @env11,@env2,@env10,@env0 ; 04 : SqWoobble
	.word @env5,@env6,@env8,@env0 ; 05 : Blank

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cc,$04,$c0,$00,$03
@env2:
	.byte $cc,$cc,$c0,$c0,$00,$00
@env3:
	.byte $00,$c8,$c8,$c7,$c6,$c5,$c5,$c4,$c3,$c0,$00,$09
@env4:
	.byte $00,$ce,$cc,$ca,$c8,$c6,$c3,$c2,$00,$07
@env5:
	.byte $00,$cf,$7f,$00,$02
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $00,$cc,$c0,$00,$02
@env8:
	.byte $7f,$00,$00
@env9:
	.byte $c2,$7f,$00,$00
@env10:
	.byte $c1,$7f,$00,$00
@env11:
	.byte $0c,$ca,$c6,$c7,$c7,$c5,$c7,$c2,$04,$c1,$00,$09,$c1,$c0,$0f,$c0,$00,$0f
@env12:
	.byte $00,$c1,$7f,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$68,$0f,$40 ; 00 kickcki1.dmc (Pitch:15)

@song0ch0:
	.byte $46, $03
@song0ch0loop:
	.byte $7c, $86
@song0ref6:
	.byte $1f, $83, $1f, $89, $1f, $89, $1f, $83, $1f, $89, $24, $95, $7d, $25, $95, $27, $95, $7f, $2c, $95
@song0ref26:
	.byte $1d, $8f, $19, $8f, $14, $8f, $19, $89, $1b, $89, $1a, $83, $19, $89, $19, $85, $20, $85, $24, $85, $25, $89, $22, $83
	.byte $24, $89, $22, $89, $1d, $83, $1e, $83, $1b, $8f
	.byte $41, $22
	.word @song0ref26
@song0ref63:
	.byte $8b, $29, $83, $28, $83, $27, $83, $24, $89, $25, $89, $1d, $83, $1e, $83, $20, $89, $19, $83, $1d, $83, $1e, $83
	.byte $41, $0b
	.word @song0ref63
	.byte $2a, $89, $2a, $83, $2a, $95
	.byte $41, $17
	.word @song0ref63
	.byte $8b, $21, $8f, $1e, $8f, $1d, $ad, $8b, $21, $8f, $1e, $8f, $1d, $ad, $8b, $21, $8f, $1e, $8f, $88, $1d, $ad, $86
@song0ref121:
	.byte $21, $83, $21, $89, $21, $89, $21, $83, $23, $89, $20, $83, $1d, $89, $1d, $83, $19, $95, $21, $83, $21, $89, $21, $89
	.byte $21, $83, $23, $83, $20, $b3
	.byte $41, $12
	.word @song0ref121
	.byte $7c
	.byte $41, $12
	.word @song0ref6
@song0ref158:
	.byte $25, $83, $22, $89, $1d, $8f, $1d, $89, $1e, $83, $25, $89, $25, $83, $1e, $95, $20, $85, $2a, $85, $2a, $85, $2a, $85
	.byte $29, $85, $27, $85, $25, $83, $22, $89, $1e, $83, $1d, $95
	.byte $41, $12
	.word @song0ref158
@song0ref197:
	.byte $27, $85, $27, $83, $27, $85, $25, $85, $24, $85, $20, $83, $1d, $89, $1d, $83, $19, $97
	.byte $41, $24
	.word @song0ref158
	.byte $41, $12
	.word @song0ref158
	.byte $41, $12
	.word @song0ref197
	.byte $41, $1e
	.word @song0ref121
	.byte $41, $12
	.word @song0ref121
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref234:
	.byte $7b, $86, $29, $83, $29, $89, $29, $89, $25, $83, $29, $89, $7c, $2c, $95, $7d, $20, $95, $24, $95, $7f, $27, $95, $88
@song0ref258:
	.byte $19, $8f, $14, $8f, $11, $8f, $16, $89, $18, $89, $17, $83, $16, $89, $14, $85, $1d, $85, $20, $85, $22, $89, $1e, $83
	.byte $20, $89, $1d, $89, $19, $83, $1b, $83, $18, $8f
	.byte $41, $22
	.word @song0ref258
@song0ref295:
	.byte $8b, $20, $83, $1f, $83, $1e, $83, $1c, $89, $1d, $89, $15, $83, $16, $83, $19, $89, $16, $83, $19, $83, $1b, $83
	.byte $41, $0b
	.word @song0ref295
	.byte $25, $89, $25, $83, $25, $89, $00, $89
	.byte $41, $17
	.word @song0ref295
	.byte $8b, $1c, $8f, $1b, $8f, $19, $8d, $00, $9d, $8b, $1c, $8f, $1b, $8f, $19, $8d, $00, $9d, $8b, $28, $8f, $27, $8f, $25
	.byte $ad
@song0ref357:
	.byte $25, $83, $25, $89, $25, $89, $25, $83, $27, $89, $29, $83, $25, $89, $22, $83, $20, $95, $25, $83, $25, $89, $25, $89
	.byte $25, $83, $27, $83, $29, $b3
	.byte $41, $12
	.word @song0ref357
	.byte $41, $12
	.word @song0ref234
	.byte $88
@song0ref394:
	.byte $29, $83, $25, $89, $20, $8f, $21, $89, $22, $83, $2a, $89, $2a, $83, $22, $95, $24, $85, $2e, $85, $2e, $85, $2e, $85
	.byte $2c, $85, $2a, $85, $29, $83, $25, $89, $22, $83, $20, $95
	.byte $41, $12
	.word @song0ref394
@song0ref433:
	.byte $2a, $85, $2a, $83, $2a, $85, $29, $85, $27, $85, $25, $af
	.byte $41, $24
	.word @song0ref394
	.byte $41, $12
	.word @song0ref394
	.byte $41, $0c
	.word @song0ref433
	.byte $41, $1e
	.word @song0ref357
	.byte $41, $12
	.word @song0ref357
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $8a
@song0ref465:
	.byte $0f, $89, $1b, $89, $0f, $89, $1b, $89, $14, $89, $20, $89, $16, $89, $22, $89, $18, $89, $24, $89, $1b, $89, $27
@song0ref488:
	.byte $89
@song0ref489:
	.byte $0d, $89, $19, $89, $0d, $89, $19, $89, $0d, $89, $19, $89, $0d, $89, $19, $89, $0d, $89, $19, $89, $11, $89, $1d, $89
	.byte $12, $89, $1e, $89, $13, $89, $20
	.byte $41, $20
	.word @song0ref488
@song0ref523:
	.byte $89, $0d, $89, $19, $89, $0d, $89, $19, $89, $12, $89, $1e, $89, $14, $89, $20, $89, $0d, $89, $19, $89, $0d, $89, $19
	.byte $89, $12, $83, $00, $89, $14, $83, $20, $89, $14
	.byte $41, $11
	.word @song0ref523
@song0ref560:
	.byte $15, $89, $21, $89, $17, $89, $23, $89, $19, $89, $25, $89, $19, $89, $25, $89
	.byte $41, $10
	.word @song0ref560
	.byte $41, $10
	.word @song0ref560
@song0ref582:
	.byte $15, $89, $21, $89, $15, $89, $21, $89, $0d, $89, $19, $89, $0d, $89, $19, $89
	.byte $41, $10
	.word @song0ref582
	.byte $41, $10
	.word @song0ref582
	.byte $41, $18
	.word @song0ref465
	.byte $84
	.byte $41, $14
	.word @song0ref489
	.byte $41, $14
	.word @song0ref489
@song0ref614:
	.byte $0d, $89, $19, $89, $0d, $89, $19, $89, $14, $89, $20, $89, $16, $89, $24, $89, $19, $89, $25, $89, $19, $89, $25
	.byte $41, $15
	.word @song0ref488
	.byte $41, $14
	.word @song0ref489
	.byte $41, $17
	.word @song0ref614
	.byte $89, $8a
	.byte $41, $10
	.word @song0ref582
	.byte $41, $10
	.word @song0ref582
	.byte $41, $10
	.word @song0ref582
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $7f, $80
@song0ref663:
	.byte $20, $89, $20, $83, $20, $89, $20, $83, $20, $89, $84, $21, $00, $81, $74, $1a, $83, $75, $19, $83, $74, $19, $83, $19
	.byte $83, $73, $17, $83, $17, $83, $74, $17, $83, $75
@song0ref697:
	.byte $17, $83, $17, $83, $76, $17, $83, $7a
@song0ref705:
	.byte $17, $83, $7f, $1b, $81, $00, $1c, $81, $00, $1c, $81, $00, $1c, $81, $00
@song0ref720:
	.byte $82, $14, $00, $87, $80, $20, $85, $20, $81, $82, $20, $89, $80, $20, $85, $20, $81
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
@song0ref758:
	.byte $82, $14, $00
@song0ref761:
	.byte $81, $80, $20, $83, $20, $83, $20, $83, $7b, $84, $19, $83, $7f, $80, $20, $83, $20, $83, $20, $83
	.byte $41, $11
	.word @song0ref758
	.byte $41, $11
	.word @song0ref758
@song0ref787:
	.byte $82, $14, $00, $81, $14, $00, $81, $80, $20, $83, $82, $14, $00, $81, $7b, $84, $19, $83, $7f, $80, $20, $83, $20, $83
	.byte $20, $83
	.byte $41, $11
	.word @song0ref758
	.byte $41, $11
	.word @song0ref758
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $41, $0d
	.word @song0ref720
	.byte $84, $21, $83, $74, $18, $83, $75, $18, $83, $74, $18, $83, $18, $83, $73, $17, $83, $17, $83, $74, $17, $83, $7f, $82
	.byte $14, $00, $81, $75, $84, $17, $83, $17, $83, $76
	.byte $41, $10
	.word @song0ref705
	.byte $41, $0f
	.word @song0ref761
	.byte $41, $13
	.word @song0ref787
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $41, $31
	.word @song0ref663
	.byte $41, $0f
	.word @song0ref761
	.byte $41, $13
	.word @song0ref787
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $41, $11
	.word @song0ref758
	.byte $41, $11
	.word @song0ref758
	.byte $41, $11
	.word @song0ref758
	.byte $41, $11
	.word @song0ref758
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $75, $84
	.byte $41, $16
	.word @song0ref697
	.byte $41, $0f
	.word @song0ref761
@song0ref939:
	.byte $82, $14, $00, $81, $80, $20, $83, $20, $83, $20, $83, $84, $18, $81, $00, $85, $80, $20, $83, $20, $83
	.byte $41, $0c
	.word @song0ref939
	.byte $80, $20, $83, $20, $83, $20, $83
	.byte $41, $11
	.word @song0ref939
	.byte $41, $0c
	.word @song0ref939
	.byte $80, $20, $83, $20, $83, $20, $83
	.byte $41, $11
	.word @song0ref758
	.byte $41, $13
	.word @song0ref787
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref993:
	.byte $01, $89, $00, $89, $01, $89, $00, $89
@song0ref1001:
	.byte $01, $95, $01, $95, $01, $89, $01, $89, $01, $83, $01, $83, $01, $83, $01, $83
@song0ref1017:
	.byte $01, $95, $01, $95, $01, $95, $01, $95, $01, $95, $01, $95
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $01, $95, $01, $95, $01, $95, $01, $95
	.byte $41, $24
	.word @song0ref993
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $41, $0c
	.word @song0ref1017
	.byte $01, $95, $01, $95
	.byte $41, $1c
	.word @song0ref1001
	.byte $41, $0c
	.word @song0ref1017
	.byte $01, $95, $01, $95, $42
	.word @song0ch4loop
