; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_you_saved_the_princess=music_data_you_saved_the_princess
.endif

music_data_you_saved_the_princess:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : You saved the princess
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 313,261

.export music_data_you_saved_the_princess
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env4,@env0 ; 00 : Noise long
	.word @env3,@env2,@env4,@env0 ; 01 : Noise short
	.word @env6,@env2,@env7,@env0 ; 02 : Long instrumental
	.word @env9,@env2,@env5,@env0 ; 03 : Death instrument

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cc,$04,$c0,$00,$03
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $00,$cc,$c0,$00,$02
@env4:
	.byte $7f,$00,$00
@env5:
	.byte $c2,$7f,$00,$00
@env6:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env7:
	.byte $c0,$c2,$00,$01
@env8:
	.byte $00,$c1,$7f,$00,$02
@env9:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c6,$c5,$c3,$c2,$c1,$c0,$00,$0c

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$68,$0f,$40 ; 00 kickcki1.dmc (Pitch:15)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 01 PERCUSSION 4.dmc (Pitch:15)

@song0ch0:
	.byte $46, $03, $84, $20, $85, $1f, $85, $20, $85
@song0ch0loop:
@song0ref11:
	.byte $1d, $ad, $1e, $95, $1f, $95, $20, $ad, $25, $95, $29, $8f, $29, $83, $27, $95, $29, $95, $2a, $95, $24, $95, $27, $ad
	.byte $25, $95, $20, $85, $1f, $85, $20, $85
	.byte $41, $20
	.word @song0ref11
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $97
@song0ch1loop:
	.byte $84
@song0ref52:
	.byte $14, $ad, $16, $95, $17, $95, $18, $ad, $1d, $95, $20, $95, $1e, $95, $20, $95, $22, $95, $1b, $95, $1e, $95, $00, $95
	.byte $1d, $95, $00, $95
	.byte $41, $1c
	.word @song0ref52
	.byte $42
	.word @song0ch1loop
@song0ch2:
	.byte $84, $14, $95
@song0ch2loop:
	.byte $86
@song0ref91:
	.byte $19, $89, $25, $89, $19, $89, $25, $89, $19, $89, $25, $89
	.byte $41, $0c
	.word @song0ref91
	.byte $1d, $89, $29, $89, $1d, $89, $29, $89, $84, $1e, $89, $2a, $89, $1e, $89, $2a, $89, $20, $89, $2c, $89, $20, $89, $2c
	.byte $89, $19, $89, $25, $89, $14, $89, $20, $89, $16, $89, $22, $89, $18, $89, $24, $89, $86
@song0ref148:
	.byte $0d, $89, $19, $89, $0d, $89, $19, $89, $0d, $89, $19, $89
	.byte $41, $0c
	.word @song0ref148
	.byte $11, $89, $1d, $89, $11, $89, $1d, $89, $84, $12, $89, $1e, $89, $12, $89, $1e, $89, $14, $89, $20, $89, $14, $89, $20
	.byte $89, $0d, $89, $19, $89, $0a, $89, $16, $89, $0b, $89, $17, $89, $0c, $89, $18, $89, $42
	.word @song0ch2loop
@song0ch3:
	.byte $97
@song0ch3loop:
	.byte $75
@song0ref210:
	.byte $80, $14, $00, $87, $82, $20, $85, $20, $81, $80, $20, $89, $82, $20, $85, $20, $81
	.byte $41, $0d
	.word @song0ref210
	.byte $41, $0d
	.word @song0ref210
	.byte $41, $0d
	.word @song0ref210
	.byte $77
@song0ref237:
	.byte $80, $14, $00, $81, $14, $00, $81, $82, $20, $85, $20, $81, $80, $20, $89, $82, $20, $85, $20, $81
	.byte $41, $0d
	.word @song0ref210
	.byte $41, $10
	.word @song0ref237
	.byte $41, $0d
	.word @song0ref210
	.byte $41, $10
	.word @song0ref237
	.byte $41, $0d
	.word @song0ref210
	.byte $41, $10
	.word @song0ref237
	.byte $41, $0d
	.word @song0ref210
	.byte $41, $10
	.word @song0ref237
	.byte $41, $0d
	.word @song0ref210
	.byte $41, $10
	.word @song0ref237
	.byte $41, $0d
	.word @song0ref210
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $97
@song0ch4loop:
@song0ref295:
	.byte $01, $95, $02, $95, $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $0c
	.word @song0ref295
	.byte $41, $0c
	.word @song0ref295
	.byte $41, $0c
	.word @song0ref295
	.byte $41, $0c
	.word @song0ref295
	.byte $01, $95, $02, $95, $42
	.word @song0ch4loop
