; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_underworld=music_data_underworld
.endif

music_data_underworld:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Underworld
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_underworld
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env13,@env1,@env11,@env0 ; 00 : SqWoobble
	.word @env10,@env4,@env8,@env0 ; 01 : Death effect
	.word @env2,@env5,@env8,@env0 ; 02 : Instrumental
	.word @env3,@env5,@env7,@env0 ; 03 : Triangle
	.word @env9,@env5,@env12,@env0 ; 04 : Long instrumental
	.word @env6,@env5,@env7,@env0 ; 05 : Noise short

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $cc,$cc,$c0,$c0,$00,$00
@env2:
	.byte $00,$c8,$c8,$c7,$c6,$c5,$c5,$c4,$c3,$c0,$00,$09
@env3:
	.byte $00,$cf,$07,$c0,$00,$03
@env4:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$0a
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $00,$cc,$c0,$00,$02
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $c2,$7f,$00,$00
@env9:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env10:
	.byte $00,$ce,$cc,$cb,$ca,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$0b
@env11:
	.byte $c1,$7f,$00,$00
@env12:
	.byte $c0,$c2,$00,$01
@env13:
	.byte $0c,$ca,$c6,$c7,$c7,$c5,$c7,$c2,$04,$c1,$00,$09,$c1,$c0,$0f,$c0,$00,$0f
@env14:
	.byte $00,$c1,$7f,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$68,$0f,$40 ; 00 kickcki1.dmc (Pitch:15)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 01 PERCUSSION 4.dmc (Pitch:15)

@song0ch0:
	.byte $46, $04
@song0ch0loop:
@song0ref4:
	.byte $76, $86
@song0ref6:
	.byte $01, $83, $0d, $83, $40, $0a, $83, $0a, $83, $40, $0b, $83, $0b, $bf
	.byte $41, $0c
	.word @song0ref6
@song0ref23:
	.byte $06, $83, $12, $83, $03, $83, $0f, $83, $04, $83, $10, $bf
	.byte $41, $0c
	.word @song0ref23
	.byte $41, $0b
	.word @song0ref6
	.byte $83, $71, $82, $1f, $83, $80, $1f
@song0ref48:
	.byte $81, $83, $73, $83, $74, $83, $75, $83, $76, $83, $7a, $83, $7b, $83, $7c, $83, $7d, $83, $7f, $83, $74, $83, $70, $83
	.byte $81
	.byte $41, $0b
	.word @song0ref4
	.byte $83, $71, $82, $23, $83, $80, $23
	.byte $41, $0e
	.word @song0ref48
	.byte $76, $86
	.byte $41, $0b
	.word @song0ref23
	.byte $83, $71, $82, $2f, $83, $80, $15
	.byte $41, $0e
	.word @song0ref48
	.byte $76, $86
	.byte $41, $0b
	.word @song0ref23
	.byte $83, $71, $82, $2f, $83, $80, $21
	.byte $41, $0a
	.word @song0ref48
	.byte $7f, $81, $7a, $84, $1c, $81, $1b, $81, $1a, $81, $19, $89, $1c, $89, $1b, $89, $15, $89, $14, $89, $1a, $89, $19, $81
	.byte $1f, $81, $1e, $81, $1d, $81, $23, $81, $22, $81, $21, $85, $1c, $85, $18, $85, $17, $85, $16, $85, $15, $85, $71, $80
	.byte $1b
	.byte $41, $0a
	.word @song0ref48
	.byte $7f, $87, $70, $af, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref176:
	.byte $7f, $84
@song0ref178:
	.byte $19, $83, $25
@song0ref181:
	.byte $83, $16, $83, $22, $83, $17, $83, $23, $bf
	.byte $41, $0c
	.word @song0ref178
@song0ref193:
	.byte $12, $83, $1e, $83, $0f, $83, $1b, $83, $10, $83, $1c, $bf
	.byte $41, $0c
	.word @song0ref193
	.byte $41, $0b
	.word @song0ref178
	.byte $83, $71, $82, $28, $83, $80, $28
@song0ref218:
	.byte $81, $83, $73, $83, $74, $83, $75, $83, $76, $83, $79, $83, $7a, $83, $7c, $83, $7d, $83, $7f, $83, $74, $83, $71, $83
	.byte $70, $81
	.byte $41, $0b
	.word @song0ref176
	.byte $83, $71, $82, $2c, $83, $80, $2c
	.byte $41, $0e
	.word @song0ref218
	.byte $78, $84
	.byte $41, $0b
	.word @song0ref193
	.byte $83, $71, $82, $2c, $83, $80, $1e
	.byte $41, $0e
	.word @song0ref218
	.byte $79, $84
	.byte $41, $0b
	.word @song0ref193
	.byte $83, $71, $82, $2c, $83, $80, $1e
	.byte $41, $0a
	.word @song0ref218
	.byte $7f, $81, $7b, $84, $28, $81, $27, $81, $26, $81, $25, $89, $28, $89, $27, $89, $21, $89, $20, $89, $26, $89, $25, $81
	.byte $2b, $81, $2a, $81, $29, $81, $2f, $81, $2e, $81, $2d, $85, $28, $85, $24, $85, $23, $85, $22, $85, $21, $85, $71, $80
	.byte $20
	.byte $41, $0a
	.word @song0ref218
	.byte $7f, $87, $70, $af, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $88
	.byte $41, $0b
	.word @song0ref178
	.byte $83, $18, $83, $19, $83
	.byte $41, $0b
	.word @song0ref178
	.byte $83, $18, $83, $24, $83
	.byte $41, $0b
	.word @song0ref178
	.byte $83, $18, $83, $19, $83
	.byte $41, $0b
	.word @song0ref178
	.byte $83, $18, $83, $24, $83
	.byte $41, $0b
	.word @song0ref193
	.byte $83, $11, $83, $12, $83
	.byte $41, $0b
	.word @song0ref193
	.byte $83, $11, $83, $1d, $83
	.byte $41, $0b
	.word @song0ref193
	.byte $83, $11, $83, $12, $83
	.byte $41, $0b
	.word @song0ref193
	.byte $83, $11, $83, $1d, $83
	.byte $41, $0b
	.word @song0ref178
	.byte $83, $18, $83, $19, $83
	.byte $41, $0b
	.word @song0ref178
	.byte $83, $18, $83, $24, $83
	.byte $41, $0b
	.word @song0ref178
	.byte $83, $18, $83, $19, $83
	.byte $41, $0b
	.word @song0ref178
	.byte $83, $18, $83, $24, $83
	.byte $41, $0b
	.word @song0ref193
	.byte $83, $11, $83, $12, $83
	.byte $41, $0b
	.word @song0ref193
	.byte $83, $11, $83, $1d, $83
	.byte $41, $0b
	.word @song0ref193
	.byte $83, $11, $83, $12, $83
	.byte $41, $0b
	.word @song0ref193
	.byte $83, $1b, $83, $1a, $83, $19, $83, $25, $83, $19, $83, $25, $83, $17, $83, $23, $83, $17, $83, $23, $83, $16, $83, $22
	.byte $83, $16, $83, $22, $83, $15, $83, $21, $83, $15, $83, $21, $83, $14, $83, $20, $83, $14, $83, $20, $83, $14, $83, $20
	.byte $83, $14, $83, $14, $83, $14, $83, $20, $83, $11, $83, $1d, $83, $12, $83, $1e, $83, $13, $83, $14, $83, $14, $83, $20
	.byte $41, $08
	.word @song0ref181
	.byte $83, $18, $83, $24, $83, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $7f, $8a
@song0ref557:
	.byte $14
@song0ref558:
	.byte $00, $81, $73, $1f, $83
@song0ref563:
	.byte $1f, $83
@song0ref565:
	.byte $1f, $83, $7f, $1d, $83, $73, $1f, $83, $1f, $83, $1f, $83, $7f, $14, $83, $7d, $15, $00, $81, $7f, $14, $83, $73
	.byte $41, $0b
	.word @song0ref565
	.byte $41, $17
	.word @song0ref558
	.byte $73
	.byte $41, $0b
	.word @song0ref565
	.byte $41, $17
	.word @song0ref558
	.byte $73
	.byte $41, $0b
	.word @song0ref565
	.byte $41, $17
	.word @song0ref558
	.byte $73
	.byte $41, $0c
	.word @song0ref565
	.byte $73, $1f, $1f, $81
	.byte $41, $0a
	.word @song0ref563
@song0ref619:
	.byte $7f, $14, $83, $74, $1f, $83, $7d, $15, $00, $81, $7f, $14, $83, $73
	.byte $41, $0c
	.word @song0ref565
	.byte $73, $1f, $1f, $81
	.byte $41, $0a
	.word @song0ref563
	.byte $41, $09
	.word @song0ref619
	.byte $73
	.byte $41, $0b
	.word @song0ref565
	.byte $41, $17
	.word @song0ref558
	.byte $73
	.byte $41, $0b
	.word @song0ref565
	.byte $41, $17
	.word @song0ref558
	.byte $73
	.byte $41, $0b
	.word @song0ref565
	.byte $41, $17
	.word @song0ref558
	.byte $73, $1f, $83, $7b, $1d, $81, $1d, $81, $1d, $81, $1d, $81, $1d, $81, $7f, $1d, $81
	.byte $41, $18
	.word @song0ref557
	.byte $73
	.byte $41, $0b
	.word @song0ref565
	.byte $41, $10
	.word @song0ref558
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref698:
	.byte $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $08
	.word @song0ref698
	.byte $41, $08
	.word @song0ref698
	.byte $41, $08
	.word @song0ref698
@song0ref715:
	.byte $01, $89, $00, $89, $02, $95, $01, $89, $00, $89, $02, $95
	.byte $41, $0c
	.word @song0ref715
	.byte $41, $0c
	.word @song0ref715
	.byte $41, $0c
	.word @song0ref715
@song0ref736:
	.byte $01, $89, $02, $89, $01, $89, $02, $89
	.byte $41, $08
	.word @song0ref736
	.byte $41, $08
	.word @song0ref736
	.byte $41, $08
	.word @song0ref736
	.byte $41, $08
	.word @song0ref736
	.byte $42
	.word @song0ch4loop
