; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_new_song=music_data_new_song
.endif

music_data_new_song:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : New song
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 385,320

.export music_data_new_song
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env8,@env4,@env9,@env0 ; 00 : Long instrumental
	.word @env5,@env4,@env6,@env0 ; 01 : Noise short
	.word @env1,@env4,@env7,@env0 ; 02 : Instrumental
	.word @env3,@env4,@env7,@env0 ; 03 : Instrumental 2
	.word @env2,@env4,@env6,@env0 ; 04 : Blank

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c8,$c8,$c7,$c6,$c5,$c5,$c4,$c3,$c0,$00,$09
@env2:
	.byte $00,$cf,$7f,$00,$02
@env3:
	.byte $00,$cc,$02,$ca,$c3,$c3,$c2,$c0,$00,$07
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $00,$cc,$c0,$00,$02
@env6:
	.byte $7f,$00,$00
@env7:
	.byte $c2,$7f,$00,$00
@env8:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env9:
	.byte $c0,$c2,$00,$01
@env10:
	.byte $00,$c1,$7f,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$68,$0f,$40 ; 00 kickcki1.dmc (Pitch:15)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 01 PERCUSSION 4.dmc (Pitch:15)

@song0ch0:
	.byte $46, $05
@song0ch0loop:
	.byte $84, $19, $83, $0d, $83, $20, $83, $1c, $83, $10, $83, $23, $83, $1c, $83, $1e, $83, $12, $83, $25, $83, $1e, $83, $1c
	.byte $83, $80, $31, $83, $31, $9b, $00, $91, $ff, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $84, $25, $83, $31, $83, $31, $83, $25, $83, $2f, $83, $2f, $83, $2f, $83, $23, $83, $2d, $83, $2d, $83, $2d, $83, $2c
	.byte $83, $80, $29, $83, $29, $af, $ff, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $86, $0d, $83, $19, $81, $19, $0d, $83, $19, $83, $10, $83, $1c, $81, $1c, $10, $83, $1c, $83, $12, $83, $1e, $81, $1e
	.byte $12, $83, $1e, $81, $1e, $19, $83, $80, $19, $9b, $00, $91, $ff, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $82, $20, $83, $88, $23, $23, $00
@song0ref124:
	.byte $82, $20, $83, $20, $83, $20, $83, $80, $1f, $00, $81
	.byte $41, $09
	.word @song0ref124
	.byte $82, $20, $83, $20, $83, $20, $83, $80, $1f, $83, $00, $a9, $ff, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref155:
	.byte $01, $83, $00, $83, $02, $89, $01, $83, $00, $83, $02, $89
	.byte $41, $0b
	.word @song0ref155
	.byte $a9, $ff, $42
	.word @song0ch4loop
