; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_castleworld=music_data_castleworld
.endif

music_data_castleworld:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Castleworld
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 313,261

.export music_data_castleworld
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env4,@env6,@env0 ; 00 : Instrumental
	.word @env7,@env4,@env5,@env0 ; 01 : Sample Kick
	.word @env8,@env4,@env6,@env0 ; 02 : Death instrument
	.word @env3,@env4,@env5,@env0 ; 03 : Blank
	.word @env2,@env4,@env5,@env0 ; 04 : Drums Sus

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c8,$c8,$c7,$c6,$c5,$c5,$c4,$c3,$c0,$00,$09
@env2:
	.byte $00,$ce,$cc,$ca,$c8,$c6,$c3,$c2,$00,$07
@env3:
	.byte $00,$cf,$7f,$00,$02
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $7f,$00,$00
@env6:
	.byte $c2,$7f,$00,$00
@env7:
	.byte $00,$c1,$7f,$00,$02
@env8:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c6,$c5,$c3,$c2,$c1,$c0,$00,$0c

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$68,$0f,$40 ; 00 kickcki1.dmc (Pitch:15)

@song0ch0:
	.byte $46, $05
@song0ch0loop:
	.byte $81, $76, $80
@song0ref7:
	.byte $1b, $81, $1a, $81, $19, $81, $1a, $81, $1b, $81, $1c, $81, $1b, $81, $1a, $81
	.byte $41, $10
	.word @song0ref7
	.byte $74
@song0ref27:
	.byte $27, $81, $26, $81, $25, $81, $26, $81, $27, $81, $28, $81, $27, $81, $26, $81
	.byte $41, $10
	.word @song0ref27
	.byte $77
	.byte $41, $10
	.word @song0ref7
	.byte $41, $10
	.word @song0ref7
@song0ref53:
	.byte $1a, $81, $19, $81, $1a, $81, $1b, $81, $1a, $81, $1b, $81, $1a, $81, $19, $81
	.byte $41, $10
	.word @song0ref53
	.byte $82
@song0ref73:
	.byte $1e, $81, $1f, $81, $1e, $81, $1d, $81, $1e, $81, $1d, $81, $1c, $81, $1d, $81
	.byte $41, $0f
	.word @song0ref73
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $76, $84
	.byte $41, $10
	.word @song0ref7
	.byte $41, $10
	.word @song0ref7
	.byte $78
	.byte $41, $10
	.word @song0ref7
	.byte $41, $10
	.word @song0ref7
	.byte $79
	.byte $41, $10
	.word @song0ref7
	.byte $41, $10
	.word @song0ref7
	.byte $41, $10
	.word @song0ref53
	.byte $41, $10
	.word @song0ref53
	.byte $41, $10
	.word @song0ref73
	.byte $41, $10
	.word @song0ref73
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $00, $bd, $bf, $86, $10, $9d, $0f, $8d, $13, $8d, $12, $9d, $11, $8d, $17, $8d, $16, $8d, $11, $8d, $10, $8d, $11, $8d
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $7f, $88, $14, $00, $8b, $79, $1d, $81, $00, $89, $7f, $14, $00, $8b, $79, $1d, $81, $00, $89, $78, $14, $00, $14, $00
	.byte $1b, $81, $1b, $81, $14, $00, $79, $14, $00, $1b, $7a, $81, $1b, $81, $7b, $14, $00, $14, $7c, $00, $1b, $81, $1b, $81
	.byte $7f, $1b, $81, $1b, $81, $1b, $81, $1b, $81
@song0ref219:
	.byte $14, $00, $83, $76, $1b, $81, $1b, $81, $79, $1d, $81, $00, $81, $1b, $85, $7f, $14, $00, $83, $77, $1b, $81, $00, $81
	.byte $1d, $85, $1b, $85, $7f
	.byte $41, $18
	.word @song0ref219
	.byte $7f
	.byte $41, $18
	.word @song0ref219
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $bf, $01, $8d, $01, $8d, $01, $81, $01, $81, $01, $81, $01, $81, $01, $81, $01, $81, $01, $81, $01, $81
@song0ref280:
	.byte $01, $8d, $01, $8d, $01, $8d, $01, $8d, $01, $8d, $01, $8d
	.byte $41, $0c
	.word @song0ref280
	.byte $42
	.word @song0ch4loop
