
.scope piece00
	.include "paniccut_0_params.inc"
	bits_bank := $00
	slopes_bank := $21
	.segment "BANK_00"
	bits:
		.incbin "paniccut_0_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "paniccut_0_slopes.bin"
.endscope

.scope piece01
	.include "paniccut_1_params.inc"
	bits_bank := $01
	slopes_bank := $21
	.segment "BANK_01"
	bits:
		.incbin "paniccut_1_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "paniccut_1_slopes.bin"
.endscope

.scope piece02
	.include "paniccut_2_params.inc"
	bits_bank := $02
	slopes_bank := $21
	.segment "BANK_02"
	bits:
		.incbin "paniccut_2_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "paniccut_2_slopes.bin"
.endscope

.scope piece03
	.include "paniccut_3_params.inc"
	bits_bank := $03
	slopes_bank := $21
	.segment "BANK_03"
	bits:
		.incbin "paniccut_3_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "paniccut_3_slopes.bin"
.endscope

.scope piece04
	.include "paniccut_4_params.inc"
	bits_bank := $04
	slopes_bank := $21
	.segment "BANK_04"
	bits:
		.incbin "paniccut_4_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "paniccut_4_slopes.bin"
.endscope

.scope piece05
	.include "paniccut_5_params.inc"
	bits_bank := $05
	slopes_bank := $21
	.segment "BANK_05"
	bits:
		.incbin "paniccut_5_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "paniccut_5_slopes.bin"
.endscope

.scope piece06
	.include "paniccut_6_params.inc"
	bits_bank := $06
	slopes_bank := $21
	.segment "BANK_06"
	bits:
		.incbin "paniccut_6_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "paniccut_6_slopes.bin"
.endscope

.scope piece07
	.include "paniccut_7_params.inc"
	bits_bank := $07
	slopes_bank := $21
	.segment "BANK_07"
	bits:
		.incbin "paniccut_7_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "paniccut_7_slopes.bin"
.endscope

.scope piece08
	.include "paniccut_8_params.inc"
	bits_bank := $08
	slopes_bank := $21
	.segment "BANK_08"
	bits:
		.incbin "paniccut_8_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "paniccut_8_slopes.bin"
.endscope

.scope piece09
	.include "paniccut_9_params.inc"
	bits_bank := $09
	slopes_bank := $21
	.segment "BANK_09"
	bits:
		.incbin "paniccut_9_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "paniccut_9_slopes.bin"
.endscope

.scope piece0a
	.include "paniccut_10_params.inc"
	bits_bank := $0a
	slopes_bank := $21
	.segment "BANK_0a"
	bits:
		.incbin "paniccut_10_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "paniccut_10_slopes.bin"
.endscope

.scope piece0b
	.include "paniccut_11_params.inc"
	bits_bank := $0b
	slopes_bank := $21
	.segment "BANK_0b"
	bits:
		.incbin "paniccut_11_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "paniccut_11_slopes.bin"
.endscope

.scope piece0c
	.include "paniccut_12_params.inc"
	bits_bank := $0c
	slopes_bank := $22
	.segment "BANK_0c"
	bits:
		.incbin "paniccut_12_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_12_slopes.bin"
.endscope

.scope piece0d
	.include "paniccut_13_params.inc"
	bits_bank := $0d
	slopes_bank := $22
	.segment "BANK_0d"
	bits:
		.incbin "paniccut_13_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_13_slopes.bin"
.endscope

.scope piece0e
	.include "paniccut_14_params.inc"
	bits_bank := $0e
	slopes_bank := $22
	.segment "BANK_0e"
	bits:
		.incbin "paniccut_14_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_14_slopes.bin"
.endscope

.scope piece0f
	.include "paniccut_15_params.inc"
	bits_bank := $0f
	slopes_bank := $22
	.segment "BANK_0f"
	bits:
		.incbin "paniccut_15_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_15_slopes.bin"
.endscope

.scope piece10
	.include "paniccut_16_params.inc"
	bits_bank := $10
	slopes_bank := $22
	.segment "BANK_10"
	bits:
		.incbin "paniccut_16_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_16_slopes.bin"
.endscope

.scope piece11
	.include "paniccut_17_params.inc"
	bits_bank := $11
	slopes_bank := $22
	.segment "BANK_11"
	bits:
		.incbin "paniccut_17_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_17_slopes.bin"
.endscope

.scope piece12
	.include "paniccut_18_params.inc"
	bits_bank := $12
	slopes_bank := $22
	.segment "BANK_12"
	bits:
		.incbin "paniccut_18_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_18_slopes.bin"
.endscope

.scope piece13
	.include "paniccut_19_params.inc"
	bits_bank := $13
	slopes_bank := $22
	.segment "BANK_13"
	bits:
		.incbin "paniccut_19_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_19_slopes.bin"
.endscope

.scope piece14
	.include "paniccut_20_params.inc"
	bits_bank := $14
	slopes_bank := $22
	.segment "BANK_14"
	bits:
		.incbin "paniccut_20_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_20_slopes.bin"
.endscope

.scope piece15
	.include "paniccut_21_params.inc"
	bits_bank := $15
	slopes_bank := $22
	.segment "BANK_15"
	bits:
		.incbin "paniccut_21_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_21_slopes.bin"
.endscope

.scope piece16
	.include "paniccut_22_params.inc"
	bits_bank := $16
	slopes_bank := $22
	.segment "BANK_16"
	bits:
		.incbin "paniccut_22_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_22_slopes.bin"
.endscope

.scope piece17
	.include "paniccut_23_params.inc"
	bits_bank := $17
	slopes_bank := $22
	.segment "BANK_17"
	bits:
		.incbin "paniccut_23_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_23_slopes.bin"
.endscope

.scope piece18
	.include "paniccut_24_params.inc"
	bits_bank := $18
	slopes_bank := $22
	.segment "BANK_18"
	bits:
		.incbin "paniccut_24_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_24_slopes.bin"
.endscope

.scope piece19
	.include "paniccut_25_params.inc"
	bits_bank := $19
	slopes_bank := $22
	.segment "BANK_19"
	bits:
		.incbin "paniccut_25_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_25_slopes.bin"
.endscope

.scope piece1a
	.include "paniccut_26_params.inc"
	bits_bank := $1a
	slopes_bank := $22
	.segment "BANK_1a"
	bits:
		.incbin "paniccut_26_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_26_slopes.bin"
.endscope

.scope piece1b
	.include "paniccut_27_params.inc"
	bits_bank := $1b
	slopes_bank := $22
	.segment "BANK_1b"
	bits:
		.incbin "paniccut_27_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "paniccut_27_slopes.bin"
.endscope

.scope piece1c
	.include "paniccut_28_params.inc"
	bits_bank := $1c
	slopes_bank := $23
	.segment "BANK_1c"
	bits:
		.incbin "paniccut_28_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "paniccut_28_slopes.bin"
.endscope

.scope piece1d
	.include "paniccut_29_params.inc"
	bits_bank := $1d
	slopes_bank := $23
	.segment "BANK_1d"
	bits:
		.incbin "paniccut_29_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "paniccut_29_slopes.bin"
.endscope

.scope piece1e
	.include "paniccut_30_params.inc"
	bits_bank := $1e
	slopes_bank := $23
	.segment "BANK_1e"
	bits:
		.incbin "paniccut_30_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "paniccut_30_slopes.bin"
.endscope

.scope piece1f
	.include "paniccut_31_params.inc"
	bits_bank := $1f
	slopes_bank := $23
	.segment "BANK_1f"
	bits:
		.incbin "paniccut_31_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "paniccut_31_slopes.bin"
.endscope

.scope piece20
	.include "paniccut_32_params.inc"
	bits_bank := $20
	slopes_bank := $23
	.segment "BANK_20"
	bits:
		.incbin "paniccut_32_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "paniccut_32_slopes.bin"
.endscope

.scope piece21
	.include "paniccut_33_params.inc"
	bits_bank := $21
	slopes_bank := $23
	.segment "BANK_21"
	bits:
		.incbin "paniccut_33_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "paniccut_33_slopes.bin"
.endscope
