; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_disco_mario_or_something=music_data_disco_mario_or_something
.endif

music_data_disco_mario_or_something:
	.byte 13
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,313,261 ; 00 : Castleworld
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,317,264 ; 01 : Cloud
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256 ; 02 : Death
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,325,271 ; 03 : Enter in a pipe
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,296,247 ; 04 : Game Over
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,319,266 ; 05 : Hurry up
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,294,245 ; 06 : In an other castle
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,358,298 ; 07 : Overworld
	.word @song8ch0,@song8ch1,@song8ch2,@song8ch3,@song8ch4,266,221 ; 08 : Starman
	.word @song9ch0,@song9ch1,@song9ch2,@song9ch3,@song9ch4,307,256 ; 09 : Underworld
	.word @song10ch0,@song10ch1,@song10ch2,@song10ch3,@song10ch4,378,315 ; 0a : Victory
	.word @song11ch0,@song11ch1,@song11ch2,@song11ch3,@song11ch4,325,271 ; 0b : Waterworld
	.word @song12ch0,@song12ch1,@song12ch2,@song12ch3,@song12ch4,313,261 ; 0c : You saved the princess

.export music_data_disco_mario_or_something
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env11,@env13,@env0 ; 00 : bass1
	.word @env6,@env9,@env13,@env0 ; 01 : Blank
	.word @env16,@env8,@env14,@env0 ; 02 : Death effect
	.word @env12,@env8,@env14,@env0 ; 03 : Death effect 2
	.word @env21,@env9,@env14,@env0 ; 04 : Death instrument
	.word @env4,@env9,@env13,@env0 ; 05 : Drums Sus
	.word @env3,@env9,@env14,@env0 ; 06 : Instrumental
	.word @env7,@env9,@env14,@env0 ; 07 : Instrumental 2
	.word @env15,@env9,@env18,@env0 ; 08 : Long instrumental
	.word @env1,@env9,@env13,@env0 ; 09 : Noise long
	.word @env10,@env9,@env13,@env0 ; 0a : Noise short
	.word @env20,@env9,@env13,@env0 ; 0b : Sample Kick
	.word @env19,@env2,@env17,@env0 ; 0c : SqWoobble
	.word @env5,@env9,@env13,@env0 ; 0d : Triangle

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cc,$04,$c0,$00,$03
@env2:
	.byte $cc,$cc,$c0,$c0,$00,$00
@env3:
	.byte $00,$c8,$c8,$c7,$c6,$c5,$c5,$c4,$c3,$c0,$00,$09
@env4:
	.byte $00,$ce,$cc,$ca,$c8,$c6,$c3,$c2,$00,$07
@env5:
	.byte $00,$cf,$07,$c0,$00,$03
@env6:
	.byte $00,$cf,$7f,$00,$02
@env7:
	.byte $00,$cc,$02,$ca,$c3,$c3,$c2,$c0,$00,$07
@env8:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$0a
@env9:
	.byte $c0,$7f,$00,$01
@env10:
	.byte $00,$cc,$c0,$00,$02
@env11:
	.byte $bd,$ba,$b7,$b4,$00,$03
@env12:
	.byte $00,$c8,$c4,$c0,$00,$03
@env13:
	.byte $7f,$00,$00
@env14:
	.byte $c2,$7f,$00,$00
@env15:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env16:
	.byte $00,$ce,$cc,$cb,$ca,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$0b
@env17:
	.byte $c1,$7f,$00,$00
@env18:
	.byte $c0,$c2,$00,$01
@env19:
	.byte $0c,$ca,$c6,$c7,$c7,$c5,$c7,$c2,$04,$c1,$00,$09,$c1,$c0,$0f,$c0,$00,$0f
@env20:
	.byte $00,$c1,$7f,$00,$02
@env21:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c6,$c5,$c3,$c2,$c1,$c0,$00,$0c

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$68,$0f,$40 ; 00 kickcki1.dmc (Pitch:15)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 01 PERCUSSION 4.dmc (Pitch:15)

@song0ch0:
	.byte $45, $05
@song0ch0loop:
	.byte $81, $76, $8c
@song0ref7:
	.byte $1b, $81, $1a, $81, $19, $81, $1a, $81, $1b, $81, $1c, $81, $1b, $81, $1a, $81
	.byte $41, $10
	.word @song0ref7
	.byte $74
@song0ref27:
	.byte $27, $81, $26, $81, $25, $81, $26, $81, $27, $81, $28, $81, $27, $81, $26, $81
	.byte $41, $10
	.word @song0ref27
	.byte $77
	.byte $41, $10
	.word @song0ref7
	.byte $41, $10
	.word @song0ref7
@song0ref53:
	.byte $1a, $81, $19, $81, $1a, $81, $1b, $81, $1a, $81, $1b, $81, $1a, $81, $19, $81
	.byte $41, $10
	.word @song0ref53
	.byte $96
@song0ref73:
	.byte $1e, $81, $1f, $81, $1e, $81, $1d, $81, $1e, $81, $1d, $81, $1c, $81, $1d, $81
	.byte $41, $0f
	.word @song0ref73
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $76, $88
	.byte $41, $10
	.word @song0ref7
	.byte $41, $10
	.word @song0ref7
	.byte $78
	.byte $41, $10
	.word @song0ref7
	.byte $41, $10
	.word @song0ref7
	.byte $79
	.byte $41, $10
	.word @song0ref7
	.byte $41, $10
	.word @song0ref7
	.byte $41, $10
	.word @song0ref53
	.byte $41, $10
	.word @song0ref53
	.byte $41, $10
	.word @song0ref73
	.byte $41, $10
	.word @song0ref73
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $00, $bd, $bf, $82, $10, $9d, $0f, $8d, $13, $8d, $12, $9d, $11, $8d, $17, $8d, $16, $8d, $11, $8d, $10, $8d, $11, $8d
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $7f, $8a, $14, $00, $8b, $79, $1d, $81, $00, $89, $7f, $14, $00, $8b, $79, $1d, $81, $00, $89, $78, $14, $00, $14, $00
	.byte $1b, $81, $1b, $81, $14, $00, $79, $14, $00, $1b, $7a, $81, $1b, $81, $7b, $14, $00, $14, $7c, $00, $1b, $81, $1b, $81
	.byte $7f, $1b, $81, $1b, $81, $1b, $81, $1b, $81
@song0ref219:
	.byte $14, $00, $83, $76, $1b, $81, $1b, $81, $79, $1d, $81, $00, $81, $1b, $85, $7f, $14, $00, $83, $77, $1b, $81, $00, $81
	.byte $1d, $85, $1b, $85, $7f
	.byte $41, $18
	.word @song0ref219
	.byte $7f
	.byte $41, $18
	.word @song0ref219
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $bf, $01, $8d, $01, $8d, $01, $81, $01, $81, $01, $81, $01, $81, $01, $81, $01, $81, $01, $81, $01, $81
@song0ref280:
	.byte $01, $8d, $01, $8d, $01, $8d, $01, $8d, $01, $8d, $01, $8d
	.byte $41, $0c
	.word @song0ref280
	.byte $42
	.word @song0ch4loop
@song1ch0:
	.byte $45, $03
@song1ch0loop:
	.byte $7b, $98
@song1ref6:
	.byte $20, $89, $20, $89, $20, $89, $1d, $83, $20, $89, $20, $89, $1d, $83, $20, $83, $1d, $83, $20, $89, $20, $89, $20, $89
	.byte $20, $89, $1b, $83, $20, $89, $20, $89, $1b, $83, $20, $83, $1b, $83, $20, $89
	.byte $41, $28
	.word @song1ref6
@song1ref49:
	.byte $8b, $00, $85, $76, $8e
@song1ref54:
	.byte $27, $83, $29, $83, $2c, $83, $00, $83, $2c, $81, $00, $9d, $27, $81, $2c, $83, $00, $83, $a3, $72, $84, $38, $89, $74
	.byte $98, $14, $ad
	.byte $41, $1a
	.word @song1ref49
	.byte $41, $1a
	.word @song1ref49
	.byte $41, $1a
	.word @song1ref49
	.byte $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $7b, $98
@song1ref96:
	.byte $25, $89, $25, $89, $25, $8f, $27, $83, $00, $83, $27, $8f, $27, $89, $27, $89, $24, $89, $24, $89, $24, $8f, $24, $83
	.byte $00, $83, $24, $8f, $24, $89, $24, $89
	.byte $41, $20
	.word @song1ref96
	.byte $8b, $00, $85, $79
	.byte $41, $12
	.word @song1ref54
@song1ref138:
	.byte $33, $83, $2e, $83, $00, $83, $30, $83, $00, $89, $72, $1b
@song1ref150:
	.byte $73, $81, $81, $74, $81, $81, $75, $81, $81, $76, $81, $81, $77, $81, $81, $78, $81, $81, $79, $81, $81, $78, $8d, $77
	.byte $81, $76, $81, $81, $75, $81, $81, $74, $81, $81, $73, $81, $8b, $00, $85, $79
	.byte $41, $12
	.word @song1ref54
	.byte $2c, $83, $00, $9b, $72, $18
	.byte $41, $1a
	.word @song1ref150
	.byte $79
	.byte $41, $12
	.word @song1ref54
	.byte $41, $25
	.word @song1ref138
	.byte $79
	.byte $41, $12
	.word @song1ref54
	.byte $2c, $83, $00, $9b, $72, $18
	.byte $41, $17
	.word @song1ref150
	.byte $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $90
@song1ref227:
	.byte $0d, $89, $25, $89, $0d, $89, $25, $89, $0f, $89, $27, $89, $0f, $89, $27, $89, $14, $89, $20, $89, $14, $89, $20, $89
	.byte $14, $89, $20, $89, $14, $89, $20, $89
	.byte $41, $20
	.word @song1ref227
	.byte $41, $20
	.word @song1ref227
	.byte $41, $20
	.word @song1ref227
	.byte $41, $20
	.word @song1ref227
	.byte $41, $20
	.word @song1ref227
	.byte $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $7f, $94
@song1ref280:
	.byte $15, $89, $79, $1e, $85, $1e, $81, $76, $92, $1e, $89, $78, $94, $1e, $85, $1e, $81, $7f, $15, $89, $79, $1e, $85, $1e
	.byte $81, $76, $92, $1e, $89, $78, $94, $1e, $85, $1e, $81, $7f
	.byte $41, $18
	.word @song1ref280
	.byte $7f
	.byte $41, $18
	.word @song1ref280
	.byte $7f
	.byte $41, $18
	.word @song1ref280
	.byte $7f
	.byte $41, $18
	.word @song1ref280
	.byte $7f
	.byte $41, $18
	.word @song1ref280
	.byte $7f
	.byte $41, $18
	.word @song1ref280
@song1ref339:
	.byte $15, $89, $1e, $85, $1e, $81, $79, $92, $1e, $89, $7f, $94, $1e, $85, $1e, $81, $15, $89, $1e, $85, $1e, $81, $79, $92
	.byte $1e, $89, $7f, $94, $1e, $85, $1e, $81
	.byte $41, $18
	.word @song1ref280
	.byte $7f
	.byte $41, $18
	.word @song1ref280
	.byte $7f
	.byte $41, $18
	.word @song1ref280
	.byte $41, $18
	.word @song1ref339
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $df, $df, $df, $df
@song1ref393:
	.byte $97, $02, $ad, $02, $95, $97, $02, $ad, $02, $95, $97, $02, $ad, $02, $95, $97, $02, $ad, $02, $95
	.byte $41, $14
	.word @song1ref393
	.byte $42
	.word @song1ch4loop
@song2ch0:
	.byte $45, $03, $7a, $84, $22, $23, $24, $86, $21, $8f, $7b, $8e, $1b, $83, $22, $89, $22, $83, $22, $85, $20, $85, $1b, $85
	.byte $84, $1f, $83, $1c, $89, $1c, $83, $18, $8f
@song2ch0loop:
	.byte $97, $42
	.word @song2ch0loop
@song2ch1:
	.byte $97, $7b, $88, $24, $83, $2a, $89, $2a, $83, $2a, $85, $29, $85, $27, $85, $25, $a7
@song2ch1loop:
	.byte $97, $42
	.word @song2ch1loop
@song2ch2:
	.byte $97, $90, $14, $89, $20, $89, $14, $89, $20, $89, $0d, $89, $19, $89, $0d, $85, $00, $87
@song2ch2loop:
	.byte $97, $42
	.word @song2ch2loop
@song2ch3:
	.byte $97, $d9
@song2ch3loop:
	.byte $97, $42
	.word @song2ch3loop
@song2ch4:
	.byte $97, $01, $95, $02, $95, $01, $95, $02, $8f
@song2ch4loop:
	.byte $97, $42
	.word @song2ch4loop
@song3ch0:
	.byte $45, $03, $7c, $8c, $1e, $83, $1e, $89, $1e, $89, $1e, $83, $1e, $89, $23, $95, $7d, $24, $95, $26, $95, $7f, $2b, $95
@song3ch0loop:
	.byte $00, $95, $42
	.word @song3ch0loop
@song3ch1:
	.byte $7b, $8c, $28, $83, $28, $89, $28, $89, $24, $83, $28, $89, $7c, $2b, $95, $7d, $1f, $95, $23, $95, $7f, $26, $95
@song3ch1loop:
	.byte $00, $95, $42
	.word @song3ch1loop
@song3ch2:
	.byte $82, $0e, $89, $1a, $89, $0e, $89, $1a, $89, $13, $89, $1f, $89, $15, $89, $21, $89, $17, $89, $23, $89, $1a, $89, $26
	.byte $89
@song3ch2loop:
	.byte $00, $95, $42
	.word @song3ch2loop
@song3ch3:
	.byte $94, $20, $89, $20, $83, $20, $89, $20, $83, $20, $89, $8a, $21, $00, $81, $74, $1a, $83, $75, $19, $83, $74, $19, $83
	.byte $19, $83, $73, $17, $83, $17, $83, $74, $17, $83, $75, $17, $83, $17, $83, $76, $17, $83, $7a, $17, $83, $7f, $1b, $81
	.byte $00, $1c, $81, $00, $1c, $81, $00, $1c, $81, $00
@song3ch3loop:
	.byte $00, $95, $42
	.word @song3ch3loop
@song3ch4:
	.byte $df, $01, $89, $01, $89, $01, $83, $01, $83, $01, $83, $01, $83
@song3ch4loop:
	.byte $00, $95, $42
	.word @song3ch4loop
@song4ch0:
	.byte $45, $03, $7c, $90, $1d, $83, $00, $89, $19, $83, $00, $89, $14, $89, $1e, $95, $1b, $95, $1d, $83, $1b, $83, $1d, $a1
	.byte $00, $89
@song4ch0loop:
	.byte $97, $42
	.word @song4ch0loop
@song4ch1:
@song4ref32:
	.byte $7c, $90, $25, $83, $00, $89, $20, $83, $00, $89, $1d, $89, $21, $85, $23, $85, $21, $85, $20, $85, $22, $85, $20, $85
	.byte $20, $b9
@song4ch1loop:
	.byte $97, $42
	.word @song4ch1loop
@song4ch2:
	.byte $41, $0b
	.word @song4ref32
	.byte $95, $23, $95, $25, $b9
@song4ch2loop:
	.byte $97, $42
	.word @song4ch2loop
@song4ch3:
	.byte $ff, $9b
@song4ch3loop:
	.byte $97, $42
	.word @song4ch3loop
@song4ch4:
	.byte $ff, $87, $01, $83, $01, $83, $02, $85
@song4ch4loop:
	.byte $97, $42
	.word @song4ch4loop
@song5ch0:
	.byte $45, $03, $90, $11, $00, $21, $81, $00, $81, $21, $81, $21, $81, $00, $81, $12, $81, $22, $81, $00, $81, $22, $81, $22
	.byte $81, $00, $81, $13, $81, $23, $81, $00, $81, $23, $81, $23, $81, $00, $81, $24, $81, $00, $81, $24, $9d
@song5ch0loop:
	.byte $00, $81, $42
	.word @song5ch0loop
@song5ch1:
	.byte $90, $1d, $81, $27, $85, $27, $81, $27, $85, $1e, $81, $28, $85, $28, $81, $28, $85, $1f, $81, $29, $85, $29, $81, $29
	.byte $85, $2a, $85, $2a, $9d
@song5ch1loop:
	.byte $00, $81, $42
	.word @song5ch1loop
@song5ch2:
	.byte $9a, $24, $81, $30, $85, $30, $81, $30, $85, $25, $81, $31, $85, $31, $81, $31, $85, $26, $81, $32, $85, $32, $81, $32
	.byte $85, $20, $85, $82, $20, $9d
@song5ch2loop:
	.byte $00, $81, $42
	.word @song5ch2loop
@song5ch3:
	.byte $ef
@song5ch3loop:
	.byte $83, $42
	.word @song5ch3loop
@song5ch4:
	.byte $ef
@song5ch4loop:
	.byte $83, $42
	.word @song5ch4loop
@song6ch0:
	.byte $45, $03, $7c, $90, $1d, $83, $00, $89, $19, $83, $00, $89, $14, $89, $1e, $95, $1b, $95, $1d, $83, $1b, $83, $1d, $a1
	.byte $00, $ff
@song6ch0loop:
	.byte $97, $42
	.word @song6ch0loop
@song6ch1:
	.byte $7c, $90, $25, $83, $00, $89, $20, $83, $00, $89, $1d, $89, $21, $85, $23, $85, $21, $85, $20, $85, $22, $85, $20, $85
	.byte $20, $ff, $af
@song6ch1loop:
	.byte $97, $42
	.word @song6ch1loop
@song6ch2:
	.byte $90, $0d, $89, $19, $89, $0d, $89, $19, $89, $15, $89, $21, $89, $17, $89, $23, $89, $25, $ff, $af
@song6ch2loop:
	.byte $97, $42
	.word @song6ch2loop
@song6ch3:
	.byte $94
@song6ref90:
	.byte $20, $89, $20, $83, $20, $89, $20, $83, $20, $89, $7b, $8a, $1a, $81, $00, $81, $74, $1a, $85, $75, $19, $74, $00, $83
	.byte $19, $83, $73, $17, $83, $17, $83, $74, $17, $83, $7f, $94, $20, $89, $20, $83, $20, $89, $20, $83, $20, $83, $20, $83
	.byte $41, $20
	.word @song6ref90
	.byte $8d
@song6ch3loop:
	.byte $97, $42
	.word @song6ch3loop
@song6ch4:
@song6ref147:
	.byte $01, $95, $02, $95, $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $0b
	.word @song6ref147
	.byte $87
@song6ch4loop:
	.byte $97, $42
	.word @song6ch4loop
@song7ch0:
	.byte $45, $03
@song7ch0loop:
	.byte $7c, $8c
@song7ref6:
	.byte $1f, $83, $1f, $89, $1f, $89, $1f, $83, $1f, $89, $24, $95, $7d, $25, $95, $27, $95, $7f, $2c, $95
@song7ref26:
	.byte $1d, $8f, $19, $8f, $14, $8f, $19, $89, $1b, $89, $1a, $83, $19, $89, $19, $85, $20, $85, $24, $85, $25, $89, $22, $83
	.byte $24, $89, $22, $89, $1d, $83, $1e, $83, $1b, $8f
	.byte $41, $22
	.word @song7ref26
@song7ref63:
	.byte $8b, $29, $83, $28, $83, $27, $83, $24, $89, $25, $89, $1d, $83, $1e, $83, $20, $89, $19, $83, $1d, $83, $1e, $83
	.byte $41, $0b
	.word @song7ref63
	.byte $2a, $89, $2a, $83, $2a, $95
	.byte $41, $17
	.word @song7ref63
	.byte $8b, $21, $8f, $1e, $8f, $1d, $ad, $8b, $21, $8f, $1e, $8f, $1d, $ad, $8b, $21, $8f, $1e, $8f, $98, $1d, $ad, $8c
@song7ref121:
	.byte $21, $83, $21, $89, $21, $89, $21, $83, $23, $89, $20, $83, $1d, $89, $1d, $83, $19, $95, $21, $83, $21, $89, $21, $89
	.byte $21, $83, $23, $83, $20, $b3
	.byte $41, $12
	.word @song7ref121
	.byte $7c
	.byte $41, $12
	.word @song7ref6
@song7ref158:
	.byte $25, $83, $22, $89, $1d, $8f, $1d, $89, $1e, $83, $25, $89, $25, $83, $1e, $95, $20, $85, $2a, $85, $2a, $85, $2a, $85
	.byte $29, $85, $27, $85, $25, $83, $22, $89, $1e, $83, $1d, $95
	.byte $41, $12
	.word @song7ref158
@song7ref197:
	.byte $27, $85, $27, $83, $27, $85, $25, $85, $24, $85, $20, $83, $1d, $89, $1d, $83, $19, $97
	.byte $41, $24
	.word @song7ref158
	.byte $41, $12
	.word @song7ref158
	.byte $41, $12
	.word @song7ref197
	.byte $41, $1e
	.word @song7ref121
	.byte $41, $12
	.word @song7ref121
	.byte $42
	.word @song7ch0loop
@song7ch1:
@song7ch1loop:
@song7ref234:
	.byte $7b, $8c, $29, $83, $29, $89, $29, $89, $25, $83, $29, $89, $7c, $2c, $95, $7d, $20, $95, $24, $95, $7f, $27, $95, $98
@song7ref258:
	.byte $19, $8f, $14, $8f, $11, $8f, $16, $89, $18, $89, $17, $83, $16, $89, $14, $85, $1d, $85, $20, $85, $22, $89, $1e, $83
	.byte $20, $89, $1d, $89, $19, $83, $1b, $83, $18, $8f
	.byte $41, $22
	.word @song7ref258
@song7ref295:
	.byte $8b, $20, $83, $1f, $83, $1e, $83, $1c, $89, $1d, $89, $15, $83, $16, $83, $19, $89, $16, $83, $19, $83, $1b, $83
	.byte $41, $0b
	.word @song7ref295
	.byte $25, $89, $25, $83, $25, $89, $00, $89
	.byte $41, $17
	.word @song7ref295
	.byte $8b, $1c, $8f, $1b, $8f, $19, $8d, $00, $9d, $8b, $1c, $8f, $1b, $8f, $19, $8d, $00, $9d, $8b, $28, $8f, $27, $8f, $25
	.byte $ad
@song7ref357:
	.byte $25, $83, $25, $89, $25, $89, $25, $83, $27, $89, $29, $83, $25, $89, $22, $83, $20, $95, $25, $83, $25, $89, $25, $89
	.byte $25, $83, $27, $83, $29, $b3
	.byte $41, $12
	.word @song7ref357
	.byte $41, $12
	.word @song7ref234
	.byte $98
@song7ref394:
	.byte $29, $83, $25, $89, $20, $8f, $21, $89, $22, $83, $2a, $89, $2a, $83, $22, $95, $24, $85, $2e, $85, $2e, $85, $2e, $85
	.byte $2c, $85, $2a, $85, $29, $83, $25, $89, $22, $83, $20, $95
	.byte $41, $12
	.word @song7ref394
@song7ref433:
	.byte $2a, $85, $2a, $83, $2a, $85, $29, $85, $27, $85, $25, $af
	.byte $41, $24
	.word @song7ref394
	.byte $41, $12
	.word @song7ref394
	.byte $41, $0c
	.word @song7ref433
	.byte $41, $1e
	.word @song7ref357
	.byte $41, $12
	.word @song7ref357
	.byte $42
	.word @song7ch1loop
@song7ch2:
@song7ch2loop:
	.byte $82
@song7ref465:
	.byte $0f, $89, $1b, $89, $0f, $89, $1b, $89, $14, $89, $20, $89, $16, $89, $22, $89, $18, $89, $24, $89, $1b, $89, $27
@song7ref488:
	.byte $89
@song7ref489:
	.byte $0d, $89, $19, $89, $0d, $89, $19, $89, $0d, $89, $19, $89, $0d, $89, $19, $89, $0d, $89, $19, $89, $11, $89, $1d, $89
	.byte $12, $89, $1e, $89, $13, $89, $20
	.byte $41, $20
	.word @song7ref488
@song7ref523:
	.byte $89, $0d, $89, $19, $89, $0d, $89, $19, $89, $12, $89, $1e, $89, $14, $89, $20, $89, $0d, $89, $19, $89, $0d, $89, $19
	.byte $89, $12, $83, $00, $89, $14, $83, $20, $89, $14
	.byte $41, $11
	.word @song7ref523
@song7ref560:
	.byte $15, $89, $21, $89, $17, $89, $23, $89, $19, $89, $25, $89, $19, $89, $25, $89
	.byte $41, $10
	.word @song7ref560
	.byte $41, $10
	.word @song7ref560
@song7ref582:
	.byte $15, $89, $21, $89, $15, $89, $21, $89, $0d, $89, $19, $89, $0d, $89, $19, $89
	.byte $41, $10
	.word @song7ref582
	.byte $41, $10
	.word @song7ref582
	.byte $41, $18
	.word @song7ref465
	.byte $8a
	.byte $41, $14
	.word @song7ref489
	.byte $41, $14
	.word @song7ref489
@song7ref614:
	.byte $0d, $89, $19, $89, $0d, $89, $19, $89, $14, $89, $20, $89, $16, $89, $24, $89, $19, $89, $25, $89, $19, $89, $25
	.byte $41, $15
	.word @song7ref488
	.byte $41, $14
	.word @song7ref489
	.byte $41, $17
	.word @song7ref614
	.byte $89, $82
	.byte $41, $10
	.word @song7ref582
	.byte $41, $10
	.word @song7ref582
	.byte $41, $10
	.word @song7ref582
	.byte $42
	.word @song7ch2loop
@song7ch3:
@song7ch3loop:
	.byte $7f, $94
@song7ref663:
	.byte $20, $89, $20, $83, $20, $89, $20, $83, $20, $89, $8a, $21, $00, $81, $74, $1a, $83, $75, $19, $83, $74, $19, $83, $19
	.byte $83, $73, $17, $83, $17, $83, $74, $17, $83, $75
@song7ref697:
	.byte $17, $83, $17, $83, $76, $17, $83, $7a
@song7ref705:
	.byte $17, $83, $7f, $1b, $81, $00, $1c, $81, $00, $1c, $81, $00, $1c, $81, $00
@song7ref720:
	.byte $92, $14, $00, $87, $94, $20, $85, $20, $81, $92, $20, $89, $94, $20, $85, $20, $81
	.byte $41, $0d
	.word @song7ref720
	.byte $41, $0d
	.word @song7ref720
	.byte $41, $0d
	.word @song7ref720
	.byte $41, $0d
	.word @song7ref720
	.byte $41, $0d
	.word @song7ref720
	.byte $41, $0d
	.word @song7ref720
	.byte $41, $0d
	.word @song7ref720
@song7ref758:
	.byte $92, $14, $00
@song7ref761:
	.byte $81, $94, $20, $83, $20, $83, $20, $83, $7b, $8a, $19, $83, $7f, $94, $20, $83, $20, $83, $20, $83
	.byte $41, $11
	.word @song7ref758
	.byte $41, $11
	.word @song7ref758
@song7ref787:
	.byte $92, $14, $00, $81, $14, $00, $81, $94, $20, $83, $92, $14, $00, $81, $7b, $8a, $19, $83, $7f, $94, $20, $83, $20, $83
	.byte $20, $83
	.byte $41, $11
	.word @song7ref758
	.byte $41, $11
	.word @song7ref758
	.byte $41, $0d
	.word @song7ref720
	.byte $41, $0d
	.word @song7ref720
	.byte $41, $0d
	.word @song7ref720
	.byte $41, $0d
	.word @song7ref720
	.byte $8a, $21, $83, $74, $18, $83, $75, $18, $83, $74, $18, $83, $18, $83, $73, $17, $83, $17, $83, $74, $17, $83, $7f, $92
	.byte $14, $00, $81, $75, $8a, $17, $83, $17, $83, $76
	.byte $41, $10
	.word @song7ref705
	.byte $41, $0f
	.word @song7ref761
	.byte $41, $13
	.word @song7ref787
	.byte $41, $11
	.word @song7ref758
	.byte $41, $13
	.word @song7ref787
	.byte $41, $11
	.word @song7ref758
	.byte $41, $13
	.word @song7ref787
	.byte $41, $31
	.word @song7ref663
	.byte $41, $0f
	.word @song7ref761
	.byte $41, $13
	.word @song7ref787
	.byte $41, $11
	.word @song7ref758
	.byte $41, $13
	.word @song7ref787
	.byte $41, $11
	.word @song7ref758
	.byte $41, $13
	.word @song7ref787
	.byte $41, $11
	.word @song7ref758
	.byte $41, $13
	.word @song7ref787
	.byte $41, $11
	.word @song7ref758
	.byte $41, $11
	.word @song7ref758
	.byte $41, $11
	.word @song7ref758
	.byte $41, $11
	.word @song7ref758
	.byte $41, $11
	.word @song7ref758
	.byte $41, $13
	.word @song7ref787
	.byte $75, $8a
	.byte $41, $16
	.word @song7ref697
	.byte $41, $0f
	.word @song7ref761
@song7ref939:
	.byte $92, $14, $00, $81, $94, $20, $83, $20, $83, $20, $83, $8a, $18, $81, $00, $85, $94, $20, $83, $20, $83
	.byte $41, $0c
	.word @song7ref939
	.byte $94, $20, $83, $20, $83, $20, $83
	.byte $41, $11
	.word @song7ref939
	.byte $41, $0c
	.word @song7ref939
	.byte $94, $20, $83, $20, $83, $20, $83
	.byte $41, $11
	.word @song7ref758
	.byte $41, $13
	.word @song7ref787
	.byte $42
	.word @song7ch3loop
@song7ch4:
@song7ch4loop:
@song7ref993:
	.byte $01, $89, $00, $89, $01, $89, $00, $89
@song7ref1001:
	.byte $01, $95, $01, $95, $01, $89, $01, $89, $01, $83, $01, $83, $01, $83, $01, $83
@song7ref1017:
	.byte $01, $95, $01, $95, $01, $95, $01, $95, $01, $95, $01, $95
	.byte $41, $0c
	.word @song7ref1017
	.byte $41, $0c
	.word @song7ref1017
	.byte $41, $0c
	.word @song7ref1017
	.byte $41, $0c
	.word @song7ref1017
	.byte $41, $0c
	.word @song7ref1017
	.byte $41, $0c
	.word @song7ref1017
	.byte $41, $0c
	.word @song7ref1017
	.byte $01, $95, $01, $95, $01, $95, $01, $95
	.byte $41, $24
	.word @song7ref993
	.byte $41, $0c
	.word @song7ref1017
	.byte $41, $0c
	.word @song7ref1017
	.byte $41, $0c
	.word @song7ref1017
	.byte $01, $95, $01, $95
	.byte $41, $1c
	.word @song7ref1001
	.byte $41, $0c
	.word @song7ref1017
	.byte $01, $95, $01, $95, $42
	.word @song7ch4loop
@song8ch0:
	.byte $45, $02
@song8ch0loop:
	.byte $7a, $98
@song8ref6:
	.byte $21, $89, $21, $89, $21, $89, $1e, $83, $21, $89, $21, $89, $1e, $83, $21, $83, $1e, $83, $21, $89, $21, $89, $21, $89
	.byte $21, $89, $1c, $83, $21, $89, $21, $89, $1c, $83, $21, $83, $1c, $83, $21, $89
	.byte $41, $28
	.word @song8ref6
	.byte $42
	.word @song8ch0loop
@song8ch1:
@song8ch1loop:
	.byte $7d, $98
@song8ref55:
	.byte $1a, $89, $1a, $89, $1a, $8f, $1c, $83, $00, $83, $1c, $8f, $1c, $89, $1c, $89, $19, $89, $19, $89, $19, $8f, $19, $83
	.byte $00, $83, $19, $8f, $19, $89, $19, $89
	.byte $41, $20
	.word @song8ref55
	.byte $42
	.word @song8ch1loop
@song8ch2:
@song8ch2loop:
	.byte $90
@song8ref95:
	.byte $0e, $89, $26, $89, $0e, $89, $26, $89, $10, $89, $28, $89, $10, $89, $28, $89, $15, $89, $21, $89, $15, $89, $21, $89
	.byte $15, $89, $21, $89, $15, $89, $21, $89
	.byte $41, $20
	.word @song8ref95
	.byte $42
	.word @song8ch2loop
@song8ch3:
@song8ch3loop:
	.byte $7f, $94
@song8ref136:
	.byte $15, $89, $79, $1e, $85, $1e, $81, $76, $92, $1e, $89, $78, $94, $1e, $85, $1e, $81, $7f, $15, $89, $79, $1e, $85, $1e
	.byte $81, $76, $92, $1e, $89, $78, $94, $1e, $85, $1e, $81, $7f
	.byte $41, $18
	.word @song8ref136
	.byte $7f
	.byte $41, $18
	.word @song8ref136
	.byte $7f
	.byte $41, $18
	.word @song8ref136
	.byte $42
	.word @song8ch3loop
@song8ch4:
@song8ch4loop:
	.byte $df, $df, $df, $df, $42
	.word @song8ch4loop
@song9ch0:
	.byte $45, $04
@song9ch0loop:
@song9ref4:
	.byte $76, $9a
@song9ref6:
	.byte $01, $83, $0d, $83, $40, $0a, $83, $0a, $83, $40, $0b, $83, $0b, $bf
	.byte $41, $0c
	.word @song9ref6
@song9ref23:
	.byte $06, $83, $12, $83, $03, $83, $0f, $83, $04, $83, $10, $bf
	.byte $41, $0c
	.word @song9ref23
	.byte $41, $0b
	.word @song9ref6
	.byte $83, $71, $84, $1f, $83, $98, $1f
@song9ref48:
	.byte $81, $83, $73, $83, $74, $83, $75, $83, $76, $83, $7a, $83, $7b, $83, $7c, $83, $7d, $83, $7f, $83, $74, $83, $70, $83
	.byte $81
	.byte $41, $0b
	.word @song9ref4
	.byte $83, $71, $84, $23, $83, $98, $23
	.byte $41, $0e
	.word @song9ref48
	.byte $76, $9a
	.byte $41, $0b
	.word @song9ref23
	.byte $83, $71, $84, $2f, $83, $98, $15
	.byte $41, $0e
	.word @song9ref48
	.byte $76, $9a
	.byte $41, $0b
	.word @song9ref23
	.byte $83, $71, $84, $2f, $83, $98, $21
	.byte $41, $0a
	.word @song9ref48
	.byte $7f, $81, $7a, $8c, $1c, $81, $1b, $81, $1a, $81, $19, $89, $1c, $89, $1b, $89, $15, $89, $14, $89, $1a, $89, $19, $81
	.byte $1f, $81, $1e, $81, $1d, $81, $23, $81, $22, $81, $21, $85, $1c, $85, $18, $85, $17, $85, $16, $85, $15, $85, $71, $98
	.byte $1b
	.byte $41, $0a
	.word @song9ref48
	.byte $7f, $87, $70, $af, $42
	.word @song9ch0loop
@song9ch1:
@song9ch1loop:
@song9ref176:
	.byte $7f, $8c
@song9ref178:
	.byte $19, $83, $25
@song9ref181:
	.byte $83, $16, $83, $22, $83, $17, $83, $23, $bf
	.byte $41, $0c
	.word @song9ref178
@song9ref193:
	.byte $12, $83, $1e, $83, $0f, $83, $1b, $83, $10, $83, $1c, $bf
	.byte $41, $0c
	.word @song9ref193
	.byte $41, $0b
	.word @song9ref178
	.byte $83, $71, $84, $28, $83, $98, $28
@song9ref218:
	.byte $81, $83, $73, $83, $74, $83, $75, $83, $76, $83, $79, $83, $7a, $83, $7c, $83, $7d, $83, $7f, $83, $74, $83, $71, $83
	.byte $70, $81
	.byte $41, $0b
	.word @song9ref176
	.byte $83, $71, $84, $2c, $83, $98, $2c
	.byte $41, $0e
	.word @song9ref218
	.byte $78, $8c
	.byte $41, $0b
	.word @song9ref193
	.byte $83, $71, $84, $2c, $83, $98, $1e
	.byte $41, $0e
	.word @song9ref218
	.byte $79, $8c
	.byte $41, $0b
	.word @song9ref193
	.byte $83, $71, $84, $2c, $83, $98, $1e
	.byte $41, $0a
	.word @song9ref218
	.byte $7f, $81, $7b, $8c, $28, $81, $27, $81, $26, $81, $25, $89, $28, $89, $27, $89, $21, $89, $20, $89, $26, $89, $25, $81
	.byte $2b, $81, $2a, $81, $29, $81, $2f, $81, $2e, $81, $2d, $85, $28, $85, $24, $85, $23, $85, $22, $85, $21, $85, $71, $98
	.byte $20
	.byte $41, $0a
	.word @song9ref218
	.byte $7f, $87, $70, $af, $42
	.word @song9ch1loop
@song9ch2:
@song9ch2loop:
	.byte $90
	.byte $41, $0b
	.word @song9ref178
	.byte $83, $18, $83, $19, $83
	.byte $41, $0b
	.word @song9ref178
	.byte $83, $18, $83, $24, $83
	.byte $41, $0b
	.word @song9ref178
	.byte $83, $18, $83, $19, $83
	.byte $41, $0b
	.word @song9ref178
	.byte $83, $18, $83, $24, $83
	.byte $41, $0b
	.word @song9ref193
	.byte $83, $11, $83, $12, $83
	.byte $41, $0b
	.word @song9ref193
	.byte $83, $11, $83, $1d, $83
	.byte $41, $0b
	.word @song9ref193
	.byte $83, $11, $83, $12, $83
	.byte $41, $0b
	.word @song9ref193
	.byte $83, $11, $83, $1d, $83
	.byte $41, $0b
	.word @song9ref178
	.byte $83, $18, $83, $19, $83
	.byte $41, $0b
	.word @song9ref178
	.byte $83, $18, $83, $24, $83
	.byte $41, $0b
	.word @song9ref178
	.byte $83, $18, $83, $19, $83
	.byte $41, $0b
	.word @song9ref178
	.byte $83, $18, $83, $24, $83
	.byte $41, $0b
	.word @song9ref193
	.byte $83, $11, $83, $12, $83
	.byte $41, $0b
	.word @song9ref193
	.byte $83, $11, $83, $1d, $83
	.byte $41, $0b
	.word @song9ref193
	.byte $83, $11, $83, $12, $83
	.byte $41, $0b
	.word @song9ref193
	.byte $83, $1b, $83, $1a, $83, $19, $83, $25, $83, $19, $83, $25, $83, $17, $83, $23, $83, $17, $83, $23, $83, $16, $83, $22
	.byte $83, $16, $83, $22, $83, $15, $83, $21, $83, $15, $83, $21, $83, $14, $83, $20, $83, $14, $83, $20, $83, $14, $83, $20
	.byte $83, $14, $83, $14, $83, $14, $83, $20, $83, $11, $83, $1d, $83, $12, $83, $1e, $83, $13, $83, $14, $83, $14, $83, $20
	.byte $41, $08
	.word @song9ref181
	.byte $83, $18, $83, $24, $83, $42
	.word @song9ch2loop
@song9ch3:
@song9ch3loop:
	.byte $7f, $94
@song9ref557:
	.byte $14
@song9ref558:
	.byte $00, $81, $73, $1f, $83
@song9ref563:
	.byte $1f, $83
@song9ref565:
	.byte $1f, $83, $7f, $1d, $83, $73, $1f, $83, $1f, $83, $1f, $83, $7f, $14, $83, $7d, $15, $00, $81, $7f, $14, $83, $73
	.byte $41, $0b
	.word @song9ref565
	.byte $41, $17
	.word @song9ref558
	.byte $73
	.byte $41, $0b
	.word @song9ref565
	.byte $41, $17
	.word @song9ref558
	.byte $73
	.byte $41, $0b
	.word @song9ref565
	.byte $41, $17
	.word @song9ref558
	.byte $73
	.byte $41, $0c
	.word @song9ref565
	.byte $73, $1f, $1f, $81
	.byte $41, $0a
	.word @song9ref563
@song9ref619:
	.byte $7f, $14, $83, $74, $1f, $83, $7d, $15, $00, $81, $7f, $14, $83, $73
	.byte $41, $0c
	.word @song9ref565
	.byte $73, $1f, $1f, $81
	.byte $41, $0a
	.word @song9ref563
	.byte $41, $09
	.word @song9ref619
	.byte $73
	.byte $41, $0b
	.word @song9ref565
	.byte $41, $17
	.word @song9ref558
	.byte $73
	.byte $41, $0b
	.word @song9ref565
	.byte $41, $17
	.word @song9ref558
	.byte $73
	.byte $41, $0b
	.word @song9ref565
	.byte $41, $17
	.word @song9ref558
	.byte $73, $1f, $83, $7b, $1d, $81, $1d, $81, $1d, $81, $1d, $81, $1d, $81, $7f, $1d, $81
	.byte $41, $18
	.word @song9ref557
	.byte $73
	.byte $41, $0b
	.word @song9ref565
	.byte $41, $10
	.word @song9ref558
	.byte $42
	.word @song9ch3loop
@song9ch4:
@song9ch4loop:
@song9ref698:
	.byte $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $08
	.word @song9ref698
	.byte $41, $08
	.word @song9ref698
	.byte $41, $08
	.word @song9ref698
@song9ref715:
	.byte $01, $89, $00, $89, $02, $95, $01, $89, $00, $89, $02, $95
	.byte $41, $0c
	.word @song9ref715
	.byte $41, $0c
	.word @song9ref715
	.byte $41, $0c
	.word @song9ref715
@song9ref736:
	.byte $01, $89, $02, $89, $01, $89, $02, $89
	.byte $41, $08
	.word @song9ref736
	.byte $41, $08
	.word @song9ref736
	.byte $41, $08
	.word @song9ref736
	.byte $41, $08
	.word @song9ref736
	.byte $42
	.word @song9ch4loop
@song10ch0:
	.byte $45, $04, $90
@song10ref4:
	.byte $14, $81, $19, $81, $1d, $81, $20, $81, $25, $81, $29, $81, $2c, $89, $29, $89
@song10ref20:
	.byte $15, $81, $19, $81, $1c, $81, $21, $81, $25, $81, $28, $81, $2d, $89, $28, $89
@song10ref36:
	.byte $17, $81, $1b, $81, $1e, $81, $23, $81, $27, $81, $2a, $81, $2f, $89, $2f, $81, $2f, $81, $2f, $81, $29, $8f, $00, $9b
@song10ch0loop:
	.byte $af, $42
	.word @song10ch0loop
@song10ch1:
	.byte $83, $90, $11, $81
	.byte $41, $09
	.word @song10ref4
	.byte $89, $20, $89, $00, $81, $10, $81
	.byte $41, $09
	.word @song10ref20
	.byte $89, $21, $89, $00, $81, $12, $81
	.byte $41, $09
	.word @song10ref36
	.byte $89, $27, $89, $31, $8f, $00, $9b
@song10ch1loop:
	.byte $af, $42
	.word @song10ch1loop
@song10ch2:
	.byte $88, $0d, $89, $19, $89, $0d, $89, $19, $89, $09, $89, $15, $89, $09, $89, $15, $89, $17, $89, $23, $89, $17, $89, $23
	.byte $89, $90, $0d, $95, $00, $95
@song10ch2loop:
	.byte $af, $42
	.word @song10ch2loop
@song10ch3:
	.byte $df, $df
@song10ch3loop:
	.byte $af, $42
	.word @song10ch3loop
@song10ch4:
@song10ref146:
	.byte $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $08
	.word @song10ref146
@song10ch4loop:
	.byte $af, $42
	.word @song10ch4loop
@song11ch0:
	.byte $45, $03, $90
@song11ref4:
	.byte $19, $85, $18, $85, $17, $85, $16, $85, $17, $85, $18, $85, $19, $81, $19, $81, $19, $81, $00, $81, $1b, $81, $00, $81
	.byte $1c, $91, $00, $81
@song11ch0loop:
	.byte $90, $1e, $95, $1d, $95, $1e, $ad, $1e, $95, $1d, $8d, $20, $85, $1e, $ad, $1c, $95, $1b, $95, $1c, $ad, $1c, $95, $16
	.byte $8d, $20, $85, $1e, $ad, $27, $89, $76, $84, $25, $89, $7f, $90, $25, $89, $76, $84, $25, $89, $7f, $90, $24, $89, $75
	.byte $84, $24, $89, $90, $36, $85, $38, $81, $00, $85, $36, $81, $7f, $25, $89, $75, $84, $25, $89, $7f, $90, $24, $89, $75
	.byte $84, $24, $89, $7f, $90, $23, $89, $75, $84, $23, $89, $90, $34, $85, $36, $81, $00, $85, $34, $81, $7f, $17, $95, $1c
	.byte $85, $1e, $85, $22, $85, $22, $81, $22, $81, $22, $89, $1c, $81, $1b, $95
	.byte $41, $1c
	.word @song11ref4
	.byte $42
	.word @song11ch0loop
@song11ch1:
	.byte $90
@song11ref151:
	.byte $19, $85, $1b, $85, $1d, $85, $1e, $85, $20, $85, $21, $85, $22, $81, $22, $81, $22, $81, $00, $81, $22, $81, $00, $81
	.byte $22, $8d, $1e, $85
@song11ch1loop:
	.byte $90, $27, $95, $26, $95, $27
@song11ref186:
	.byte $99, $1e, $81, $20, $81, $22, $81, $23, $81, $25, $81, $27, $95, $26, $8d, $28, $85, $27, $a9, $1e, $81, $25, $95, $24
	.byte $95, $25
	.byte $41, $09
	.word @song11ref186
	.byte $24, $81, $25, $95, $1e, $8d, $28, $85, $27, $a9, $1e, $81, $2a, $89, $7a, $84, $2a, $89, $7f, $90, $2a, $89, $7a, $84
	.byte $2a, $89, $7f, $90, $2a, $89, $7b, $84, $2a, $89, $7f, $90, $2a, $85, $2c, $81, $00, $85, $2a, $81, $28, $89, $7b, $84
	.byte $28, $89, $7f, $90, $28, $89, $7b, $84, $28, $89, $7f, $90, $28, $89, $7b, $84, $28, $89, $7f, $90, $28, $85, $2a, $81
	.byte $00, $85, $28, $81, $27, $95, $20, $85, $22, $85, $28, $85, $27, $81, $27, $81, $27, $89, $22, $81, $23, $95
	.byte $41, $1c
	.word @song11ref151
	.byte $42
	.word @song11ch1loop
@song11ch2:
	.byte $df
@song11ch2loop:
	.byte $82
@song11ref318:
	.byte $17, $89, $23, $89, $12, $89, $1e, $89, $14, $89, $20, $89, $16, $89, $22, $89
	.byte $41, $10
	.word @song11ref318
@song11ref337:
	.byte $19, $89, $25, $89, $12, $89, $1e, $89
	.byte $41, $08
	.word @song11ref337
	.byte $41, $08
	.word @song11ref337
	.byte $17, $89, $23, $89, $19, $89, $25
@song11ref358:
	.byte $89, $17, $89, $23, $89, $16, $89, $22, $89, $15, $89, $21, $89, $14, $89, $20, $89, $19, $89, $25, $89, $18, $89, $24
	.byte $41, $09
	.word @song11ref358
@song11ref385:
	.byte $0b, $89, $17, $89, $0b, $89, $17, $89
	.byte $41, $08
	.word @song11ref385
	.byte $0d, $89, $19, $89, $11, $89, $1d, $89, $12, $89, $1e, $89, $16, $89, $22, $89, $42
	.word @song11ch2loop
@song11ch3:
	.byte $76, $80, $1d, $77, $81, $71, $23, $81, $81, $72, $81, $81, $81, $73, $81, $81, $81, $74, $81, $81, $81, $75, $81, $81
	.byte $81, $76, $81, $81, $81, $77, $81, $81, $76, $81, $81, $81, $75, $81, $74, $81, $81, $73, $81, $81, $72, $81, $81, $71
	.byte $81, $81, $81, $93, $70, $85
@song11ch3loop:
	.byte $79, $94
@song11ref472:
	.byte $20, $89, $20, $95, $20, $89, $20
@song11ref479:
	.byte $89, $20, $89, $20, $89, $20, $89, $20, $89, $20, $95, $20, $89, $20, $83, $20, $83, $20, $83, $20, $83, $20, $89, $20
	.byte $83, $20, $83
	.byte $41, $22
	.word @song11ref472
	.byte $41, $15
	.word @song11ref472
	.byte $41, $0e
	.word @song11ref479
	.byte $89, $20, $89, $20, $89, $20, $89, $98, $19, $95, $94, $20, $95, $98, $18, $95, $94, $20, $95, $42
	.word @song11ch3loop
@song11ch4:
	.byte $97, $02, $ad, $02, $85, $02, $85, $02, $85
@song11ch4loop:
@song11ref547:
	.byte $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $08
	.word @song11ref547
	.byte $41, $08
	.word @song11ref547
	.byte $41, $08
	.word @song11ref547
	.byte $41, $08
	.word @song11ref547
	.byte $41, $08
	.word @song11ref547
	.byte $41, $08
	.word @song11ref547
	.byte $01, $95, $02, $95, $01, $95, $02, $85, $02, $85, $02, $85, $42
	.word @song11ch4loop
@song12ch0:
	.byte $45, $03, $90, $20, $85, $1f, $85, $20, $85
@song12ch0loop:
	.byte $90
@song12ref12:
	.byte $1d, $ad, $1e, $95, $1f, $95, $20, $ad, $25, $95, $29, $8f, $29, $83, $27, $95, $29, $95, $2a, $95, $24, $95, $27, $ad
	.byte $25, $95, $20, $85, $1f, $85, $20, $85
	.byte $41, $20
	.word @song12ref12
	.byte $42
	.word @song12ch0loop
@song12ch1:
	.byte $97
@song12ch1loop:
	.byte $90
@song12ref53:
	.byte $14, $ad, $16, $95, $17, $95, $18, $ad, $1d, $95, $20, $95, $1e, $95, $20, $95, $22, $95, $1b, $95, $1e, $95, $00, $95
	.byte $1d, $95, $00, $95
	.byte $41, $1c
	.word @song12ref53
	.byte $42
	.word @song12ch1loop
@song12ch2:
	.byte $90, $14, $95
@song12ch2loop:
	.byte $88
@song12ref92:
	.byte $19, $89, $25, $89, $19, $89, $25, $89, $19, $89, $25, $89
	.byte $41, $0c
	.word @song12ref92
	.byte $1d, $89, $29, $89, $1d, $89, $29, $89, $90, $1e, $89, $2a, $89, $1e, $89, $2a, $89, $20, $89, $2c, $89, $20, $89, $2c
	.byte $89, $19, $89, $25, $89, $14, $89, $20, $89, $16, $89, $22, $89, $18, $89, $24, $89, $88
@song12ref149:
	.byte $0d, $89, $19, $89, $0d, $89, $19, $89, $0d, $89, $19, $89
	.byte $41, $0c
	.word @song12ref149
	.byte $11, $89, $1d, $89, $11, $89, $1d, $89, $90, $12, $89, $1e, $89, $12, $89, $1e, $89, $14, $89, $20, $89, $14, $89, $20
	.byte $89, $0d, $89, $19, $89, $0a, $89, $16, $89, $0b, $89, $17, $89, $0c, $89, $18, $89, $42
	.word @song12ch2loop
@song12ch3:
	.byte $97
@song12ch3loop:
	.byte $75
@song12ref211:
	.byte $92, $14, $00, $87, $94, $20, $85, $20, $81, $92, $20, $89, $94, $20, $85, $20, $81
	.byte $41, $0d
	.word @song12ref211
	.byte $41, $0d
	.word @song12ref211
	.byte $41, $0d
	.word @song12ref211
	.byte $77
@song12ref238:
	.byte $92, $14, $00, $81, $14, $00, $81, $94, $20, $85, $20, $81, $92, $20, $89, $94, $20, $85, $20, $81
	.byte $41, $0d
	.word @song12ref211
	.byte $41, $10
	.word @song12ref238
	.byte $41, $0d
	.word @song12ref211
	.byte $41, $10
	.word @song12ref238
	.byte $41, $0d
	.word @song12ref211
	.byte $41, $10
	.word @song12ref238
	.byte $41, $0d
	.word @song12ref211
	.byte $41, $10
	.word @song12ref238
	.byte $41, $0d
	.word @song12ref211
	.byte $41, $10
	.word @song12ref238
	.byte $41, $0d
	.word @song12ref211
	.byte $42
	.word @song12ch3loop
@song12ch4:
	.byte $97
@song12ch4loop:
@song12ref296:
	.byte $01, $95, $02, $95, $01, $95, $02, $95, $01, $95, $02, $95
	.byte $41, $0c
	.word @song12ref296
	.byte $41, $0c
	.word @song12ref296
	.byte $41, $0c
	.word @song12ref296
	.byte $41, $0c
	.word @song12ref296
	.byte $01, $95, $02, $95, $42
	.word @song12ch4loop
