; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-5
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Song 1
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$7f,$0f,$40,$03 ; 00 sm64_mario_boing (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$94,$0f,$40,$00 ; 01 sm64_mario_doh (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$06 ; 02 sm64_mario_falli (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$c7,$0f,$40,$02 ; 03 sm64_mario_haha (Pitch:15)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$c8,$0f,$40,$03 ; 04 sm64_mario_hello (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$05 ; 05 sm64_mario_here_ (Pitch:15)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$a5,$0f,$40,$03 ; 06 sm64_mario_hoo (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a2,$0f,$40,$07 ; 07 sm64_mario_hooho (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a3,$0f,$40,$0a ; 08 sm64_mario_hurt (Pitch:15)
	.byte $25+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 09 sm64_mario_its_m (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$f0,$0f,$40,$04 ; 0a sm64_mario_lets_ (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$09 ; 0b sm64_mario_lost_ (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ee,$0f,$40,$08 ; 0c sm64_mario_mamma (Pitch:15)
	.byte $29+.lobyte(FAMISTUDIO_DPCM_PTR),$ed,$0f,$40,$07 ; 0d sm64_mario_okey- (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$a0,$0f,$40,$06 ; 0e sm64_mario_oof (Pitch:15)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$ba,$0f,$40,$02 ; 0f sm64_mario_pulli (Pitch:15)
	.byte $29+.lobyte(FAMISTUDIO_DPCM_PTR),$f3,$0f,$40,$0a ; 10 sm64_mario_snore (Pitch:15)
	.byte $65+.lobyte(FAMISTUDIO_DPCM_PTR),$57,$0f,$40,$00 ; 11 sm64_mario_snore 1 (Pitch:15)
	.byte $61+.lobyte(FAMISTUDIO_DPCM_PTR),$51,$0f,$40,$02 ; 12 sm64_mario_ungh (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 13 sm64_mario_waha (Pitch:15)
	.byte $3c+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$08 ; 14 sm64_mario_weak (Pitch:15)
	.byte $3c+.lobyte(FAMISTUDIO_DPCM_PTR),$f0,$0f,$40,$04 ; 15 sm64_mario_whoa (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$f6,$0f,$40,$09 ; 16 sm64_mario_yahoo (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$05 ; 17 sm64_mario_yawn (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 18 sm64_mario_yippe (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47
	.byte $41, $0f
	.word @song0ref5
	.byte $47
	.byte $41, $0f
	.word @song0ref5
	.byte $47, $ff, $ff, $bf, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref40:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0f
	.word @song0ref40
	.byte $41, $0f
	.word @song0ref40
	.byte $ff, $ff, $bf, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $41, $0f
	.word @song0ref40
	.byte $41, $0f
	.word @song0ref40
	.byte $41, $0f
	.word @song0ref40
	.byte $ff, $ff, $bf, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $41, $0f
	.word @song0ref40
	.byte $41, $0f
	.word @song0ref40
	.byte $41, $0f
	.word @song0ref40
	.byte $ff, $ff, $bf, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $83, $01, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $19, $18, $17, $16, $15, $14, $13, $12, $11
	.byte $10, $0f, $0e, $00, $ff, $ff, $85
	.byte $41, $0f
	.word @song0ref40
	.byte $41, $0f
	.word @song0ref40
	.byte $41, $0f
	.word @song0ref40
	.byte $42
	.word @song0ch4loop
