
.ifndef __DPCM_SFX_INC
__DPCM_SFX_INC = 1

SFX_mario_boing = 0
SFX_mario_doh =   1
SFX_mario_falli = 2
SFX_mario_haha =  3
SFX_mario_hello = 4
SFX_mario_here_ = 5
SFX_mario_hoo =   6
SFX_mario_hooho = 7
SFX_mario_hurt =  8
SFX_mario_its_m = 9
SFX_mario_lets_ = 10
SFX_mario_lost_ = 11
SFX_mario_mamma = 12
SFX_mario_okey =  13
SFX_mario_oof =   14
SFX_mario_pulli = 15
SFX_mario_snore = 16
SFX_mario_snore = 17
SFX_mario_ungh =  18
SFX_mario_waha =  19
SFX_mario_weak =  20
SFX_mario_whoa =  21
SFX_mario_yahoo = 22
SFX_mario_yawn =  23
SFX_mario_yippe = 24

.endif
