
; 
.global JumpEngine

; global imports typically found in common.s
.global GetEnemyOffscreenBits
.global GetScreenPosition
.global LoadAreaPointer
.global GetAreaType
.global GetXOffscreenBits
.global EnemyGfxHandler
.global RelativeEnemyPosition
.global ImposeGravityBlock
.global ImposeGravity
.global PlayerEnemyDiff
.global Bitmasks
.global RelWOfs
.global GetProperObjOffset
.global MoveObjectHorizontally
.global MoveD_EnemyVertically
.global MoveEnemyHorizontally
.global GetOffScreenBitsSet
.global RelativeFireballPosition
.global GetFireballBoundBox
.global GetPlayerOffscreenBits
.global RelativePlayerPosition
.global RelativeBlockPosition
.global GetBlockOffscreenBits
.global InitVStf
.global GetMiscOffscreenBits

; code likely in collision.s
.global GetMiscBoundBox
.global BlockBufferCollision

