; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_in_an_other_castle=music_data_in_an_other_castle
.endif

music_data_in_an_other_castle:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : in an other castle
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_in_an_other_castle
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env4,@env0 ; 00 : Instrument 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00
@env4:
	.byte $c2,$7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $77, $80
@song0ref3:
	.byte $38, $87, $76, $37, $87, $36, $87, $40, $50, $87, $38, $87, $37, $87, $36, $87, $40, $50, $87, $38, $87, $37, $87, $36
	.byte $87, $40, $50, $87, $38, $87, $37, $85, $00, $36, $85, $00, $40, $50, $85, $00, $77
	.byte $41, $23
	.word @song0ref3
	.byte $48, $75, $2c, $a5, $76, $19, $91, $74, $29, $b9, $76, $28, $a5, $48, $77, $19, $93, $76, $20, $91, $19, $93, $20, $91
	.byte $77, $26, $a7, $76, $19, $91, $00, $20, $8f, $00, $48, $77, $1a, $91, $76, $21, $91, $1a, $91, $29, $b9, $74, $28, $a5
	.byte $77, $1a, $91, $76, $21, $91, $1a, $91, $74, $26, $e1, $44, $00
@song0ch1:
	.byte $77, $80, $31, $87, $76, $30, $87, $2f, $87, $2e, $87, $2f, $87, $2e, $87, $2d, $87, $2c, $87, $2d, $87, $2c, $87, $2b
	.byte $87, $2a, $87, $2b, $87, $2a, $85, $00, $29, $85, $00, $28, $85, $00, $77, $29, $87, $76, $28, $87, $27, $87, $26, $87
	.byte $27, $87, $26, $87, $25, $87, $24, $87, $25, $87, $24, $87, $23, $87, $22, $87, $23, $87, $24, $85, $00, $25, $85, $00
	.byte $26, $85, $00, $78, $38, $a5, $00, $91, $77, $2c, $b9, $75, $2c, $a5, $00, $d1, $76, $2c, $a7, $00, $a7, $bb, $75, $2c
	.byte $b9, $77, $2c, $a5, $00, $b9, $2b, $e1, $44, $00
@song0ch2:
@song0ref216:
	.byte $ff, $ff, $bf, $ff, $9f, $ff, $a7, $ff, $ff, $bf, $44, $00
@song0ch3:
	.byte $41, $0b
	.word @song0ref216
@song0ch4:
	.byte $41, $0b
	.word @song0ref216
@song0ch5:
	.byte $ff, $ff, $bf, $77, $80, $19, $91, $76, $20, $91, $00, $91, $20, $91, $19, $8f, $00, $20, $8f, $00, $19, $8f, $00, $20
	.byte $8f, $00, $d3, $19, $91, $00, $20, $8f, $00, $a9
@song0ref271:
	.byte $bb, $21, $91, $21, $8f, $00, $23, $8f, $00, $21, $8f, $00, $20, $8f, $00
	.byte $41, $0f
	.word @song0ref271
	.byte $44, $00
@song0ch6:
	.byte $41, $0b
	.word @song0ref216
