; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_victory=music_data_victory
.endif

music_data_victory:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : victory
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_victory
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env1,@env2,@env0 ; 00 : Alto Sax
	.word @env3,@env1,@env2,@env0 ; 01 : Baritone Sax MMC5

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$7f,$00,$01
@env2:
	.byte $7f,$00,$00
@env3:
	.byte $00,$c0,$cf,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0d,$40 ; 00 Sunsoft Bass A# (Pitch:13)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0f,$40 ; 01 Sunsoft Bass A# (Pitch:15)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0c,$40 ; 02 Sunsoft Bass B (Pitch:12)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0d,$40 ; 03 Sunsoft Bass B (Pitch:13)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$09,$40 ; 04 Sunsoft Bass C (Pitch:9)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0a,$40 ; 05 Sunsoft Bass C (Pitch:10)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0b,$40 ; 06 Sunsoft Bass C (Pitch:11)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0c,$40 ; 07 Sunsoft Bass C (Pitch:12)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0d,$40 ; 08 Sunsoft Bass C (Pitch:13)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0e,$40 ; 09 Sunsoft Bass C (Pitch:14)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0f,$40 ; 0a Sunsoft Bass C (Pitch:15)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0b,$40 ; 0b Sunsoft Bass C# (Pitch:11)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0c,$40 ; 0c Sunsoft Bass C# (Pitch:12)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0d,$40 ; 0d Sunsoft Bass C# (Pitch:13)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0e,$40 ; 0e Sunsoft Bass C# (Pitch:14)
	.byte $79+.lobyte(FAMISTUDIO_DPCM_PTR),$1a,$0a,$40 ; 0f Sunsoft Bass D (Pitch:10)
	.byte $79+.lobyte(FAMISTUDIO_DPCM_PTR),$1a,$0b,$40 ; 10 Sunsoft Bass D (Pitch:11)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $77, $80, $1e, $ff, $f3, $20, $f7, $20, $bb, $20, $bb, $48
	.byte $22, $ff, $e1, $23, $ff, $e1, $48, $20, $ff, $ff, $89, $48, $1e, $ff, $ff, $e5, $1e, $ff, $ff, $e5
@song0ref37:
	.byte $48
@song0ref38:
	.byte $00, $99
@song0ref40:
	.byte $1e, $97, $00, $97, $1e
@song0ref45:
	.byte $99, $00, $97, $20, $97, $00, $99, $20, $97, $00, $97, $20, $99, $00, $97, $20, $97
	.byte $41, $08
	.word @song0ref38
	.byte $48, $20, $b3, $1e, $b3, $1c, $b1, $1e, $b3, $1b, $97, $00, $99, $20, $b1, $1e, $b3, $1e, $b3, $48, $20, $99, $20, $b1
	.byte $1e, $ff, $83, $00, $b3, $7b, $23, $b1, $23, $b3, $23, $b3, $48
@song0ref102:
	.byte $23, $99, $23, $b1, $23, $ff, $83, $00, $97, $77, $1e, $99, $00, $97
@song0ref116:
	.byte $1e, $97, $00, $99, $20, $97, $00, $97, $1e, $99
	.byte $41, $0e
	.word @song0ref37
	.byte $41, $08
	.word @song0ref40
	.byte $41, $0a
	.word @song0ref116
	.byte $41, $0e
	.word @song0ref37
	.byte $41, $08
	.word @song0ref40
	.byte $1e, $97, $00, $99, $7e, $1b, $b1, $19, $99, $48, $17, $b3, $00, $cd, $1b, $b3, $19, $97, $17, $cd, $77
	.byte $41, $0a
	.word @song0ref116
	.byte $48, $1e, $b3, $00, $ff, $9d, $7b, $1e, $a5, $1e, $8b, $20, $b1, $00, $cd, $21, $99, $48, $22, $99, $21, $97, $22, $97
	.byte $1e, $99, $20, $97, $22, $97
	.byte $41, $12
	.word @song0ref38
	.byte $1e, $99
	.byte $41, $0a
	.word @song0ref37
	.byte $41, $08
	.word @song0ref116
	.byte $20
	.byte $41, $0b
	.word @song0ref45
	.byte $1e, $99, $48, $00, $99, $1e, $97, $00, $97, $22, $99, $00, $97, $22, $97
	.byte $41, $14
	.word @song0ref38
	.byte $48, $00, $99, $20
@song0ref232:
	.byte $97, $00, $97
@song0ref235:
	.byte $23, $99, $00, $97, $23, $97, $00, $99, $20, $b1, $1e, $b3, $1c, $b3, $1c, $97, $1b, $b3, $48, $ff, $9f, $00, $b3, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $77, $80, $27, $ff, $f3, $28, $f7, $28, $bb, $28, $bb, $25, $ff, $e1, $27, $ff, $e1, $25, $ff, $ff, $89, $00, $d7, $7b
	.byte $2a, $d7, $2c, $d7, $2d, $d7, $2e, $95, $2f, $93, $2e, $ff, $ff, $b7, $00, $99, $77, $23
	.byte $41, $0b
	.word @song0ref232
	.byte $23
	.byte $41, $0b
	.word @song0ref232
	.byte $27, $97, $00, $97, $27, $99, $23, $b3, $23, $b3, $20, $b1, $22, $b3, $1e, $97, $00, $99, $23, $b1, $23, $b3, $23, $b3
	.byte $41, $08
	.word @song0ref102
	.byte $b3, $7b
@song0ref340:
	.byte $28, $b1, $27, $b3, $27, $b3, $28, $99, $28, $b1, $27, $ff, $83, $00, $97, $77
	.byte $41, $08
	.word @song0ref235
@song0ref359:
	.byte $23, $97, $00, $97, $25, $99, $00, $99, $23
	.byte $41, $0b
	.word @song0ref232
	.byte $25
	.byte $41, $0b
	.word @song0ref232
	.byte $41, $09
	.word @song0ref359
	.byte $41, $0b
	.word @song0ref232
	.byte $25
	.byte $41, $0b
	.word @song0ref232
@song0ref385:
	.byte $7e, $27, $b1, $25, $99, $23, $b3, $00, $cd, $27, $b3, $25, $97, $23, $cd, $77, $23, $97, $00, $99, $23, $97, $00, $97
	.byte $25, $99, $23
@song0ref412:
	.byte $b3, $00, $ff, $9d, $2a, $a5, $2a, $8b, $2a, $b1, $00, $cd, $2a, $99, $2a, $99, $2a, $97, $2a, $97, $2a, $99, $2a, $97
	.byte $2a, $97, $00, $99, $23
	.byte $41, $0b
	.word @song0ref232
	.byte $41, $08
	.word @song0ref359
	.byte $25
	.byte $41, $0b
	.word @song0ref232
	.byte $25, $97, $00, $97, $25, $99, $00, $97, $25, $97
@song0ref461:
	.byte $00, $99, $25, $97, $00, $97, $25, $99
	.byte $41, $08
	.word @song0ref461
	.byte $00, $97, $25, $97, $00, $99, $23
	.byte $41, $0b
	.word @song0ref232
	.byte $23, $97, $00, $97, $23, $99, $00, $99, $23
@song0ref491:
	.byte $97, $00, $97
@song0ref494:
	.byte $27, $99, $00, $97, $27, $97, $00, $99, $23, $b1, $23, $b3, $20, $b3, $22, $97, $1e, $b3, $ff, $9f, $00, $b3, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref520:
	.byte $ff, $ff, $ff, $eb, $ff, $ff, $ff, $c7, $ff, $ff, $8b, $ff, $ff, $ff, $ff, $ff, $cf
@song0ref537:
	.byte $ff, $ff, $ff, $ab, $ff, $ff, $ff, $ab
	.byte $41, $08
	.word @song0ref537
	.byte $41, $08
	.word @song0ref537
	.byte $41, $08
	.word @song0ref537
	.byte $41, $08
	.word @song0ref537
	.byte $41, $08
	.word @song0ref537
	.byte $ff, $d5, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $41, $19
	.word @song0ref520
	.byte $41, $08
	.word @song0ref537
	.byte $41, $08
	.word @song0ref537
	.byte $41, $08
	.word @song0ref537
	.byte $41, $08
	.word @song0ref537
	.byte $41, $08
	.word @song0ref537
	.byte $ff, $d5, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $fb, $0e, $b9, $02, $bb, $0a, $f7, $00, $f9, $f1, $08, $b7, $0e, $b5, $01, $ef, $00, $b7, $0c, $99, $0c, $99, $08, $c1
	.byte $08, $9d, $08, $9f, $01, $9f, $08, $9d, $09, $9f, $08, $9f, $0e, $ff, $ff, $ff, $ff, $ff, $cd
@song0ref633:
	.byte $00, $99, $0e, $b1, $02, $99, $0a, $97, $04, $97, $08, $99, $0c, $97, $00, $97, $0d, $b3, $0c, $97, $01, $b3, $0c, $97
	.byte $0c, $99, $0a, $b3, $0e, $b3, $0c, $b1, $0c, $b3, $0c, $b3, $0a, $b1, $0e, $b3, $0e, $b3, $0a, $99, $0a, $b1, $0e, $ff
	.byte $83, $00, $ff, $d3, $ff, $85, $05, $97, $06, $99, $07, $97, $0c, $97, $0c, $8b, $0c, $8b, $0c, $97, $0c, $97, $0c, $99
@song0ref705:
	.byte $02, $b1, $0a, $99, $02, $99, $0a, $97, $0e, $97, $01, $99, $00, $97, $0d, $b3, $08, $95, $03, $0c, $b3, $00, $cd
	.byte $41, $0e
	.word @song0ref705
	.byte $01, $b1, $0d, $08, $95, $03, $0c, $b3, $00, $ff, $9d, $9b, $11, $b1, $0b, $99, $02, $b1, $00, $ff, $ff, $89, $eb, $0e
	.byte $a5, $0e, $89, $0e, $b3, $00, $e7
@song0ref762:
	.byte $0e, $99, $0e, $97, $0e, $97, $0e, $99
	.byte $41, $08
	.word @song0ref762
	.byte $0e, $97, $0e, $97, $00, $99, $0e, $b1, $02, $99, $0a, $e7, $00, $97, $08, $99, $9b, $0e, $97, $01, $b3, $0c, $97, $01
	.byte $97, $08, $b3, $08, $97, $08, $99, $01, $b1, $09, $b3, $0e, $97, $0e, $99, $0a, $99, $0f, $97, $10, $e7
	.byte $41, $11
	.word @song0ref633
	.byte $99, $9b, $0c, $97, $01, $b3, $08, $97, $0c, $97, $00, $99, $0a, $b1, $0e, $99, $0c, $b1, $0c, $b3, $0c, $b3, $ff, $9f
	.byte $00, $b3, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $77, $82, $2a, $ff, $f3, $2c, $f7, $2c, $bb, $2c, $bb, $25, $ff, $e1, $27, $ff, $e1, $29, $ff, $ff, $89, $00, $d7, $7b
	.byte $2e, $d7, $2f, $d7, $30, $d7, $31, $95, $33, $93, $31, $ff, $ff, $b7, $00, $99, $77
@song0ref892:
	.byte $27, $97, $00, $97, $27, $99, $00, $97, $28, $97, $00, $99, $28
@song0ref905:
	.byte $97, $00, $97, $29, $99, $00, $97, $29, $97, $00, $99, $2a, $97, $00, $97, $2a, $99, $28, $b3, $27, $b3, $25, $b1, $25
	.byte $b3, $23, $97, $00, $99
	.byte $41, $0e
	.word @song0ref340
	.byte $b3, $7b, $2c, $b1, $2a, $b3, $2a, $b3, $2c, $99, $2c, $b1, $2a, $ff, $83, $00, $97, $77
	.byte $41, $08
	.word @song0ref494
@song0ref958:
	.byte $28, $97, $00, $97, $28, $99, $00, $99
	.byte $41, $10
	.word @song0ref892
	.byte $41, $08
	.word @song0ref494
	.byte $41, $08
	.word @song0ref958
	.byte $41, $10
	.word @song0ref892
	.byte $41, $08
	.word @song0ref494
	.byte $41, $0e
	.word @song0ref385
	.byte $77, $27, $97
@song0ref987:
	.byte $00, $99, $28, $97, $00, $97, $28, $99, $27
	.byte $41, $1c
	.word @song0ref412
	.byte $41, $10
	.word @song0ref892
	.byte $28, $99, $00, $99, $28
	.byte $41, $0b
	.word @song0ref491
	.byte $29
	.byte $41, $0b
	.word @song0ref905
	.byte $29, $97, $00, $97, $28, $99
	.byte $41, $08
	.word @song0ref987
	.byte $00, $97, $28, $97, $00, $99
	.byte $41, $13
	.word @song0ref892
	.byte $99, $29, $97, $00, $97, $2a, $99, $00, $97, $2a, $97, $00, $99, $28, $b1, $27, $b3, $25, $b3, $25, $97, $23, $b3, $ff
	.byte $9f, $00, $b3, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $7b, $82, $17, $ff, $f3, $10, $f7, $10, $bb, $17, $bb, $12, $ff, $e1, $17, $ff, $e1, $19, $ff, $ff, $89, $12, $ff, $ff
	.byte $e5, $12, $ff, $df, $7f, $12, $a9, $14, $ab, $16, $a9, $77
@song0ref1099:
	.byte $17, $b3, $17, $b3, $1c, $b1, $1c, $b3, $1d, $b3, $1d, $b1, $1e, $b3, $1e, $97, $23, $99
@song0ref1117:
	.byte $1c, $b3, $1b, $b3, $19, $b1, $12, $b3
@song0ref1125:
	.byte $17, $97, $00, $99, $7b, $1c, $b1, $17, $b3, $17, $b3, $1c, $99, $1c, $b1, $17, $b3, $7f, $12, $97, $14, $99, $16, $97
	.byte $41, $16
	.word @song0ref1125
@song0ref1152:
	.byte $17, $b3, $77, $0f, $b1, $10, $b3, $12, $b3, $7f, $17, $b3, $77, $0f, $b3, $10, $b1, $12, $b3, $7f
	.byte $41, $10
	.word @song0ref1152
	.byte $7f
	.byte $41, $10
	.word @song0ref1152
	.byte $7f
	.byte $41, $08
	.word @song0ref1152
	.byte $17, $b3, $00, $ff, $9d, $7b, $12, $a5, $12, $8b, $14, $b1, $00, $cd, $15, $99, $16, $99, $15, $97, $16, $97, $12, $99
	.byte $14, $97, $16, $97
	.byte $41, $08
	.word @song0ref1099
	.byte $12, $b3, $12, $b3, $17, $b3, $17, $b1, $19, $b3, $19, $b3, $18, $b1, $17, $b3, $16, $b3, $14, $99, $13, $97, $12, $97
	.byte $12, $99, $14, $97, $16, $97
	.byte $41, $08
	.word @song0ref1099
	.byte $11, $b3, $11, $b3, $12, $b3, $12, $97, $17, $97
	.byte $41, $09
	.word @song0ref1117
	.byte $b3, $ff, $9f, $00, $b3, $42
	.word @song0ch6loop
