; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_game_over=music_data_game_over
.endif

music_data_game_over:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : game over
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_game_over
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env6,@env2,@env5,@env0 ; 00 : Trumpet
	.word @env6,@env2,@env3,@env0 ; 01 : French Horn
	.word @env6,@env2,@env1,@env0 ; 02 : Trombone MMC5
	.word @env6,@env2,@env4,@env0 ; 03 : Trombone1 MMC5

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c3,$7f,$00,$00
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00
@env4:
	.byte $c2,$7f,$00,$00
@env5:
	.byte $c1,$7f,$00,$00
@env6:
	.byte $00,$c0,$cf,$00,$02

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7f, $80
@song0ref7:
	.byte $34, $8d, $00, $85, $33
@song0ref12:
	.byte $8d, $00, $85, $7b, $32, $89, $33, $89, $32, $89, $31, $89, $30, $89, $00, $89, $2f, $89, $00, $89, $7f, $2e, $95, $7b
	.byte $2f, $89, $00, $89, $48, $7f, $31, $8d, $00, $85, $30
@song0ref47:
	.byte $8d, $00, $85, $7b, $2f
@song0ref52:
	.byte $89, $30, $89, $2f, $89, $2e, $89, $2d, $89, $00, $89, $2c, $89, $00, $89, $7f, $2b, $95, $7b, $2c, $89, $00, $89, $48
@song0ref76:
	.byte $7f, $2f, $95, $2d, $85, $00, $81, $2d, $85, $00, $81, $29, $95, $7a, $2a, $89, $00, $89
	.byte $41, $10
	.word @song0ref76
	.byte $48, $75, $27, $89, $28, $89, $29, $89, $76, $2a, $89, $2b, $89, $2c, $89, $77, $2d, $89, $2e, $89, $78, $2f, $89
@song0ref120:
	.byte $30, $89, $31, $89, $79, $33, $89, $31, $89, $00, $89, $7a, $2f, $89, $00, $89, $48, $7f
	.byte $41, $3c
	.word @song0ref7
	.byte $48
@song0ref142:
	.byte $7f, $2b, $8d, $00, $85, $2b, $85, $00, $81, $2b, $85, $00, $81, $2e
@song0ref156:
	.byte $8d, $00, $85, $27, $8d, $00, $85, $7b, $2f, $89, $31, $89, $2f, $89, $2e, $89, $2c, $89, $00, $89, $27, $89, $00, $89
	.byte $48, $7f
@song0ref182:
	.byte $33, $8d, $00, $85
@song0ref186:
	.byte $33, $85, $00, $81, $33, $85, $00, $81, $33, $8d, $00, $85
	.byte $41, $0d
	.word @song0ref182
	.byte $85, $00, $81
	.byte $41, $09
	.word @song0ref186
	.byte $85, $00, $81, $33, $95, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $7f, $80, $2c, $8d, $00, $85, $2c
	.byte $41, $19
	.word @song0ref12
	.byte $7f, $2c, $8d, $00, $85, $2c
	.byte $41, $19
	.word @song0ref47
@song0ref235:
	.byte $7f, $2a, $95, $2a, $85, $00, $81, $2a, $85, $00, $81, $7e, $27, $95, $7a, $27, $89, $00, $89
	.byte $41, $10
	.word @song0ref235
	.byte $75, $27, $89, $28, $89, $29, $89, $2a, $89, $76, $2b, $89, $2c, $89, $77, $2d, $89, $2e, $89, $2f, $89, $78
	.byte $41, $0e
	.word @song0ref120
	.byte $7f, $2c, $8d, $00, $85, $2c
	.byte $41, $19
	.word @song0ref12
	.byte $7f, $2c, $8d, $00, $85, $2c
	.byte $41, $19
	.word @song0ref47
	.byte $7f
@song0ref301:
	.byte $27, $8d, $00, $85, $27, $85, $00, $81, $27, $85, $00, $81, $27
	.byte $41, $17
	.word @song0ref156
	.byte $41, $0c
	.word @song0ref142
	.byte $2b, $8d, $00, $85, $2b, $8d, $00, $85, $7b, $33, $89, $32, $89, $31
	.byte $41, $09
	.word @song0ref52
	.byte $2a, $89, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $7e, $82
@song0ref345:
	.byte $28, $8d, $00, $85, $28, $8d, $00, $9d, $79, $28, $95, $28, $95, $28, $95, $00, $95, $28, $95, $7e
	.byte $41, $12
	.word @song0ref345
@song0ref368:
	.byte $7f, $2f, $95, $2f, $85, $00, $81, $2f, $85, $00, $81, $2f, $95, $7d, $2f, $89, $00, $89
	.byte $41, $10
	.word @song0ref368
	.byte $97, $74, $27, $95, $00, $95, $75, $27, $95, $00, $95, $76, $27, $95, $00, $95, $78, $27, $95, $7e
	.byte $41, $12
	.word @song0ref345
	.byte $7e
	.byte $41, $12
	.word @song0ref345
	.byte $00, $95, $2b, $95, $00, $95, $2b, $95, $00, $95, $2c, $95, $00, $95, $2c, $95, $7e, $2e, $8d, $00, $85, $2e, $85, $00
	.byte $81, $2e, $85, $00, $81, $2e, $8d, $00, $85, $2e, $8d, $00, $85, $79, $2e, $95, $2e, $95, $2e, $95, $2e, $95, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref466:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $10
	.word @song0ref466
	.byte $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $00, $95, $77, $84
@song0ref497:
	.byte $23, $95, $00, $95, $23, $95, $00, $95, $23, $95, $00, $95
	.byte $41, $0c
	.word @song0ref497
@song0ref512:
	.byte $23, $95, $00, $95, $23, $95, $00, $95, $27, $95, $00, $95, $27, $95, $00, $95, $27, $95, $00, $95, $27, $95, $00, $95
	.byte $73, $23, $95, $00, $95, $74, $23, $95, $00, $95, $75, $23, $95, $00, $95, $76, $23, $95, $00, $95, $77
	.byte $41, $0c
	.word @song0ref497
	.byte $41, $0c
	.word @song0ref497
	.byte $41, $16
	.word @song0ref512
	.byte $7b
	.byte $41, $0d
	.word @song0ref301
	.byte $8d, $00, $85, $27, $8d, $00, $85, $27, $8d, $00, $85, $77, $27, $95, $27, $95, $27, $95, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $78, $86
@song0ref594:
	.byte $10, $95, $00, $95, $17, $95, $00, $95, $10, $95, $00, $95, $17, $95, $00, $95
	.byte $41, $10
	.word @song0ref594
	.byte $0f, $95, $00, $95, $0b, $95, $00, $95, $0f, $95, $00, $95, $0b, $95, $00, $95, $73, $12, $95, $00, $95, $74, $0b, $95
	.byte $00, $95, $75, $12, $95, $00, $95, $76, $0b, $95, $00, $95, $78
	.byte $41, $10
	.word @song0ref594
	.byte $41, $10
	.word @song0ref594
	.byte $1b, $95, $00, $95, $1b, $95, $00, $95, $14, $95, $00, $95, $14, $95, $00, $95, $7b, $1b, $8d, $00, $85, $1b, $85, $00
	.byte $81, $1b, $85, $00, $81
@song0ref685:
	.byte $1b, $8d, $00, $85, $1b, $8d, $00, $85, $1b, $8d, $00, $85
	.byte $41, $0c
	.word @song0ref685
	.byte $42
	.word @song0ch6loop
