; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_waterworld=music_data_waterworld
.endif

music_data_waterworld:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : waterworld
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_waterworld
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env2,@env3,@env1,@env0 ; 00 : Electric Bass (fingered)
	.word @env2,@env3,@env1,@env0 ; 01 : Acoustic Grand Piano MMC5

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c2,$c1,$00,$01
@env2:
	.byte $00,$cf,$7f,$00,$02
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $79, $80, $33, $9f, $00, $34, $8d, $00, $35, $d1
@song0ref15:
	.byte $00, $83, $34, $8d, $00, $33, $9f, $00, $32, $8d, $00, $33, $9f, $00, $34, $8d, $00, $35, $8f, $48, $c1
	.byte $41, $12
	.word @song0ref15
	.byte $9f, $00, $34, $8d, $00, $33, $9f, $00, $48, $32, $8d, $00, $31, $9f, $00, $30, $8d, $00, $2e, $9f, $00, $91, $7d, $33
	.byte $95, $00, $bf
@song0ref66:
	.byte $76, $33, $8d, $00, $33, $8f, $32, $8f, $33, $8d, $00, $48, $31, $8d, $00, $91, $74, $22, $8d, $00, $79, $31, $b1, $00
	.byte $76, $37, $8d, $00, $91, $74, $22, $8d, $00, $76, $31, $b3, $30, $8d, $00, $91, $74, $20, $8d, $00, $76, $30, $8f, $48
	.byte $c1, $00, $83, $74, $38, $8d, $00, $38, $8d, $00, $37, $8d, $00, $35, $8d, $00, $31, $8d, $00, $91, $31, $8d, $00, $31
	.byte $8d, $00, $91, $31, $8d, $00, $31, $9f, $00, $48, $31, $8d, $00, $31, $8d, $00, $31, $8d, $00, $31, $8d, $00, $30, $8d
	.byte $00, $91, $30, $8d, $00, $30, $8d, $00, $91, $30, $8d, $00, $30, $9f, $00, $33, $8d, $00, $33, $8d, $00, $32, $8d, $00
	.byte $33, $8d, $00, $48, $2e, $8d, $00, $91, $73, $20, $8d, $00, $75, $2e, $b1, $00, $74, $37, $8d, $00, $91, $73, $1f, $8d
	.byte $00, $75, $2e, $b1, $00, $74, $3a, $8d, $00, $91, $73, $1b, $8d, $00, $74, $2c, $8f, $48, $c1, $00, $83, $76, $38, $8d
	.byte $00, $78, $38, $8d, $00, $7a, $37, $8d, $00, $7c, $38, $8d, $00, $7e, $37, $9f, $00, $2b, $8d, $00, $2b, $8d, $00, $2c
	.byte $8d, $00, $2d, $8d, $00, $2e, $9f, $00, $48, $2e, $8d, $00, $2e, $8d, $00, $30, $8d, $00, $32, $8d, $00, $33, $8d, $00
	.byte $91, $38, $8d, $00, $37, $8d, $00, $91, $38, $8d, $00, $37, $9f, $00
	.byte $41, $ca
	.word @song0ref66
	.byte $79, $33, $8d, $00, $27, $9f, $00, $27, $8d, $00, $48, $7b
@song0ref311:
	.byte $27, $a1, $78, $22, $8d, $00, $7b, $2b, $9f, $00, $2e, $8d, $00, $35, $af, $00, $81, $35, $af, $00, $81, $35, $c5, $48
	.byte $bf, $00, $85, $33, $8d, $00, $33, $8d, $00, $30, $8d, $00, $33, $8d, $00, $35, $ff, $85, $00, $85, $48, $31, $8d, $00
	.byte $31, $8d, $00, $2e, $8d, $00, $31, $8d, $00, $35, $ff, $85, $00, $85, $33, $8d, $00, $30, $9f, $00, $2c, $8d, $00, $48
	.byte $41, $24
	.word @song0ref311
@song0ref386:
	.byte $38, $af, $00, $81, $2c, $a1, $2e, $8d, $00, $30, $a1, $48, $8d, $00, $81, $2c, $af, $00, $81, $2e, $e3, $00, $83, $2c
	.byte $9f, $00, $2c, $8d, $00, $2c, $8d, $00, $2b, $8d, $00, $29, $8d, $00, $48
	.byte $41, $43
	.word @song0ref311
	.byte $48
	.byte $41, $24
	.word @song0ref311
	.byte $41, $19
	.word @song0ref386
	.byte $74, $2c, $8f, $2b, $a1, $2c, $8f, $48
@song0ref443:
	.byte $29, $8d, $00, $91, $2c, $8f, $2b, $a1, $2c, $8d, $00, $2a, $b3, $24, $b3, $25, $b3, $27, $8f, $48, $9f, $00, $81, $29
	.byte $9f, $00, $2c, $8f, $2b, $a1, $2c, $8d, $00, $29, $87, $00, $85, $2c, $87, $00, $85, $31, $87, $00, $85, $35, $87, $00
	.byte $85, $31, $87, $00, $85, $2c, $87, $00, $85, $2a, $a1, $48, $91, $24, $af, $00, $81, $2c, $ff, $85, $00, $85, $2c, $8f
	.byte $2b, $a1, $2c, $8d, $00, $48, $2e, $8d, $00, $91, $75, $2e, $8f, $2d, $a1, $2e, $8d, $00, $2e, $8d, $00, $91, $2e, $8f
	.byte $2d, $a1, $76, $2e, $8d, $00, $77, $2e, $b3, $36, $8f, $48, $a3, $35, $a1, $32, $8f, $33, $a1, $2e, $8f, $2c, $8d, $00
	.byte $91, $2c, $8f, $2b, $a1, $2c, $8d, $00, $2b, $8d, $00, $91, $48, $2b, $8f, $2a, $8d, $00, $91, $2a, $8d, $00, $29, $9f
	.byte $00, $75, $14, $8f, $13, $a1, $14, $8f, $08, $a1, $77, $2c, $8f, $2b, $a1, $2c, $8d, $00, $48, $74
	.byte $41, $90
	.word @song0ref443
	.byte $9f, $00, $79, $38, $8f, $37, $a1, $38, $8f
@song0ref619:
	.byte $48, $2c, $9f, $00
@song0ref623:
	.byte $76, $14, $8f, $13, $a1
@song0ref628:
	.byte $14, $8f, $08, $9f, $00, $79, $38, $8f, $37, $a1, $38, $8f, $2c, $9f, $00, $76, $14, $8f, $13, $8f, $48, $91
	.byte $41, $0e
	.word @song0ref628
@song0ref653:
	.byte $78, $2c, $8d, $00, $79, $2d, $9f, $00, $7a, $2d, $8d, $00, $79, $2e, $9f, $00, $48, $2e, $8d, $00, $2f, $9f, $00, $2f
	.byte $8d, $00, $30, $9f, $00, $91, $7d, $38, $95, $00, $bf, $79, $38, $8f, $37, $a1, $38, $8d, $00, $48, $35, $8d, $00, $91
	.byte $38, $8d, $00, $37, $a1, $38, $8d, $00, $36, $af, $00, $81, $30, $af, $00, $81, $31, $af, $00, $81, $33, $8f, $48, $9f
	.byte $00, $81, $35, $9f, $00, $38, $8f, $37, $a1, $38, $8d, $00, $35, $87, $00, $85, $38, $87, $00, $85, $3d, $87, $00, $85
	.byte $40, $4d, $87, $00, $85, $3d, $87, $00, $85, $38, $87, $00, $85, $36, $a1, $48, $8d, $00, $81, $30, $af, $00, $81, $38
	.byte $ff, $85, $00, $85, $38, $8f, $37, $a1, $38, $8d, $00, $48, $3a, $87, $00, $97, $3a, $8f, $39, $a1, $3a, $8d, $00, $3a
	.byte $8d, $00, $91, $3a, $8f, $39, $a1, $3a, $8d, $00, $3a, $af, $00, $81, $40, $4e, $8f, $48, $9f, $00, $81, $40, $4d, $8d
	.byte $00, $91, $3e, $8d, $00, $3f, $8d, $00, $91, $3a, $8d, $00, $38, $8d, $00, $91, $38, $8f, $37, $a1, $38, $8d, $00, $3a
	.byte $8d, $00, $91, $48, $3a, $8d, $00, $3c, $8d, $00, $91, $3c, $8d, $00, $3d, $8d, $00, $91
	.byte $41, $0e
	.word @song0ref623
	.byte $8d, $00
	.byte $41, $1a
	.word @song0ref619
	.byte $41, $0e
	.word @song0ref628
	.byte $41, $bf
	.word @song0ref653
	.byte $9f, $00, $76, $14, $8f, $13, $9f, $00, $7d, $36, $87, $00, $85, $35, $95, $00, $9b, $38, $95, $00, $9b, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $79, $80, $3f, $9f, $00, $40, $4c, $8d, $00, $40, $4d, $d1
@song0ref914:
	.byte $00, $83, $40, $4c, $8d, $00, $3f, $9f, $00, $3e, $8d, $00, $3f, $9f, $00, $40, $4c, $8d, $00, $40, $4d, $8f, $c1
	.byte $41, $12
	.word @song0ref914
	.byte $9f, $00, $40, $4c, $8d, $00, $3f, $9f, $00, $3e, $8d, $00, $3d, $9f, $00, $3c, $8d, $00, $3a, $9f, $00, $91, $7d, $37
	.byte $95, $00, $ff, $87
@song0ref968:
	.byte $76, $35, $8d, $00, $91, $74, $25, $8d, $00, $79, $35, $a1, $00, $8f, $74, $0f, $8d, $00, $91, $25, $8d, $00, $76, $37
	.byte $b3, $3a, $8d, $00, $91, $74, $24, $8d, $00, $76, $38, $8f, $c1, $00, $83, $73, $20, $8d, $00, $20, $8d, $00, $91, $20
	.byte $8d, $00, $74
@song0ref1019:
	.byte $33, $8d, $00, $91, $34, $8d, $00, $35, $8d, $00, $91, $34, $8d, $00, $33, $9f, $00, $33, $8d, $00, $33, $8d, $00, $33
	.byte $8d, $00, $33, $8d, $00
	.byte $41, $11
	.word @song0ref1019
@song0ref1051:
	.byte $73, $24, $8d, $00, $1b, $8d, $00, $91, $24, $8d, $00, $74, $35, $8d, $00, $91, $73, $22, $8d, $00, $75, $35, $a1, $00
	.byte $8f, $73, $19, $8d, $00, $91, $22, $8d, $00, $75, $33, $b1, $00, $73, $18, $8d, $00, $91, $20, $8d, $00, $74, $33, $8f
	.byte $c1, $00, $83, $1b, $8d, $00, $76, $17, $8d, $00, $91, $79, $1b, $8d, $00, $7a, $16, $8d, $00, $91, $7e, $37, $8d, $00
	.byte $37, $8d, $00, $38, $8d, $00, $39, $8d, $00, $7a, $16, $8d, $00, $91, $7e, $3a, $8d, $00, $3a, $8d, $00, $3c, $8d, $00
	.byte $3e, $8d, $00, $3f, $8d, $00, $91, $3a, $8d, $00, $3a, $8d, $00, $91, $3a, $8d, $00, $3a, $9f, $00, $c7
	.byte $41, $47
	.word @song0ref968
	.byte $41, $11
	.word @song0ref1019
	.byte $41, $66
	.word @song0ref1051
	.byte $91, $79, $33, $9f, $00, $33, $8d, $00, $7b
@song0ref1186:
	.byte $33, $af, $00, $81, $37, $9f, $00, $3a, $8d, $00, $40, $4d, $af, $00, $81, $40, $4d, $af, $00, $81, $40, $4d, $c5, $bf
	.byte $00, $85, $3f, $8d, $00, $3f, $8d, $00, $3c, $8d, $00, $3f, $8d, $00, $40, $4d, $ff, $85, $00, $85, $3d, $8d, $00, $3d
	.byte $8d, $00, $3a, $8d, $00, $3d, $8d, $00, $40, $4d, $ff, $85, $00, $85, $3f, $8d, $00, $3c, $9f, $00, $38, $8d, $00
	.byte $41, $1a
	.word @song0ref1186
@song0ref1260:
	.byte $78, $1b, $8d, $00, $7b, $3c, $8d, $00, $3f, $8d, $00, $40, $50, $af, $00, $81, $38, $a1, $3a, $8d, $00, $3c, $a1, $8d
	.byte $00, $81, $38, $af, $00, $81, $3a, $e3, $00, $83, $38, $9f, $00, $38, $8d, $00, $38, $8d, $00, $37, $8d, $00, $91
	.byte $41, $42
	.word @song0ref1186
	.byte $41, $1a
	.word @song0ref1186
	.byte $41, $22
	.word @song0ref1260
	.byte $c7
@song0ref1317:
	.byte $73
@song0ref1318:
	.byte $19
@song0ref1319:
	.byte $8d, $00, $91, $1d, $8d, $00, $1d, $8d, $00, $91, $1d, $8d, $00
@song0ref1332:
	.byte $1b
@song0ref1333:
	.byte $8d, $00, $91, $1e, $8d, $00, $1e, $8d, $00, $91, $1e, $8d, $00, $1d, $8d, $00, $91, $20, $8d, $00, $18, $8d, $00, $91
	.byte $1e, $8d, $00
	.byte $41, $0e
	.word @song0ref1318
	.byte $41, $23
	.word @song0ref1318
	.byte $20, $8d, $00, $91, $20, $8d, $00
	.byte $41, $0e
	.word @song0ref1318
@song0ref1376:
	.byte $1e
@song0ref1377:
	.byte $8d, $00, $91, $22, $8d, $00, $22, $8d, $00, $91, $22, $8d, $00, $1d, $8d, $00, $91, $20, $8d, $00, $20, $8d, $00, $91
	.byte $74, $20, $8d, $00, $75
	.byte $41, $15
	.word @song0ref1332
@song0ref1409:
	.byte $1e, $8d, $00, $91, $22, $8d, $00, $20
@song0ref1417:
	.byte $8d, $00, $91, $25, $8d, $00, $25, $8d, $00, $91, $25, $8d, $00, $77, $2e, $8d, $00, $91, $2e, $8f, $30, $8d, $00, $91
	.byte $2c, $8d, $00, $31, $9f, $00, $75, $20, $8f, $1f, $a1, $20, $8f, $14, $a1, $00, $c5
	.byte $41, $2a
	.word @song0ref1317
	.byte $41, $0e
	.word @song0ref1318
	.byte $41, $23
	.word @song0ref1318
	.byte $20, $8d, $00, $91, $20, $8d, $00
	.byte $41, $0e
	.word @song0ref1318
	.byte $41, $1c
	.word @song0ref1376
	.byte $75
	.byte $41, $15
	.word @song0ref1332
	.byte $41, $2c
	.word @song0ref1409
@song0ref1487:
	.byte $9f, $00, $79, $40, $50, $8f, $40, $4f, $a1, $40, $50, $8f, $38, $9f, $00, $76, $20, $8f, $1f, $a1, $20, $8f, $14
	.byte $41, $0e
	.word @song0ref1487
@song0ref1513:
	.byte $8f, $91, $20, $8f, $14, $9f, $00, $79, $40, $50, $8f, $40, $4f, $a1, $40, $50, $8f, $38, $9f, $00, $78, $38, $8d, $00
	.byte $79, $39, $9f, $00, $7a, $39, $8d, $00, $79, $3a, $9f, $00, $3a, $8d, $00, $3b, $9f, $00, $3b, $8d, $00, $3c, $9f, $00
	.byte $91, $7d, $3c, $95, $00, $bf, $79, $40, $50, $8f, $40, $4f, $a1, $40, $50, $8d, $00, $40, $4d, $8d, $00, $91, $40, $50
	.byte $8d, $00, $40, $4f, $a1, $40, $50, $8d, $00, $40, $4e, $af, $00, $81, $3c, $af, $00, $81, $3d, $af, $00, $81, $3f, $8f
	.byte $9f, $00, $81, $40, $4d, $9f, $00, $40, $50, $8f, $40, $4f, $a1, $40, $50, $8d, $00, $76, $0d
	.byte $41, $0d
	.word @song0ref1319
@song0ref1631:
	.byte $79, $40, $4e, $a1, $8d, $00, $81, $3c, $af, $00, $81, $40, $50, $ff, $85, $00, $85, $40, $50, $8f, $40, $4f, $a1, $40
	.byte $50, $8d, $00, $40, $52, $87, $00, $97, $40, $52, $8f, $40, $51, $a1, $40, $52, $8d, $00, $40, $52, $8d, $00, $91, $40
	.byte $52, $8f, $40, $51, $a1, $40, $52, $8d, $00, $40, $52, $af, $00, $81, $40, $5a, $8f, $9f, $00, $81, $40, $59, $8d, $00
	.byte $91, $40, $56, $8d, $00, $40, $57, $8d, $00, $91, $40, $52, $8d, $00, $40, $50, $8d, $00, $91, $40, $50, $8f, $40, $4f
	.byte $a1, $40, $50, $8d, $00, $40, $4f, $8d, $00, $91, $40, $4f, $8d, $00, $40, $4e, $8d, $00, $91, $40, $4e, $8d, $00, $40
	.byte $4d, $8d, $00, $91
@song0ref1755:
	.byte $76, $20, $8f, $1f, $a1, $20, $8f, $14, $9f, $00, $79, $40, $50, $8f, $40, $4f, $a1, $40, $50, $8d, $00, $38, $9f, $00
	.byte $41, $0e
	.word @song0ref1755
	.byte $8f, $38, $9f, $00, $76, $20, $8f, $1f
	.byte $41, $5c
	.word @song0ref1513
	.byte $41, $0d
	.word @song0ref1319
	.byte $41, $5c
	.word @song0ref1631
	.byte $9f, $00, $76, $20, $8f, $1f, $9f, $00, $7d, $38, $87, $00, $85, $38, $95, $00, $9b, $3d, $95, $00, $9b, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref1824:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $41, $0f
	.word @song0ref1824
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $76, $82, $0f, $9f, $00, $10, $8d, $00, $11, $d1
@song0ref1975:
	.byte $00, $83, $10, $8d, $00, $0f, $9f, $00, $0e, $8d, $00, $0f, $9f, $00, $10, $8d, $00, $11, $8f, $c1
	.byte $41, $12
	.word @song0ref1975
	.byte $9f, $00, $10, $8d, $00, $0f, $9f, $00, $0e, $8d, $00, $0d, $9f, $00, $0c, $8d, $00, $0a, $9f, $00, $91, $7d, $3a, $95
	.byte $00, $ff, $87
@song0ref2025:
	.byte $74, $0d, $8d, $00, $91, $29, $8d, $00, $22, $8d, $00, $91, $22, $8d, $00, $a3, $27, $8d, $00, $22, $8d, $00, $91, $22
	.byte $8d, $00, $14, $8d, $00, $91, $27, $8d, $00, $20, $8d, $00, $91, $20, $8d, $00, $14, $8d, $00, $91, $73, $24, $8d, $00
	.byte $24, $8d, $00, $91, $24
@song0ref2078:
	.byte $8d, $00, $1f, $8d, $00, $91, $25, $8d, $00, $1b, $8d, $00, $91, $25
	.byte $41, $0d
	.word @song0ref2078
@song0ref2095:
	.byte $24, $8d, $00, $20, $8d, $00, $91, $24, $8d, $00, $1b, $8d, $00, $91, $24, $8d, $00, $20, $8d, $00, $91, $27, $8d, $00
	.byte $a3, $27, $8d, $00, $1a, $8d, $00, $a3, $1a, $8d, $00, $91, $20, $8d, $00, $b5, $75, $37, $a1, $00, $c5, $74, $38, $8f
	.byte $c1, $00, $83, $20, $8d, $00, $a3, $79, $20, $8d, $00, $a3, $7a, $1b, $8d, $00, $16, $8d, $00, $91, $1b, $8d, $00, $a3
	.byte $1d, $8d, $00, $16, $8d, $00, $91, $1d, $8d, $00, $1b, $8d, $00, $91, $7e, $3e, $8d, $00, $3f, $8d, $00, $91, $3e, $8d
	.byte $00, $3f, $9f, $00, $c7
	.byte $41, $41
	.word @song0ref2025
	.byte $41, $0d
	.word @song0ref2078
	.byte $41, $60
	.word @song0ref2095
	.byte $78
@song0ref2206:
	.byte $13, $8d, $00, $91, $25, $8d, $00, $1b, $8d, $00, $91, $22
@song0ref2218:
	.byte $8d, $00
@song0ref2220:
	.byte $13, $8d, $00, $91, $22, $8d, $00, $1b
@song0ref2228:
	.byte $8d, $00, $91, $22
@song0ref2232:
	.byte $8d, $00, $14, $8d, $00, $91, $20, $8d, $00, $1b, $8d, $00, $91, $20
	.byte $41, $0e
	.word @song0ref2232
	.byte $41, $10
	.word @song0ref2218
	.byte $41, $1a
	.word @song0ref2220
	.byte $41, $0e
	.word @song0ref2232
	.byte $8d, $00
	.byte $41, $28
	.word @song0ref2206
@song0ref2263:
	.byte $8d, $00, $14, $8d, $00, $91, $20, $8d, $00, $a3, $20, $8d, $00, $10, $8d, $00, $91, $20, $8d, $00, $10, $8d, $00, $91
	.byte $20, $8d, $00, $0f, $8d, $00, $91, $20, $8d, $00, $1b, $8d, $00, $91, $20, $8d, $00, $13, $8d, $00, $91, $1f, $8d, $00
	.byte $1b, $8d, $00, $91, $1f, $8d, $00, $20, $9f, $00, $c7
	.byte $41, $28
	.word @song0ref2206
	.byte $41, $0e
	.word @song0ref2232
	.byte $41, $10
	.word @song0ref2218
	.byte $41, $1a
	.word @song0ref2220
	.byte $41, $0e
	.word @song0ref2232
	.byte $8d, $00
	.byte $41, $28
	.word @song0ref2206
	.byte $41, $3b
	.word @song0ref2263
@song0ref2345:
	.byte $a3, $73
@song0ref2347:
	.byte $20, $8d, $00, $20, $8d, $00
@song0ref2353:
	.byte $91, $20
@song0ref2355:
	.byte $8d, $00, $a3, $20, $8d, $00, $20, $8d, $00, $91, $20, $8d, $00, $c7
	.byte $41, $0f
	.word @song0ref2353
	.byte $a3
	.byte $41, $15
	.word @song0ref2347
	.byte $a3, $25, $8d, $00, $25, $8d, $00, $91, $25
	.byte $41, $0d
	.word @song0ref2355
@song0ref2388:
	.byte $a3, $25, $8d, $00, $25, $8d, $00, $91, $25, $8d, $00, $a3, $22, $8d, $00, $22, $8d, $00, $91, $74, $22, $8d, $00, $a3
	.byte $75, $22, $8d, $00, $22, $8d, $00, $91, $22, $8d, $00, $a3, $22, $8d, $00, $a3, $27, $8d, $00, $a3, $29, $8d, $00, $29
	.byte $8d, $00, $91, $29, $8d, $00, $20
@song0ref2443:
	.byte $8d, $00, $91, $20, $8d, $00, $20, $8d, $00, $91, $20, $8d, $00, $19, $9f, $00, $ff, $b3
	.byte $41, $17
	.word @song0ref2345
	.byte $41, $0f
	.word @song0ref2353
	.byte $a3
	.byte $41, $15
	.word @song0ref2347
	.byte $a3, $25, $8d, $00, $25, $8d, $00, $91, $25
	.byte $41, $0d
	.word @song0ref2355
	.byte $41, $47
	.word @song0ref2388
@song0ref2486:
	.byte $ff, $ff, $9f, $ff, $b3, $76, $14, $8d, $00, $15, $9f, $00, $15, $8d, $00, $16, $9f, $00, $16, $8d, $00, $17, $9f, $00
	.byte $17, $8d, $00, $18, $9f, $00, $91, $7d, $3f, $95, $00, $ff, $87, $79, $0d, $87, $00, $97, $76, $1d, $8d, $00, $1d, $8d
	.byte $00, $91, $1d, $8d, $00, $79, $0f, $87, $00, $97, $76, $1e, $8d, $00, $1e, $8d, $00, $91, $1e, $8d, $00, $11, $8d, $00
	.byte $91, $20, $8d, $00, $0c, $8d, $00, $91, $1e, $8d, $00, $0d
	.byte $41, $0d
	.word @song0ref1319
	.byte $19
	.byte $41, $0d
	.word @song0ref2443
	.byte $0f
	.byte $41, $0d
	.word @song0ref1333
	.byte $11
	.byte $41, $0d
	.word @song0ref2443
	.byte $0d
	.byte $41, $0d
	.word @song0ref1319
	.byte $12
	.byte $41, $0d
	.word @song0ref1377
	.byte $11
	.byte $41, $0d
	.word @song0ref2443
	.byte $0f
	.byte $41, $0d
	.word @song0ref1333
@song0ref2601:
	.byte $11, $8d, $00, $91, $20, $8d, $00, $12, $8d, $00, $91, $1e, $8d, $00, $14
	.byte $41, $0d
	.word @song0ref2443
@song0ref2619:
	.byte $79, $40, $52, $8d, $00, $91, $40, $52, $8d, $00, $40, $54, $8d, $00, $91, $40, $50, $8d, $00, $40, $55, $8d, $00, $ff
	.byte $c5
	.byte $41, $4e
	.word @song0ref2486
	.byte $41, $0d
	.word @song0ref1319
	.byte $19
	.byte $41, $0d
	.word @song0ref2443
	.byte $0f
	.byte $41, $0d
	.word @song0ref1333
	.byte $11
	.byte $41, $0d
	.word @song0ref2443
	.byte $0d
	.byte $41, $0d
	.word @song0ref1319
	.byte $12
	.byte $41, $0d
	.word @song0ref1377
	.byte $11
	.byte $41, $0d
	.word @song0ref2443
	.byte $0f
	.byte $41, $0d
	.word @song0ref1333
	.byte $41, $0f
	.word @song0ref2601
	.byte $41, $0d
	.word @song0ref2443
	.byte $41, $0f
	.word @song0ref2619
	.byte $9f, $00, $b5, $7d, $3c, $87, $00, $85, $3d, $95, $00, $9b, $79, $0d, $95, $00, $9b, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $76, $82, $1b, $9f, $00, $1c, $8d, $00, $1d, $d1
@song0ref2718:
	.byte $00, $83, $1c, $8d, $00, $1b, $9f, $00, $1a, $8d, $00, $1b, $9f, $00, $1c, $8d, $00, $1d, $8f, $c1
	.byte $41, $12
	.word @song0ref2718
	.byte $9f, $00, $1c, $8d, $00, $1b, $9f, $00, $1a, $8d, $00, $19, $9f, $00, $18, $8d, $00, $16, $9f, $00, $91, $7d, $3f, $95
	.byte $00, $ff, $87
@song0ref2768:
	.byte $b5, $74, $25, $8d, $00, $91, $25, $8d, $00, $b5, $25, $8d, $00, $91, $25, $8d, $00, $b5, $24, $8d, $00, $91, $24, $8d
	.byte $00, $a3, $73, $27, $8d, $00, $27, $8d, $00, $91, $27, $8d, $00, $a3, $27, $8d, $00, $a3, $27, $8d, $00, $a3, $27, $8d
	.byte $00, $a3, $27, $8d, $00, $a3, $27, $8d, $00, $a3, $27, $8d, $00, $eb, $d9, $22, $8d, $00, $b5, $19, $8d, $00, $91, $1f
	.byte $8d, $00, $b5, $18, $8d, $00, $91, $1b, $8d, $00, $17, $8d, $00, $fd, $7a, $1f, $8d, $00, $a3, $1f, $8d, $00, $a3, $20
	.byte $8d, $00, $a3, $20, $8d, $00, $1f, $8d, $00, $91, $16, $8d, $00, $0f, $8d, $00, $91, $16, $8d, $00, $0f, $9f, $00, $c7
	.byte $41, $71
	.word @song0ref2768
	.byte $74, $0f, $9f, $00, $c7, $a3, $78
@song0ref2898:
	.byte $27
@song0ref2899:
	.byte $8d, $00, $a3, $25, $8d, $00, $a3, $25, $8d, $00, $a3, $25, $8d, $00, $a3, $24, $8d, $00, $91, $91, $24, $8d, $00, $a3
	.byte $24, $8d, $00, $a3, $24
	.byte $41, $0f
	.word @song0ref2899
@song0ref2931:
	.byte $25, $8d, $00, $a3, $24, $8d, $00, $a3, $24, $8d, $00, $a3, $24, $8d, $00, $a3, $24, $8d, $00, $a3
	.byte $41, $1e
	.word @song0ref2898
@song0ref2954:
	.byte $8d, $00, $1c, $8d, $00, $91, $23, $8d, $00, $1c, $8d, $00, $91, $23, $8d, $00, $1b, $8d, $00, $91, $24, $8d, $00, $a3
	.byte $24, $8d, $00, $a3, $25, $8d, $00, $a3, $25, $8d, $00, $24, $9f, $00, $c7, $a3
	.byte $41, $1e
	.word @song0ref2898
	.byte $41, $0f
	.word @song0ref2899
	.byte $41, $14
	.word @song0ref2931
	.byte $41, $1e
	.word @song0ref2898
	.byte $41, $27
	.word @song0ref2954
@song0ref3009:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $d7, $73, $25, $8d, $00, $25, $8d, $00, $91, $25, $8d, $00, $ff, $8f, $26, $8d, $00
	.byte $26, $8d, $00, $91, $74, $26, $8d, $00, $a3, $75, $27, $8d, $00, $91, $91, $27, $8d, $00, $a3, $26, $8d, $00, $ff, $a1
	.byte $25, $8d, $00, $91, $25, $8d, $00, $24, $8d, $00, $91, $24, $8d, $00, $25, $9f, $00, $ff, $b3
	.byte $41, $40
	.word @song0ref3009
	.byte $ff, $ff, $9f, $ff, $b3, $76
@song0ref3085:
	.byte $20, $8d, $00, $21, $9f, $00, $21, $8d, $00, $22, $9f, $00, $22, $8d, $00, $23, $9f, $00, $23, $8d, $00, $24, $9f, $00
	.byte $91, $7d, $40, $50, $95, $00, $ff, $87, $79, $19
@song0ref3119:
	.byte $87, $00, $97, $76, $20, $8d, $00, $20, $8d, $00, $91, $20, $8d, $00, $79, $1b
	.byte $41, $0d
	.word @song0ref3119
@song0ref3138:
	.byte $1d, $8d, $00, $91, $25, $8d, $00, $18, $8d, $00, $91, $20, $8d, $00, $19
	.byte $41, $0d
	.word @song0ref2443
	.byte $a3, $25, $8d, $00, $25, $8d, $00, $91, $25, $8d, $00, $1b
	.byte $41, $0d
	.word @song0ref2443
	.byte $1d
	.byte $41, $0d
	.word @song0ref1417
	.byte $19
	.byte $41, $0d
	.word @song0ref2443
	.byte $1e
	.byte $41, $0d
	.word @song0ref1417
	.byte $1d
	.byte $41, $0d
	.word @song0ref1377
	.byte $1b
	.byte $41, $11
	.word @song0ref1377
	.byte $22, $8d, $00
	.byte $41, $15
	.word @song0ref1409
	.byte $14
	.byte $41, $0d
	.word @song0ref2228
	.byte $19, $8d, $00, $ff, $c5, $ff, $ff, $9f, $ff, $b3
	.byte $41, $2d
	.word @song0ref3085
	.byte $41, $0d
	.word @song0ref3119
	.byte $41, $0f
	.word @song0ref3138
	.byte $41, $0d
	.word @song0ref2443
	.byte $a3, $25, $8d, $00, $25, $8d, $00, $91, $25, $8d, $00, $1b
	.byte $41, $0d
	.word @song0ref2443
	.byte $1d
	.byte $41, $0d
	.word @song0ref1417
	.byte $19
	.byte $41, $0d
	.word @song0ref2443
	.byte $1e
	.byte $41, $0d
	.word @song0ref1417
	.byte $1d
	.byte $41, $0d
	.word @song0ref1377
	.byte $1b
	.byte $41, $11
	.word @song0ref1377
	.byte $22, $8d, $00
	.byte $41, $15
	.word @song0ref1409
	.byte $14
	.byte $41, $0d
	.word @song0ref2228
	.byte $0d, $9f, $00, $b5, $79, $14, $87, $00, $85, $0d, $95, $00, $9b, $19, $95, $00, $9b, $42
	.word @song0ch6loop
