; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_cloud=music_data_cloud
.endif

music_data_cloud:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : cloud
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_cloud
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env2,@env3,@env6,@env0 ; 00 : Acoustic Bass
	.word @env7,@env3,@env5,@env0 ; 01 : Steel Drums
	.word @env2,@env3,@env4,@env0 ; 02 : Duty 0
	.word @env1,@env3,@env4,@env0 ; 03 : Acoustic Grand Piano

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c7,$c5,$c3,$c0,$00,$04
@env2:
	.byte $00,$cf,$7f,$00,$02
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $7f,$00,$00
@env5:
	.byte $c2,$7f,$00,$00
@env6:
	.byte $c1,$7f,$00,$00
@env7:
	.byte $00,$c0,$cf,$00,$02

@samples:
	.byte $45+.lobyte(FAMISTUDIO_DPCM_PTR),$31,$0d,$40 ; 00 snare (Pitch:13)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$21,$0c,$40 ; 01 snare2 (Pitch:12)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $82
@song0ref6:
	.byte $37, $97, $39, $97, $33, $8b, $34, $97, $32, $89, $33, $8b, $32, $89, $30, $97, $30, $97, $32, $97, $48, $33, $97, $33
	.byte $8b, $32, $89, $30, $8b, $32, $89, $34, $8b, $37, $89, $39, $8b, $34, $89, $37, $8b, $32, $89, $34, $8b, $30, $89, $32
	.byte $8b, $30, $89, $48, $34, $97, $37, $97, $39, $8b, $34, $89, $37, $8b, $32, $89, $34, $8b, $30, $89, $33, $8b, $34, $89
	.byte $33, $8b, $32, $89, $30, $8b, $32, $89, $48, $33, $97, $30, $8b, $32, $89, $34, $8b, $37, $89, $33, $8b, $34, $89, $32
	.byte $8b, $30, $89, $32, $97, $30, $97, $32, $97, $48
	.byte $41, $64
	.word @song0ref6
	.byte $30
@song0ref116:
	.byte $97, $48, $30, $97, $2b, $8b, $2d, $89, $30, $97, $2b, $8b, $2d, $89, $30, $8b, $32, $89, $34, $8b, $30, $89, $35, $8b
	.byte $34, $89, $35, $8b, $37, $89, $48, $30, $97, $30, $97, $2b, $8b, $2d, $89, $30, $8b, $2b, $89, $35, $8b, $34, $89, $32
	.byte $8b, $30, $89, $29, $8b, $28, $89, $29, $8b, $2b, $89, $48, $30, $97, $2b, $8b, $2d, $89, $30, $97, $2b, $8b, $2d, $89
	.byte $30, $8b, $30, $89, $32, $8b, $34, $89, $30, $8b, $2b, $89, $2d, $8b, $2b, $89, $48, $30, $97, $30, $8b, $2f, $89, $30
	.byte $8b, $2b, $89, $2d, $8b, $30, $89, $35, $8b, $34, $89, $35, $8b, $37, $89, $30, $97, $2f
	.byte $41, $6d
	.word @song0ref116
	.byte $32, $97, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $99, $80
@song0ref241:
	.byte $1d, $97, $00, $97, $1f, $97, $00, $97, $1c, $97, $00, $97, $21, $97, $00, $97, $1a, $97, $00, $97, $1f, $97, $00, $97
	.byte $18, $97, $00, $97, $18, $97, $00, $97
	.byte $41, $20
	.word @song0ref241
	.byte $41, $20
	.word @song0ref241
	.byte $41, $20
	.word @song0ref241
	.byte $41, $20
	.word @song0ref241
	.byte $41, $20
	.word @song0ref241
	.byte $41, $20
	.word @song0ref241
	.byte $41, $1e
	.word @song0ref241
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $79, $84
@song0ref300:
	.byte $11, $b1, $13, $b1, $10, $b1, $15, $b1, $0e, $b1, $13, $b1, $0c, $97, $0c, $97, $0e, $97, $10, $97
	.byte $41, $14
	.word @song0ref300
	.byte $41, $14
	.word @song0ref300
	.byte $41, $14
	.word @song0ref300
	.byte $41, $14
	.word @song0ref300
	.byte $41, $14
	.word @song0ref300
	.byte $41, $14
	.word @song0ref300
	.byte $41, $10
	.word @song0ref300
	.byte $0c, $97, $0c, $97, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $77, $86
@song0ref351:
	.byte $13, $85, $00, $8f, $7f, $15, $85, $00
@song0ref359:
	.byte $8f, $77
@song0ref361:
	.byte $13, $85, $00, $8f, $7f, $15, $85, $00, $83
@song0ref370:
	.byte $15, $83, $00, $83
@song0ref374:
	.byte $77
@song0ref375:
	.byte $13
@song0ref376:
	.byte $85, $00, $8f, $13, $85, $00, $8f, $13, $85, $00, $8f, $13, $85, $00, $8f
	.byte $41, $18
	.word @song0ref351
	.byte $17, $97, $13, $85, $00, $8f, $13
@song0ref401:
	.byte $85, $00, $8f
@song0ref404:
	.byte $13, $85, $00, $8f, $7f, $15, $85, $00, $8f, $77, $13, $85, $00, $8f, $13, $85, $00, $83, $7f
	.byte $41, $14
	.word @song0ref370
	.byte $41, $0f
	.word @song0ref375
	.byte $83, $7f, $15, $83, $00, $83, $77, $13, $85, $00, $8f, $15
	.byte $41, $0f
	.word @song0ref376
	.byte $13, $85, $00, $8f
	.byte $41, $10
	.word @song0ref361
	.byte $7f, $15, $85, $00, $8f
	.byte $41, $10
	.word @song0ref374
@song0ref459:
	.byte $13, $85, $00, $8f, $13, $85, $00, $83, $7f, $15, $83, $00, $83, $77, $13, $85, $00, $8f, $15
	.byte $41, $0f
	.word @song0ref401
	.byte $7f, $15, $85, $00, $8f, $77
	.byte $41, $10
	.word @song0ref459
	.byte $41, $10
	.word @song0ref375
	.byte $7f, $15, $85, $00, $8f, $77
	.byte $41, $10
	.word @song0ref459
	.byte $17, $97
	.byte $41, $10
	.word @song0ref375
	.byte $41, $18
	.word @song0ref361
	.byte $7f, $15, $85, $00, $8f, $77
	.byte $41, $18
	.word @song0ref351
	.byte $17, $97
	.byte $41, $0f
	.word @song0ref351
	.byte $8f, $77
	.byte $41, $10
	.word @song0ref459
	.byte $41, $10
	.word @song0ref375
	.byte $13, $85, $00, $8f
	.byte $41, $10
	.word @song0ref361
	.byte $17, $97
	.byte $41, $0f
	.word @song0ref351
	.byte $41, $11
	.word @song0ref359
	.byte $7f, $15, $85, $00, $8f, $77
	.byte $41, $0f
	.word @song0ref404
	.byte $8f
	.byte $41, $10
	.word @song0ref459
	.byte $17, $97
	.byte $41, $10
	.word @song0ref375
	.byte $41, $1c
	.word @song0ref361
	.byte $41, $10
	.word @song0ref404
	.byte $7f, $15, $83, $00, $83, $77, $13, $85, $00, $8f, $15, $85, $00, $8f, $13, $85, $00, $8f, $7f, $15, $85, $00, $8f, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref598:
	.byte $02, $b1, $01, $b1, $02, $b1, $01, $b1, $02, $b1, $01, $b1, $02, $b1, $01, $b1
	.byte $41, $10
	.word @song0ref598
	.byte $41, $10
	.word @song0ref598
	.byte $41, $10
	.word @song0ref598
	.byte $41, $10
	.word @song0ref598
	.byte $41, $10
	.word @song0ref598
	.byte $41, $10
	.word @song0ref598
	.byte $41, $10
	.word @song0ref598
	.byte $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
@song0ref639:
	.byte $ff, $cf, $ff, $cf, $ff, $cf, $ff, $cf, $ff, $cf, $ff, $cf, $ff, $cf, $ff, $cf
	.byte $41, $10
	.word @song0ref639
	.byte $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $99, $80
@song0ref664:
	.byte $18, $97, $00, $97, $1c, $97, $00, $97, $18, $97, $00, $97, $1c, $97, $00, $97, $15, $97, $00, $97, $1a, $97, $00, $97
	.byte $13, $97, $00, $97, $13, $97, $00, $97
	.byte $41, $20
	.word @song0ref664
	.byte $41, $20
	.word @song0ref664
	.byte $41, $20
	.word @song0ref664
	.byte $41, $20
	.word @song0ref664
	.byte $41, $20
	.word @song0ref664
	.byte $41, $20
	.word @song0ref664
	.byte $41, $1e
	.word @song0ref664
	.byte $42
	.word @song0ch6loop
