; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_enter_in_a_pipe=music_data_enter_in_a_pipe
.endif

music_data_enter_in_a_pipe:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : enter in a pipe
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_enter_in_a_pipe
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env5,@env0 ; 00 : Acoustic Bass
	.word @env1,@env2,@env4,@env0 ; 01 : Duty 2
	.word @env1,@env2,@env3,@env0 ; 02 : Duty 0

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00
@env4:
	.byte $c2,$7f,$00,$00
@env5:
	.byte $c1,$7f,$00,$00

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0d,$40 ; 00 Sunsoft Bass A# (Pitch:13)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$09,$40 ; 01 Sunsoft Bass B (Pitch:9)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0c,$40 ; 02 Sunsoft Bass B (Pitch:12)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0d,$40 ; 03 Sunsoft Bass B (Pitch:13)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0e,$40 ; 04 Sunsoft Bass B (Pitch:14)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$05,$40 ; 05 Sunsoft Bass C (Pitch:5)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$06,$40 ; 06 Sunsoft Bass C (Pitch:6)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$08,$40 ; 07 Sunsoft Bass C (Pitch:8)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$09,$40 ; 08 Sunsoft Bass C (Pitch:9)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0a,$40 ; 09 Sunsoft Bass C (Pitch:10)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0b,$40 ; 0a Sunsoft Bass C (Pitch:11)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0d,$40 ; 0b Sunsoft Bass C (Pitch:13)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$07,$40 ; 0c Sunsoft Bass C# (Pitch:7)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$08,$40 ; 0d Sunsoft Bass C# (Pitch:8)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$09,$40 ; 0e Sunsoft Bass C# (Pitch:9)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0a,$40 ; 0f Sunsoft Bass C# (Pitch:10)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0c,$40 ; 10 Sunsoft Bass C# (Pitch:12)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $79, $80, $21, $78, $82, $22, $77, $81, $76, $81, $75, $81, $71, $81, $79, $80, $21, $78, $82, $22, $77, $81, $76, $81
	.byte $75, $81, $71, $81, $72, $85, $71, $85
@song0ref33:
	.byte $79, $80, $21, $78, $82, $22, $77, $81, $76, $81, $75, $81, $71, $81, $79, $80, $23, $78, $82, $24, $77, $81, $76, $81
	.byte $75, $81, $71, $81, $72, $85, $71, $85, $79, $80, $24, $78, $82, $25, $77, $81, $76, $81, $75, $81, $71, $81, $72, $85
	.byte $71, $85, $79, $80, $25, $78, $82, $26, $77, $81, $76, $81, $75, $81, $71, $81, $72, $85, $71, $9d
	.byte $41, $0c
	.word @song0ref33
	.byte $79, $80, $24, $78, $82, $25, $77, $81, $76, $81, $75, $81, $71, $81, $79, $80, $25, $78, $82, $26, $77, $81, $76, $81
	.byte $75, $81, $71, $81, $79, $81
@song0ref134:
	.byte $27, $9d, $74, $81, $71, $81, $72, $81, $73, $87, $79, $2a, $2b, $9d, $74, $81, $71, $81, $72, $81, $73, $87, $79, $2c
	.byte $2d, $2e, $9b, $74, $81, $71, $81, $72, $81, $73, $87, $79, $83, $2d, $9b, $74, $81, $71, $81, $72, $81, $73, $87, $79
	.byte $81, $2c, $9d, $74, $81, $71, $81, $72, $81, $73, $87, $79, $2a, $29, $8b, $74, $81, $71, $81, $72, $81, $73, $28, $79
	.byte $27, $26, $9f, $78, $4e, $ff, $81, $4e, $fe, $83, $4e, $00, $83, $4e, $02, $83, $4e, $01, $81, $4e, $00, $81, $4e, $ff
	.byte $81, $48
@song0ref232:
	.byte $4e, $fe, $83, $77, $4e, $00, $83, $4e, $01, $81, $4e, $02, $81, $4e, $01, $81, $4e, $00, $81, $4e, $ff, $81, $4e, $fe
	.byte $83, $4e, $ff, $81, $4e, $00, $81, $4e, $01, $81, $76, $4e, $02, $81, $4e, $01, $81, $4e, $00, $83, $4e, $fe, $81, $75
	.byte $81, $74, $4e, $ff, $81, $73, $4e, $00, $81, $4e, $01, $81, $4e, $02, $83, $4e, $00, $83, $4e, $fe, $83, $4e, $ff, $81
	.byte $4e, $00, $81, $4e, $01, $81, $4e, $02, $83, $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $81
	.byte $4e, $01, $81, $71, $4e, $02
@song0ref334:
	.byte $11, $73, $12, $76, $4e, $00, $13, $79, $14, $15, $16, $95, $15, $89, $74, $81, $71, $81, $72, $81, $73, $81, $79, $81
	.byte $16, $8b, $74, $81, $71, $81, $72, $81, $73, $81, $79, $1b, $1c, $1d, $8d, $74, $81, $71, $81, $79, $1b, $1c, $1d, $9b
	.byte $74, $81, $71, $81, $72, $81, $73, $87, $79
@song0ref391:
	.byte $1f, $81, $20, $93, $1f, $95, $1d, $1b, $89, $74, $81, $71, $81, $72, $81, $73, $81, $79, $81, $19, $18, $89, $74, $81
	.byte $71, $81, $72, $81, $73, $81, $79, $17, $16, $9f, $78, $4e, $fd, $81, $4e, $fc, $83, $4e, $ff, $81, $4e, $01, $81, $4e
	.byte $04, $83, $4e, $03, $81, $4e, $00, $81, $4e, $fe, $81, $4e, $fc, $83, $77, $4e, $ff, $81, $4e, $00, $81, $4e, $03, $81
	.byte $4e, $04, $81, $4e, $03, $81, $4e, $00, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00, $81, $4e, $03, $81
	.byte $76, $4e, $04, $81, $4e, $03, $81, $4e, $00, $81, $4e, $ff, $81, $4e, $fc, $81, $75, $81, $74, $4e, $fe, $81, $73, $4e
	.byte $00, $81, $4e, $03, $81, $4e, $04, $83, $4e, $01, $81, $4e, $ff, $81, $4e, $fc, $83, $4e, $fd, $81, $4e, $00, $81, $4e
	.byte $02, $81, $79, $4e, $00, $80, $17, $81, $4e, $f7, $81, $4e, $09, $18, $4e, $00, $8f, $17, $8d, $74, $81, $71, $81, $72
	.byte $81, $73, $81, $79, $18, $8d, $48, $74, $81, $71, $81, $72, $81, $73, $81, $79, $1b, $a1, $74, $81, $71, $81, $72, $81
	.byte $73, $85, $79, $8f, $74, $81, $71, $81, $72, $81, $73, $81, $79
@song0ref596:
	.byte $1d, $97, $4e, $f6, $1c, $4e, $01, $81, $4e, $f7, $1b, $4e, $f5, $1a, $4e, $0a, $81, $4e, $07, $19, $4e, $03, $18, $4e
	.byte $fd, $17, $4e, $00, $16, $18, $1b, $1d, $1e, $81, $1f, $8f, $1e, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $1f
	.byte $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $22, $23, $24, $a3, $74, $81, $71, $81, $72, $81, $73, $97, $79, $23
	.byte $97, $24, $8b, $74, $81, $71, $81, $72, $81, $73, $81, $79, $81, $25, $26, $9b, $74, $81, $71, $81, $72, $81, $73, $87
	.byte $79, $21, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $81, $22, $b3, $74, $81, $71, $81, $72, $81, $73, $89, $79
	.byte $21, $95, $22, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $48, $79, $81, $23, $24, $9b, $74, $81, $71, $81, $72, $81
	.byte $73, $87, $79, $1f, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $83, $20, $99, $74, $81, $71, $81, $72, $81, $73
	.byte $89, $79, $1d, $ab, $4e, $fa, $81, $4e, $f7, $81, $4e, $f8, $81, $4e, $fe, $81, $4e, $02, $81, $4e, $08, $81, $4e, $09
	.byte $81, $4e, $06, $81, $4e, $00, $81, $74, $4e, $fb, $81, $71, $4e, $f7, $81, $72, $4e, $f8, $81, $73, $4e, $00, $81, $79
	.byte $82, $26
	.byte $41, $34
	.word @song0ref134
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
	.byte $41, $20
	.word @song0ref232
	.byte $71, $4e, $02, $82
	.byte $41, $6b
	.word @song0ref334
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $79, $82, $1a, $81, $80, $1a, $73, $81, $71, $81, $72, $81, $79, $82, $1a, $81, $80, $1a, $73, $81, $71, $81, $72, $87
	.byte $71, $85
@song0ref860:
	.byte $79, $82, $1a, $81, $80, $1a, $73, $81, $71, $81, $72, $81, $79, $82, $1b, $81, $80, $1b, $73, $81, $71, $81, $72, $87
	.byte $71, $85, $79, $82, $1c, $81, $80, $1c, $73, $81, $71, $81, $72, $87, $71, $85, $79, $82, $1d, $81, $80, $1d, $73, $81
	.byte $71, $81, $72, $87, $71, $9d
	.byte $41, $0b
	.word @song0ref860
	.byte $72, $81, $79, $82, $1c, $81, $80, $1c, $73, $81, $71, $81, $72, $81, $79, $82, $1d, $81, $80, $1d, $73, $81, $71, $81
	.byte $72, $81, $7a, $84, $18, $77, $16, $76, $81, $75, $81
@song0ref952:
	.byte $72, $1a, $73, $81, $7a, $81
@song0ref958:
	.byte $77, $18, $76, $81, $75, $81, $72, $14
@song0ref966:
	.byte $73, $81, $7a, $1d, $77, $1b
@song0ref972:
	.byte $76, $81, $75, $81, $72, $16, $73, $81, $7a, $18, $77, $16, $76, $81, $75, $81, $72, $19, $73, $81, $7a, $1a
	.byte $41, $12
	.word @song0ref958
	.byte $41, $0b
	.word @song0ref958
@song0ref1000:
	.byte $7a, $17, $77, $15
@song0ref1004:
	.byte $76, $81, $75, $81, $72, $19, $73, $81, $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $13, $73, $81, $7a, $1d, $77, $1b
	.byte $76, $81, $75, $81, $72, $16, $73, $81
	.byte $41, $12
	.word @song0ref1000
@song0ref1039:
	.byte $7a, $17, $77, $15, $76, $81, $75, $81, $72, $19, $73, $81, $7a, $16, $77, $14
@song0ref1055:
	.byte $76, $81, $75, $81, $72, $13
@song0ref1061:
	.byte $73, $81, $7a, $18
@song0ref1065:
	.byte $77, $16, $76, $81, $75, $81
@song0ref1071:
	.byte $72, $12, $73, $81, $7a, $1c, $77, $1a, $76, $81, $75, $81, $72, $14, $73, $81, $7a, $16, $77, $14, $76, $81, $75, $81
	.byte $72, $18, $73, $81, $7a, $81
	.byte $41, $12
	.word @song0ref1065
	.byte $41, $12
	.word @song0ref1065
	.byte $41, $12
	.word @song0ref1065
	.byte $41, $11
	.word @song0ref1065
	.byte $7a, $16, $77, $14, $76, $81, $75, $81, $72, $12
	.byte $41, $14
	.word @song0ref1061
	.byte $41, $12
	.word @song0ref1065
	.byte $41, $12
	.word @song0ref1065
	.byte $41, $12
	.word @song0ref1065
	.byte $41, $12
	.word @song0ref1065
	.byte $77, $16, $76, $81, $75, $81, $72, $12, $73, $81, $7a, $1a
	.byte $41, $12
	.word @song0ref958
	.byte $41, $12
	.word @song0ref958
	.byte $41, $12
	.word @song0ref958
	.byte $41, $12
	.word @song0ref958
	.byte $41, $12
	.word @song0ref958
	.byte $41, $0b
	.word @song0ref958
	.byte $7a, $1f, $77, $1d
	.byte $41, $08
	.word @song0ref1004
@song0ref1175:
	.byte $72, $1b, $73, $81, $7a, $1d, $77, $1b, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $1f, $77, $1d
	.byte $41, $08
	.word @song0ref1004
	.byte $41, $08
	.word @song0ref1175
	.byte $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $19
@song0ref1211:
	.byte $73, $81, $7a, $1d, $77, $1b, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $20, $77, $1e
	.byte $41, $08
	.word @song0ref1004
	.byte $72, $1c
	.byte $41, $09
	.word @song0ref1211
	.byte $41, $08
	.word @song0ref1004
	.byte $72, $1c
	.byte $41, $0e
	.word @song0ref966
	.byte $41, $12
	.word @song0ref958
	.byte $41, $12
	.word @song0ref958
	.byte $77, $18, $76, $81, $75, $81, $72, $14, $73, $81, $7a, $18, $77, $16, $76, $81, $75, $81, $72, $81, $73, $81, $7a, $1a
	.byte $77, $18, $76, $81, $75, $81, $72, $14, $73, $81, $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref972
	.byte $41, $08
	.word @song0ref952
	.byte $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref972
	.byte $41, $08
	.word @song0ref952
	.byte $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $1d, $77, $1b, $76, $81, $75, $81, $72, $16, $73, $81
	.byte $7a, $21, $77, $1f
	.byte $41, $08
	.word @song0ref1004
@song0ref1336:
	.byte $72, $1d, $73, $81, $7a, $81, $77, $1b, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $21, $77, $1f
	.byte $41, $08
	.word @song0ref1004
	.byte $41, $08
	.word @song0ref1336
	.byte $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $19, $73, $81, $7a, $1c
@song0ref1376:
	.byte $77, $1a, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $20, $77, $1e
@song0ref1390:
	.byte $76, $81, $75, $81, $72, $18, $73, $81, $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $1c, $73, $81, $7a, $81
	.byte $41, $12
	.word @song0ref1376
	.byte $77, $1a, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $81, $77, $14
	.byte $41, $08
	.word @song0ref1390
@song0ref1432:
	.byte $72, $12, $73, $81, $7a, $1d, $77, $1b, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $81, $77, $14
	.byte $41, $08
	.word @song0ref1004
	.byte $41, $0a
	.word @song0ref1432
	.byte $76, $81, $75, $81, $72, $19, $73, $81, $7a, $20, $77, $1e, $76, $81, $75, $81, $72, $12, $73, $81, $7a, $21, $77, $1f
	.byte $76, $81, $75, $81, $72, $1c, $73, $81, $7a, $22, $77, $20, $76, $81, $75, $81, $72, $1d, $73, $81, $7a, $1e, $77, $1c
	.byte $76, $81, $75, $81, $72, $1e, $73, $81, $7a, $1f, $77, $1d, $76, $81, $75, $81, $72, $1a, $73, $81, $7a, $1b, $77, $19
	.byte $76, $81, $75, $81, $72, $1b, $73, $81, $7a, $1c, $77, $1a, $76, $81, $75, $81, $72, $17, $73, $81, $7a, $81, $77, $15
	.byte $76, $81, $75, $81, $72, $18, $73, $81, $7a, $81, $77, $16
	.byte $41, $08
	.word @song0ref1055
	.byte $72, $14, $73, $81, $7a, $1a
	.byte $41, $12
	.word @song0ref958
	.byte $41, $12
	.word @song0ref958
	.byte $41, $0b
	.word @song0ref958
	.byte $41, $12
	.word @song0ref1000
	.byte $41, $12
	.word @song0ref1000
	.byte $41, $1f
	.word @song0ref1039
	.byte $41, $12
	.word @song0ref1065
	.byte $41, $12
	.word @song0ref1065
	.byte $77, $16, $76, $81, $75, $81
@song0ch1loop:
	.byte $41, $0f
	.word @song0ref1071
	.byte $41, $11
	.word @song0ref1065
	.byte $7a, $16, $77, $14, $76, $81, $75, $81, $72, $12
	.byte $41, $14
	.word @song0ref1061
	.byte $41, $12
	.word @song0ref1065
	.byte $41, $12
	.word @song0ref1065
	.byte $41, $12
	.word @song0ref1065
	.byte $41, $12
	.word @song0ref1065
	.byte $77, $16, $76, $81, $75, $81, $72, $12, $73, $81, $7a, $1a
	.byte $41, $12
	.word @song0ref958
	.byte $41, $12
	.word @song0ref958
	.byte $41, $12
	.word @song0ref958
	.byte $41, $12
	.word @song0ref958
	.byte $41, $12
	.word @song0ref958
	.byte $41, $0b
	.word @song0ref958
	.byte $7a, $1f, $77, $1d
	.byte $41, $08
	.word @song0ref1004
	.byte $41, $0a
	.word @song0ref1175
	.byte $42
	.word @song0ch1loop
@song0ch2:
	.byte $84, $1f, $00, $87, $1f, $00, $93, $1f, $00, $87, $1f, $00, $93, $1f, $00, $93, $1f, $00, $ab, $1a, $0e, $85, $00, $1b
	.byte $0f, $85, $00, $1c, $10, $85, $00, $1d, $11, $85, $00
@song0ref1715:
	.byte $18
@song0ref1716:
	.byte $0f, $93, $1f, $00, $87, $0f
@song0ref1722:
	.byte $89, $18, $00, $87, $0a, $89, $1f, $0c, $89, $00, $87, $18, $13, $93, $1f, $00, $87, $13, $89, $18, $00, $87, $13, $81
	.byte $12, $85, $1f, $0f
@song0ref1750:
	.byte $89, $00, $87, $18, $11, $93, $1f, $00, $87, $11
	.byte $41, $0c
	.word @song0ref1722
	.byte $11, $93, $1f, $00, $83, $83, $11
	.byte $41, $0c
	.word @song0ref1722
	.byte $11, $93, $1f, $00, $87, $11
	.byte $41, $0c
	.word @song0ref1722
	.byte $11, $93, $1f, $00, $87, $11
	.byte $41, $0c
	.word @song0ref1722
	.byte $41, $12
	.word @song0ref1716
	.byte $41, $12
	.word @song0ref1716
@song0ref1797:
	.byte $14, $93, $1f, $00, $87, $14, $89, $18, $00, $87, $0f, $81, $87, $1f, $14
@song0ref1812:
	.byte $89, $00, $87, $18, $15, $93, $1f, $00, $87, $15, $89, $18, $00, $87, $10, $89, $1f, $15, $89, $00, $87, $18, $16, $93
	.byte $1f, $00, $87, $16, $89, $18, $00, $87, $11, $89, $1f, $16, $89, $00, $87, $18, $95, $1f, $00, $87, $18, $8b, $00, $87
	.byte $13, $89, $1f, $18
	.byte $41, $11
	.word @song0ref1812
	.byte $0f, $89, $00, $87, $18, $0e, $93, $1f, $00, $87, $0e, $89, $18, $00, $87, $0e, $89, $1f, $10
	.byte $41, $0a
	.word @song0ref1750
	.byte $89, $18, $00, $87, $0f, $89, $1f, $0c, $89, $00, $87, $18, $0a, $93, $1f, $00, $87, $0a, $89, $18, $00, $87, $0c, $89
	.byte $1f, $0e, $89, $00, $87
	.byte $41, $2d
	.word @song0ref1715
	.byte $41, $0c
	.word @song0ref1722
	.byte $11, $93, $1f, $00, $83
@song0ch2loop:
	.byte $83, $11
	.byte $41, $0c
	.word @song0ref1722
	.byte $11, $93, $1f, $00, $87, $11
	.byte $41, $0c
	.word @song0ref1722
	.byte $11, $93, $1f, $00, $87, $11
	.byte $41, $0c
	.word @song0ref1722
	.byte $41, $12
	.word @song0ref1716
	.byte $41, $12
	.word @song0ref1716
	.byte $41, $0c
	.word @song0ref1797
	.byte $42
	.word @song0ch2loop
@song0ch3:
	.byte $78, $84
@song0ref1967:
	.byte $1e, $73, $20, $72, $81, $71, $81, $21, $00, $78, $1e, $73, $20, $72, $81, $71, $81, $21, $00, $8b, $78
	.byte $41, $0d
	.word @song0ref1967
	.byte $78, $1e, $73, $20, $72, $81, $71, $81, $21, $00, $8b, $78, $1e, $73, $20, $72, $81, $71, $81, $21, $00, $95, $22, $21
	.byte $72, $20, $81, $1f, $73, $81, $1e, $78, $1b, $77, $81, $76, $1a, $81, $75, $19, $81, $18, $74, $81, $17, $83, $73, $16
	.byte $85, $72, $15, $85, $71, $89
@song0ref2045:
	.byte $78, $1e, $73, $20, $72, $81, $71, $81, $21, $00, $75, $21, $73, $22, $72, $81, $71, $81, $23, $00, $78, $1e, $75, $1f
	.byte $73, $81, $72, $81
@song0ref2073:
	.byte $71, $81, $20, $75, $21, $73, $22, $72, $81, $71, $81, $23, $00
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $10
	.word @song0ref2045
@song0ch3loop:
	.byte $41, $08
	.word @song0ref2073
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $18
	.word @song0ref2045
	.byte $41, $08
	.word @song0ref2045
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $8f, $11, $0d, $85, $00, $01, $08, $85, $00, $04, $0e, $85, $00, $0c, $02, $85, $00
@song0ref2258:
	.byte $08, $95, $00, $89, $08, $89, $00, $89, $06, $89, $07, $89, $00, $89, $0f, $95, $00, $89, $0f, $89, $00, $89, $0f, $81
	.byte $09, $85, $08, $8b, $00, $87, $03, $02, $93, $05, $00
@song0ref2293:
	.byte $87
@song0ref2294:
	.byte $02
@song0ref2295:
	.byte $89, $03, $00, $87, $06, $89, $05, $07
@song0ref2303:
	.byte $89, $00, $87, $03, $02, $93, $05, $00, $83, $83
	.byte $41, $11
	.word @song0ref2294
	.byte $41, $12
	.word @song0ref2293
	.byte $41, $0e
	.word @song0ref2293
	.byte $08, $93, $05, $00, $87, $08
	.byte $41, $0c
	.word @song0ref2295
	.byte $08, $93, $05, $00, $87, $08
	.byte $41, $0c
	.word @song0ref2295
@song0ref2340:
	.byte $0a, $93, $05, $00, $87, $0a, $89, $03, $00, $87, $08, $81, $87, $05, $0a
@song0ref2355:
	.byte $89, $00, $87, $03, $10, $93, $05, $00, $87, $10, $89, $03, $00, $87, $0e, $89, $05, $10, $89, $00, $87, $03, $0b, $93
	.byte $05, $00, $87, $0b, $89, $03, $00, $87, $02, $89, $05, $0b, $89, $00, $87, $03, $95, $05, $00, $87, $03, $8b, $00, $87
	.byte $0f, $89, $05, $03
	.byte $41, $11
	.word @song0ref2355
	.byte $08, $89, $00, $87, $03, $0d, $93, $05, $00, $87, $0d, $89, $03, $00, $87, $0d, $89, $05, $0e
	.byte $41, $08
	.word @song0ref2303
	.byte $87, $02, $89, $03, $00, $87, $08, $89, $05, $07, $89, $00, $87, $03, $06, $93, $05, $00, $87, $06, $89, $03, $00, $87
	.byte $07, $89, $05, $0d, $89, $00, $87
	.byte $41, $36
	.word @song0ref2258
@song0ch4loop:
	.byte $83
	.byte $41, $11
	.word @song0ref2294
	.byte $41, $12
	.word @song0ref2293
	.byte $41, $0e
	.word @song0ref2293
	.byte $08, $93, $05, $00, $87, $08
	.byte $41, $0c
	.word @song0ref2295
	.byte $08, $93, $05, $00, $87, $08
	.byte $41, $0c
	.word @song0ref2295
	.byte $41, $0c
	.word @song0ref2340
	.byte $42
	.word @song0ch4loop
@song0ch5:
	.byte $ff, $d7, $71, $84
@song0ref2505:
	.byte $26, $27, $ab, $2a, $2b, $ab, $2c, $2d, $2e, $ad, $2d, $a9, $2d, $2c, $ab, $2a, $29, $91, $28, $27, $26, $9b
@song0ref2527:
	.byte $e9, $11, $12, $13, $14, $15, $16, $95, $15, $93, $16, $93, $1b, $1c, $1d, $91, $1b, $1c, $1d, $a9
	.byte $41, $08
	.word @song0ref391
@song0ref2550:
	.byte $93, $19, $18, $91, $17, $16, $f3, $17, $81, $4e, $f7, $81, $4e, $09, $18, $4e, $00, $8f, $17, $8d, $87, $18, $95, $1b
	.byte $c5
	.byte $41, $13
	.word @song0ref596
	.byte $95, $1f, $95, $22, $23, $24, $c1, $23, $97, $24, $95, $25, $26, $a9, $21, $97, $22, $c3, $21, $95, $22, $97, $23, $24
	.byte $a9, $1f, $99, $20, $a9, $1d, $c5
	.byte $41, $16
	.word @song0ref2505
@song0ch5loop:
	.byte $41, $14
	.word @song0ref2527
	.byte $41, $08
	.word @song0ref391
	.byte $41, $0e
	.word @song0ref2550
	.byte $42
	.word @song0ch5loop
@song0ch6:
	.byte $ff, $bf, $77, $84
@song0ref2629:
	.byte $13, $74, $13, $72, $16, $16, $71, $1b, $81, $75, $13, $73, $13
@song0ref2642:
	.byte $72, $16, $71, $81, $1b, $81, $77, $13, $76, $13, $75, $16, $74, $81, $1b, $73, $81, $13, $81, $72, $16, $81, $1b, $71
	.byte $81, $77, $13, $74, $81, $72, $16, $81, $71, $1b, $81, $75, $13, $73, $81
	.byte $41, $18
	.word @song0ref2642
@song0ref2684:
	.byte $72, $16
@song0ref2686:
	.byte $71, $81, $1b, $81, $77, $13, $76, $13, $75, $15, $74, $81, $1b, $73, $81, $13, $81, $72, $15, $81, $1b, $71, $81, $77
	.byte $13, $74, $81, $72, $15, $81, $71, $1b, $81, $75, $13, $73, $81, $72, $15
	.byte $41, $0f
	.word @song0ref2686
@song0ref2728:
	.byte $77, $14
@song0ref2730:
	.byte $74, $14, $72, $16, $16, $71, $1a, $81, $75, $14, $73, $14
@song0ref2742:
	.byte $72, $16, $71, $81, $1a, $81, $77, $14, $76, $14, $75, $16, $74, $81
@song0ref2756:
	.byte $1a, $73, $81, $14, $81, $72, $16, $81, $1a, $71, $81, $77, $14, $74, $81, $72, $16, $81, $71, $1a, $81, $75, $14, $73
	.byte $81
	.byte $41, $18
	.word @song0ref2742
	.byte $41, $18
	.word @song0ref2742
	.byte $41, $11
	.word @song0ref2742
	.byte $41, $1f
	.word @song0ref2730
	.byte $41, $18
	.word @song0ref2742
	.byte $41, $18
	.word @song0ref2742
	.byte $41, $10
	.word @song0ref2742
	.byte $77
	.byte $41, $20
	.word @song0ref2629
	.byte $41, $18
	.word @song0ref2642
	.byte $41, $18
	.word @song0ref2642
	.byte $41, $10
	.word @song0ref2642
@song0ref2815:
	.byte $77, $14, $74, $14, $72, $18, $18, $71, $1b, $81, $75, $14, $73, $14
@song0ref2829:
	.byte $72, $18, $71, $81, $1b, $81, $77, $14, $76, $14, $75, $18, $74, $81, $1b, $73, $81, $14, $81, $72, $18, $81, $1b, $71
	.byte $81, $77, $14, $74, $81, $72, $18, $81, $71, $1b, $81, $75, $14, $73, $81
	.byte $41, $10
	.word @song0ref2829
@song0ref2871:
	.byte $77, $15, $74, $81, $72, $18, $81, $71, $1b, $81, $75, $15, $73, $81, $72, $18, $71, $81, $1b, $81, $77, $15, $76, $15
	.byte $75, $18, $74, $81, $1b, $73, $81, $15, $81, $72, $18, $81, $1b, $71, $81
	.byte $41, $18
	.word @song0ref2871
	.byte $77, $16, $74, $16, $72, $1a, $1a, $71, $1f, $81, $75, $16, $73, $16
@song0ref2927:
	.byte $72, $1a, $71, $81, $1f, $81, $77, $16, $76, $16, $75, $1a, $74, $81, $1f, $73, $81, $16, $81, $72, $1a, $81, $1f, $71
	.byte $81, $77, $16, $74, $81, $72, $1a, $81, $71, $1f, $81, $75, $16, $73, $81
	.byte $41, $10
	.word @song0ref2927
@song0ref2969:
	.byte $77, $18, $74, $81, $72, $1b, $81, $71, $1f, $81, $75, $18, $73, $81
@song0ref2983:
	.byte $72, $1b, $71, $81, $1f, $81, $77, $18, $76, $18, $75, $1b, $74, $81, $1f, $73, $81, $18, $81, $72, $1b, $81, $1f, $71
	.byte $81
	.byte $41, $18
	.word @song0ref2969
	.byte $77, $18, $74, $18, $72, $1b, $1b, $71, $1f, $81, $75, $18, $73, $18
	.byte $41, $10
	.word @song0ref2983
	.byte $41, $18
	.word @song0ref2969
@song0ref3031:
	.byte $77, $18, $74, $81, $72, $1a, $81, $71, $1e, $81, $75, $18, $73, $81, $72, $1a, $71, $81, $1e, $81, $77, $18, $76, $18
	.byte $75, $1a, $74, $81, $1e, $73, $81, $18, $81, $72, $1a, $81, $1e, $71, $81
	.byte $41, $18
	.word @song0ref3031
	.byte $77, $18, $74, $18, $72, $1b, $1b, $71, $20, $81, $75, $18, $73, $18
@song0ref3087:
	.byte $72, $1b, $71, $81, $20, $81, $77, $18, $76, $18, $75, $1b, $74, $81, $20, $73, $81, $18, $81, $72, $1b, $81, $20, $71
	.byte $81, $77, $18, $74, $81, $72, $1b, $81, $71, $20, $81, $75, $18, $73, $81
	.byte $41, $10
	.word @song0ref3087
@song0ref3129:
	.byte $77, $1a, $74, $81, $72, $1d, $81, $71, $20, $81, $75, $1a, $73, $81, $72, $1d, $71, $81, $20, $81, $77, $1a, $76, $1a
	.byte $75, $1d, $74, $81, $20, $73, $81, $1a, $81, $72, $1d, $81, $20, $71, $81
	.byte $41, $18
	.word @song0ref3129
	.byte $77
	.byte $41, $20
	.word @song0ref2629
	.byte $41, $18
	.word @song0ref2642
	.byte $41, $19
	.word @song0ref2684
	.byte $41, $0f
	.word @song0ref2686
	.byte $41, $20
	.word @song0ref2728
	.byte $41, $18
	.word @song0ref2742
	.byte $41, $08
	.word @song0ref2742
@song0ch6loop:
	.byte $41, $10
	.word @song0ref2756
	.byte $41, $11
	.word @song0ref2742
	.byte $41, $1f
	.word @song0ref2730
	.byte $41, $18
	.word @song0ref2742
	.byte $41, $18
	.word @song0ref2742
	.byte $41, $10
	.word @song0ref2742
	.byte $77
	.byte $41, $20
	.word @song0ref2629
	.byte $41, $18
	.word @song0ref2642
	.byte $41, $18
	.word @song0ref2642
	.byte $41, $10
	.word @song0ref2642
	.byte $41, $20
	.word @song0ref2815
	.byte $42
	.word @song0ch6loop
