; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_death=music_data_death
.endif

music_data_death:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : death
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_death
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env5,@env9,@env0 ; 00 : Instrument 6
	.word @env4,@env5,@env8,@env0 ; 01 : Duty 2
	.word @env4,@env5,@env7,@env0 ; 02 : Duty 0
	.word @env10,@env6,@env7,@env0 ; 03 : Instrument 10
	.word @env4,@env5,@env7,@env0 ; 04 : Instrument 8
	.word @env1,@env2,@env8,@env0 ; 05 : thud

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cd,$cc,$ca,$c9,$c8,$02,$c6,$c6,$c5,$c4,$c2,$c1,$c0,$00,$0e
@env2:
	.byte $cf,$cc,$cb,$c7,$c5,$c0,$b7,$b4,$ad,$a7,$a3,$a0,$9c,$99,$98,$03,$99,$00,$10
@env3:
	.byte $00,$c4,$c6,$c8,$c9,$cb,$cc,$cd,$ce,$ce,$cf,$00,$0a
@env4:
	.byte $00,$cf,$7f,$00,$02
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $c6,$c8,$00,$01
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $c2,$7f,$00,$00
@env9:
	.byte $c1,$7f,$00,$00
@env10:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$ca,$c9,$c7,$c5,$c4,$c3,$c1,$c0,$00,$0e

@samples:
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$10,$0b,$40 ; 00 hisnare (Pitch:11)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$10,$0c,$40 ; 01 hisnare (Pitch:12)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$10,$0d,$40 ; 02 hisnare (Pitch:13)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $81, $7e, $80, $2a, $ff, $93, $2e, $af, $2a, $ff, $93, $2e, $ad, $48
@song0ref15:
	.byte $81, $2a, $af, $2e, $af, $2a, $af, $2e, $af, $2c, $ff, $93, $2c, $97, $2e, $93, $48
@song0ref32:
	.byte $81, $2f, $ff, $93, $2e, $97, $2c, $95, $2e, $af, $2a, $e1, $2a, $97, $2e, $93, $48, $81, $2c, $af, $25, $af, $29, $af
	.byte $2c, $af, $2a, $ff, $c3, $44, $00
@song0ch1:
	.byte $7c, $82, $1e, $89, $ff, $89, $22, $af, $1e, $ff, $93, $22, $af, $1e, $af, $22, $af, $1e, $af, $22, $af, $20, $ff, $93
	.byte $20, $97, $22, $95, $23, $ff, $93, $22, $97, $20, $95, $22, $af, $1e, $e1, $1e, $97, $22, $95, $20, $af, $19, $af, $1d
	.byte $af, $20, $af, $1e, $ff, $c5, $44, $00
@song0ch2:
	.byte $84, $12, $af, $0d, $af, $12, $af, $0d, $af, $12, $af, $0d, $af, $12, $af, $0d, $af, $12, $af, $0d, $af, $12, $af, $16
	.byte $af, $14, $af, $0d, $af, $11, $af, $0d, $af, $14, $af, $0d, $af, $11, $af, $0d, $af, $12, $af, $0d, $af, $12, $af, $0d
	.byte $af, $11, $af, $0d, $af, $11, $af, $0d, $af, $12, $af, $0d, $af, $0f, $af, $11, $af, $44, $00
@song0ch3:
	.byte $86
@song0ref190:
	.byte $25, $af, $25, $af, $25, $af, $25, $af, $25, $af, $25, $af, $25, $af, $25, $af
	.byte $41, $10
	.word @song0ref190
	.byte $41, $10
	.word @song0ref190
	.byte $41, $10
	.word @song0ref190
	.byte $44, $00
@song0ch4:
@song0ref218:
	.byte $02, $8b, $00, $95, $02, $89, $01, $8b, $00, $89, $03, $95, $02, $8b, $00, $95, $02, $89, $01, $8b, $00, $89, $03, $95
	.byte $41, $18
	.word @song0ref218
	.byte $41, $18
	.word @song0ref218
	.byte $41, $18
	.word @song0ref218
	.byte $41, $18
	.word @song0ref218
	.byte $41, $18
	.word @song0ref218
	.byte $41, $18
	.word @song0ref218
	.byte $41, $18
	.word @song0ref218
	.byte $44, $00
@song0ch5:
	.byte $81, $7e, $88, $2a, $ff, $93, $2e, $af, $2a, $ff, $93, $2e, $ad
	.byte $41, $10
	.word @song0ref15
	.byte $41, $10
	.word @song0ref32
	.byte $81, $2c, $af, $25, $af, $29, $af, $2c, $af, $2a, $ff, $c3, $44, $00
@song0ch6:
	.byte $8a
@song0ref301:
	.byte $0c, $af, $0c, $af, $0c, $af, $0c, $af, $0c, $af, $0c, $af, $0c, $af, $0c, $af
	.byte $41, $10
	.word @song0ref301
	.byte $41, $10
	.word @song0ref301
	.byte $41, $10
	.word @song0ref301
	.byte $44, $00
