; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_overworld=music_data_overworld
.endif

music_data_overworld:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : overworld
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_overworld
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env5,@env0 ; 00 : Acoustic Bass
	.word @env1,@env2,@env4,@env0 ; 01 : Duty 2
	.word @env1,@env2,@env3,@env0 ; 02 : Duty 0

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00
@env4:
	.byte $c2,$7f,$00,$00
@env5:
	.byte $c1,$7f,$00,$00

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0d,$40 ; 00 Sunsoft Bass A# (Pitch:13)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$09,$40 ; 01 Sunsoft Bass B (Pitch:9)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0c,$40 ; 02 Sunsoft Bass B (Pitch:12)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0d,$40 ; 03 Sunsoft Bass B (Pitch:13)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0e,$40 ; 04 Sunsoft Bass B (Pitch:14)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$01,$40 ; 05 Sunsoft Bass C (Pitch:1)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$02,$40 ; 06 Sunsoft Bass C (Pitch:2)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$05,$40 ; 07 Sunsoft Bass C (Pitch:5)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$06,$40 ; 08 Sunsoft Bass C (Pitch:6)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$08,$40 ; 09 Sunsoft Bass C (Pitch:8)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$09,$40 ; 0a Sunsoft Bass C (Pitch:9)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0a,$40 ; 0b Sunsoft Bass C (Pitch:10)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0b,$40 ; 0c Sunsoft Bass C (Pitch:11)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0d,$40 ; 0d Sunsoft Bass C (Pitch:13)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$03,$40 ; 0e Sunsoft Bass C# (Pitch:3)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$04,$40 ; 0f Sunsoft Bass C# (Pitch:4)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$07,$40 ; 10 Sunsoft Bass C# (Pitch:7)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$08,$40 ; 11 Sunsoft Bass C# (Pitch:8)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$09,$40 ; 12 Sunsoft Bass C# (Pitch:9)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0a,$40 ; 13 Sunsoft Bass C# (Pitch:10)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0b,$40 ; 14 Sunsoft Bass C# (Pitch:11)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0c,$40 ; 15 Sunsoft Bass C# (Pitch:12)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0e,$40 ; 16 Sunsoft Bass C# (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $79, $80, $21, $78, $82, $22, $77, $81, $76, $81, $75, $81, $71, $81, $79, $80, $21, $78, $82, $22, $77, $81, $76, $81
	.byte $75, $81, $71, $81, $72, $85, $71, $85
@song0ref33:
	.byte $79, $80, $21, $78, $82, $22, $77, $81, $76, $81, $75, $81, $71, $81, $79, $80, $23, $78, $82, $24, $77, $81, $76, $81
	.byte $75, $81, $71, $81, $72, $85, $71, $85, $79, $80, $24, $78, $82, $25, $77, $81, $76, $81, $75, $81, $71, $81, $72, $85
	.byte $71, $85, $79, $80, $25, $78, $82, $26, $77, $81, $76, $81, $75, $81, $71, $81, $72, $85, $71, $9d
	.byte $41, $0c
	.word @song0ref33
	.byte $79, $80, $24, $78, $82, $25, $77, $81, $76, $81, $75, $81, $71, $81, $79, $80, $25, $78, $82, $26, $77, $81, $76, $81
	.byte $75, $81, $71, $81, $79, $81
@song0ref134:
	.byte $27, $9d, $74, $81, $71, $81, $72, $81, $73, $87, $79, $2a, $2b, $9d, $74, $81, $71, $81, $72, $81, $73, $87, $79, $2c
	.byte $2d, $2e, $9b, $74, $81, $71, $81, $72, $81, $73, $87, $79, $83, $2d, $9b, $74, $81, $71, $81, $72, $81, $73, $87, $79
	.byte $81, $2c, $9d, $74, $81, $71, $81, $72, $81, $73, $87, $79, $2a, $29, $8b, $74, $81, $71, $81, $72, $81, $73, $28, $79
	.byte $27, $26
@song0ref208:
	.byte $9f, $78, $4e, $ff, $81, $4e, $fe, $83, $4e, $00, $83, $4e, $02, $83, $4e, $01, $81, $4e, $00, $81, $4e, $ff, $81, $48
@song0ref232:
	.byte $4e, $fe, $83, $77, $4e, $00, $83, $4e, $01, $81, $4e, $02, $81, $4e, $01, $81, $4e, $00, $81, $4e, $ff, $81, $4e, $fe
	.byte $83, $4e, $ff, $81, $4e, $00, $81, $4e, $01, $81, $76, $4e, $02, $81, $4e, $01, $81, $4e, $00, $83, $4e, $fe, $81, $75
	.byte $81, $74, $4e, $ff, $81, $73, $4e, $00, $81, $4e, $01, $81, $4e, $02, $83, $4e, $00, $83, $4e, $fe, $83, $4e, $ff, $81
	.byte $4e, $00, $81, $4e, $01, $81, $4e, $02, $83, $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $81
	.byte $4e, $01, $81, $71, $4e, $02, $11, $73, $12, $76, $4e, $00, $13, $79, $14, $15, $16, $95, $15, $89, $74, $81, $71, $81
	.byte $72, $81, $73, $81, $79, $81, $16, $8b, $74, $81, $71, $81, $72, $81, $73, $81, $79, $1b, $1c, $1d, $8d, $74, $81, $71
	.byte $81, $79, $1b, $1c, $1d, $9b, $74, $81, $71, $81, $72, $81, $73, $87, $79, $1f, $81, $20, $93, $1f, $95, $1d, $1b, $89
	.byte $74, $81, $71, $81, $72, $81, $73, $81, $79, $81, $19, $18, $89, $74, $81, $71, $81, $72, $81, $73, $81, $79, $17, $16
@song0ref424:
	.byte $9f, $78, $4e, $fd, $81, $4e, $fc, $83, $4e, $ff, $81, $4e, $01, $81, $4e, $04, $83, $4e, $03, $81, $4e, $00, $81, $4e
	.byte $fe, $81, $4e, $fc, $83, $77, $4e, $ff, $81, $4e, $00, $81, $4e, $03, $81, $4e, $04, $81, $4e, $03, $81, $4e, $00, $81
	.byte $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00, $81, $4e, $03, $81, $76, $4e, $04, $81, $4e, $03, $81, $4e, $00
	.byte $81, $4e, $ff, $81, $4e, $fc, $81, $75, $81, $74, $4e, $fe, $81, $73, $4e, $00, $81, $4e, $03, $81, $4e, $04, $83, $4e
	.byte $01, $81, $4e, $ff, $81, $4e, $fc, $83, $4e, $fd, $81, $4e, $00, $81, $4e, $02, $81, $79, $4e, $00, $80, $17, $81, $4e
	.byte $f7, $81, $4e, $09, $18, $4e, $00, $8f, $17, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $18, $8d, $48, $74, $81
	.byte $71, $81, $72, $81, $73, $81, $79, $1b
@song0ref576:
	.byte $a1, $74, $81, $71, $81, $72, $81, $73, $85, $79, $8f, $74, $81, $71, $81, $72, $81, $73, $81, $79, $1d, $97, $4e, $f6
	.byte $1c, $4e, $01, $81, $4e, $f7, $1b, $4e, $f5, $1a, $4e, $0a, $81, $4e, $07, $19, $4e, $03, $18, $4e, $fd, $17, $4e, $00
	.byte $16, $18, $1b
@song0ref627:
	.byte $1d, $1e, $81, $1f, $8f, $1e, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $1f, $8d, $74, $81, $71, $81, $72, $81
	.byte $73, $81, $79, $22, $23, $24, $a3, $74, $81, $71, $81, $72, $81, $73, $97, $79, $23, $97, $24, $8b, $74, $81, $71, $81
	.byte $72, $81, $73, $81, $79, $81, $25, $26, $9b, $74, $81, $71, $81, $72, $81, $73, $87, $79, $21, $8d, $74, $81, $71, $81
	.byte $72, $81, $73, $81, $79, $81, $22, $b3, $74, $81, $71, $81, $72, $81, $73, $89, $79, $21, $95, $22, $8d, $74, $81, $71
	.byte $81, $72, $81, $73, $81, $48, $79, $81, $23, $24, $9b, $74, $81, $71, $81, $72, $81, $73, $87, $79, $1f, $8d, $74, $81
	.byte $71, $81, $72, $81, $73, $81, $79, $83, $20, $99, $74, $81, $71, $81, $72, $81, $73, $89, $79, $1d, $ab, $4e, $fa, $81
	.byte $4e, $f7, $81, $4e, $f8, $81, $4e, $fe, $81, $4e, $02, $81, $4e, $08, $81, $4e, $09, $81, $4e, $06, $81, $4e, $00, $81
	.byte $74, $4e, $fb, $81, $71, $4e, $f7, $81, $72, $4e, $f8, $81, $73, $4e, $00, $81, $79, $82, $26
	.byte $41, $34
	.word @song0ref134
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
	.byte $41, $bb
	.word @song0ref232
@song0ref824:
	.byte $99, $74, $81, $71, $81, $72, $81, $73, $89, $79, $8f, $74, $81, $71, $81, $72, $81, $73, $81, $79, $1f, $a5, $74, $81
	.byte $71, $81, $72, $81, $73, $81, $79, $1b, $1c, $81, $1d, $8f, $1c, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $1d
	.byte $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $20, $21, $22
	.byte $41, $0a
	.word @song0ref824
	.byte $79, $1a, $9f, $4e, $fa, $81, $4e, $f5, $83, $4e, $f9, $81, $4e, $ff, $81, $4e, $04, $81, $4e, $09, $81, $48, $4e, $0b
	.byte $81, $4e, $00, $81, $4e, $f9, $81, $4e, $09, $1b, $4e, $02, $81, $4e, $00, $9d, $74, $81, $71, $81, $72, $81, $73, $8b
	.byte $71, $8b, $00, $c7
@song0ref940:
	.byte $79, $27, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $29, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $2b
	.byte $a5, $74, $81, $71, $81, $72, $81, $73, $81
	.byte $41, $0c
	.word @song0ref940
	.byte $79, $81, $2a, $2b, $a1, $74, $81, $71, $81, $72, $81, $73, $81, $79, $27, $8d, $74, $81, $71, $81, $72, $81, $73, $81
	.byte $79, $2b, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $27, $81, $28, $29, $91, $4e, $fc, $81, $4e, $04, $2a, $4e
	.byte $fb, $29, $4e, $fe, $81, $4e, $02, $81, $4e, $fb, $28, $4e, $fc, $81, $4e, $04, $29, $4e, $00, $81, $4e, $fd, $81, $4e
	.byte $04, $2a, $4e, $00, $27, $26, $8f, $74, $81, $71, $81, $72, $81, $73, $95, $71, $9f, $48, $8f, $79, $8f, $74, $81, $71
	.byte $81, $72, $81, $73, $81, $79, $28, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $83, $29, $93, $4e, $fc, $81, $4e
	.byte $04, $2a, $4e, $fb, $29, $4e, $fe, $81, $4e, $02, $81, $4e, $fb, $28, $4e, $fc, $81, $74, $4e, $04, $29, $71, $4e, $00
	.byte $81, $72, $4e, $fd, $81, $73, $4e, $04, $2a, $79, $4e, $00, $2b, $2c, $2d, $89, $74, $81, $71, $81, $72, $81, $73, $81
	.byte $79, $81, $2c, $2b, $93, $4e, $fc, $81, $4e, $02, $2c, $4e, $03, $81, $4e, $fe, $2b, $4e, $02, $81, $4e, $fc, $2a, $4e
	.byte $fd, $81, $4e, $04, $2b, $4e, $00, $81, $74, $4e, $fd, $81, $71, $4e, $02, $2c, $79, $4e, $00, $29, $8d, $74, $81, $71
	.byte $81, $72, $81, $73, $81, $79, $28, $95, $29, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $83, $4e, $03, $2a, $4e
	.byte $fc, $81, $4e, $00, $2b, $a5, $71, $4e, $fe, $81, $72, $4e, $fc, $81, $73, $81, $74
@song0ref1233:
	.byte $4e, $fd, $81, $4e, $00, $81, $4e, $01, $81, $4e, $04, $83, $4e, $03, $81, $4e, $01, $81, $4e, $00, $81, $4e, $fd, $81
	.byte $4e, $fc, $83
@song0ref1260:
	.byte $4e, $fe, $81, $4e, $00, $81, $4e, $02, $81, $4e, $04, $83, $4e, $03, $81, $4e, $00, $81, $4e, $ff, $81, $4e, $fc, $83
	.byte $00, $71, $4e, $ff, $2b, $72, $4e, $00, $81, $73, $4e, $03, $81, $4e, $04, $83, $4e, $02, $81, $4e, $00, $81, $4e, $fe
	.byte $81, $4e, $fc, $83
	.byte $41, $0a
	.word @song0ref1233
	.byte $71, $4e, $00, $81, $74, $82
@song0ref1321:
	.byte $1f, $76, $32, $79, $1f, $8b, $74, $81, $73, $83, $74, $21, $76, $34, $79, $21, $8b, $74, $81, $73, $83, $74, $81, $76
	.byte $34, $79, $21, $81, $4e, $f9, $81, $4e, $01, $22, $4e, $00, $a3, $74, $1f, $76, $32, $79, $1f, $89, $48, $87, $74, $21
	.byte $76, $34, $79, $21, $8b, $74, $81, $73, $83, $74, $22, $76, $35, $79, $22, $a3, $74, $81, $73, $81, $71, $81, $74
	.byte $41, $12
	.word @song0ref1321
	.byte $4e, $00, $9d, $4e, $05, $23, $4e, $fc, $81, $4e, $01, $24, $74, $4e, $00, $26, $76, $39, $79, $26, $91, $74, $24, $76
	.byte $37, $79, $24, $a9, $74, $22, $76, $35, $79, $22, $8b, $74, $81, $73, $81, $71, $81, $74, $21, $76, $34, $79, $21, $8b
	.byte $74, $81, $73, $83, $74, $1f, $76, $32, $79, $1f, $8b, $74, $81, $73, $83, $74, $1d, $76, $30, $79, $1d, $91, $74, $21
	.byte $76, $34, $79, $21, $91, $74, $24, $76, $37, $79, $24, $91, $74, $26, $76, $39, $79, $26, $91, $74, $28, $76, $3b, $79
	.byte $28, $9d, $4e, $fe, $81, $4e, $fc, $83, $4e, $fd, $81, $4e, $00, $81, $75, $81, $74, $26, $76, $39, $79, $26, $9d, $4e
	.byte $fe, $81, $4e, $fc, $83, $4e, $fd, $81, $4e, $00, $81, $75, $81, $48, $74, $1f, $76, $32, $79, $1f, $9d, $4e, $fe, $81
	.byte $4e, $fc, $83
	.byte $41, $0c
	.word @song0ref1233
	.byte $4e, $04, $81, $71, $81, $72, $4e, $03, $81, $73, $4e, $00, $81, $74, $4e, $ff, $81, $4e, $fc, $83
@song0ref1565:
	.byte $4e, $fd, $81, $4e, $ff, $81, $4e, $00, $81, $4e, $03, $81, $4e, $04, $83, $4e, $02, $81, $4e, $00, $81, $4e, $fe, $81
	.byte $4e, $fc, $83, $4e, $fd, $81, $4e, $00, $81, $4e, $01, $81, $4e, $04, $83, $4e, $03, $81, $4e, $01, $81, $00, $71, $4e
	.byte $fd, $1f, $72, $4e, $fc, $81, $73, $81
	.byte $41, $08
	.word @song0ref1260
	.byte $41, $0f
	.word @song0ref1565
	.byte $4e, $00, $81, $4e, $fd, $81, $4e, $fc, $81, $4e, $00, $81, $79, $28, $29, $9d, $74, $81, $71, $81, $72, $81, $73, $87
	.byte $79, $2c, $2d, $9d, $74, $81, $71, $81, $72, $81, $73, $87, $79, $2e, $2f, $30, $9b, $74, $81, $71, $81, $72, $81, $73
	.byte $87, $79, $83, $2f, $9b, $74, $81, $71, $81, $72, $81, $73, $87, $79, $81, $2e, $9d, $74, $81, $71, $81, $72, $81, $73
	.byte $87, $79, $2c, $2b, $8b, $74, $81, $71, $81, $72, $81, $73, $2a, $79, $29, $28
	.byte $41, $28
	.word @song0ref208
	.byte $71, $4e, $02, $13, $73, $14, $76, $4e, $00, $15, $79, $16, $17, $18, $95, $17, $89, $74, $81, $71, $81, $72, $81, $73
	.byte $81, $79, $81, $18, $8b, $74, $81, $71, $81, $72, $81, $73, $81, $79, $1d, $1e, $1f, $8d, $74, $81, $71, $81, $79, $1d
	.byte $1e, $1f, $9b, $74, $81, $71, $81, $72, $81, $73, $87, $79, $21, $81, $22, $93, $21, $95, $1f, $1d, $89, $74, $81, $71
	.byte $81, $72, $81, $73, $81, $79, $81, $1b, $1a, $89, $74, $81, $71, $81, $72, $81, $73, $81, $79, $19, $18
	.byte $41, $25
	.word @song0ref424
	.byte $79, $4e, $00, $80, $19, $81, $4e, $f7, $81, $4e, $06, $1a, $4e, $00, $8f, $19, $8d, $74, $81, $71, $81, $72, $81, $73
	.byte $81, $79, $1a, $8d, $48, $74, $81, $71, $81, $72, $81, $73, $81, $79, $1d
	.byte $41, $0a
	.word @song0ref576
	.byte $79, $1f, $97, $4e, $f9, $1e, $4e, $04, $81, $4e, $fc, $1d, $1c, $1b, $4e, $fa, $1a, $4e, $f7, $19, $4e, $0c, $81, $4e
	.byte $00, $18, $1a, $1d, $1f, $20, $81, $21, $8f, $20, $8d, $74, $81, $71, $81, $72, $81, $73, $81, $79, $21, $8d, $74, $81
	.byte $71, $81, $72, $81, $73, $81, $79, $24, $25, $26
	.byte $41, $0a
	.word @song0ref824
	.byte $79, $21, $a5, $74, $81, $71, $81, $72, $81, $73, $81, $79
	.byte $41, $14
	.word @song0ref627
	.byte $41, $0a
	.word @song0ref824
	.byte $79, $1c, $9f, $4e, $fa, $81, $4e, $0a, $1d, $81, $4e, $f9, $1c, $4e, $ff, $81, $4e, $04, $81, $4e, $09, $81, $48, $4e
	.byte $f6, $1b, $4e, $00, $1c, $4e, $f9, $81, $4e, $07, $1d, $4e, $00, $9f, $74, $81, $71, $81, $72, $81, $73, $8b, $71, $8b
	.byte $00, $af, $79, $2b, $78, $82, $2c, $77, $81, $76, $81, $75, $81, $71, $81, $72, $85, $71, $85, $79, $80, $2c, $78, $82
	.byte $2d, $77, $81, $76, $81, $75, $81, $71, $81, $72, $85, $71, $8b, $00, $8f, $79, $26
	.byte $41, $34
	.word @song0ref134
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $79, $82, $1a, $81, $80, $1a, $73, $81, $71, $81, $72, $81, $79, $82, $1a, $81, $80, $1a, $73, $81, $71, $81, $72, $87
	.byte $71, $85
@song0ref2056:
	.byte $79, $82, $1a, $81, $80, $1a, $73, $81, $71, $81, $72, $81, $79, $82, $1b, $81, $80, $1b, $73, $81, $71, $81, $72, $87
	.byte $71, $85, $79, $82, $1c, $81, $80, $1c, $73, $81, $71, $81, $72, $87, $71, $85, $79, $82, $1d, $81, $80, $1d, $73, $81
	.byte $71, $81, $72, $87, $71, $9d
	.byte $41, $0b
	.word @song0ref2056
	.byte $72, $81, $79, $82, $1c, $81, $80, $1c, $73, $81, $71, $81, $72, $81, $79, $82, $1d, $81, $80, $1d, $73, $81, $71, $81
	.byte $72, $81, $7a, $84, $18, $77, $16, $76, $81, $75, $81
@song0ref2148:
	.byte $72, $1a, $73, $81, $7a, $81
@song0ref2154:
	.byte $77, $18
@song0ref2156:
	.byte $76, $81, $75, $81, $72, $14
@song0ref2162:
	.byte $73, $81, $7a, $1d, $77, $1b
@song0ref2168:
	.byte $76, $81, $75, $81, $72, $16, $73, $81, $7a, $18, $77, $16, $76, $81, $75, $81, $72, $19, $73, $81, $7a, $1a
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $0b
	.word @song0ref2154
@song0ref2196:
	.byte $7a, $17, $77, $15
@song0ref2200:
	.byte $76, $81, $75, $81, $72, $19, $73, $81, $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $13, $73, $81, $7a, $1d, $77, $1b
	.byte $76, $81, $75, $81, $72, $16, $73, $81
	.byte $41, $12
	.word @song0ref2196
@song0ref2235:
	.byte $7a, $17, $77, $15, $76, $81, $75, $81, $72, $19, $73, $81, $7a, $16, $77, $14
@song0ref2251:
	.byte $76, $81, $75, $81, $72, $13
@song0ref2257:
	.byte $73, $81, $7a, $18
@song0ref2261:
	.byte $77, $16, $76, $81, $75, $81
@song0ref2267:
	.byte $72, $12, $73, $81, $7a, $1c, $77, $1a, $76, $81, $75, $81, $72, $14, $73, $81, $7a, $16, $77, $14, $76, $81, $75, $81
	.byte $72, $18, $73, $81, $7a, $81
	.byte $41, $12
	.word @song0ref2261
	.byte $41, $12
	.word @song0ref2261
	.byte $41, $12
	.word @song0ref2261
	.byte $41, $11
	.word @song0ref2261
	.byte $7a, $16, $77, $14, $76, $81, $75, $81, $72, $12
	.byte $41, $14
	.word @song0ref2257
	.byte $41, $12
	.word @song0ref2261
	.byte $41, $12
	.word @song0ref2261
	.byte $41, $12
	.word @song0ref2261
	.byte $41, $12
	.word @song0ref2261
	.byte $77, $16, $76, $81, $75, $81, $72, $12, $73, $81, $7a, $1a
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $0b
	.word @song0ref2154
	.byte $7a, $1f, $77, $1d
	.byte $41, $08
	.word @song0ref2200
@song0ref2371:
	.byte $72, $1b, $73, $81, $7a, $1d, $77, $1b, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $1f, $77, $1d
	.byte $41, $08
	.word @song0ref2200
	.byte $41, $08
	.word @song0ref2371
@song0ref2397:
	.byte $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $19
@song0ref2407:
	.byte $73, $81, $7a, $1d, $77, $1b, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $20, $77, $1e
	.byte $41, $08
	.word @song0ref2200
	.byte $72, $1c
	.byte $41, $09
	.word @song0ref2407
	.byte $41, $08
	.word @song0ref2200
	.byte $72, $1c
	.byte $41, $0e
	.word @song0ref2162
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
@song0ref2447:
	.byte $77, $18, $76, $81, $75, $81, $72, $14, $73, $81, $7a, $18, $77, $16, $76, $81, $75, $81, $72, $81
@song0ref2467:
	.byte $73, $81, $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $14, $73, $81, $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $1d, $77, $1b, $76, $81, $75, $81, $72, $16, $73, $81
	.byte $7a, $21, $77, $1f
	.byte $41, $08
	.word @song0ref2200
@song0ref2532:
	.byte $72, $1d, $73, $81, $7a, $81, $77, $1b, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $21, $77, $1f
	.byte $41, $08
	.word @song0ref2200
	.byte $41, $08
	.word @song0ref2532
	.byte $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $19
@song0ref2568:
	.byte $73, $81, $7a, $1c
@song0ref2572:
	.byte $77, $1a, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $20, $77, $1e
@song0ref2586:
	.byte $76, $81, $75, $81, $72, $18, $73, $81, $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $1c, $73, $81, $7a, $81
	.byte $41, $12
	.word @song0ref2572
	.byte $77, $1a, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $81, $77, $14
	.byte $41, $08
	.word @song0ref2586
@song0ref2628:
	.byte $72, $12, $73, $81, $7a, $1d, $77, $1b, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $81, $77, $14
	.byte $41, $08
	.word @song0ref2200
	.byte $41, $0a
	.word @song0ref2628
	.byte $76, $81, $75, $81, $72, $19, $73, $81, $7a, $20, $77, $1e, $76, $81, $75, $81, $72, $12, $73, $81, $7a, $21, $77, $1f
	.byte $76, $81, $75, $81, $72, $1c, $73, $81, $7a, $22, $77, $20
@song0ref2690:
	.byte $76, $81, $75, $81, $72, $1d, $73, $81, $7a, $1e, $77, $1c, $76, $81, $75, $81, $72, $1e, $73, $81, $7a, $1f, $77, $1d
	.byte $76, $81, $75, $81, $72, $1a, $73, $81, $7a, $1b, $77, $19
@song0ref2726:
	.byte $76, $81, $75, $81, $72, $1b, $73, $81, $7a, $1c, $77, $1a, $76, $81, $75, $81, $72, $17, $73, $81, $7a, $81, $77, $15
	.byte $76, $81, $75, $81, $72, $18, $73, $81, $7a, $81, $77, $16
	.byte $41, $08
	.word @song0ref2251
	.byte $72, $14, $73, $81, $7a, $1a
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $0b
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2196
	.byte $41, $12
	.word @song0ref2196
	.byte $41, $1f
	.word @song0ref2235
	.byte $41, $12
	.word @song0ref2261
	.byte $41, $12
	.word @song0ref2261
	.byte $77, $16, $76, $81, $75, $81
@song0ch1loop:
	.byte $41, $0f
	.word @song0ref2267
	.byte $41, $11
	.word @song0ref2261
	.byte $7a, $16, $77, $14, $76, $81, $75, $81, $72, $12
	.byte $41, $14
	.word @song0ref2257
	.byte $41, $12
	.word @song0ref2261
	.byte $41, $12
	.word @song0ref2261
	.byte $41, $12
	.word @song0ref2261
	.byte $41, $12
	.word @song0ref2261
	.byte $77, $16, $76, $81, $75, $81, $72, $12, $73, $81, $7a, $1a
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $0b
	.word @song0ref2154
	.byte $7a, $1f, $77, $1d
	.byte $41, $08
	.word @song0ref2200
	.byte $41, $0a
	.word @song0ref2371
	.byte $41, $08
	.word @song0ref2200
	.byte $41, $08
	.word @song0ref2371
	.byte $41, $0e
	.word @song0ref2397
	.byte $41, $08
	.word @song0ref2200
	.byte $72, $1c
	.byte $41, $09
	.word @song0ref2407
	.byte $41, $08
	.word @song0ref2200
	.byte $72, $1c
	.byte $41, $0e
	.word @song0ref2162
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $13
	.word @song0ref2447
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $7a, $16, $77, $14
@song0ref2927:
	.byte $76, $81, $75, $81, $72, $16, $73, $81, $7a, $1a, $77, $18, $76, $81, $75, $81
	.byte $41, $0a
	.word @song0ref2628
	.byte $41, $08
	.word @song0ref2200
	.byte $41, $08
	.word @song0ref2628
	.byte $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $19, $73, $81, $7a, $1b, $77, $19, $76, $81, $75, $81, $72, $16, $73, $81
	.byte $7a, $1c, $77, $1a, $76, $81, $75, $81, $72, $17
@song0ref2986:
	.byte $73, $81, $7a, $24, $77, $22
@song0ref2992:
	.byte $76, $81, $75, $81, $72, $18, $73, $81, $7a, $1c, $77, $1a, $76, $81, $75, $81, $72, $20, $73, $81, $7a, $1b, $77, $19
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $17, $73, $81, $7a, $22, $77, $20
	.byte $41, $08
	.word @song0ref2927
	.byte $72, $1e, $73, $81, $7a, $19, $77, $17
	.byte $41, $08
	.word @song0ref2168
	.byte $72, $15, $73, $81, $7a, $1a
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $0b
	.word @song0ref2154
	.byte $72, $83, $71, $14, $85, $00, $c5, $7a, $18, $77, $16
	.byte $41, $08
	.word @song0ref2156
@song0ref3070:
	.byte $72, $14, $73, $81, $7a, $30, $77, $2e, $76, $81, $75, $81, $72, $19, $73, $81, $7a, $21, $77, $1f, $76, $81, $75, $81
	.byte $72, $2c, $73, $81, $7a, $18, $77, $16
@song0ref3102:
	.byte $76, $81, $75, $81, $72, $1d, $73, $81, $7a, $81, $77, $1b, $76, $81, $75, $81
	.byte $41, $0e
	.word @song0ref3070
	.byte $7a, $17, $77, $15
	.byte $41, $08
	.word @song0ref3102
@song0ref3128:
	.byte $72, $13, $73, $81, $7a, $2f, $77, $2d, $76, $81, $75, $81, $72, $19
@song0ref3142:
	.byte $73, $81, $7a, $1f, $77, $1d
@song0ref3148:
	.byte $76, $81, $75, $81, $72, $2b, $73, $81, $7a, $17, $77, $15
@song0ref3160:
	.byte $76, $81, $75, $81, $72, $1b, $73, $81, $7a, $1d, $77, $1b, $76, $81, $75, $81
	.byte $41, $14
	.word @song0ref3128
@song0ref3179:
	.byte $7a, $1c, $77, $1a
@song0ref3183:
	.byte $76, $81, $75, $81, $72, $13, $73, $81, $7a, $2f, $77, $2d, $76, $81, $75, $81, $72, $18
	.byte $41, $0d
	.word @song0ref3142
	.byte $41, $0b
	.word @song0ref3179
	.byte $73, $81, $7a, $1f, $77, $1d, $76, $81, $75, $81, $72, $2b, $73, $81, $7a, $15, $77, $13
	.byte $41, $08
	.word @song0ref2726
@song0ref3228:
	.byte $72, $11, $73, $81, $7a, $2d, $77, $2b
@song0ref3236:
	.byte $76, $81, $75, $81, $72, $18, $73, $81, $7a, $21, $77, $1f, $76, $81, $75, $81, $72, $29, $73, $81, $7a, $15, $77, $13
	.byte $76, $81, $75, $81, $72, $1d, $73, $81, $7a, $1c, $77, $1a, $76, $81, $75, $81
	.byte $41, $0e
	.word @song0ref3228
	.byte $7a, $1a, $77, $18
@song0ref3283:
	.byte $76, $81, $75, $81, $72, $1d, $73, $81, $7a, $1f
@song0ref3293:
	.byte $77, $1d, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $32, $77, $30, $76, $81, $75, $81, $72, $1b, $73, $81, $7a, $23
	.byte $77, $21, $76, $81, $75, $81, $72, $2e, $73, $81, $7a, $1a, $77, $18, $76, $81, $75, $81, $72, $1f, $73, $81, $7a, $81
	.byte $41, $11
	.word @song0ref3293
	.byte $7a, $19, $77, $17, $76, $81, $75, $81, $72, $1f, $73, $81, $7a, $81, $77, $1d, $76, $81, $75, $81
@song0ref3364:
	.byte $72, $15, $73, $81, $7a, $31, $77, $2f, $76, $81, $75, $81, $72, $1b
@song0ref3378:
	.byte $73, $81, $7a, $21, $77, $1f, $76, $81, $75, $81, $72, $2d, $73, $81, $7a, $19, $77, $17
	.byte $41, $08
	.word @song0ref3283
	.byte $41, $10
	.word @song0ref3364
	.byte $41, $08
	.word @song0ref2690
	.byte $72, $15, $73, $81, $7a, $31, $77, $2f, $76, $81, $75, $81, $72, $1a
	.byte $41, $09
	.word @song0ref3378
	.byte $41, $08
	.word @song0ref2690
	.byte $72, $15, $73, $81, $7a, $31, $77, $2f
@song0ref3433:
	.byte $76, $81, $75, $81, $72, $1a, $73, $81, $7a, $21, $77, $1f, $76, $81, $75, $81, $72, $2d, $73, $81, $7a, $17, $77, $15
	.byte $41, $08
	.word @song0ref2690
	.byte $72, $13, $73, $81, $7a, $2f, $77, $2d, $76, $81, $75, $81, $72, $1a, $73, $81, $7a, $23, $77, $21
	.byte $41, $08
	.word @song0ref3148
	.byte $72, $1f, $73, $81, $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref3183
	.byte $72, $1a, $73, $81, $7a, $23, $77, $21, $76, $81, $75, $81, $72, $2b, $73, $81, $7a, $21, $77, $1f, $76, $81, $75, $81
	.byte $72, $81
@song0ref3520:
	.byte $73, $81, $7a, $24, $77, $22, $76, $81, $75, $81, $72, $1d, $73, $81, $7a, $2b, $77, $29
@song0ref3538:
	.byte $76, $81, $75, $81, $72, $20, $73, $81, $7a, $21, $77, $1f, $76, $81, $75, $81, $72, $27
	.byte $41, $12
	.word @song0ref3520
	.byte $73, $81, $7a, $24, $77, $22
	.byte $41, $08
	.word @song0ref2690
@song0ref3568:
	.byte $72, $20
@song0ref3570:
	.byte $73, $81, $7a, $24, $77, $22, $76, $81, $75, $81, $72, $1a, $73, $81, $7a, $2a, $77, $28, $76, $81, $75, $81, $72, $20
	.byte $73, $81, $7a, $1e, $77, $1c, $76, $81, $75, $81, $72, $26
	.byte $41, $12
	.word @song0ref3570
	.byte $73, $81, $7a, $24, $77, $22
	.byte $41, $08
	.word @song0ref3433
	.byte $72, $20
	.byte $41, $12
	.word @song0ref3520
	.byte $41, $12
	.word @song0ref3520
	.byte $73, $81, $7a, $24, $77, $22
	.byte $41, $08
	.word @song0ref2690
	.byte $41, $13
	.word @song0ref3568
	.byte $41, $12
	.word @song0ref3570
	.byte $73, $81, $7a, $24, $77, $22
@song0ref3647:
	.byte $76, $81, $75, $81, $72, $1a, $73, $81, $7a, $1e, $77, $1c, $76, $81, $75, $81, $72, $20, $73, $81, $7a, $23, $77, $21
	.byte $76, $81, $75, $81, $72, $1a, $73, $81, $7a, $26, $77, $24, $76, $81, $75, $81, $72, $1f
@song0ref3689:
	.byte $73, $81, $7a, $23, $77, $21, $76, $81, $75, $81, $72, $22, $73, $81, $7a, $1e, $77, $1c, $76, $81, $75, $81, $72, $1f
	.byte $73, $81, $7a, $26, $77, $24, $76, $81, $75, $81, $72, $1a
	.byte $41, $0d
	.word @song0ref3689
	.byte $7a, $22, $77, $20, $76, $81, $75, $81, $72, $1a, $73, $81, $7a, $25, $77, $23, $76, $81, $75, $81, $72, $1e, $73, $81
	.byte $7a, $28, $77, $26, $76, $81, $75, $81, $72, $21
@song0ref3762:
	.byte $73, $81, $7a, $25, $77, $23, $76, $81, $75, $81, $72, $24, $73, $81, $7a, $22, $77, $20, $76, $81, $75, $81, $72, $21
	.byte $73, $81, $7a, $28, $77, $26, $76, $81, $75, $81, $72, $1e
	.byte $41, $0d
	.word @song0ref3762
	.byte $7a, $81, $77, $1f, $76, $81, $75, $81, $72, $1e, $73, $81, $7a, $24, $77, $22, $76, $81, $75, $81, $72, $1d, $73, $81
	.byte $7a, $28, $77, $26
	.byte $41, $08
	.word @song0ref3538
@song0ref3832:
	.byte $72, $24, $73, $81, $7a, $81, $77, $22, $76, $81, $75, $81, $72, $1d, $73, $81, $7a, $28, $77, $26
	.byte $41, $08
	.word @song0ref3538
	.byte $41, $08
	.word @song0ref3832
	.byte $7a, $21, $77, $1f, $76, $81, $75, $81, $72, $20
@song0ref3868:
	.byte $73, $81, $7a, $24, $77, $22, $76, $81, $75, $81, $72, $1d, $73, $81, $7a, $2a, $77, $28
	.byte $41, $08
	.word @song0ref3538
	.byte $72, $26
	.byte $41, $09
	.word @song0ref3868
	.byte $41, $08
	.word @song0ref3538
	.byte $72, $26, $73, $81, $7a, $24, $77, $22, $76, $81, $75, $81, $72, $1d, $73, $81, $7a, $1a, $77, $18, $76, $81, $75, $81
	.byte $72, $20
@song0ref3923:
	.byte $73, $81
@song0ref3925:
	.byte $7a, $1c, $77, $1a, $76, $81, $75, $81, $72, $16, $73, $81, $7a, $1f, $77, $1d
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $1b
	.byte $41, $09
	.word @song0ref3923
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $1b
	.byte $41, $09
	.word @song0ref3923
	.byte $76, $81, $75, $81, $72, $18, $73, $81, $7a, $19, $77, $17
	.byte $41, $08
	.word @song0ref2726
@song0ref3972:
	.byte $72, $15, $73, $81, $7a, $1f, $77, $1d, $76, $81, $75, $81, $72, $18, $73, $81, $7a, $19, $77, $17
	.byte $41, $08
	.word @song0ref2726
	.byte $41, $0a
	.word @song0ref3972
	.byte $76, $81, $75, $81, $72, $1b, $73, $81, $7a, $18, $77, $16, $76, $81, $75, $81, $72, $15
	.byte $41, $09
	.word @song0ref2467
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref2168
	.byte $72, $1a, $73, $81, $7a, $18, $77, $16, $76, $81, $75, $81, $72, $14
	.byte $41, $09
	.word @song0ref2467
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $7a, $1e, $77, $1c
	.byte $41, $08
	.word @song0ref2168
	.byte $41, $08
	.word @song0ref2148
	.byte $41, $08
	.word @song0ref3925
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $1b
	.byte $41, $09
	.word @song0ref3923
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $1b
	.byte $41, $09
	.word @song0ref3923
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $1b
	.byte $41, $09
	.word @song0ref3923
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $1b
	.byte $41, $09
	.word @song0ref3923
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $1b
	.byte $41, $09
	.word @song0ref3923
	.byte $41, $08
	.word @song0ref3236
	.byte $72, $1b, $73, $81, $7a, $1c, $77, $1a
	.byte $41, $08
	.word @song0ref3283
	.byte $72, $18, $73, $81, $7a, $21, $77, $1f
	.byte $41, $08
	.word @song0ref2726
	.byte $72, $1d, $73, $81, $7a, $1f, $77, $1d
	.byte $41, $08
	.word @song0ref2992
	.byte $72, $1b
@song0ref4206:
	.byte $73, $81, $7a, $1f, $77, $1d, $76, $81, $75, $81, $72, $18, $73, $81, $7a, $22, $77, $20
	.byte $41, $08
	.word @song0ref2726
	.byte $72, $1e
	.byte $41, $09
	.word @song0ref4206
	.byte $41, $08
	.word @song0ref2726
	.byte $72, $1e, $73, $81, $7a, $1f, $77, $1d
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $1b
	.byte $41, $09
	.word @song0ref3923
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $1b
	.byte $41, $09
	.word @song0ref3923
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $1b, $73, $81, $7a, $1c, $77, $1a
	.byte $41, $08
	.word @song0ref2927
	.byte $72, $81
	.byte $41, $14
	.word @song0ref2568
	.byte $41, $12
	.word @song0ref2572
	.byte $77, $1a
	.byte $41, $08
	.word @song0ref2168
	.byte $72, $18, $73, $81, $7a, $1c, $77, $1a, $76, $81, $75, $81
@song0ref4298:
	.byte $72, $14, $73, $81, $7a, $1f, $77, $1d, $76, $81, $75, $81, $72, $18, $73, $81, $7a, $81, $77, $16
	.byte $41, $08
	.word @song0ref2726
	.byte $41, $08
	.word @song0ref4298
	.byte $7a, $1c, $77, $1a
	.byte $41, $08
	.word @song0ref3160
	.byte $72, $18, $73, $81, $7a, $1e, $77, $1c, $76, $81, $75, $81, $72, $19, $73, $81, $7a, $26, $77, $24
	.byte $41, $08
	.word @song0ref3647
	.byte $72, $22, $73, $81, $7a, $1d, $77, $1b, $76, $81, $75, $81, $72, $1a, $73, $81, $7a, $1c, $77, $1a, $76, $81, $75, $81
	.byte $72, $19
	.byte $41, $0f
	.word @song0ref2986
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $17
	.byte $41, $09
	.word @song0ref3923
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $1b
	.byte $41, $09
	.word @song0ref3923
	.byte $41, $08
	.word @song0ref2586
	.byte $72, $1b
	.byte $41, $09
	.word @song0ref3923
	.byte $76, $81, $75, $81, $72, $18, $73, $81, $72, $83, $71, $16, $85, $79, $82, $28, $81, $80, $28, $73, $81, $71, $81, $72
	.byte $87, $71, $85, $79, $82, $29, $81, $80, $29, $73, $81, $71, $81, $72, $87, $71, $89, $00, $91, $7a, $84, $18, $77, $16
	.byte $76, $81, $75, $81, $72, $26, $73, $81, $7a, $1a
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2154
	.byte $41, $0b
	.word @song0ref2154
	.byte $41, $12
	.word @song0ref2196
	.byte $41, $12
	.word @song0ref2196
	.byte $41, $1f
	.word @song0ref2235
	.byte $41, $12
	.word @song0ref2261
	.byte $41, $12
	.word @song0ref2261
	.byte $77, $16, $76, $81, $75, $81, $42
	.word @song0ch1loop
@song0ch2:
@song0ref4498:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $08
	.word @song0ref4498
@song0ch2loop:
	.byte $41, $08
	.word @song0ref4498
	.byte $41, $08
	.word @song0ref4498
	.byte $41, $08
	.word @song0ref4498
	.byte $41, $08
	.word @song0ref4498
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch2loop
@song0ch3:
	.byte $78, $84
@song0ref4531:
	.byte $1e, $73, $20, $72, $81, $71, $81, $21, $00, $78, $1e, $73, $20, $72, $81, $71, $81, $21, $00, $8b, $78
	.byte $41, $0d
	.word @song0ref4531
	.byte $78, $1e, $73, $20, $72, $81, $71, $81, $21, $00, $8b, $78, $1e, $73, $20, $72, $81, $71, $81, $21, $00, $95, $22, $21
	.byte $72, $20, $81, $1f, $73, $81, $1e, $78, $1b, $77, $81, $76, $1a, $81, $75, $19, $81, $18, $74, $81, $17, $83, $73, $16
	.byte $85, $72, $15, $85, $71
@song0ref4608:
	.byte $89
@song0ref4609:
	.byte $78, $1e, $73, $20, $72, $81, $71, $81, $21, $00, $75, $21, $73, $22, $72, $81, $71, $81, $23, $00
@song0ref4629:
	.byte $78, $1e, $75, $1f, $73, $81, $72, $81
@song0ref4637:
	.byte $71, $81, $20, $75, $21, $73, $22, $72, $81, $71, $81, $23, $00
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $10
	.word @song0ref4609
@song0ch3loop:
	.byte $41, $08
	.word @song0ref4637
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
@song0ref4837:
	.byte $78, $1e, $73, $20, $72, $81, $71, $81, $21, $00, $8b, $75, $21, $73, $22, $72, $81, $71, $81, $23, $00, $bb, $78, $1e
	.byte $75, $20, $74, $83, $73, $21, $81, $72, $81, $22, $81, $71, $81, $23, $81
	.byte $41, $0c
	.word @song0ref4629
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $0d
	.word @song0ref4837
	.byte $a3, $78, $1e, $75, $1f, $73, $81, $72, $81, $71, $83, $00
	.byte $41, $19
	.word @song0ref4608
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $18
	.word @song0ref4609
	.byte $41, $10
	.word @song0ref4609
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $8f, $16, $11, $85, $00, $01, $0a, $85, $00, $04, $12, $85, $00, $0e, $02, $85, $00
@song0ref5119:
	.byte $0a, $95, $00, $89, $0a, $89, $00, $89, $08, $89, $09, $89, $00, $89, $13, $95, $00, $89, $13, $89, $00, $89, $13, $81
	.byte $0b, $85, $0a, $8b, $00, $87, $03, $02, $93, $05, $00
@song0ref5154:
	.byte $87
@song0ref5155:
	.byte $02
@song0ref5156:
	.byte $89, $03, $00, $87, $08, $89, $05, $09
@song0ref5164:
	.byte $89, $00, $87, $03, $02, $93, $05, $00, $83, $83
	.byte $41, $11
	.word @song0ref5155
	.byte $41, $12
	.word @song0ref5154
	.byte $41, $0e
	.word @song0ref5154
	.byte $0a, $93, $05, $00, $87, $0a
	.byte $41, $0c
	.word @song0ref5156
	.byte $0a, $93, $05, $00, $87, $0a
	.byte $41, $0c
	.word @song0ref5156
@song0ref5201:
	.byte $0c, $93, $05, $00, $87, $0c, $89, $03, $00, $87, $0a, $81, $87, $05, $0c
@song0ref5216:
	.byte $89, $00, $87, $03, $14, $93, $05, $00, $87, $14, $89, $03, $00, $87, $12, $89, $05, $14
@song0ref5234:
	.byte $89, $00, $87, $03, $0d, $93, $05, $00, $87, $0d, $89, $03, $00, $87, $02, $89, $05, $0d, $89, $00, $87, $03, $95, $05
	.byte $00, $87, $03, $8b, $00, $87, $13, $89, $05, $03
	.byte $41, $11
	.word @song0ref5216
	.byte $0a, $89, $00, $87, $03, $11, $93, $05, $00, $87, $11, $89, $03, $00, $87, $11, $89, $05, $12
	.byte $41, $08
	.word @song0ref5164
	.byte $87, $02, $89, $03, $00, $87, $0a, $89, $05, $09
@song0ref5303:
	.byte $89, $00, $87, $03, $08, $93, $05, $00, $87, $08, $89, $03, $00, $87, $09, $89, $05, $11, $89, $00, $87
	.byte $41, $36
	.word @song0ref5119
@song0ch4loop:
	.byte $83
	.byte $41, $11
	.word @song0ref5155
	.byte $41, $12
	.word @song0ref5154
	.byte $41, $0e
	.word @song0ref5154
	.byte $0a, $93, $05, $00, $87, $0a
	.byte $41, $0c
	.word @song0ref5156
	.byte $0a, $93, $05, $00, $87, $0a
	.byte $41, $0c
	.word @song0ref5156
	.byte $41, $43
	.word @song0ref5201
	.byte $41, $08
	.word @song0ref5164
	.byte $87, $02, $89, $03, $00, $87, $01, $89, $05, $03
	.byte $41, $0e
	.word @song0ref5234
	.byte $03, $89, $05, $16, $89, $00, $87, $03, $0a, $93, $05, $00, $87, $0a
	.byte $41, $0c
	.word @song0ref5156
	.byte $0a, $89, $00, $87, $08, $06, $89, $00, $b7, $03, $09, $93, $05, $00, $87, $09, $89, $03, $00, $87, $09, $89, $05, $0f
	.byte $89, $00, $87, $03, $07, $93, $05, $00, $87, $07, $89, $03, $00, $87, $07, $89, $05, $10
	.byte $41, $0e
	.word @song0ref5303
	.byte $08, $89, $05, $07
	.byte $41, $08
	.word @song0ref5303
	.byte $83, $83, $08, $89, $03, $00, $87, $08, $89, $05, $07, $89, $00, $87, $16, $11, $93, $17, $00, $87, $11, $89, $16, $00
	.byte $87, $11, $89, $17, $10, $89, $00, $87, $16, $0f, $93, $17, $00, $87, $0f, $89, $16, $00, $87, $0f, $89, $17, $11
@song0ref5491:
	.byte $89, $00, $87, $16, $09, $93, $17, $00, $87, $09, $89, $16, $00, $87, $09, $89, $17, $0f
	.byte $41, $12
	.word @song0ref5491
@song0ref5512:
	.byte $89, $00, $87, $03, $13, $93, $05, $00, $87, $13, $91, $00, $85, $87
@song0ref5526:
	.byte $05, $13
@song0ref5528:
	.byte $89, $00, $87, $03, $09, $93, $05, $00, $87, $09, $91, $00, $8d, $05, $09
	.byte $41, $0c
	.word @song0ref5512
	.byte $8d
	.byte $41, $11
	.word @song0ref5526
	.byte $41, $08
	.word @song0ref5164
	.byte $87, $02, $91, $00, $8d, $05, $02, $89, $00, $87, $03, $12, $93, $05, $00, $87, $12, $91, $00, $8d, $05, $12
	.byte $41, $0a
	.word @song0ref5512
	.byte $89, $03, $00, $87, $08, $89, $05, $11
	.byte $41, $0a
	.word @song0ref5528
	.byte $89, $03, $00, $87, $12, $89, $05, $13
@song0ref5597:
	.byte $89, $00, $87, $16
@song0ref5601:
	.byte $02, $93, $17, $00, $87, $02
@song0ref5607:
	.byte $89, $16, $00, $87, $09, $89, $17, $11, $89, $00, $87, $16, $14, $93, $17, $00, $87, $14, $89, $16, $00, $87, $14, $81
	.byte $0c, $85, $17, $02
@song0ref5635:
	.byte $89, $00, $87, $16, $13, $93, $17, $00, $87, $13
	.byte $41, $0c
	.word @song0ref5607
	.byte $13, $93, $17, $00, $83, $83, $13
	.byte $41, $0c
	.word @song0ref5607
	.byte $13, $93, $17, $00, $87, $13
	.byte $41, $0c
	.word @song0ref5607
	.byte $13, $93, $17, $00, $87, $13
	.byte $41, $0c
	.word @song0ref5607
	.byte $41, $12
	.word @song0ref5601
	.byte $41, $12
	.word @song0ref5601
	.byte $0d, $93, $17, $00, $87, $0d, $89, $16, $00, $87, $02, $81, $87, $17, $0d, $89, $00, $87, $16, $15, $93, $17, $00, $87
	.byte $15, $89, $16, $00, $87, $0b, $89, $17, $15
@song0ref5715:
	.byte $89, $00, $87, $16, $03, $93, $17, $00, $87, $03, $89, $16, $00, $87, $13, $89, $17, $03, $89, $00, $87, $16, $95, $17
	.byte $00, $87, $16, $8b, $00, $87, $14, $89, $17, $16
	.byte $41, $0a
	.word @song0ref5635
	.byte $89, $16, $00, $87, $0e, $89, $17, $16
	.byte $41, $0e
	.word @song0ref5715
	.byte $16, $89, $17, $04
	.byte $41, $16
	.word @song0ref5597
	.byte $02, $93, $04, $95, $0e, $95, $00, $95
	.byte $41, $36
	.word @song0ref5119
	.byte $42
	.word @song0ch4loop
@song0ch5:
	.byte $41, $08
	.word @song0ref4498
	.byte $41, $08
	.word @song0ref4498
@song0ch5loop:
	.byte $41, $08
	.word @song0ref4498
	.byte $41, $08
	.word @song0ref4498
	.byte $41, $08
	.word @song0ref4498
	.byte $41, $08
	.word @song0ref4498
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch5loop
@song0ch6:
	.byte $ff, $bf, $77, $84
@song0ref5814:
	.byte $13, $74, $13, $72, $16, $16, $71, $1b, $81, $75, $13, $73, $13
@song0ref5827:
	.byte $72, $16, $71, $81, $1b, $81, $77, $13
@song0ref5835:
	.byte $76, $13, $75, $16, $74, $81, $1b, $73, $81, $13, $81, $72, $16, $81, $1b, $71, $81, $77, $13, $74, $81, $72, $16, $81
	.byte $71, $1b, $81, $75, $13, $73, $81
	.byte $41, $18
	.word @song0ref5827
@song0ref5869:
	.byte $72, $16
@song0ref5871:
	.byte $71, $81, $1b, $81, $77, $13, $76, $13, $75, $15, $74, $81, $1b, $73, $81, $13, $81, $72, $15, $81, $1b, $71, $81, $77
	.byte $13, $74, $81, $72, $15, $81, $71, $1b, $81, $75, $13, $73, $81, $72, $15
	.byte $41, $0f
	.word @song0ref5871
@song0ref5913:
	.byte $77, $14
@song0ref5915:
	.byte $74, $14, $72, $16, $16, $71, $1a, $81, $75, $14, $73, $14
@song0ref5927:
	.byte $72, $16, $71, $81, $1a, $81, $77, $14, $76, $14, $75, $16, $74, $81
@song0ref5941:
	.byte $1a, $73, $81, $14, $81, $72, $16, $81, $1a, $71, $81, $77, $14, $74, $81, $72, $16, $81, $71, $1a, $81, $75, $14, $73
	.byte $81
	.byte $41, $18
	.word @song0ref5927
	.byte $41, $18
	.word @song0ref5927
	.byte $41, $11
	.word @song0ref5927
	.byte $41, $1f
	.word @song0ref5915
	.byte $41, $18
	.word @song0ref5927
	.byte $41, $18
	.word @song0ref5927
	.byte $41, $10
	.word @song0ref5927
	.byte $77
	.byte $41, $20
	.word @song0ref5814
	.byte $41, $18
	.word @song0ref5827
	.byte $41, $18
	.word @song0ref5827
	.byte $41, $10
	.word @song0ref5827
@song0ref6000:
	.byte $77, $14, $74, $14, $72, $18, $18, $71, $1b, $81, $75, $14, $73, $14
@song0ref6014:
	.byte $72, $18, $71, $81, $1b, $81, $77, $14, $76, $14, $75, $18, $74, $81, $1b, $73, $81, $14, $81, $72, $18, $81, $1b, $71
	.byte $81, $77, $14, $74, $81, $72, $18, $81, $71, $1b, $81, $75, $14, $73, $81
	.byte $41, $10
	.word @song0ref6014
@song0ref6056:
	.byte $77, $15, $74, $81, $72, $18, $81, $71, $1b, $81, $75, $15, $73, $81, $72, $18, $71, $81, $1b, $81, $77, $15, $76, $15
	.byte $75, $18, $74, $81, $1b, $73, $81, $15, $81, $72, $18, $81, $1b, $71, $81
	.byte $41, $18
	.word @song0ref6056
@song0ref6098:
	.byte $77, $16, $74, $16, $72, $1a, $1a, $71, $1f, $81, $75, $16, $73, $16
@song0ref6112:
	.byte $72, $1a, $71, $81, $1f, $81, $77, $16, $76, $16, $75, $1a, $74, $81, $1f, $73, $81, $16, $81, $72, $1a, $81, $1f, $71
	.byte $81, $77, $16, $74, $81, $72, $1a, $81, $71, $1f, $81, $75, $16, $73, $81
	.byte $41, $10
	.word @song0ref6112
@song0ref6154:
	.byte $77, $18, $74, $81, $72, $1b, $81, $71, $1f, $81, $75, $18, $73, $81
@song0ref6168:
	.byte $72, $1b, $71, $81, $1f, $81, $77, $18, $76, $18, $75, $1b, $74, $81, $1f, $73, $81, $18, $81, $72, $1b, $81, $1f, $71
	.byte $81
	.byte $41, $18
	.word @song0ref6154
@song0ref6196:
	.byte $77, $18, $74, $18, $72, $1b, $1b, $71, $1f, $81, $75, $18, $73, $18
	.byte $41, $10
	.word @song0ref6168
	.byte $41, $18
	.word @song0ref6154
@song0ref6216:
	.byte $77, $18, $74, $81, $72, $1a, $81, $71, $1e, $81, $75, $18, $73, $81, $72, $1a, $71, $81, $1e, $81, $77, $18, $76, $18
	.byte $75, $1a, $74, $81, $1e, $73, $81, $18, $81, $72, $1a, $81, $1e, $71, $81
	.byte $41, $18
	.word @song0ref6216
	.byte $77, $18, $74, $18, $72, $1b, $1b, $71, $20, $81, $75, $18, $73, $18
@song0ref6272:
	.byte $72, $1b, $71, $81, $20, $81, $77, $18, $76, $18, $75, $1b, $74, $81, $20, $73, $81, $18, $81, $72, $1b, $81, $20, $71
	.byte $81, $77, $18, $74, $81, $72, $1b, $81, $71, $20, $81, $75, $18, $73, $81
	.byte $41, $10
	.word @song0ref6272
@song0ref6314:
	.byte $77, $1a, $74, $81, $72, $1d, $81, $71, $20, $81, $75, $1a, $73, $81, $72, $1d, $71, $81, $20, $81, $77, $1a, $76, $1a
	.byte $75, $1d, $74, $81, $20, $73, $81, $1a, $81, $72, $1d, $81, $20, $71, $81
	.byte $41, $18
	.word @song0ref6314
	.byte $77
	.byte $41, $20
	.word @song0ref5814
	.byte $41, $18
	.word @song0ref5827
	.byte $41, $19
	.word @song0ref5869
	.byte $41, $0f
	.word @song0ref5871
	.byte $41, $20
	.word @song0ref5913
	.byte $41, $18
	.word @song0ref5927
	.byte $41, $08
	.word @song0ref5927
@song0ch6loop:
	.byte $41, $10
	.word @song0ref5941
	.byte $41, $11
	.word @song0ref5927
	.byte $41, $1f
	.word @song0ref5915
	.byte $41, $18
	.word @song0ref5927
	.byte $41, $18
	.word @song0ref5927
	.byte $41, $10
	.word @song0ref5927
	.byte $77
	.byte $41, $20
	.word @song0ref5814
	.byte $41, $18
	.word @song0ref5827
	.byte $41, $18
	.word @song0ref5827
	.byte $41, $10
	.word @song0ref5827
	.byte $41, $20
	.word @song0ref6000
	.byte $41, $10
	.word @song0ref6014
	.byte $41, $18
	.word @song0ref6056
	.byte $41, $18
	.word @song0ref6056
	.byte $41, $20
	.word @song0ref6098
	.byte $41, $10
	.word @song0ref6112
	.byte $41, $18
	.word @song0ref6154
	.byte $41, $18
	.word @song0ref6154
	.byte $41, $20
	.word @song0ref6000
	.byte $41, $10
	.word @song0ref6014
@song0ref6440:
	.byte $77, $16, $74, $81, $72, $1a, $81, $71, $1d, $81, $75, $16, $73, $81
@song0ref6454:
	.byte $72, $1a, $71, $81, $1d, $81, $77, $16, $76, $16, $75, $1a, $74, $81, $1d, $73, $81, $16, $81, $72, $1a, $81, $1d, $71
	.byte $81
	.byte $41, $18
	.word @song0ref6440
	.byte $77
	.byte $41, $20
	.word @song0ref5814
	.byte $41, $11
	.word @song0ref5827
	.byte $41, $0b
	.word @song0ref5835
	.byte $13, $81, $16, $81, $1b, $00, $bb
	.byte $41, $08
	.word @song0ref6196
	.byte $41, $10
	.word @song0ref6168
	.byte $41, $18
	.word @song0ref6154
@song0ref6508:
	.byte $77, $18, $74, $81, $72, $1d, $81, $71, $21, $81, $75, $18, $73, $81, $72, $1d, $71, $81, $21, $81, $77, $18, $76, $18
	.byte $75, $1d, $74, $81, $21, $73, $81, $18, $81, $72, $1d, $81, $21, $71, $81
	.byte $41, $18
	.word @song0ref6508
@song0ref6550:
	.byte $77, $1a, $74, $1a, $72, $1d, $1d, $71, $22, $81, $75, $1a, $73, $1a
@song0ref6564:
	.byte $72, $1d, $71, $81, $22, $81, $77, $1a, $76, $1a, $75, $1d, $74, $81, $22, $73, $81, $1a, $81, $72, $1d, $81, $22, $71
	.byte $81, $77, $1a, $74, $81, $72, $1d, $81, $71, $22, $81, $75, $1a, $73, $81
	.byte $41, $18
	.word @song0ref6564
	.byte $41, $18
	.word @song0ref6564
	.byte $41, $11
	.word @song0ref6564
	.byte $74, $1a, $72, $1d, $1d, $71, $21, $81, $75, $1a, $73, $1a
@song0ref6624:
	.byte $72, $1d, $71, $81, $21, $81, $77, $1a, $76, $1a, $75, $1d, $74, $81, $21, $73, $81, $1a, $81, $72, $1d, $81, $21, $71
	.byte $81
@song0ref6649:
	.byte $77, $1a, $74, $81, $72, $1d, $81, $71, $21, $81, $75, $1a, $73, $81
	.byte $41, $12
	.word @song0ref6624
@song0ref6666:
	.byte $72, $1f, $81, $71, $23, $81, $75, $1a, $73, $81, $72, $1f, $71, $81, $23, $81, $77, $1a, $76, $1a, $75, $1f, $74, $81
	.byte $23, $73, $81, $1a, $81, $72, $1f, $81, $23, $71, $81, $77, $1a, $74, $81
	.byte $41, $16
	.word @song0ref6666
	.byte $77, $1c, $74, $1c, $72, $1f, $1f, $71, $24, $81, $75, $1c, $73, $1c
@song0ref6722:
	.byte $72, $1f, $71, $81, $24, $81, $77, $1c, $76, $1c, $75, $1f, $74, $81, $24, $73, $81, $1c, $81, $72, $1f, $81, $24, $71
	.byte $81
@song0ref6747:
	.byte $77, $1c, $74, $81, $72, $1f, $81, $71, $24, $81, $75, $1c, $73, $81
	.byte $41, $18
	.word @song0ref6722
	.byte $41, $18
	.word @song0ref6722
	.byte $41, $10
	.word @song0ref6722
	.byte $41, $20
	.word @song0ref6550
	.byte $41, $10
	.word @song0ref6564
	.byte $41, $08
	.word @song0ref6747
	.byte $41, $18
	.word @song0ref6722
	.byte $41, $10
	.word @song0ref6722
	.byte $41, $20
	.word @song0ref6550
	.byte $41, $10
	.word @song0ref6564
	.byte $41, $08
	.word @song0ref6747
	.byte $41, $18
	.word @song0ref6722
	.byte $41, $10
	.word @song0ref6722
@song0ref6800:
	.byte $77, $15, $74, $15, $72, $18, $18, $71, $1d, $81, $75, $15, $73, $15
@song0ref6814:
	.byte $72, $18, $71, $81, $1d, $81, $77, $15, $76, $15, $75, $18, $74, $81, $1d, $73, $81, $15, $81, $72, $18, $81, $1d, $71
	.byte $81, $77, $15, $74, $81, $72, $18, $81, $71, $1d, $81, $75, $15, $73, $81
	.byte $41, $10
	.word @song0ref6814
@song0ref6856:
	.byte $77, $13, $74, $81, $72, $17, $81, $71, $1c, $81, $75, $13, $73, $81, $72, $17, $71, $81, $1c, $81, $77, $13, $76, $13
	.byte $75, $17, $74, $81, $1c, $73, $81, $13, $81, $72, $17, $81, $1c, $71, $81
	.byte $41, $18
	.word @song0ref6856
	.byte $77, $1a, $74, $1a, $72, $1d, $1d, $71, $1f, $81, $75, $1a, $73, $1a
@song0ref6912:
	.byte $72, $1d, $71, $81, $1f, $81, $77, $1a, $76, $1a, $75, $1d, $74, $81, $1f, $73, $81, $1a, $81, $72, $1d, $81, $1f, $71
	.byte $81, $77, $1a, $74, $81, $72, $1d, $81, $71, $1f, $81, $75, $1a, $73, $81
	.byte $41, $10
	.word @song0ref6912
@song0ref6954:
	.byte $77, $18, $74, $81, $72, $1c, $81, $71, $1f, $81, $75, $18, $73, $81, $72, $1c, $71, $81, $1f, $81, $77, $18, $76, $18
	.byte $75, $1c, $74, $81, $1f, $73, $81, $18, $81, $72, $1c, $81, $1f, $71, $81
	.byte $41, $18
	.word @song0ref6954
	.byte $41, $20
	.word @song0ref6800
	.byte $41, $18
	.word @song0ref6814
	.byte $72, $18
@song0ref7004:
	.byte $71, $81, $1d, $81, $77, $15, $76, $15, $75, $17, $74, $81, $1d, $73, $81, $15, $81, $72, $17, $81, $1d, $71, $81, $77
	.byte $15, $74, $81, $72, $17, $81, $71, $1d, $81, $75, $15, $73, $81, $72, $17
	.byte $41, $0f
	.word @song0ref7004
	.byte $77, $16
@song0ref7048:
	.byte $74, $16, $72, $18, $18, $71, $1c, $81, $75, $16, $73, $16
@song0ref7060:
	.byte $72, $18, $71, $81, $1c, $81, $77, $16, $76, $16, $75, $18, $74, $81, $1c, $73, $81, $16, $81, $72, $18, $81, $1c, $71
	.byte $81, $77, $16, $74, $81, $72, $18, $81, $71, $1c, $81, $75, $16, $73, $81
	.byte $41, $18
	.word @song0ref7060
	.byte $41, $18
	.word @song0ref7060
	.byte $41, $11
	.word @song0ref7060
	.byte $41, $1f
	.word @song0ref7048
	.byte $41, $18
	.word @song0ref7060
	.byte $41, $18
	.word @song0ref7060
	.byte $41, $10
	.word @song0ref7060
	.byte $41, $20
	.word @song0ref6800
	.byte $41, $18
	.word @song0ref6814
	.byte $41, $18
	.word @song0ref6814
	.byte $41, $10
	.word @song0ref6814
@song0ref7132:
	.byte $77, $16, $74, $16, $72, $1a, $1a, $71, $1d, $81, $75, $16, $73, $16
	.byte $41, $10
	.word @song0ref6454
	.byte $41, $18
	.word @song0ref6440
@song0ref7152:
	.byte $77, $17, $74, $81, $72, $1a, $81, $71, $1d, $81, $75, $17, $73, $81, $72, $1a, $71, $81, $1d, $81, $77, $17, $76, $17
	.byte $75, $1a, $74, $81, $1d, $73, $81, $17, $81, $72, $1a, $81, $1d, $71, $81
	.byte $41, $18
	.word @song0ref7152
	.byte $77, $18, $74, $18, $72, $1c, $1c, $71, $21, $81, $75, $18, $73, $18
@song0ref7208:
	.byte $72, $1c, $71, $81, $21, $81, $77, $18, $76, $18, $75, $1c, $74, $81, $21, $73, $81, $18, $81, $72, $1c, $81, $21, $71
	.byte $81, $77, $18, $74, $81, $72, $1c, $81, $71, $21, $81, $75, $18, $73, $81
	.byte $41, $10
	.word @song0ref7208
	.byte $41, $08
	.word @song0ref6649
	.byte $41, $18
	.word @song0ref6624
	.byte $41, $10
	.word @song0ref6624
	.byte $41, $08
	.word @song0ref7132
	.byte $41, $10
	.word @song0ref6454
	.byte $41, $18
	.word @song0ref6440
	.byte $41, $18
	.word @song0ref6954
	.byte $41, $18
	.word @song0ref6954
	.byte $00, $ff, $ff, $ff, $fd, $42
	.word @song0ch6loop
