; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_starman=music_data_starman
.endif

music_data_starman:
	.byte 1
	.word @instruments
	.word @samples-5
; 00 : Starman
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_starman
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env4,@env5,@env1,@env0 ; 00 : Overworld lead
	.word @env4,@env5,@env9,@env0 ; 01 : 50% Pulse
	.word @env3,@env5,@env8,@env0 ; 02 : Closed Hat
	.word @env12,@env7,@env8,@env0 ; 03 : SS Noise snare(D3)
	.word @env14,@env5,@env8,@env0 ; 04 : Open Hat
	.word @env4,@env5,@env10,@env0 ; 05 : 25% Pulse

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c2,$c1,$00,$01
@env2:
	.byte $c2,$c0,$00,$01
@env3:
	.byte $00,$cc,$c9,$c4,$c2,$c1,$06,$c0,$00,$07
@env4:
	.byte $00,$cf,$7f,$00,$02
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $00,$bd,$7f,$00,$02
@env7:
	.byte $c0,$c1,$c2,$00,$02
@env8:
	.byte $7f,$00,$00
@env9:
	.byte $c2,$7f,$00,$00
@env10:
	.byte $c1,$7f,$00,$00
@env11:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env12:
	.byte $00,$cf,$c9,$04,$c7,$04,$c5,$04,$c3,$00,$08
@env13:
	.byte $00,$ce,$7f,$00,$02
@env14:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c5,$c4,$c4,$c3,$02,$c2,$06,$c1,$00,$0e
@env15:
	.byte $cc,$c0,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0d,$0d,$40,$01 ; 00 Punch Kick (Pitch:13)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $7b, $82, $31, $89, $3d, $91, $7a, $83, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74, $83, $73, $83, $72, $83
	.byte $71, $83, $7f, $4e, $05, $80, $01, $89, $02, $89
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref39:
	.byte $03, $95, $82, $25, $1e, $1b, $25, $22, $1e, $80, $0a, $89, $00, $89, $82, $25, $1e, $1b, $25, $22, $1e, $80, $0d, $95
	.byte $82, $25, $1e, $1b, $25, $22, $1e, $1b, $22, $1e, $1b, $25, $22, $1e, $00, $87, $25, $1e, $1b, $25, $22, $1e, $80, $0a
	.byte $89, $0d, $89, $82, $25, $1e, $1b, $25, $22, $1e, $80, $0a, $89, $48, $01, $95, $82, $24, $1d, $19, $24, $20, $1d, $80
	.byte $05, $89, $00, $89, $82, $24, $1d, $19, $24, $20, $1d, $80, $0c, $95, $82, $24, $1d, $19, $24, $20, $1d, $19, $20, $1d
	.byte $19, $24, $20, $1d, $00, $87, $24, $1d, $19, $24, $20, $1d, $80, $08, $89, $0c, $89, $82, $24, $1d, $19, $24, $20, $00
	.byte $80, $05, $89, $48
	.byte $41, $6a
	.word @song0ref39
	.byte $48
	.byte $41, $6a
	.word @song0ref39
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $80, $20, $ad, $21, $95, $00, $95
@song0ch1loop:
	.byte $4e, $01, $21, $89, $8a, $50, $fb, $2d, $2e, $89, $22, $ad, $49, .lobyte(@env11), .hibyte(@env11), $c7, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $80, $29, $9d, $28, $81, $27, $81, $26, $81, $25, $81, $24, $ad, $49, .lobyte(@env11), .hibyte(@env11)
	.byte $c7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $25, $95, $00, $89, $26, $95, $00, $89, $4e, $02, $26, $89, $8a
	.byte $50, $fc, $32, $33, $89, $27, $ad, $49, .lobyte(@env11), .hibyte(@env11), $c7, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $80, $2e, $9d, $2d, $81, $2c, $81, $2b, $81, $2a, $81, $29, $ad, $49, .lobyte(@env11), .hibyte(@env11), $af, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $80, $30, $ad, $2c, $95, $00, $95, $2d, $89, $8a, $50, $fa, $39, $3a, $83, $2e
	.byte $8f, $49, .lobyte(@env11), .hibyte(@env11), $a3, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $2a, $95, $4e, $01
	.byte $29, $a1, $27, $a1, $25, $95, $24, $95, $25, $89, $24, $a1, $1d, $ad, $20, $95, $00, $89, $21, $95, $00, $89, $42
	.word @song0ch1loop
@song0ch2:
	.byte $c7, $4e, $05, $80, $01, $89, $02, $89
@song0ch2loop:
@song0ref336:
	.byte $03, $95, $00, $89, $0a, $89, $00, $95, $0d, $95, $00, $ad, $0a, $89, $0d, $89, $00, $89, $0a, $89, $01, $95, $00, $89
	.byte $05, $89, $00, $95, $0c, $95, $00, $ad, $08, $89, $0c, $89, $00, $89, $05, $89
	.byte $41, $28
	.word @song0ref336
	.byte $41, $28
	.word @song0ref336
	.byte $42
	.word @song0ch2loop
@song0ch3:
	.byte $86, $1b, $89, $1b, $95, $1b, $89, $1b, $95, $88, $31, $89, $84, $31, $89
@song0ch3loop:
@song0ref401:
	.byte $88, $31, $89, $84, $31, $89, $31, $89, $31, $89, $86, $1b, $95, $84, $31, $89, $31, $89
	.byte $41, $0e
	.word @song0ref401
	.byte $41, $0c
	.word @song0ref401
@song0ref425:
	.byte $86, $1b, $89, $88, $31, $89, $86, $1b, $89, $84, $31, $89, $31, $89, $86, $1b, $95, $84, $31, $89, $31, $89
	.byte $41, $0e
	.word @song0ref401
	.byte $41, $0e
	.word @song0ref401
	.byte $41, $0c
	.word @song0ref401
	.byte $41, $10
	.word @song0ref425
	.byte $41, $0e
	.word @song0ref401
	.byte $41, $0e
	.word @song0ref401
	.byte $41, $0c
	.word @song0ref401
	.byte $41, $10
	.word @song0ref425
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $01, $89, $01, $89, $00, $89, $01, $89, $01, $89, $00, $89, $01, $89, $00, $89
@song0ch4loop:
@song0ref491:
	.byte $01, $95, $00, $95, $01, $95, $00, $95, $01, $95, $00, $95, $01, $95, $00, $95, $01, $95
@song0ref509:
	.byte $00, $95, $01, $95, $01, $89, $01, $95, $01, $95, $00, $89
	.byte $41, $16
	.word @song0ref491
	.byte $41, $0c
	.word @song0ref509
	.byte $41, $16
	.word @song0ref491
	.byte $41, $0c
	.word @song0ref509
	.byte $01, $95, $00, $95, $42
	.word @song0ch4loop
@song0ch5:
	.byte $df
@song0ch5loop:
@song0ref542:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $42
	.word @song0ch5loop
@song0ch6:
	.byte $df
@song0ch6loop:
	.byte $41, $0c
	.word @song0ref542
	.byte $42
	.word @song0ch6loop
