; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Arpeggios are used, you must set FAMISTUDIO_USE_ARPEGGIO = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_waterworld=music_data_waterworld
.endif

music_data_waterworld:
	.byte 1
	.word @instruments
	.word @samples-5
; 00 : Waterworld
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_waterworld
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env9,@env11,@env16,@env0 ; 00 : 50% Pulse
	.word @env12,@env11,@env14,@env0 ; 01 : Noise short
	.word @env10,@env11,@env14,@env0 ; 02 : Noise long
	.word @env9,@env11,@env5,@env0 ; 03 : Overworld lead
	.word @env9,@env23,@env6,@env8 ; 04 : Bass
	.word @env9,@env11,@env17,@env0 ; 05 : 25% Pulse
	.word @env22,@env23,@env6,@env13 ; 06 : DPCM

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$bd,$b6,$00,$00
@env2:
	.byte $c0,$bd,$ba,$00,$00
@env3:
	.byte $c0,$bd,$b9,$00,$00
@env4:
	.byte $00,$c0,$bd,$bd,$c0,$c3,$c3,$00,$01
@env5:
	.byte $c2,$c1,$00,$01
@env6:
	.byte $c2,$c0,$00,$01
@env7:
	.byte $c0,$bb,$b7,$00,$00
@env8:
	.byte $00,$bf,$7f,$00,$02
@env9:
	.byte $00,$cf,$7f,$00,$02
@env10:
	.byte $00,$cf,$04,$c0,$00,$03
@env11:
	.byte $c0,$7f,$00,$01
@env12:
	.byte $00,$cf,$c0,$00,$02
@env13:
	.byte $00,$bd,$7f,$00,$02
@env14:
	.byte $7f,$00,$00
@env15:
	.byte $00,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$00,$01
@env16:
	.byte $c2,$7f,$00,$00
@env17:
	.byte $c1,$7f,$00,$00
@env18:
	.byte $c0,$bc,$b9,$00,$00
@env19:
	.byte $c0,$bc,$b7,$00,$00
@env20:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env21:
	.byte $00,$c0,$b8,$b8,$c0,$c8,$c8,$00,$01
@env22:
	.byte $00,$ce,$7f,$00,$02
@env23:
	.byte $cc,$c0,$00,$01
@env24:
	.byte $00,$c0,$bd,$bc,$bd,$bf,$c1,$c3,$c4,$c3,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0d,$0d,$40,$01 ; 00 Punch Kick (Pitch:13)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $49, .lobyte(@env0), .hibyte(@env0), $4a, $b5, $80, $40
	.byte $4c, $00, $b1, $86, $2b, $83, $2c, $91, $80, $40, $4c, $86, $29, $89, $00, $89, $20, $8b, $00, $8b, $80, $40, $4c, $86
	.byte $22, $87, $23, $8b, $48, $9b, $22, $89, $00, $8b, $80, $40, $4c, $86, $23, $95, $25, $8b, $00, $8b, $22, $97, $80, $40
	.byte $4c, $86, $1d, $95, $1e, $8b, $00, $8b, $80, $40, $4c, $86, $1e, $87, $8a, $50, $f4, $2a, $2c, $8b, $48, $20, $99, $49
	.byte .lobyte(@env24), .hibyte(@env24), $99, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $40, $4c, $00, $b1, $86, $1e
	.byte $97, $80, $40, $4c, $00, $95, $86, $25, $8b, $00, $8b, $80, $40, $4c, $86, $1b, $87, $8a, $50, $f2, $27, $29, $8b, $48
	.byte $1d, $99, $86, $1b, $89, $00, $8b, $80, $40, $4c, $86, $19, $89, $00, $89, $16, $8b, $00, $8b, $19, $97, $80, $40, $4c
	.byte $00, $95, $86, $1b, $81, $8a, $50, $eb, $27, $28, $83, $1c, $8f, $80, $40, $4c, $86, $1b, $87, $00, $8b, $48, $9b, $19
	.byte $97, $80, $40, $4c, $8a, $19, $89, $49, .lobyte(@env15), .hibyte(@env15), $c1, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $80, $40, $4c, $86, $14, $95, $16, $99, $80, $40, $4c, $86, $19, $87, $00, $8b, $48, $1e, $85, $8a, $50, $f4, $2a
	.byte $2c, $8b, $20, $83, $49, .lobyte(@env21), .hibyte(@env21), $99, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $40
	.byte $4c, $86, $1e, $b1, $19, $97, $80, $40, $4c, $86, $14, $89, $00, $a5, $80, $40, $4c, $86, $15, $95, $48, $00, $99, $19
	.byte $89, $00, $8b, $80, $40, $4c, $86, $1e, $89, $00, $89, $20, $8b, $00, $8b, $21, $97, $80, $40, $4c, $86, $1e, $89, $00
	.byte $89, $19, $8b, $00, $8b, $80, $40, $4c, $86, $1e, $95, $48, $00, $99, $22, $83, $8a, $50, $f6, $2e, $2f, $83, $23, $8b
	.byte $80, $40, $4c, $00, $95, $86, $21, $b3, $80, $40, $4c, $86, $20, $95, $1e, $8b, $00, $8b, $80, $40, $4c, $86, $1c, $81
	.byte $8a, $50, $f2, $28, $29, $83, $1d, $8b, $48, $49, .lobyte(@env4), .hibyte(@env4), $b5, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $80, $40, $4c, $86, $19, $89, $00, $a5, $1d, $97, $80, $40, $4c, $86, $1e, $89, $00, $a5, $80, $40, $4c, $86, $1d
	.byte $95, $48, $b5, $80, $40, $4c, $86, $1e, $89, $00, $89, $1d, $8b, $00, $8b, $20, $89, $00, $8b, $80, $40, $4c, $86, $1d
	.byte $89, $00, $89, $1e, $8b, $00, $8b, $80, $40, $4c, $86, $1d, $87, $00, $8b, $48, $9b, $16, $89, $00, $8b, $80, $40, $4c
	.byte $86, $22, $b1, $16, $89, $00, $8b, $80, $40, $4c, $86, $20, $b1, $80, $40, $4c, $86, $16, $87, $00, $8b, $48, $1e, $99
	.byte $00, $89, $16, $8b, $80, $40, $4c, $00, $95, $86, $1c, $85, $8a, $50, $f2, $28, $29, $83, $1d, $a5, $80, $40, $4c, $8a
	.byte $1d, $b1, $80, $40, $4c, $86, $1c, $83, $1b, $85, $1a, $87, $48, $19, $b3, $80, $40, $4c, $8a, $19, $cb, $80, $40, $4c
	.byte $86, $1b, $b1, $80, $40, $4c, $86, $1a, $87, $19, $8b, $48, $18, $99, $19, $89, $00, $8b, $80, $40, $4c, $86, $18, $95
	.byte $19, $8b, $00, $8b, $18, $97, $80, $40, $4c, $00, $95, $86, $1b, $8b, $00, $8b, $80, $40, $4c, $86, $1d, $95, $48, $9b
	.byte $20, $89, $00, $8b, $80, $40, $4c, $00, $95, $86, $22, $b3, $80, $40, $4c, $86, $20, $89, $00, $a5, $80, $40, $4c, $86
	.byte $22, $87, $23, $8b, $48, $9b, $22, $89, $00, $8b, $80, $40, $4c, $86, $20, $b1, $49, .lobyte(@env20), .hibyte(@env20)
	.byte $99, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $40, $4c, $49, .lobyte(@env20), .hibyte(@env20), $8a, $20, $b1
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $40, $4c, $49, .lobyte(@env20), .hibyte(@env20), $8a, $20, $93, $00
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $4c, $88, $0d, $99, $19, $83, $00, $91, $4b, .lobyte(@env7), .hibyte(@env7), $80, $29, $97, $4b, .lobyte(@env11), .hibyte(@env11)
	.byte $4c, $88, $14, $85, $00, $91, $14, $97, $4b, .lobyte(@env7), .hibyte(@env7), $80, $29, $97, $00, $99, $4b, .lobyte(@env11)
	.byte .hibyte(@env11), $4c, $88, $0d, $97, $9b, $4b, .lobyte(@env7), .hibyte(@env7), $80, $29, $97, $4b, .lobyte(@env11)
	.byte .hibyte(@env11), $4c, $88, $14, $97, $19, $99, $00, $97, $4b, .lobyte(@env7), .hibyte(@env7), $80, $29, $97, $4b, .lobyte(@env11)
	.byte .hibyte(@env11), $4c, $88, $14, $99, $11, $97, $0d, $99, $19, $83, $00, $91, $4b, .lobyte(@env19), .hibyte(@env19)
	.byte $80, $27, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $14, $85, $00, $91, $14, $97, $4b, .lobyte(@env19)
	.byte .hibyte(@env19), $80, $27, $97, $00, $99, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $0d, $97, $9b, $4b, .lobyte(@env19)
	.byte .hibyte(@env19), $80, $27, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $14, $97, $19, $99, $00, $97, $4b
	.byte .lobyte(@env19), .hibyte(@env19), $80, $27, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $14, $99, $11, $97
	.byte $06, $99, $12, $83, $00, $91, $4b, .lobyte(@env18), .hibyte(@env18), $80, $29, $97, $4b, .lobyte(@env11), .hibyte(@env11)
	.byte $4c, $88, $0d, $85, $00, $91, $0d, $97, $4b, .lobyte(@env18), .hibyte(@env18), $80, $29, $97, $00, $99, $4b, .lobyte(@env11)
	.byte .hibyte(@env11), $4c, $88, $06, $97, $9b, $4b, .lobyte(@env18), .hibyte(@env18), $80, $29, $97, $4b, .lobyte(@env11)
	.byte .hibyte(@env11), $4c, $88, $0d, $97, $12, $99, $00, $97, $4b, .lobyte(@env18), .hibyte(@env18), $80, $29, $97, $4b
	.byte .lobyte(@env11), .hibyte(@env11), $4c, $88, $0d, $99, $0a, $97, $0b, $99, $17, $83, $00, $91, $4b, .lobyte(@env3), .hibyte(@env3)
	.byte $80, $28, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $12, $85, $00, $91, $12, $97, $4b, .lobyte(@env3), .hibyte(@env3)
	.byte $80, $28, $97, $00, $99, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $0b, $97, $9b, $4b, .lobyte(@env3), .hibyte(@env3)
	.byte $80, $28, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $12, $97, $17, $99, $00, $97, $4b, .lobyte(@env3), .hibyte(@env3)
	.byte $80, $28, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $12, $99, $0b, $97, $05, $99, $11, $83, $00, $91, $4b
	.byte .lobyte(@env3), .hibyte(@env3), $80, $27, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $0c, $85, $00, $91
	.byte $0c, $97, $4b, .lobyte(@env3), .hibyte(@env3), $80, $27, $97, $00, $99, $4b, .lobyte(@env11), .hibyte(@env11), $4c
	.byte $88, $05, $97, $9b, $4b, .lobyte(@env3), .hibyte(@env3), $80, $27, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c
	.byte $88, $0c, $97, $11, $99, $00, $97, $4b, .lobyte(@env3), .hibyte(@env3), $80, $27, $97, $4b, .lobyte(@env11), .hibyte(@env11)
	.byte $4c, $88, $0c, $99, $09, $97, $0a, $99, $16, $83, $00, $91, $4b, .lobyte(@env2), .hibyte(@env2), $80, $26, $97, $4b
	.byte .lobyte(@env11), .hibyte(@env11), $4c, $88, $11, $85, $00, $91, $11, $97, $4b, .lobyte(@env2), .hibyte(@env2), $80
	.byte $26, $97, $00, $99, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $0a, $97, $9b, $4b, .lobyte(@env2), .hibyte(@env2)
	.byte $80, $26, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $11, $97, $16, $99, $00, $97, $4b, .lobyte(@env2), .hibyte(@env2)
	.byte $80, $26, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $11, $99, $0e, $97, $0f, $99, $1b, $83, $00, $91, $4b
	.byte .lobyte(@env3), .hibyte(@env3), $80, $25, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $16, $85, $00, $91
	.byte $16, $97, $4b, .lobyte(@env3), .hibyte(@env3), $80, $25, $97, $00, $99, $4b, .lobyte(@env11), .hibyte(@env11), $4c
	.byte $88, $0f, $97, $9b, $4b, .lobyte(@env3), .hibyte(@env3), $80, $25, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c
	.byte $88, $16, $97, $1b, $99, $00, $97, $4b, .lobyte(@env3), .hibyte(@env3), $80, $25, $97, $4b, .lobyte(@env11), .hibyte(@env11)
	.byte $4c, $88, $0f, $99, $0a, $97, $08, $99, $14, $83, $00, $91, $4b, .lobyte(@env1), .hibyte(@env1), $80, $27, $97, $4b
	.byte .lobyte(@env11), .hibyte(@env11), $4c, $88, $0f, $85, $00, $91, $0f, $97, $4b, .lobyte(@env1), .hibyte(@env1), $80
	.byte $27, $97, $00, $99, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $08, $97, $9b, $4b, .lobyte(@env1), .hibyte(@env1)
	.byte $80, $27, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $0f, $97, $14, $99, $00, $97, $4b, .lobyte(@env1), .hibyte(@env1)
	.byte $80, $27, $97, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $88, $0b, $99, $0c, $97, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $8c
@song0ref1176:
	.byte $0d, $99, $19, $83, $00, $ab, $14, $85, $00, $91, $14, $97, $00, $b3, $0d, $97, $9b, $00, $97, $14, $97, $19, $99, $00
	.byte $b1, $14, $99, $11, $97
	.byte $41, $1d
	.word @song0ref1176
	.byte $06, $99, $12, $83, $00, $ab, $0d, $85, $00, $91, $0d, $97, $00, $b3, $06, $97, $9b, $00, $97, $0d, $97, $12, $99, $00
	.byte $b1, $0d, $99, $0a, $97, $0b, $99, $17, $83, $00, $ab, $12, $85, $00, $91, $12, $97, $00, $b3, $0b, $97, $9b, $00, $97
	.byte $12, $97, $17, $99, $00, $b1, $12, $99, $0b, $97, $05, $99, $11, $83, $00, $ab, $0c, $85, $00, $91, $0c, $97, $00, $b3
	.byte $05, $97, $9b, $00, $97, $0c, $97, $11, $99, $00, $b1, $0c, $99, $09, $97, $0a, $99, $16, $83, $00, $ab, $11, $85, $00
	.byte $91, $11, $97, $00, $b3, $0a, $97, $9b, $00, $97, $11, $97, $16, $99, $00, $b1, $11, $99, $0e, $97, $0f, $99, $1b, $83
	.byte $00, $ab, $16, $85, $00, $91, $16, $97, $00, $b3, $0f, $97, $9b, $00, $97, $16, $97, $1b, $99, $00, $b1, $0f, $99, $0a
	.byte $97, $08, $99, $14, $83, $00, $ab, $0f, $85, $00, $91, $0f, $97, $00, $b3, $08, $97, $9b, $00, $97, $0f, $97, $14, $99
	.byte $00, $b1, $0b, $99, $0c, $97, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref1386:
	.byte $7f, $82, $32, $8b, $74, $32, $8b, $7f, $32, $89, $74, $32, $8b, $7f, $84, $32, $8b, $74, $32, $89, $7f, $82, $32, $8b
	.byte $74, $32, $8b, $7f, $32, $89, $74, $32, $8b, $7f, $84, $32, $8b, $74, $32, $89, $7f, $82, $32, $8b, $74, $32, $8b, $7f
	.byte $84, $32, $89, $74, $32, $8b
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $41, $20
	.word @song0ref1386
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref1489:
	.byte $01, $8b, $00, $bf, $01, $8b, $00, $bf, $01, $8b, $00, $a5, $01, $8b, $00, $bf, $01, $8b, $00, $bf, $01, $8b, $00, $a5
	.byte $41, $18
	.word @song0ref1489
	.byte $41, $18
	.word @song0ref1489
	.byte $41, $18
	.word @song0ref1489
	.byte $41, $18
	.word @song0ref1489
	.byte $41, $18
	.word @song0ref1489
	.byte $41, $18
	.word @song0ref1489
	.byte $41, $18
	.word @song0ref1489
	.byte $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
@song0ref1538:
	.byte $ff, $d5, $ff, $d5, $ff, $d5, $ff, $d5, $ff, $d5, $ff, $d5, $ff, $d5, $ff, $d5
	.byte $41, $10
	.word @song0ref1538
	.byte $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $41, $10
	.word @song0ref1538
	.byte $41, $10
	.word @song0ref1538
	.byte $42
	.word @song0ch6loop
