; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Arpeggios are used, you must set FAMISTUDIO_USE_ARPEGGIO = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_enter_in_a_pipe=music_data_enter_in_a_pipe
.endif

music_data_enter_in_a_pipe:
	.byte 1
	.word @instruments
	.word @samples-5
; 00 : Enter in a pipe
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_enter_in_a_pipe
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env11,@env14,@env3,@env7 ; 00 : DPCM
	.word @env5,@env6,@env8,@env0 ; 01 : 12.5% Pulse
	.word @env4,@env6,@env8,@env0 ; 02 : Closed Hat
	.word @env13,@env6,@env8,@env0 ; 03 : Open Hat
	.word @env5,@env6,@env2,@env0 ; 04 : Overworld lead
	.word @env12,@env6,@env8,@env0 ; 05 : 08 Crash

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$bd,$b9,$00,$00
@env2:
	.byte $c2,$c1,$00,$01
@env3:
	.byte $c2,$c0,$00,$01
@env4:
	.byte $00,$cc,$c9,$c4,$c2,$c1,$06,$c0,$00,$07
@env5:
	.byte $00,$cf,$7f,$00,$02
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $00,$bd,$7f,$00,$02
@env8:
	.byte $7f,$00,$00
@env9:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env10:
	.byte $00,$c0,$b8,$b8,$c0,$c8,$c8,$00,$01
@env11:
	.byte $00,$ce,$7f,$00,$02
@env12:
	.byte $00,$cf,$ce,$03,$cd,$06,$cc,$cc,$cb,$04,$ca,$03,$c9,$c9,$c8,$02,$c7,$04,$c6,$04,$c5,$c5,$c4,$04,$c3,$02,$c2,$07,$c1,$00,$1c
@env13:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c5,$c4,$c4,$c3,$02,$c2,$06,$c1,$00,$0e
@env14:
	.byte $cc,$c0,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0d,$0d,$40,$01 ; 00 Punch Kick (Pitch:13)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $4e, $fd, $88, $18, $9b, $1b, $8d, $00, $8b, $1f, $9b, $20, $85, $00, $85, $1f, $8b, $49, .lobyte(@env10), .hibyte(@env10)
	.byte $9d, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $20, $85, $00, $85, $1f, $8b, $22, $85, $00, $85, $1f, $8b, $20
	.byte $85, $00, $85, $1f, $8b, $48, $00, $8d, $18, $83, $00, $85, $24, $9b, $18, $85, $00, $85, $22, $9b, $18, $83, $00, $85
	.byte $20, $9b, $18, $85, $00, $85, $1f, $9b, $49, .lobyte(@env9), .hibyte(@env9), $a9, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $00
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $c7, $42
	.word @song0ch0loop
@song0ch1:
	.byte $4e, $fc, $80, $11, $9b, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $8d, $4b, .lobyte(@env6), .hibyte(@env6), $4c
	.byte $80, $1d, $8b, $00, $8d, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $8b, $4b, .lobyte(@env6), .hibyte(@env6), $4c
	.byte $80, $11, $9b, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $9b, $4b, .lobyte(@env6), .hibyte(@env6), $4c, $80, $11
	.byte $8d, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $8b, $4b, .lobyte(@env6), .hibyte(@env6), $4c, $80, $1d, $8d, $11
	.byte $8b, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $8d, $4b, .lobyte(@env6), .hibyte(@env6), $4c, $80, $11, $85, $00
	.byte $83, $ff, $ef
@song0ch1loop:
	.byte $4c, $c7, $42
	.word @song0ch1loop
@song0ch2:
	.byte $4e, $fc, $80, $11, $9b, $00, $8d, $1d, $8b, $00, $9b, $11, $9b, $00, $9b, $11, $8d, $00, $8b, $1d, $8d, $11, $8b, $00
	.byte $8d, $11, $85, $00, $83, $ff, $ef
@song0ch2loop:
	.byte $c7, $42
	.word @song0ch2loop
@song0ch3:
@song0ref209:
	.byte $84, $31, $9b, $86, $31, $9b, $84, $31, $9b, $86, $31, $9b
	.byte $41, $08
	.word @song0ref209
	.byte $8a, $31, $ff, $b1, $00, $b9
@song0ch3loop:
	.byte $c7, $42
	.word @song0ch3loop
@song0ch4:
@song0ref235:
	.byte $01, $9b, $00, $9b, $01, $9b, $00, $9b
	.byte $41, $08
	.word @song0ref235
	.byte $01, $9b, $00, $ff, $cf
@song0ch4loop:
	.byte $c7, $42
	.word @song0ch4loop
@song0ch5:
	.byte $ff, $ef, $ff, $ef
@song0ch5loop:
	.byte $c7, $42
	.word @song0ch5loop
@song0ch6:
	.byte $ff, $ef, $ff, $ef
@song0ch6loop:
	.byte $c7, $42
	.word @song0ch6loop
