; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_cloud=music_data_cloud
.endif

music_data_cloud:
	.byte 1
	.word @instruments
	.word @samples-5
; 00 : Cloud
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_cloud
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env6,@env5,@env7,@env0 ; 00 : Noise short
	.word @env2,@env5,@env7,@env0 ; 01 : Noise long
	.word @env13,@env1,@env11,@env0 ; 02 : SqWoobble
	.word @env3,@env5,@env8,@env0 ; 03 : Instrumental 2
	.word @env10,@env4,@env8,@env0 ; 04 : Death effect
	.word @env9,@env5,@env12,@env0 ; 05 : Long instrumental

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $cc,$cc,$c0,$c0,$00,$00
@env2:
	.byte $00,$cf,$04,$c0,$00,$03
@env3:
	.byte $00,$cc,$02,$ca,$c3,$c3,$c2,$c0,$00,$07
@env4:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$0a
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $00,$cf,$c0,$00,$02
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $c2,$7f,$00,$00
@env9:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env10:
	.byte $00,$ce,$cc,$cb,$ca,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$0b
@env11:
	.byte $c1,$7f,$00,$00
@env12:
	.byte $c0,$c2,$00,$01
@env13:
	.byte $0c,$ca,$c6,$c7,$c7,$c5,$c7,$c2,$04,$c1,$00,$09,$c1,$c0,$0f,$c0,$00,$0f

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7b, $84
@song0ref7:
	.byte $20, $a1, $20, $a1, $20, $a1, $1d, $8f, $20, $a1, $20, $a1, $1d, $8f, $20, $8f, $1d, $8f, $20, $a1, $48, $20, $a1, $20
	.byte $a1, $20, $a1, $1b, $8f, $20, $a1, $20, $a1, $1b, $8f, $20, $8f, $1b, $8f, $20, $a1, $48
	.byte $41, $28
	.word @song0ref7
@song0ref52:
	.byte $48, $a3, $00, $95, $76, $86
@song0ref58:
	.byte $27, $8f, $29, $8f, $2c, $8f, $00, $8f, $2c, $89, $00, $dd, $27, $89, $2c, $8f, $00, $8f, $48, $eb, $72, $88, $38, $a1
	.byte $74, $84, $14, $ff, $8d
	.byte $41, $1b
	.word @song0ref52
	.byte $41, $1b
	.word @song0ref52
	.byte $41, $1b
	.word @song0ref52
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $7b, $84
@song0ref102:
	.byte $25, $a1, $25, $a1, $25, $b3, $27, $8f, $00, $8f, $27, $b3, $27, $a1, $27, $a1, $24, $a1, $24, $a1, $24, $b3, $24, $8f
	.byte $00, $8f, $24, $b3, $24, $a1, $24, $a1
	.byte $41, $20
	.word @song0ref102
	.byte $a3, $00, $95, $79
	.byte $41, $12
	.word @song0ref58
@song0ref144:
	.byte $33, $8f, $2e, $8f, $00, $8f, $30, $8f, $00, $a1, $72, $1b
@song0ref156:
	.byte $83, $73, $85, $85, $74, $85, $85, $75, $85, $85, $76, $85, $85, $77, $85, $85, $78, $85, $85, $79, $85, $85, $78, $a9
	.byte $77, $85, $76, $85, $85, $75, $85, $85, $74, $85, $85, $73, $85, $a3, $00, $95, $79
	.byte $41, $12
	.word @song0ref58
	.byte $2c, $8f, $00, $d7, $72, $18
	.byte $41, $1b
	.word @song0ref156
	.byte $79
	.byte $41, $12
	.word @song0ref58
	.byte $41, $26
	.word @song0ref144
	.byte $79
	.byte $41, $12
	.word @song0ref58
	.byte $2c, $8f, $00, $d7, $72, $18
	.byte $41, $18
	.word @song0ref156
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $8a
@song0ref234:
	.byte $0d, $a1, $25, $a1, $0d, $a1, $25, $a1, $0f, $a1, $27, $a1, $0f, $a1, $27, $a1, $14, $a1, $20, $a1, $14, $a1, $20, $a1
	.byte $14, $a1, $20, $a1, $14, $a1, $20, $a1
	.byte $41, $20
	.word @song0ref234
	.byte $41, $20
	.word @song0ref234
	.byte $41, $20
	.word @song0ref234
	.byte $41, $20
	.word @song0ref234
	.byte $41, $20
	.word @song0ref234
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $7f, $80
@song0ref287:
	.byte $15, $a1, $79, $1e, $95, $1e, $89, $76, $82, $1e, $a1, $78, $80, $1e, $95, $1e, $89, $7f, $15, $a1, $79, $1e, $95, $1e
	.byte $89, $76, $82, $1e, $a1, $78, $80, $1e, $95, $1e, $89, $7f
	.byte $41, $18
	.word @song0ref287
	.byte $7f
	.byte $41, $18
	.word @song0ref287
	.byte $7f
	.byte $41, $18
	.word @song0ref287
	.byte $7f
	.byte $41, $18
	.word @song0ref287
	.byte $7f
	.byte $41, $18
	.word @song0ref287
	.byte $7f
	.byte $41, $18
	.word @song0ref287
@song0ref346:
	.byte $15, $a1, $1e, $95, $1e, $89, $79, $82, $1e, $a1, $7f, $80, $1e, $95, $1e, $89, $15, $a1, $1e, $95, $1e, $89, $79, $82
	.byte $1e, $a1, $7f, $80, $1e, $95, $1e, $89
	.byte $41, $18
	.word @song0ref287
	.byte $7f
	.byte $41, $18
	.word @song0ref287
	.byte $7f
	.byte $41, $18
	.word @song0ref287
	.byte $41, $18
	.word @song0ref346
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref396:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $41, $12
	.word @song0ref396
	.byte $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $41, $12
	.word @song0ref396
	.byte $41, $12
	.word @song0ref396
	.byte $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $41, $12
	.word @song0ref396
	.byte $41, $12
	.word @song0ref396
	.byte $42
	.word @song0ch6loop
