; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Arpeggios are used, you must set FAMISTUDIO_USE_ARPEGGIO = 1.
; Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_neonlights=music_data_neonlights
.endif

music_data_neonlights:
	.byte 14
	.word @instruments
	.word @samples-5
; 00 : Overworld
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Underworld
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word @song1ch5
	.word @song1ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : Waterworld
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word @song2ch5
	.word @song2ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 03 : Castleworld
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word @song3ch5
	.word @song3ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 04 : Cloud
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word @song4ch5
	.word @song4ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 05 : Enter in a pipe
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.word @song5ch5
	.word @song5ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 06 : Starman
	.word @song6ch0
	.word @song6ch1
	.word @song6ch2
	.word @song6ch3
	.word @song6ch4
	.word @song6ch5
	.word @song6ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 07 : Death
	.word @song7ch0
	.word @song7ch1
	.word @song7ch2
	.word @song7ch3
	.word @song7ch4
	.word @song7ch5
	.word @song7ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 08 : Game Over
	.word @song8ch0
	.word @song8ch1
	.word @song8ch2
	.word @song8ch3
	.word @song8ch4
	.word @song8ch5
	.word @song8ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 09 : You saved the princess
	.word @song9ch0
	.word @song9ch1
	.word @song9ch2
	.word @song9ch3
	.word @song9ch4
	.word @song9ch5
	.word @song9ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 0a : In an other castle
	.word @song10ch0
	.word @song10ch1
	.word @song10ch2
	.word @song10ch3
	.word @song10ch4
	.word @song10ch5
	.word @song10ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 0b : Victory
	.word @song11ch0
	.word @song11ch1
	.word @song11ch2
	.word @song11ch3
	.word @song11ch4
	.word @song11ch5
	.word @song11ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 0c : Hurry up
	.word @song12ch0
	.word @song12ch1
	.word @song12ch2
	.word @song12ch3
	.word @song12ch4
	.word @song12ch5
	.word @song12ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 0d : New Song
	.word @song13ch0
	.word @song13ch1
	.word @song13ch2
	.word @song13ch3
	.word @song13ch4
	.word @song13ch5
	.word @song13ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_neonlights
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env14,@env20,@env27,@env0 ; 00 : Closed Hat
	.word @env16,@env20,@env27,@env0 ; 01 : 12.5% Pulse
	.word @env47,@env20,@env27,@env0 ; 02 : Open Hat
	.word @env44,@env48,@env9,@env22 ; 03 : DPCM
	.word @env43,@env25,@env27,@env0 ; 04 : SS Noise snare(D3)
	.word @env16,@env20,@env29,@env0 ; 05 : 50% Pulse
	.word @env16,@env48,@env9,@env13 ; 06 : Bass
	.word @env21,@env20,@env27,@env0 ; 07 : Noise short
	.word @env17,@env20,@env27,@env0 ; 08 : Noise long
	.word @env16,@env20,@env8,@env0 ; 09 : Overworld lead
	.word @env16,@env20,@env35,@env0 ; 0a : 25% Pulse
	.word @env45,@env20,@env26,@env0 ; 0b : Lead 2
	.word @env46,@env20,@env27,@env0 ; 0c : 08 Crash
	.word @env31,@env20,@env37,@env0 ; 0d : Long instrumental
	.word @env38,@env10,@env35,@env0 ; 0e : SqWoobble
	.word @env33,@env19,@env29,@env0 ; 0f : Death effect
	.word @env18,@env20,@env29,@env0 ; 10 : Instrumental 2
	.word @env24,@env20,@env27,@env0 ; 11 : 09 Layered Crash
	.word @env42,@env20,@env29,@env0 ; 12 : Death instrument
	.word @env3,@env32,@env27,@env0 ; 13 : Instrument 1
	.word @env12,@env20,@env27,@env0 ; 14 : Drums Sus
	.word @env23,@env19,@env29,@env0 ; 15 : Death effect 2
	.word @env30,@env20,@env29,@env0 ; 16 : Instrumental
	.word @env15,@env20,@env27,@env0 ; 17 : Triangle

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$bd,$b6,$00,$00
@env2:
	.byte $00,$c0,$b5,$b5,$c0,$cb,$cb,$00,$01
@env3:
	.byte $00,$cf,$04,$cb,$c6,$c2,$c0,$00,$06
@env4:
	.byte $00,$c0,$ba,$b7,$ba,$c0,$c6,$c9,$c6,$00,$01
@env5:
	.byte $c0,$bd,$ba,$00,$00
@env6:
	.byte $c0,$bd,$b9,$00,$00
@env7:
	.byte $00,$c0,$bd,$bd,$c0,$c3,$c3,$00,$01
@env8:
	.byte $c2,$c1,$00,$01
@env9:
	.byte $c2,$c0,$00,$01
@env10:
	.byte $cc,$cc,$c0,$c0,$00,$00
@env11:
	.byte $c0,$bb,$b7,$00,$00
@env12:
	.byte $00,$ce,$cc,$ca,$c8,$c6,$c3,$c2,$00,$07
@env13:
	.byte $00,$bf,$7f,$00,$02
@env14:
	.byte $00,$cc,$c9,$c4,$c2,$c1,$06,$c0,$00,$07
@env15:
	.byte $00,$cf,$07,$c0,$00,$03
@env16:
	.byte $00,$cf,$7f,$00,$02
@env17:
	.byte $00,$cf,$04,$c0,$00,$03
@env18:
	.byte $00,$cc,$02,$ca,$c3,$c3,$c2,$c0,$00,$07
@env19:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$0a
@env20:
	.byte $c0,$7f,$00,$01
@env21:
	.byte $00,$cf,$c0,$00,$02
@env22:
	.byte $00,$bd,$7f,$00,$02
@env23:
	.byte $00,$c8,$c4,$c0,$00,$03
@env24:
	.byte $00,$cf,$cd,$cc,$03,$cb,$02,$ca,$c9,$02,$c8,$c8,$cf,$ce,$cc,$cb,$c9,$03,$c8,$03,$c7,$02,$ce,$cb,$c6,$05,$c5,$c5,$c4,$04,$c3,$02,$c2,$07,$c1,$00,$22
@env25:
	.byte $c0,$c1,$c2,$00,$02
@env26:
	.byte $c3,$c2,$00,$01
@env27:
	.byte $7f,$00,$00
@env28:
	.byte $00,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$00,$01
@env29:
	.byte $c2,$7f,$00,$00
@env30:
	.byte $00,$cf,$cf,$cd,$cb,$c9,$c9,$c8,$c6,$c0,$00,$09
@env31:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env32:
	.byte $c0,$bc,$b4,$a8,$00,$03
@env33:
	.byte $00,$ce,$cc,$cb,$ca,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$0b
@env34:
	.byte $00,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$00,$01
@env35:
	.byte $c1,$7f,$00,$00
@env36:
	.byte $c0,$bc,$b9,$00,$00
@env37:
	.byte $c0,$c2,$00,$01
@env38:
	.byte $0c,$ca,$c6,$c7,$c7,$c5,$c7,$c2,$04,$c1,$00,$09,$c1,$c0,$0f,$c0,$00,$0f
@env39:
	.byte $c0,$bc,$b7,$00,$00
@env40:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env41:
	.byte $00,$c0,$b8,$b8,$c0,$c8,$c8,$00,$01
@env42:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c6,$c5,$c3,$c2,$c1,$c0,$00,$0c
@env43:
	.byte $00,$cf,$c9,$04,$c7,$04,$c5,$04,$c3,$00,$08
@env44:
	.byte $00,$ce,$7f,$00,$02
@env45:
	.byte $00,$cd,$7f,$00,$02
@env46:
	.byte $00,$cf,$ce,$03,$cd,$06,$cc,$cc,$cb,$04,$ca,$03,$c9,$c9,$c8,$02,$c7,$04,$c6,$04,$c5,$c5,$c4,$04,$c3,$02,$c2,$07,$c1,$00,$1c
@env47:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c5,$c4,$c4,$c3,$02,$c2,$06,$c1,$00,$0e
@env48:
	.byte $cc,$c0,$00,$01
@env49:
	.byte $00,$c0,$bd,$bc,$bd,$bf,$c1,$c3,$c4,$c3,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e5,$09,$40,$00 ; 00 bass (Pitch:9)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e5,$0a,$40,$00 ; 01 bass (Pitch:10)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e5,$0c,$40,$00 ; 02 bass (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e5,$0e,$40,$00 ; 03 bass (Pitch:14)
	.byte $3a+.lobyte(FAMISTUDIO_DPCM_PTR),$da,$08,$40,$00 ; 04 bass 2 (Pitch:8)
	.byte $3a+.lobyte(FAMISTUDIO_DPCM_PTR),$da,$09,$40,$00 ; 05 bass 2 (Pitch:9)
	.byte $3a+.lobyte(FAMISTUDIO_DPCM_PTR),$da,$0b,$40,$00 ; 06 bass 2 (Pitch:11)
	.byte $3a+.lobyte(FAMISTUDIO_DPCM_PTR),$da,$0c,$40,$00 ; 07 bass 2 (Pitch:12)
	.byte $3a+.lobyte(FAMISTUDIO_DPCM_PTR),$da,$0d,$40,$00 ; 08 bass 2 (Pitch:13)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0d,$0d,$40,$01 ; 09 Punch Kick (Pitch:13)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48
	.byte $41, $0a
	.word @song0ref5
	.byte $48
	.byte $41, $0a
	.word @song0ref5
	.byte $48
	.byte $41, $0a
	.word @song0ref5
	.byte $48
	.byte $41, $0a
	.word @song0ref5
	.byte $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref48:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $41, $0a
	.word @song0ref48
	.byte $41, $0a
	.word @song0ref48
	.byte $41, $0a
	.word @song0ref48
	.byte $41, $0a
	.word @song0ref48
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $4e, $fc, $86
@song0ref83:
	.byte $0f, $9b, $00, $8d, $1b, $8b, $00, $9b, $0f, $9b, $00, $9b, $0f, $8d, $00, $8b, $1b, $8d, $0f, $8b, $00, $8d, $0f, $85
	.byte $00, $83, $4e, $fc
	.byte $41, $1a
	.word @song0ref83
@song0ref114:
	.byte $08, $9b, $00, $8d, $14, $8b, $00, $9b, $08, $9b, $00, $9b, $08, $8d, $00, $8b, $14, $8d, $08, $8b, $00, $8d, $08, $85
	.byte $00, $83, $0d, $9b, $00, $8d, $19, $8b, $00, $9b, $0d, $9b, $00, $9b, $0d, $8d, $00, $8b, $19, $8d, $0d, $8b, $00, $8d
	.byte $0d, $85, $00, $83, $07, $9b, $00, $8d, $13, $8b, $00, $9b, $07, $9b, $00, $9b, $07, $8d, $00, $8b, $13, $8d, $07, $8b
	.byte $00, $8d, $07, $85, $00, $83, $0c, $9b, $00, $8d, $18, $8b, $00, $9b, $0c, $9b, $00, $9b, $0c, $8d, $00, $8b, $18, $8d
	.byte $0c, $8b, $00, $8d, $0c, $85, $00, $83
@song0ref218:
	.byte $11, $9b, $00, $8d, $1d, $8b, $00, $9b, $11, $9b, $00, $9b, $11, $8d, $00, $8b, $1d, $8d, $11, $8b, $00, $8d, $11, $85
	.byte $00, $83, $0a, $9b, $00, $8d, $16, $8b, $00, $9b, $0a, $9b, $00, $9b, $0a, $8d, $00, $8b, $16, $8d, $0a, $8b, $00, $8d
	.byte $0a, $85, $00, $83, $4e, $fc
	.byte $41, $1a
	.word @song0ref83
	.byte $4e, $fc
	.byte $41, $1a
	.word @song0ref83
	.byte $41, $9c
	.word @song0ref114
	.byte $4e, $fc
	.byte $41, $1a
	.word @song0ref83
	.byte $4e, $fc
	.byte $41, $1a
	.word @song0ref83
	.byte $41, $9c
	.word @song0ref114
	.byte $41, $34
	.word @song0ref114
	.byte $41, $1a
	.word @song0ref218
@song0ref302:
	.byte $ff, $d1, $0d, $89, $00, $81, $0e, $87, $00, $81, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $a2, $31, $d7
@song0ref319:
	.byte $84, $31, $9b
@song0ref322:
	.byte $80, $31, $9b, $84, $31, $9b, $80, $31, $9b, $84, $31, $9b, $80, $31, $9b
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $84, $31, $9b
@song0ref367:
	.byte $a2, $31, $b9
@song0ref370:
	.byte $88, $1b, $9b, $84, $31, $9b, $80, $31, $9b, $84, $31, $9b, $88, $1b, $9b, $84, $31, $9b, $80, $31, $9b, $84, $31, $9b
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $0c
	.word @song0ref370
	.byte $41, $12
	.word @song0ref367
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $0c
	.word @song0ref370
	.byte $98, $31, $ff, $b1, $00, $b9, $ff, $ef
	.byte $41, $0a
	.word @song0ref322
	.byte $84, $31, $9b, $80, $31, $9b, $84, $31, $9b, $98, $31, $ff, $b1, $00, $8d, $88, $1b, $81, $00, $81, $1b, $00, $81, $1b
	.byte $85, $00, $85, $1b, $85, $00, $83, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref485:
	.byte $0a, $9b, $00, $9b, $0a, $9b, $00, $9b, $0a, $9b, $00, $9b
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
@song0ref590:
	.byte $0a, $9b, $00, $b9, $0a, $9b, $00, $b9, $0a, $9b, $00, $9b
	.byte $41, $0c
	.word @song0ref590
	.byte $41, $0c
	.word @song0ref485
	.byte $0a, $9b, $00, $9b, $0a, $9b, $00, $ff, $a3, $0a, $81, $00, $81, $0a, $00, $81, $0a, $8d, $0a, $8b, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $4c
	.byte $41, $0a
	.word @song0ref48
	.byte $ff, $ef, $ff, $ef, $ff, $ef
@song0ref642:
	.byte $7e, $4e, $fd, $86
@song0ref646:
	.byte $0f, $9b, $4b, .lobyte(@env11), .hibyte(@env11), $82, $2b, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86, $1b
	.byte $8b, $00, $8d, $4b, .lobyte(@env11), .hibyte(@env11), $82, $2b, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86
	.byte $0f, $9b, $4b, .lobyte(@env11), .hibyte(@env11), $82, $2b, $9b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86, $0f
	.byte $8d, $4b, .lobyte(@env11), .hibyte(@env11), $82, $2b, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86, $1b, $8d
	.byte $0f, $8b, $4b, .lobyte(@env11), .hibyte(@env11), $82, $2b, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86, $0f
	.byte $85, $00, $83, $0f, $9b, $4b, .lobyte(@env39), .hibyte(@env39), $82, $29, $8d, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $1b, $8b, $00, $8d, $4b, .lobyte(@env39), .hibyte(@env39), $82, $29, $8b, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $0f, $9b, $4b, .lobyte(@env39), .hibyte(@env39), $82, $29, $9b, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $0f, $8d, $4b, .lobyte(@env39), .hibyte(@env39), $82, $29, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86
	.byte $1b, $8d, $0f, $8b, $4b, .lobyte(@env39), .hibyte(@env39), $82, $29, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $0f, $85, $00, $83
@song0ref792:
	.byte $08, $9b, $4b, .lobyte(@env36), .hibyte(@env36), $82, $2b, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86, $14
	.byte $8b, $00, $8d, $4b, .lobyte(@env36), .hibyte(@env36), $82, $2b, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86
	.byte $08, $9b, $4b, .lobyte(@env36), .hibyte(@env36), $82, $2b, $9b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86, $08
	.byte $8d, $4b, .lobyte(@env36), .hibyte(@env36), $82, $2b, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86, $14, $8d
	.byte $08, $8b, $4b, .lobyte(@env36), .hibyte(@env36), $82, $2b, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86, $08
	.byte $85, $00, $83, $0d, $9b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $2a, $8d, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $19, $8b, $00, $8d, $4b, .lobyte(@env6), .hibyte(@env6), $82, $2a, $8b, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $0d, $9b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $2a, $9b, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $0d, $8d, $4b, .lobyte(@env6), .hibyte(@env6), $82, $2a, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86
	.byte $19, $8d, $0d, $8b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $2a, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $0d, $85, $00, $83, $07, $9b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $8d, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $13, $8b, $00, $8d, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $8b, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $07, $9b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $9b, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $07, $8d, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86
	.byte $13, $8d, $07, $8b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $07, $85, $00, $83, $0c, $9b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $28, $8d, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $18, $8b, $00, $8d, $4b, .lobyte(@env5), .hibyte(@env5), $82, $28, $8b, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $0c, $9b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $28, $9b, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $0c, $8d, $4b, .lobyte(@env5), .hibyte(@env5), $82, $28, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86
	.byte $18, $8d, $0c, $8b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $28, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $0c, $85, $00, $83, $11, $9b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $27, $8d, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $1d, $8b, $00, $8d, $4b, .lobyte(@env6), .hibyte(@env6), $82, $27, $8b, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $11, $9b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $27, $9b, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $11, $8d, $4b, .lobyte(@env6), .hibyte(@env6), $82, $27, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86
	.byte $1d, $8d, $11, $8b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $27, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $11, $85, $00, $83, $0a, $9b, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $8d, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $16, $8b, $00, $8d, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $8b, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $0a, $9b, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $9b, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $0a, $8d, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86
	.byte $16, $8d, $0a, $8b, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $0a, $85, $00, $83, $4e, $fd
	.byte $41, $e0
	.word @song0ref646
	.byte $41, $38
	.word @song0ref792
	.byte $11, $9b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86, $1d
	.byte $8b, $00, $8d, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86
	.byte $11, $9b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $9b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86, $11
	.byte $8d, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86, $1d, $8d
	.byte $11, $8b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86, $11
	.byte $85, $00, $83
	.byte $41, $0a
	.word @song0ref302
	.byte $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $4c
	.byte $41, $e0
	.word @song0ref642
	.byte $4e, $fd, $9d, $92, $26, $83, $94, $50, $f4, $32, $33, $83, $27, $9f, $92, $24, $8b, $22, $9b, $20, $8d, $00, $8b, $1f
	.byte $9b, $1b, $8d, $00, $8b, $1d, $85, $00, $85, $1e, $85, $49, .lobyte(@env2), .hibyte(@env2), $85, $8f, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $92, $27, $8b, $29, $8d, $27, $8b, $2a, $8d, $00, $8b, $29, $9b, $27, $8d, $00, $8b, $23, $8d
	.byte $22, $8b, $49, .lobyte(@env41), .hibyte(@env41), $9d, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $20, $8d, $00
	.byte $8b, $1b, $9b, $18, $8d, $00, $8b, $1b, $8d, $1d, $8b, $00, $8d, $1e, $85, $94, $50, $f4, $2a, $2b, $83, $49, .lobyte(@env7)
	.byte .hibyte(@env7), $1f, $9b, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $1d, $8d, $00, $8b, $1b, $8b, $00, $8d, $18
	.byte $85, $00, $85, $1b, $83, $00, $85, $17, $9b, $1b, $8d, $00, $8b, $1d, $8d, $1b, $8b, $00, $8d, $1d, $85, $94, $50, $f3
	.byte $29, $2a, $83, $49, .lobyte(@env7), .hibyte(@env7), $1e, $9b, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $1d, $8d
	.byte $00, $8b, $17, $95, $00, $83, $16, $85, $00, $85, $17, $83, $00, $85
@song0ref1492:
	.byte $18, $9b, $1b, $8d, $00, $8b, $1f, $9b, $20, $85, $00, $85, $1f, $8b, $49, .lobyte(@env41), .hibyte(@env41), $9d, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $92, $20, $85, $00, $85, $1f, $8b, $22, $85, $00, $85, $1f, $8b, $20, $85, $00
	.byte $85, $1f, $8b, $00, $8d, $18, $83, $00, $85, $24, $9b, $18, $85, $00, $85, $22, $9b, $18, $83, $00, $85, $20, $9b, $18
	.byte $85, $00, $85, $1f, $9b, $49, .lobyte(@env40), .hibyte(@env40), $9d, $92, $1e, $83, $1d, $85, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $1b, $ff, $93, $1d, $c9, $1c, $83, $1b, $85, $1a, $9b, $00, $b9, $16, $9b, $1a, $9b, $1d, $8d, $00, $8b, $16, $b9
@song0ref1595:
	.byte $50, $f9, $28, $29, $8d, $94, $1d, $8b, $49, .lobyte(@env40), .hibyte(@env40), $bb, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $92, $1b, $9b, $49, .lobyte(@env40), .hibyte(@env40), $bb, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $16
	.byte $9b, $00, $9b
	.byte $41, $0c
	.word @song0ref1595
	.byte $1d, $8d, $94, $50, $f3, $29, $2b, $8b, $1f, $9b, $00, $9b, $92, $50, $0d, $2b, $29, $8d, $94, $1d, $8b, $49, .lobyte(@env4)
	.byte .hibyte(@env4), $f7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $d7, $92, $1b, $8d, $00, $8b, $1a, $8d, $00, $8b
	.byte $16, $8d, $00, $8b, $13, $8d, $00, $8b, $17, $85, $94, $50, $ee, $23, $24, $85, $18, $8b, $d9, $92, $1b, $85, $00, $83
	.byte $1d, $85, $00, $85, $1f, $85, $00, $83, $20, $85, $00, $85, $21, $85, $00, $85, $22, $a9, $1b, $8d, $00, $8b, $1d, $85
	.byte $1e, $85, $22, $85, $23, $83, $24, $9b, $27, $85, $00, $85, $24, $85, $00, $83, $1e, $9b, $1d, $9b, $18, $85, $00, $85
	.byte $1a, $81, $1b, $a5, $1d, $8d, $00, $8b, $13, $9b, $14, $8d, $00, $8b, $16, $9b, $18, $85, $00, $85, $16, $99, $1a, $85
	.byte $00, $85, $1b, $9b, $1d, $9b, $1f, $8d, $20, $83, $21, $85, $22, $9b, $27, $85, $00, $85, $26, $9b, $00, $8b, $1f, $9b
	.byte $49, .lobyte(@env41), .hibyte(@env41), $bb, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $1d, $8d, $00, $8b, $16
	.byte $8d, $00, $8b
	.byte $41, $0c
	.word @song0ref1595
	.byte $50, $f6, $22, $23, $8d, $94, $17, $8b, $49, .lobyte(@env40), .hibyte(@env40), $bb, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $92, $16, $9b, $49, .lobyte(@env40), .hibyte(@env40), $bb, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $14
	.byte $8d, $00, $8b, $16, $8d, $17, $8b
	.byte $41, $3b
	.word @song0ref1492
	.byte $49, .lobyte(@env40), .hibyte(@env40), $a9, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $42
	.word @song0ch6loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $99, $48, $ff, $ff, $99, $48, $ff, $ff, $99, $48
	.byte $ff, $ff, $99, $48, $7b, $4e, $01, $49, .lobyte(@env0), .hibyte(@env0), $4a, $96
@song1ref29:
	.byte $2c, $a1, $2a, $89, $00, $95, $2e, $87, $8a, $50, $fb, $3a, $3b, $83, $2f, $8f, $96, $2c, $89, $00, $89, $32, $a1, $33
	.byte $89, $32, $93, $2f, $89, $2c, $89, $2a, $89, $2c, $89, $26, $95, $00, $87, $48, $24, $85, $8a, $50, $fa, $30, $31, $87
	.byte $25, $8f, $96, $23, $89, $00, $95, $25, $93, $23, $89, $26, $95, $25, $a1, $23, $89, $20, $87, $00, $95, $1e, $89, $00
	.byte $95, $1f, $9f, $48, $20, $a1, $1e, $89, $00, $89, $20, $9f, $25, $89, $26, $89, $00, $95, $25, $a1, $28, $87, $00, $95
	.byte $2a, $a1, $2c, $89, $8a, $50, $0c, $38, $32, $93, $48, $96, $26, $89, $00, $89, $26, $89, $25, $89, $00, $89, $26, $89
	.byte $20, $89, $1e, $87, $20, $89, $23, $89, $25, $89, $26, $89, $27, $89, $23, $89, $20, $89, $27, $87, $20, $89, $27, $89
	.byte $2a, $89, $00, $95, $2b, $89, $00, $93, $48, $4e, $01, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $41, $86
	.word @song1ref29
	.byte $48, $7d, $2c, $89, $00, $89, $72, $2c, $87, $00, $75, $2c, $89, $00, $db, $7d, $2f, $89, $00, $89, $72, $2f, $87, $00
	.byte $75, $2f, $87, $00, $db, $48, $7d, $2e, $89, $00, $89, $72, $2e, $87, $00, $75, $2e, $89, $00, $db, $7d, $2d, $89, $00
	.byte $89, $72, $2d, $87, $00, $75, $2d, $87, $00, $db, $48, $7f, $a3, $26, $89, $8a, $50, $fd, $32, $33, $95, $27, $93, $49
	.byte .lobyte(@env40), .hibyte(@env40), $d3, $49, .lobyte(@env0), .hibyte(@env0), $4a, $96, $23, $87, $00, $95, $22, $a1
	.byte $20, $89, $00, $89, $22, $87, $48, $97, $23, $89, $20, $95, $49, .lobyte(@env40), .hibyte(@env40), $d1, $8a, $50, $18
	.byte $2c, $1e, $bd, $7e, $81, $7d, $81, $7c, $81, $7f, $12, $89, $00, $89, $96, $13, $ab, $48, $7b, $4e, $01, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a
	.byte $41, $86
	.word @song1ref29
	.byte $48, $79, $4f, $02, $82
@song1ref329:
	.byte $2c, $89, $00, $89, $74, $2c, $89, $79, $38, $89, $00, $89, $74, $38, $89, $79, $4f, $02, $2c, $89, $00, $87, $74, $2c
	.byte $89, $79, $38, $89, $00, $89, $74, $38, $89, $79, $4f, $02, $2b, $89, $00, $89, $74, $2b, $89, $79, $37, $87, $00, $89
	.byte $74, $37, $89, $79, $4f, $02, $2b, $89, $00, $89, $74, $2b, $89, $79, $37, $89, $00, $89, $74, $37, $87, $48, $79, $4f
	.byte $02, $28, $89, $00, $89, $74, $28, $89, $79, $34, $89, $00, $89, $74, $34, $89, $79, $4f, $02, $28, $89, $00, $87, $74
	.byte $28, $89, $79, $34, $89, $00, $89, $74, $34, $89, $79, $4f, $02, $27, $89, $00, $89, $74, $27, $89, $79, $33, $87, $00
	.byte $89, $74, $33, $89, $79, $4f, $02, $2a, $89, $00, $89, $74, $2a, $89, $79, $37, $89, $00, $89, $74, $37, $87, $48, $79
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref329
	.byte $48, $00, $ff, $ff, $97, $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
@song1ref487:
	.byte $ff
@song1ref488:
	.byte $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $ff, $d3, $7a, $86
@song1ref512:
	.byte $06, $89, $00, $89, $07, $ab, $4e, $07
@song1ref520:
	.byte $08, $a1, $00, $95, $08, $89, $14, $89, $00, $93, $12, $95, $14, $89, $00, $95, $08, $89, $0e, $9f, $0d, $a1, $0b, $9f
	.byte $04, $a1, $00, $95, $0d, $9f, $0b, $83, $00, $83, $0d, $89, $00, $89, $0e, $ad, $0d, $87, $00, $89, $0b, $89, $06, $89
	.byte $00, $89, $07, $ab
	.byte $41, $17
	.word @song1ref520
@song1ref575:
	.byte $95, $0d, $87, $0e, $89, $00, $89, $0e, $89, $00, $95, $0e, $89, $00, $93, $08, $89, $0e, $89, $00, $89, $0d, $ad, $0b
	.byte $87, $00, $95, $06, $89, $00, $89, $07, $ab, $00, $ff, $ff, $97, $ff, $ff, $99, $ff, $ff, $99, $ff, $d3
	.byte $41, $3a
	.word @song1ref512
	.byte $41, $17
	.word @song1ref520
	.byte $41, $2c
	.word @song1ref575
	.byte $ff, $99, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $a6
@song1ref636:
	.byte $25, $89, $00, $b9, $25, $89, $00, $b7, $25, $89, $00, $b7, $25, $89, $00, $b7
	.byte $41, $10
	.word @song1ref636
	.byte $41, $10
	.word @song1ref636
	.byte $25, $89, $00, $b9, $25, $89, $00, $ab, $25, $89, $00, $db, $25, $89
@song1ref672:
	.byte $25, $89, $00, $89, $25, $87, $4e, $00
@song1ref680:
	.byte $25, $89, $00, $b9, $25, $89, $00, $b7, $25, $89, $00, $b7, $25, $89, $00, $95
	.byte $41, $16
	.word @song1ref672
	.byte $41, $16
	.word @song1ref672
	.byte $41, $16
	.word @song1ref672
	.byte $41, $16
	.word @song1ref672
	.byte $41, $16
	.word @song1ref672
	.byte $41, $16
	.word @song1ref672
	.byte $41, $16
	.word @song1ref672
	.byte $25, $89, $00, $89, $25, $87, $4e, $07, $86
@song1ref726:
	.byte $14, $a1, $00, $95, $14, $89, $20, $89, $00, $93, $1e, $95, $20, $89, $00, $95, $14, $89, $1a, $9f, $19, $a1, $17, $9f
	.byte $10, $a1, $00, $95, $19, $9f, $17, $83, $00, $83, $19, $89, $00, $89, $1a, $ad, $19, $87, $00, $89, $17, $89, $12, $89
	.byte $00, $89, $13, $ab
	.byte $41, $17
	.word @song1ref726
	.byte $95, $19, $87, $1a, $89, $00, $89, $1a, $89, $00, $95, $1a, $89, $00, $93, $14, $89, $1a, $89, $00, $89, $19, $ad, $17
	.byte $87, $00, $95, $12, $89, $00, $89, $13, $ab, $4e, $00, $a6
	.byte $41, $10
	.word @song1ref680
	.byte $41, $16
	.word @song1ref672
	.byte $41, $16
	.word @song1ref672
	.byte $41, $16
	.word @song1ref672
	.byte $25, $89, $00, $89, $25, $87
	.byte $41, $10
	.word @song1ref636
	.byte $41, $10
	.word @song1ref636
	.byte $ff, $ff, $99, $ff, $eb, $25, $89, $25, $89, $00, $89, $25, $87, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
@song1ref858:
	.byte $98, $31, $c5, $80, $31, $93, $00, $ad, $31, $95, $00, $ab, $31, $95, $00, $ab, $31, $95, $00, $ad, $31, $93, $00, $ad
	.byte $31, $95, $00, $ab, $31, $95, $00, $ab, $7b, $31, $89, $31, $89, $31, $89, $84, $31, $a1, $80, $31, $89, $31, $87, $31
	.byte $89, $84, $31, $a1, $80, $31, $89, $31, $89, $31, $89, $84, $31, $9f, $80, $31, $89, $31, $89, $31, $89, $84, $31, $9f
	.byte $80, $31, $89, $31, $89, $31, $89, $84, $31, $a1, $80, $31, $89, $31, $87, $31, $89, $84, $31, $95, $98, $31, $e7, $80
	.byte $31, $89, $88
@song1ref957:
	.byte $1b, $89, $00, $89, $1b, $87
@song1ref963:
	.byte $98, $31, $c5
@song1ref966:
	.byte $88, $1b, $89, $80, $31, $87, $31, $89, $2f, $89, $31, $89, $31, $89, $31, $89, $31, $89, $31, $89, $2f, $87, $31, $89
	.byte $31, $89, $88, $1b, $89, $80, $31, $89, $31, $89, $2f, $89, $31, $87, $88, $1b, $89, $80, $31, $89, $31, $89, $31, $89
	.byte $2f, $89, $31, $89, $31, $89
	.byte $41, $30
	.word @song1ref966
	.byte $41, $30
	.word @song1ref966
	.byte $41, $24
	.word @song1ref966
	.byte $41, $32
	.word @song1ref963
	.byte $41, $30
	.word @song1ref966
	.byte $41, $30
	.word @song1ref966
	.byte $41, $24
	.word @song1ref966
	.byte $98, $31, $c5, $88, $1b, $9f, $00, $e7, $1b, $a1, $00, $9f, $c7, $1b, $9f, $00, $e7, $1b, $a1, $00, $9f, $c7, $1b, $9f
	.byte $00, $e7, $1b, $a1, $00, $9f, $c7, $1b, $9f, $00, $e7, $1b, $85, $00, $81, $1b, $85, $00, $81, $1b, $85, $00, $81
	.byte $41, $38
	.word @song1ref957
	.byte $41, $30
	.word @song1ref966
	.byte $41, $30
	.word @song1ref966
	.byte $41, $24
	.word @song1ref966
	.byte $41, $1e
	.word @song1ref858
	.byte $ff, $ff, $99, $ff, $eb, $31, $89, $88, $1b, $89, $00, $89, $1b, $87, $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref1121:
	.byte $02, $a1, $00, $95, $02, $89, $04, $89, $00, $93, $09, $95, $04, $89, $00, $95, $02, $89, $08, $9f, $03, $a1, $07, $9f
	.byte $05, $a1, $00, $95, $03, $9f, $07, $83, $00, $83, $03, $89, $00, $89, $08, $ad, $03, $87, $00, $89, $07, $89, $01, $89
	.byte $00, $89, $06, $ab
	.byte $41, $17
	.word @song1ref1121
@song1ref1176:
	.byte $95, $03, $87, $08, $89, $00, $89, $08, $89, $00, $95, $08, $89, $00, $93, $02, $89, $08, $89, $00, $89, $03, $ad, $07
	.byte $87, $00, $95, $01, $89, $00, $89, $06, $ab
	.byte $41, $34
	.word @song1ref1121
	.byte $41, $17
	.word @song1ref1121
	.byte $41, $21
	.word @song1ref1176
	.byte $41, $34
	.word @song1ref1121
	.byte $41, $17
	.word @song1ref1121
	.byte $41, $21
	.word @song1ref1176
	.byte $41, $34
	.word @song1ref1121
	.byte $41, $17
	.word @song1ref1121
	.byte $41, $21
	.word @song1ref1176
	.byte $41, $34
	.word @song1ref1121
	.byte $41, $17
	.word @song1ref1121
	.byte $41, $21
	.word @song1ref1176
	.byte $41, $34
	.word @song1ref1121
	.byte $41, $17
	.word @song1ref1121
	.byte $41, $21
	.word @song1ref1176
	.byte $42
	.word @song1ch4loop
@song1ch5:
@song1ch5loop:
	.byte $41, $16
	.word @song1ref487
	.byte $41, $15
	.word @song1ref488
	.byte $41, $15
	.word @song1ref488
	.byte $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $42
	.word @song1ch5loop
@song1ch6:
@song1ch6loop:
	.byte $41, $16
	.word @song1ref487
	.byte $41, $15
	.word @song1ref488
	.byte $41, $15
	.word @song1ref488
	.byte $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $42
	.word @song1ch6loop
@song2ch0:
@song2ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $49, .lobyte(@env0), .hibyte(@env0), $4a, $b5, $8a, $40
	.byte $4c, $00, $b1, $92, $2b, $83, $2c, $91, $8a, $40, $4c, $92, $29, $89, $00, $89, $20, $8b, $00, $8b, $8a, $40, $4c, $92
	.byte $22, $87, $23, $8b, $48, $9b, $22, $89, $00, $8b, $8a, $40, $4c, $92, $23, $95, $25, $8b, $00, $8b, $22, $97, $8a, $40
	.byte $4c, $92, $1d, $95, $1e, $8b, $00, $8b, $8a, $40, $4c, $92, $1e, $87, $94, $50, $f4, $2a, $2c, $8b, $48, $20, $99, $49
	.byte .lobyte(@env49), .hibyte(@env49), $99, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $40, $4c, $00, $b1, $92, $1e
	.byte $97, $8a, $40, $4c, $00, $95, $92, $25, $8b, $00, $8b, $8a, $40, $4c, $92, $1b, $87, $94, $50, $f2, $27, $29, $8b, $48
	.byte $1d, $99, $92, $1b, $89, $00, $8b, $8a, $40, $4c, $92, $19, $89, $00, $89, $16, $8b, $00, $8b, $19, $97, $8a, $40, $4c
	.byte $00, $95, $92, $1b, $81, $94, $50, $eb, $27, $28, $83, $1c, $8f, $8a, $40, $4c, $92, $1b, $87, $00, $8b, $48, $9b, $19
	.byte $97, $8a, $40, $4c, $94, $19, $89, $49, .lobyte(@env28), .hibyte(@env28), $c1, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8a, $40, $4c, $92, $14, $95, $16, $99, $8a, $40, $4c, $92, $19, $87, $00, $8b, $48, $1e, $85, $94, $50, $f4, $2a
	.byte $2c, $8b, $20, $83, $49, .lobyte(@env41), .hibyte(@env41), $99, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $40
	.byte $4c, $92, $1e, $b1, $19, $97, $8a, $40, $4c, $92, $14, $89, $00, $a5, $8a, $40, $4c, $92, $15, $95, $48, $00, $99, $19
	.byte $89, $00, $8b, $8a, $40, $4c, $92, $1e, $89, $00, $89, $20, $8b, $00, $8b, $21, $97, $8a, $40, $4c, $92, $1e, $89, $00
	.byte $89, $19, $8b, $00, $8b, $8a, $40, $4c, $92, $1e, $95, $48, $00, $99, $22, $83, $94, $50, $f6, $2e, $2f, $83, $23, $8b
	.byte $8a, $40, $4c, $00, $95, $92, $21, $b3, $8a, $40, $4c, $92, $20, $95, $1e, $8b, $00, $8b, $8a, $40, $4c, $92, $1c, $81
	.byte $94, $50, $f2, $28, $29, $83, $1d, $8b, $48, $49, .lobyte(@env7), .hibyte(@env7), $b5, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8a, $40, $4c, $92, $19, $89, $00, $a5, $1d, $97, $8a, $40, $4c, $92, $1e, $89, $00, $a5, $8a, $40, $4c, $92, $1d
	.byte $95, $48, $b5, $8a, $40, $4c, $92, $1e, $89, $00, $89, $1d, $8b, $00, $8b, $20, $89, $00, $8b, $8a, $40, $4c, $92, $1d
	.byte $89, $00, $89, $1e, $8b, $00, $8b, $8a, $40, $4c, $92, $1d, $87, $00, $8b, $48, $9b, $16, $89, $00, $8b, $8a, $40, $4c
	.byte $92, $22, $b1, $16, $89, $00, $8b, $8a, $40, $4c, $92, $20, $b1, $8a, $40, $4c, $92, $16, $87, $00, $8b, $48, $1e, $99
	.byte $00, $89, $16, $8b, $8a, $40, $4c, $00, $95, $92, $1c, $85, $94, $50, $f2, $28, $29, $83, $1d, $a5, $8a, $40, $4c, $94
	.byte $1d, $b1, $8a, $40, $4c, $92, $1c, $83, $1b, $85, $1a, $87, $48, $19, $b3, $8a, $40, $4c, $94, $19, $cb, $8a, $40, $4c
	.byte $92, $1b, $b1, $8a, $40, $4c, $92, $1a, $87, $19, $8b, $48, $18, $99, $19, $89, $00, $8b, $8a, $40, $4c, $92, $18, $95
	.byte $19, $8b, $00, $8b, $18, $97, $8a, $40, $4c, $00, $95, $92, $1b, $8b, $00, $8b, $8a, $40, $4c, $92, $1d, $95, $48, $9b
	.byte $20, $89, $00, $8b, $8a, $40, $4c, $00, $95, $92, $22, $b3, $8a, $40, $4c, $92, $20, $89, $00, $a5, $8a, $40, $4c, $92
	.byte $22, $87, $23, $8b, $48, $9b, $22, $89, $00, $8b, $8a, $40, $4c, $92, $20, $b1, $49, .lobyte(@env40), .hibyte(@env40)
	.byte $99, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $40, $4c, $49, .lobyte(@env40), .hibyte(@env40), $94, $20, $b1
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $40, $4c, $49, .lobyte(@env40), .hibyte(@env40), $94, $20, $93, $00
	.byte $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $4c, $8c, $0d, $99, $19, $83, $00, $91, $4b, .lobyte(@env11), .hibyte(@env11), $8a, $29, $97, $4b, .lobyte(@env20)
	.byte .hibyte(@env20), $4c, $8c, $14, $85, $00, $91, $14, $97, $4b, .lobyte(@env11), .hibyte(@env11), $8a, $29, $97, $00
	.byte $99, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $0d, $97, $9b, $4b, .lobyte(@env11), .hibyte(@env11), $8a, $29
	.byte $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $14, $97, $19, $99, $00, $97, $4b, .lobyte(@env11), .hibyte(@env11)
	.byte $8a, $29, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $14, $99, $11, $97, $0d, $99, $19, $83, $00, $91, $4b
	.byte .lobyte(@env39), .hibyte(@env39), $8a, $27, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $14, $85, $00, $91
	.byte $14, $97, $4b, .lobyte(@env39), .hibyte(@env39), $8a, $27, $97, $00, $99, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $8c, $0d, $97, $9b, $4b, .lobyte(@env39), .hibyte(@env39), $8a, $27, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $8c, $14, $97, $19, $99, $00, $97, $4b, .lobyte(@env39), .hibyte(@env39), $8a, $27, $97, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $8c, $14, $99, $11, $97, $06, $99, $12, $83, $00, $91, $4b, .lobyte(@env36), .hibyte(@env36), $8a, $29, $97, $4b
	.byte .lobyte(@env20), .hibyte(@env20), $4c, $8c, $0d, $85, $00, $91, $0d, $97, $4b, .lobyte(@env36), .hibyte(@env36), $8a
	.byte $29, $97, $00, $99, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $06, $97, $9b, $4b, .lobyte(@env36), .hibyte(@env36)
	.byte $8a, $29, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $0d, $97, $12, $99, $00, $97, $4b, .lobyte(@env36)
	.byte .hibyte(@env36), $8a, $29, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $0d, $99, $0a, $97, $0b, $99, $17
	.byte $83, $00, $91, $4b, .lobyte(@env6), .hibyte(@env6), $8a, $28, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c
	.byte $12, $85, $00, $91, $12, $97, $4b, .lobyte(@env6), .hibyte(@env6), $8a, $28, $97, $00, $99, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $8c, $0b, $97, $9b, $4b, .lobyte(@env6), .hibyte(@env6), $8a, $28, $97, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $8c, $12, $97, $17, $99, $00, $97, $4b, .lobyte(@env6), .hibyte(@env6), $8a, $28, $97, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $8c, $12, $99, $0b, $97, $05, $99, $11, $83, $00, $91, $4b, .lobyte(@env6), .hibyte(@env6), $8a, $27, $97, $4b
	.byte .lobyte(@env20), .hibyte(@env20), $4c, $8c, $0c, $85, $00, $91, $0c, $97, $4b, .lobyte(@env6), .hibyte(@env6), $8a
	.byte $27, $97, $00, $99, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $05, $97, $9b, $4b, .lobyte(@env6), .hibyte(@env6)
	.byte $8a, $27, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $0c, $97, $11, $99, $00, $97, $4b, .lobyte(@env6), .hibyte(@env6)
	.byte $8a, $27, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $0c, $99, $09, $97, $0a, $99, $16, $83, $00, $91, $4b
	.byte .lobyte(@env5), .hibyte(@env5), $8a, $26, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $11, $85, $00, $91
	.byte $11, $97, $4b, .lobyte(@env5), .hibyte(@env5), $8a, $26, $97, $00, $99, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $8c, $0a, $97, $9b, $4b, .lobyte(@env5), .hibyte(@env5), $8a, $26, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $8c, $11, $97, $16, $99, $00, $97, $4b, .lobyte(@env5), .hibyte(@env5), $8a, $26, $97, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $8c, $11, $99, $0e, $97, $0f, $99, $1b, $83, $00, $91, $4b, .lobyte(@env6), .hibyte(@env6), $8a, $25, $97, $4b
	.byte .lobyte(@env20), .hibyte(@env20), $4c, $8c, $16, $85, $00, $91, $16, $97, $4b, .lobyte(@env6), .hibyte(@env6), $8a
	.byte $25, $97, $00, $99, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $0f, $97, $9b, $4b, .lobyte(@env6), .hibyte(@env6)
	.byte $8a, $25, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $16, $97, $1b, $99, $00, $97, $4b, .lobyte(@env6), .hibyte(@env6)
	.byte $8a, $25, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $0f, $99, $0a, $97, $08, $99, $14, $83, $00, $91, $4b
	.byte .lobyte(@env1), .hibyte(@env1), $8a, $27, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $8c, $0f, $85, $00, $91
	.byte $0f, $97, $4b, .lobyte(@env1), .hibyte(@env1), $8a, $27, $97, $00, $99, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $8c, $08, $97, $9b, $4b, .lobyte(@env1), .hibyte(@env1), $8a, $27, $97, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $8c, $0f, $97, $14, $99, $00, $97, $4b, .lobyte(@env1), .hibyte(@env1), $8a, $27, $97, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $8c, $0b, $99, $0c, $97, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $86
@song2ref1176:
	.byte $0d, $99, $19, $83, $00, $ab, $14, $85, $00, $91, $14, $97, $00, $b3, $0d, $97, $9b, $00, $97, $14, $97, $19, $99, $00
	.byte $b1, $14, $99, $11, $97
	.byte $41, $1d
	.word @song2ref1176
	.byte $06, $99, $12, $83, $00, $ab, $0d, $85, $00, $91, $0d, $97, $00, $b3, $06, $97, $9b, $00, $97, $0d, $97, $12, $99, $00
	.byte $b1, $0d, $99, $0a, $97, $0b, $99, $17, $83, $00, $ab, $12, $85, $00, $91, $12, $97, $00, $b3, $0b, $97, $9b, $00, $97
	.byte $12, $97, $17, $99, $00, $b1, $12, $99, $0b, $97, $05, $99, $11, $83, $00, $ab, $0c, $85, $00, $91, $0c, $97, $00, $b3
	.byte $05, $97, $9b, $00, $97, $0c, $97, $11, $99, $00, $b1, $0c, $99, $09, $97, $0a, $99, $16, $83, $00, $ab, $11, $85, $00
	.byte $91, $11, $97, $00, $b3, $0a, $97, $9b, $00, $97, $11, $97, $16, $99, $00, $b1, $11, $99, $0e, $97, $0f, $99, $1b, $83
	.byte $00, $ab, $16, $85, $00, $91, $16, $97, $00, $b3, $0f, $97, $9b, $00, $97, $16, $97, $1b, $99, $00, $b1, $0f, $99, $0a
	.byte $97, $08, $99, $14, $83, $00, $ab, $0f, $85, $00, $91, $0f, $97, $00, $b3, $08, $97, $9b, $00, $97, $0f, $97, $14, $99
	.byte $00, $b1, $0b, $99, $0c, $97, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
@song2ref1386:
	.byte $7f, $8e, $32, $8b, $74, $32, $8b, $7f, $32, $89, $74, $32, $8b, $7f, $90, $32, $8b, $74, $32, $89, $7f, $8e, $32, $8b
	.byte $74, $32, $8b, $7f, $32, $89, $74, $32, $8b, $7f, $90, $32, $8b, $74, $32, $89, $7f, $8e, $32, $8b, $74, $32, $8b, $7f
	.byte $90, $32, $89, $74, $32, $8b
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $41, $20
	.word @song2ref1386
	.byte $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
@song2ref1489:
	.byte $0a, $8b, $00, $bf, $0a, $8b, $00, $bf, $0a, $8b, $00, $a5, $0a, $8b, $00, $bf, $0a, $8b, $00, $bf, $0a, $8b, $00, $a5
	.byte $41, $18
	.word @song2ref1489
	.byte $41, $18
	.word @song2ref1489
	.byte $41, $18
	.word @song2ref1489
	.byte $41, $18
	.word @song2ref1489
	.byte $41, $18
	.word @song2ref1489
	.byte $41, $18
	.word @song2ref1489
	.byte $41, $18
	.word @song2ref1489
	.byte $42
	.word @song2ch4loop
@song2ch5:
@song2ch5loop:
@song2ref1538:
	.byte $ff, $d5, $ff, $d5, $ff, $d5, $ff, $d5, $ff, $d5, $ff, $d5, $ff, $d5, $ff, $d5
	.byte $41, $10
	.word @song2ref1538
	.byte $42
	.word @song2ch5loop
@song2ch6:
@song2ch6loop:
	.byte $41, $10
	.word @song2ref1538
	.byte $41, $10
	.word @song2ref1538
	.byte $42
	.word @song2ch6loop
@song3ch0:
@song3ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48
	.byte $ff, $ff, $bf, $48, $4e, $fe, $96, $20, $87, $8a, $50, $f8, $2c, $2d, $87, $21
@song3ref33:
	.byte $91, $49, .lobyte(@env40), .hibyte(@env40), $a7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $96, $27, $83, $28, $8b
	.byte $49, .lobyte(@env40), .hibyte(@env40), $a7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $96, $29, $87, $00, $9b, $28
	.byte $87, $00, $87, $26, $91, $29, $87, $00, $87, $28, $91, $26, $87, $00, $87, $21, $91, $24, $87, $00, $87, $48, $1e, $87
	.byte $8a, $50, $f7, $2a, $2b, $87, $1f
	.byte $41, $0f
	.word @song3ref33
	.byte $2b, $91, $2d, $87, $00, $87, $27, $91, $26, $87, $00, $87, $24, $91, $26, $87, $00, $87, $48, $1c, $87, $8a, $50, $f5
	.byte $28, $29, $87, $1d
	.byte $41, $26
	.word @song3ref33
	.byte $41, $11
	.word @song3ref33
	.byte $2c, $87, $00, $87, $28, $91, $26, $87, $00, $87, $24, $91, $21, $87, $00, $87, $48, $92
@song3ref147:
	.byte $21, $a5, $24, $a5, $26, $91, $24, $87, $00, $87, $26, $87, $00, $87, $27, $83, $94, $50, $fb, $33, $34, $87, $28, $81
	.byte $49, .lobyte(@env34), .hibyte(@env34), $a7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $27, $87, $00, $87, $26
	.byte $91, $49, .lobyte(@env34), .hibyte(@env34), $93, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $24, $87, $00, $87
	.byte $21, $91, $24, $87, $00, $87, $48, $1f, $a5, $24, $a5, $26, $91, $24, $87, $00, $87, $26, $87, $00, $87, $26, $83, $94
	.byte $50, $fa, $32, $33, $87, $27, $81, $49, .lobyte(@env34), .hibyte(@env34), $a7, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $92, $26, $87, $00, $87, $24, $91, $49, .lobyte(@env34), .hibyte(@env34), $93, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $92, $21, $87, $00, $87, $1f, $91, $21, $87, $00, $87, $48, $1d, $a5, $24, $a5, $26, $91, $24, $87, $00, $87, $24
	.byte $87, $00, $87, $25, $83, $94, $50, $fa, $31, $32, $87, $26, $81, $49, .lobyte(@env34), .hibyte(@env34), $a7, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $92, $24, $87, $00, $87, $21, $91, $49, .lobyte(@env34), .hibyte(@env34), $93, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $92, $20, $87, $00, $87, $1f, $91, $1d, $87, $00, $87, $48, $1f, $a5, $21, $a5, $23, $91, $24
	.byte $87, $00, $87, $23, $91, $21, $87, $00, $87, $20, $91, $1c, $87, $00, $87, $1c, $87, $00, $87, $27, $87, $28, $97, $94
	.byte $50, $0c, $34, $31, $8b, $00, $87, $92, $26, $91, $24, $87, $00, $87, $48
	.byte $41, $7c
	.word @song3ref147
	.byte $28, $91, $2d, $87, $00, $87, $2f, $91, $30, $87, $00, $87, $2d, $87, $00, $87, $26, $87, $27, $97, $94, $50, $0c, $33
	.byte $30, $8b, $00, $87, $92, $26, $a5, $48, $ac
@song3ref406:
	.byte $28, $87, $21, $87, $27, $87, $21, $87, $26, $87, $21, $87, $27, $87, $21, $87, $28, $87, $21, $87, $29, $87, $21, $87
	.byte $28, $87, $21, $87, $27, $87, $21, $87
	.byte $41, $20
	.word @song3ref406
@song3ref441:
	.byte $48
@song3ref442:
	.byte $26, $87, $1f, $87, $25, $87, $1f, $87, $24, $87, $1f, $87, $25, $87, $1f, $87, $26, $87, $1f, $87, $27, $87, $1f, $87
	.byte $26, $87, $1f, $87, $25, $87, $1f, $87
	.byte $41, $20
	.word @song3ref442
	.byte $48
@song3ref478:
	.byte $26, $87, $1d, $87, $24, $87, $1d, $87, $23, $87, $1d, $87, $21, $87, $1d, $87, $23, $87, $1d, $87, $24, $87, $1d, $87
	.byte $26, $87, $1d, $87, $24, $87, $1d, $87
	.byte $41, $20
	.word @song3ref478
	.byte $41, $20
	.word @song3ref441
	.byte $27, $87, $20, $87, $26, $87, $20, $87, $25, $87, $20, $87, $26, $87, $20, $87, $27, $87, $20, $87, $28, $87, $20, $87
	.byte $27, $87, $20, $87, $26, $87, $20, $87, $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
@song3ref552:
	.byte $4e, $fb, $8c, $09, $87, $00, $87, $09, $87, $00, $87, $82, $21, $81, $1c, $18, $21, $1c, $81, $18, $21, $1c, $8c, $09
	.byte $87, $00, $9b, $07, $91, $82, $21, $81, $1c, $18, $21, $1c, $81, $18, $21, $1c, $8c, $09, $87, $00, $9b, $0c, $87, $00
	.byte $87, $82, $21, $81, $1c, $18, $21, $1c, $81, $18, $21, $1c, $8c, $0f, $87, $00, $87, $0e, $91, $0c, $87, $00, $87, $82
	.byte $21, $81, $1c, $18, $21, $1c, $81, $18, $21, $1c, $8c, $06, $87, $00, $87, $07, $87, $00, $87, $07, $87, $00, $87, $82
	.byte $1f, $81, $1a, $17, $1f, $1a, $81, $17, $1f, $1a, $8c, $07, $87, $00, $9b, $04, $91, $82, $1f, $81, $1a, $17, $1f, $1a
	.byte $81, $17, $1f, $1a, $8c, $07, $a5, $04, $91, $82, $1f, $81, $1a, $17, $1f, $1a, $81, $17, $1f, $1a, $8c, $09, $91, $03
	.byte $a5, $82, $1f, $81, $1a, $17, $1f, $1a, $81, $17, $1f, $1a, $8c, $02, $87, $00, $87, $05, $87, $00, $87, $05, $87, $00
	.byte $87, $82, $21, $81, $1d, $18, $21, $1d, $81, $18, $21, $1d, $8c, $05, $87, $00, $9b, $02, $91, $82, $21, $81, $1d, $18
	.byte $21, $1d, $81, $18, $21, $1d, $8c, $05, $87, $00, $9b, $05, $87, $00, $87, $82, $21, $81, $1d, $18, $21, $1d, $81, $18
	.byte $21, $1d, $8c, $07, $87, $00, $87, $08, $91, $07, $87, $00, $87, $82, $21, $81, $1d, $18, $21, $1d, $81, $18, $21, $1d
	.byte $8c, $02, $87, $00, $87, $07, $87, $00, $87, $07, $87, $00, $87, $82, $1f, $81, $1c, $1a, $1f, $1c, $81, $1a, $1f, $1c
	.byte $8c, $07, $87, $00, $9b, $07, $87, $00, $87, $82, $1f, $81, $1c, $1a, $1f, $1c
@song3ref832:
	.byte $81, $1a, $1f, $1c, $8c, $08, $b9, $82, $20, $81, $1c, $1a, $20, $1c, $81, $1a, $20, $1c, $8c, $09, $87, $82, $50, $c5
	.byte $15, $17, $87, $0b, $a5, $20, $81, $1c, $1a, $20, $1c, $81, $1a, $20, $1c, $00, $91
	.byte $41, $fa
	.word @song3ref552
	.byte $41, $22
	.word @song3ref832
	.byte $41, $fa
	.word @song3ref552
	.byte $41, $22
	.word @song3ref832
	.byte $41, $fa
	.word @song3ref552
	.byte $41, $22
	.word @song3ref832
	.byte $41, $fa
	.word @song3ref552
	.byte $41, $22
	.word @song3ref832
	.byte $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
@song3ref901:
	.byte $4e, $fc, $8c, $09, $87, $00, $87, $09, $87, $00, $87, $21, $87, $00, $87, $09, $87, $00, $9b, $07, $91, $00, $91, $09
	.byte $87, $00, $9b, $0c, $87, $00, $87, $1a, $87, $00, $87, $0f, $87, $00, $87, $0e, $91, $0c, $87, $00, $87, $11, $91, $06
@song3ref949:
	.byte $87, $00, $87, $07, $87, $00, $87, $07, $87, $00, $87, $1f, $87, $00, $87, $07, $87, $00, $9b, $04, $91, $00, $91, $07
	.byte $a5, $04, $91, $1f, $87, $00, $87, $09, $91, $03, $a5, $00, $91, $02, $87, $00, $87, $05, $87, $00, $87, $05, $87, $00
	.byte $87, $1d, $87, $00, $87, $05, $87, $00, $9b, $02, $91, $00, $91, $05, $87, $00, $9b, $05, $87, $00, $9b, $07, $87, $00
	.byte $87, $08, $91, $07, $87, $00, $87, $4e, $fe, $1d, $91, $4e, $fc, $02
	.byte $41, $13
	.word @song3ref949
@song3ref1038:
	.byte $07, $87, $00, $9b, $08, $b9, $00, $91, $09, $87, $82, $50, $c5, $15, $17, $87, $0b, $a5, $00, $a5
	.byte $41, $7f
	.word @song3ref901
	.byte $41, $13
	.word @song3ref949
	.byte $41, $10
	.word @song3ref1038
	.byte $41, $7f
	.word @song3ref901
	.byte $41, $13
	.word @song3ref949
	.byte $41, $10
	.word @song3ref1038
	.byte $41, $7f
	.word @song3ref901
	.byte $41, $13
	.word @song3ref949
	.byte $41, $10
	.word @song3ref1038
	.byte $41, $7f
	.word @song3ref901
	.byte $41, $13
	.word @song3ref949
	.byte $41, $10
	.word @song3ref1038
	.byte $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
	.byte $7f, $98, $31, $91, $31, $ff, $89, $00, $ff, $9d, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $9f
@song3ref1116:
	.byte $71, $82, $31, $8d, $72, $8d, $73, $91, $75, $8f, $77, $8d, $79, $8f, $7a, $8b, $7d, $8b, $70, $81, $7f, $83, $70, $85
	.byte $7f, $83, $70, $85, $7f, $83, $70, $85, $7f, $83, $70, $85, $7f
@song3ref1153:
	.byte $98, $31, $a5
@song3ref1156:
	.byte $88, $1b, $91, $80, $31, $87, $31, $87, $84, $31, $91, $80, $31, $87, $31, $87, $88, $1b, $91, $80, $31, $87, $31, $87
	.byte $84, $31, $91, $80, $31, $87, $31, $87
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $12
	.word @song3ref1156
	.byte $98, $31, $91, $31, $ff, $89
	.byte $41, $2c
	.word @song3ref1116
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $12
	.word @song3ref1156
	.byte $41, $1a
	.word @song3ref1153
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $12
	.word @song3ref1156
	.byte $41, $1a
	.word @song3ref1153
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $18
	.word @song3ref1156
	.byte $41, $12
	.word @song3ref1156
	.byte $98, $31, $91, $31, $ff, $89
	.byte $41, $12
	.word @song3ref1116
	.byte $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $0a, $91, $0a, $91, $00, $ff, $ff, $95, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
@song3ref1305:
	.byte $0a, $a5, $0a, $91, $0a, $87, $0a, $87, $0a, $91, $0a, $91, $0a, $91, $0a, $a5, $0a, $91, $0a, $91, $0a, $87, $0a, $87
	.byte $0a, $91, $0a, $91, $0a, $a5
	.byte $41, $1e
	.word @song3ref1305
	.byte $41, $1e
	.word @song3ref1305
	.byte $0a, $a5, $00, $ff, $c5
@song3ref1346:
	.byte $0a, $81, $00, $83, $0a, $81, $00, $83, $0a, $81, $00, $83, $0a, $81, $00, $83
	.byte $41, $10
	.word @song3ref1346
	.byte $41, $1e
	.word @song3ref1305
	.byte $41, $1e
	.word @song3ref1305
	.byte $41, $1e
	.word @song3ref1305
	.byte $41, $1e
	.word @song3ref1305
	.byte $41, $1e
	.word @song3ref1305
	.byte $41, $1e
	.word @song3ref1305
	.byte $41, $1e
	.word @song3ref1305
	.byte $41, $1e
	.word @song3ref1305
	.byte $41, $1e
	.word @song3ref1305
	.byte $41, $1e
	.word @song3ref1305
	.byte $41, $1e
	.word @song3ref1305
	.byte $0a, $91, $0a, $91, $00, $ff, $ff, $95, $42
	.word @song3ch4loop
@song3ch5:
@song3ch5loop:
@song3ref1410:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0f
	.word @song3ref1410
	.byte $41, $0f
	.word @song3ref1410
	.byte $41, $0f
	.word @song3ref1410
	.byte $42
	.word @song3ch5loop
@song3ch6:
@song3ch6loop:
	.byte $41, $0f
	.word @song3ref1410
	.byte $41, $0f
	.word @song3ref1410
	.byte $41, $0f
	.word @song3ref1410
	.byte $41, $0f
	.word @song3ref1410
	.byte $42
	.word @song3ch6loop
@song4ch0:
@song4ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7b, $9c
@song4ref7:
	.byte $20, $a1, $20, $a1, $20, $a1, $1d, $8f, $20, $a1, $20, $a1, $1d, $8f, $20, $8f, $1d, $8f, $20, $a1, $48, $20, $a1, $20
	.byte $a1, $20, $a1, $1b, $8f, $20, $a1, $20, $a1, $1b, $8f, $20, $8f, $1b, $8f, $20, $a1, $48
	.byte $41, $28
	.word @song4ref7
@song4ref52:
	.byte $48, $a3, $00, $95, $76, $a0
@song4ref58:
	.byte $27, $8f, $29, $8f, $2c, $8f, $00, $8f, $2c, $89, $00, $dd, $27, $89, $2c, $8f, $00, $8f, $48, $eb, $72, $9e, $38, $a1
	.byte $74, $9c, $14, $ff, $8d
	.byte $41, $1b
	.word @song4ref52
	.byte $41, $1b
	.word @song4ref52
	.byte $41, $1b
	.word @song4ref52
	.byte $42
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $7b, $9c
@song4ref102:
	.byte $25, $a1, $25, $a1, $25, $b3, $27, $8f, $00, $8f, $27, $b3, $27, $a1, $27, $a1, $24, $a1, $24, $a1, $24, $b3, $24, $8f
	.byte $00, $8f, $24, $b3, $24, $a1, $24, $a1
	.byte $41, $20
	.word @song4ref102
	.byte $a3, $00, $95, $79
	.byte $41, $12
	.word @song4ref58
@song4ref144:
	.byte $33, $8f, $2e, $8f, $00, $8f, $30, $8f, $00, $a1, $72, $1b
@song4ref156:
	.byte $83, $73, $85, $85, $74, $85, $85, $75, $85, $85, $76, $85, $85, $77, $85, $85, $78, $85, $85, $79, $85, $85, $78, $a9
	.byte $77, $85, $76, $85, $85, $75, $85, $85, $74, $85, $85, $73, $85, $a3, $00, $95, $79
	.byte $41, $12
	.word @song4ref58
	.byte $2c, $8f, $00, $d7, $72, $18
	.byte $41, $1b
	.word @song4ref156
	.byte $79
	.byte $41, $12
	.word @song4ref58
	.byte $41, $26
	.word @song4ref144
	.byte $79
	.byte $41, $12
	.word @song4ref58
	.byte $2c, $8f, $00, $d7, $72, $18
	.byte $41, $18
	.word @song4ref156
	.byte $42
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $9a
@song4ref234:
	.byte $0d, $a1, $25, $a1, $0d, $a1, $25, $a1, $0f, $a1, $27, $a1, $0f, $a1, $27, $a1, $14, $a1, $20, $a1, $14, $a1, $20, $a1
	.byte $14, $a1, $20, $a1, $14, $a1, $20, $a1
	.byte $41, $20
	.word @song4ref234
	.byte $41, $20
	.word @song4ref234
	.byte $41, $20
	.word @song4ref234
	.byte $41, $20
	.word @song4ref234
	.byte $41, $20
	.word @song4ref234
	.byte $42
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
	.byte $7f, $8e
@song4ref287:
	.byte $15, $a1, $79, $1e, $95, $1e, $89, $76, $90, $1e, $a1, $78, $8e, $1e, $95, $1e, $89, $7f, $15, $a1, $79, $1e, $95, $1e
	.byte $89, $76, $90, $1e, $a1, $78, $8e, $1e, $95, $1e, $89, $7f
	.byte $41, $18
	.word @song4ref287
	.byte $7f
	.byte $41, $18
	.word @song4ref287
	.byte $7f
	.byte $41, $18
	.word @song4ref287
	.byte $7f
	.byte $41, $18
	.word @song4ref287
	.byte $7f
	.byte $41, $18
	.word @song4ref287
	.byte $7f
	.byte $41, $18
	.word @song4ref287
@song4ref346:
	.byte $15, $a1, $1e, $95, $1e, $89, $79, $90, $1e, $a1, $7f, $8e, $1e, $95, $1e, $89, $15, $a1, $1e, $95, $1e, $89, $79, $90
	.byte $1e, $a1, $7f, $8e, $1e, $95, $1e, $89
	.byte $41, $18
	.word @song4ref287
	.byte $7f
	.byte $41, $18
	.word @song4ref287
	.byte $7f
	.byte $41, $18
	.word @song4ref287
	.byte $41, $18
	.word @song4ref346
	.byte $42
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
@song4ref396:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $41, $12
	.word @song4ref396
	.byte $42
	.word @song4ch4loop
@song4ch5:
@song4ch5loop:
	.byte $41, $12
	.word @song4ref396
	.byte $41, $12
	.word @song4ref396
	.byte $42
	.word @song4ch5loop
@song4ch6:
@song4ch6loop:
	.byte $41, $12
	.word @song4ref396
	.byte $41, $12
	.word @song4ref396
	.byte $42
	.word @song4ch6loop
@song5ch0:
	.byte $4e, $fd, $92, $18, $9b, $1b, $8d, $00, $8b, $1f, $9b, $20, $85, $00, $85, $1f, $8b, $49, .lobyte(@env41), .hibyte(@env41)
	.byte $9d, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $20, $85, $00, $85, $1f, $8b, $22, $85, $00, $85, $1f, $8b, $20
	.byte $85, $00, $85, $1f, $8b, $48, $00, $8d, $18, $83, $00, $85, $24, $9b, $18, $85, $00, $85, $22, $9b, $18, $83, $00, $85
	.byte $20, $9b, $18, $85, $00, $85, $1f, $9b, $49, .lobyte(@env40), .hibyte(@env40), $a9, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $00
@song5ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $c7, $42
	.word @song5ch0loop
@song5ch1:
	.byte $4e, $fc, $86, $11, $9b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $8d, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $1d, $8b, $00, $8d, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $8b, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $4c, $86, $11, $9b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $9b, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $11, $8d, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $8b, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $86
	.byte $1d, $8d, $11, $8b, $4b, .lobyte(@env6), .hibyte(@env6), $82, $29, $8d, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $86, $11, $85, $00, $83, $ff, $ef
@song5ch1loop:
	.byte $4c, $c7, $42
	.word @song5ch1loop
@song5ch2:
	.byte $4e, $fc, $86, $11, $9b, $00, $8d, $1d, $8b, $00, $9b, $11, $9b, $00, $9b, $11, $8d, $00, $8b, $1d, $8d, $11, $8b, $00
	.byte $8d, $11, $85, $00, $83, $ff, $ef
@song5ch2loop:
	.byte $c7, $42
	.word @song5ch2loop
@song5ch3:
@song5ref209:
	.byte $80, $31, $9b, $84, $31, $9b, $80, $31, $9b, $84, $31, $9b
	.byte $41, $08
	.word @song5ref209
	.byte $98, $31, $ff, $b1, $00, $b9
@song5ch3loop:
	.byte $c7, $42
	.word @song5ch3loop
@song5ch4:
@song5ref235:
	.byte $0a, $9b, $00, $9b, $0a, $9b, $00, $9b
	.byte $41, $08
	.word @song5ref235
	.byte $0a, $9b, $00, $ff, $cf
@song5ch4loop:
	.byte $c7, $42
	.word @song5ch4loop
@song5ch5:
	.byte $ff, $ef, $ff, $ef
@song5ch5loop:
	.byte $c7, $42
	.word @song5ch5loop
@song5ch6:
	.byte $ff, $ef, $ff, $ef
@song5ch6loop:
	.byte $c7, $42
	.word @song5ch6loop
@song6ch0:
	.byte $7b, $8a, $31, $89, $3d, $91, $7a, $83, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74, $83, $73, $83, $72, $83
	.byte $71, $83, $7f, $4e, $05, $92, $01, $89, $02, $89
@song6ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song6ref39:
	.byte $03, $95, $8a, $25, $1e, $1b, $25, $22, $1e, $92, $0a, $89, $00, $89, $8a, $25, $1e, $1b, $25, $22, $1e, $92, $0d, $95
	.byte $8a, $25, $1e, $1b, $25, $22, $1e, $1b, $22, $1e, $1b, $25, $22, $1e, $00, $87, $25, $1e, $1b, $25, $22, $1e, $92, $0a
	.byte $89, $0d, $89, $8a, $25, $1e, $1b, $25, $22, $1e, $92, $0a, $89, $48, $01, $95, $8a, $24, $1d, $19, $24, $20, $1d, $92
	.byte $05, $89, $00, $89, $8a, $24, $1d, $19, $24, $20, $1d, $92, $0c, $95, $8a, $24, $1d, $19, $24, $20, $1d, $19, $20, $1d
	.byte $19, $24, $20, $1d, $00, $87, $24, $1d, $19, $24, $20, $1d, $92, $08, $89, $0c, $89, $8a, $24, $1d, $19, $24, $20, $00
	.byte $92, $05, $89, $48
	.byte $41, $6a
	.word @song6ref39
	.byte $48
	.byte $41, $6a
	.word @song6ref39
	.byte $42
	.word @song6ch0loop
@song6ch1:
	.byte $92, $20, $ad, $21, $95, $00, $95
@song6ch1loop:
	.byte $4e, $01, $21, $89, $94, $50, $fb, $2d, $2e, $89, $22, $ad, $49, .lobyte(@env40), .hibyte(@env40), $c7, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $92, $29, $9d, $28, $81, $27, $81, $26, $81, $25, $81, $24, $ad, $49, .lobyte(@env40), .hibyte(@env40)
	.byte $c7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $25, $95, $00, $89, $26, $95, $00, $89, $4e, $02, $26, $89, $94
	.byte $50, $fc, $32, $33, $89, $27, $ad, $49, .lobyte(@env40), .hibyte(@env40), $c7, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $92, $2e, $9d, $2d, $81, $2c, $81, $2b, $81, $2a, $81, $29, $ad, $49, .lobyte(@env40), .hibyte(@env40), $af, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $92, $30, $ad, $2c, $95, $00, $95, $2d, $89, $94, $50, $fa, $39, $3a, $83, $2e
	.byte $8f, $49, .lobyte(@env40), .hibyte(@env40), $a3, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $2a, $95, $4e, $01
	.byte $29, $a1, $27, $a1, $25, $95, $24, $95, $25, $89, $24, $a1, $1d, $ad, $20, $95, $00, $89, $21, $95, $00, $89, $42
	.word @song6ch1loop
@song6ch2:
	.byte $c7, $4e, $05, $92, $01, $89, $02, $89
@song6ch2loop:
@song6ref336:
	.byte $03, $95, $00, $89, $0a, $89, $00, $95, $0d, $95, $00, $ad, $0a, $89, $0d, $89, $00, $89, $0a, $89, $01, $95, $00, $89
	.byte $05, $89, $00, $95, $0c, $95, $00, $ad, $08, $89, $0c, $89, $00, $89, $05, $89
	.byte $41, $28
	.word @song6ref336
	.byte $41, $28
	.word @song6ref336
	.byte $42
	.word @song6ch2loop
@song6ch3:
	.byte $88, $1b, $89, $1b, $95, $1b, $89, $1b, $95, $84, $31, $89, $80, $31, $89
@song6ch3loop:
@song6ref401:
	.byte $84, $31, $89, $80, $31, $89, $31, $89, $31, $89, $88, $1b, $95, $80, $31, $89, $31, $89
	.byte $41, $0e
	.word @song6ref401
	.byte $41, $0c
	.word @song6ref401
@song6ref425:
	.byte $88, $1b, $89, $84, $31, $89, $88, $1b, $89, $80, $31, $89, $31, $89, $88, $1b, $95, $80, $31, $89, $31, $89
	.byte $41, $0e
	.word @song6ref401
	.byte $41, $0e
	.word @song6ref401
	.byte $41, $0c
	.word @song6ref401
	.byte $41, $10
	.word @song6ref425
	.byte $41, $0e
	.word @song6ref401
	.byte $41, $0e
	.word @song6ref401
	.byte $41, $0c
	.word @song6ref401
	.byte $41, $10
	.word @song6ref425
	.byte $42
	.word @song6ch3loop
@song6ch4:
	.byte $0a, $89, $0a, $89, $00, $89, $0a, $89, $0a, $89, $00, $89, $0a, $89, $00, $89
@song6ch4loop:
@song6ref491:
	.byte $0a, $95, $00, $95, $0a, $95, $00, $95, $0a, $95, $00, $95, $0a, $95, $00, $95, $0a, $95
@song6ref509:
	.byte $00, $95, $0a, $95, $0a, $89, $0a, $95, $0a, $95, $00, $89
	.byte $41, $16
	.word @song6ref491
	.byte $41, $0c
	.word @song6ref509
	.byte $41, $16
	.word @song6ref491
	.byte $41, $0c
	.word @song6ref509
	.byte $0a, $95, $00, $95, $42
	.word @song6ch4loop
@song6ch5:
	.byte $df
@song6ch5loop:
@song6ref542:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $42
	.word @song6ch5loop
@song6ch6:
	.byte $df
@song6ch6loop:
	.byte $41, $0c
	.word @song6ref542
	.byte $42
	.word @song6ch6loop
@song7ch0:
	.byte $7a, $9e, $22, $83, $23, $83, $24, $83, $aa, $21, $b3, $48, $7b, $a0, $1b, $8f, $22, $a1, $22, $8f, $22, $95, $20, $95
	.byte $1b, $95, $9e, $1f, $8f, $1c, $a1, $1c, $8f, $18, $b3
@song7ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $c7, $42
	.word @song7ch0loop
@song7ch1:
	.byte $c7, $7b, $a4, $24, $8f, $2a, $a1, $2a, $8f, $2a, $95, $29, $95, $27, $95, $25, $fb
@song7ch1loop:
	.byte $c7, $42
	.word @song7ch1loop
@song7ch2:
	.byte $c7, $9a, $14, $a1, $20, $a1, $14, $a1, $20, $a1, $0d, $a1, $19, $a1, $0d, $a1, $00, $8f
@song7ch2loop:
	.byte $c7, $42
	.word @song7ch2loop
@song7ch3:
	.byte $c7, $ff, $ff, $8d
@song7ch3loop:
	.byte $c7, $42
	.word @song7ch3loop
@song7ch4:
	.byte $c7, $ff, $ff, $8d
@song7ch4loop:
	.byte $c7, $42
	.word @song7ch4loop
@song7ch5:
	.byte $c7, $ff, $ff, $8d
@song7ch5loop:
	.byte $c7, $42
	.word @song7ch5loop
@song7ch6:
	.byte $c7, $ff, $ff, $8d
@song7ch6loop:
	.byte $c7, $42
	.word @song7ch6loop
@song8ch0:
	.byte $7c, $9a, $1d, $91, $00, $a5, $19, $8f, $00, $a5, $14, $a3, $1e, $cb, $1b, $cb, $1d, $91, $1b, $91, $1d, $f1, $00, $a5
@song8ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $c7, $42
	.word @song8ch0loop
@song8ch1:
@song8ref33:
	.byte $7c, $9a, $25, $91, $00, $a5, $20, $8f, $00, $a5, $1d, $a3, $22, $97, $24, $97, $22, $97, $21, $97, $23, $97, $21, $97
	.byte $20, $ff, $c1
@song8ch1loop:
	.byte $c7, $42
	.word @song8ch1loop
@song8ch2:
	.byte $41, $0a
	.word @song8ref33
	.byte $1e, $cb, $1b, $cb, $25, $ff, $c1
@song8ch2loop:
	.byte $c7, $42
	.word @song8ch2loop
@song8ch3:
	.byte $ff, $ff, $ff, $fb
@song8ch3loop:
	.byte $c7, $42
	.word @song8ch3loop
@song8ch4:
	.byte $ff, $ff, $ff, $fb
@song8ch4loop:
	.byte $c7, $42
	.word @song8ch4loop
@song8ch5:
	.byte $ff, $ff, $ff, $fb
@song8ch5loop:
	.byte $c7, $42
	.word @song8ch5loop
@song8ch6:
	.byte $ff, $ff, $ff, $fb
@song8ch6loop:
	.byte $c7, $42
	.word @song8ch6loop
@song9ch0:
	.byte $9a, $20, $95, $1f, $95, $20, $95
@song9ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song9ref12:
	.byte $1d, $ad, $00, $95, $1e, $ad, $00, $95, $1f, $ad, $00, $89, $20, $ad, $00, $95, $20, $89, $22, $89, $00, $95, $24, $89
	.byte $00, $95, $25, $89, $00, $b9, $1d, $ad, $00, $89, $1b, $ad, $00, $a1, $48
	.byte $41, $1e
	.word @song9ref12
	.byte $29, $ad, $00, $89, $27, $ad, $00, $a1, $48, $29, $ad, $00, $95, $2a, $ad, $00, $95, $2b, $ad, $00, $89, $2c, $ad, $00
	.byte $95, $2c, $89, $2e, $89, $00, $95, $30, $89, $00, $95, $31, $89, $00, $b9, $35, $ad, $00, $89, $33, $ad, $00, $a1, $48
	.byte $31, $89, $00, $b9, $31, $89, $00, $ad, $34, $ad, $33, $89, $00, $95, $31, $89, $00, $95, $2e, $89, $00, $95, $31, $89
	.byte $00, $ad, $33, $89, $00, $a1, $31, $89, $00, $ff, $a5, $42
	.word @song9ch0loop
@song9ch1:
	.byte $c7
@song9ch1loop:
	.byte $9a
@song9ref143:
	.byte $14, $ad, $00, $95, $16, $ad, $00, $95, $17, $ad, $00, $89, $18, $ad, $00, $95, $18, $89, $19, $89, $00, $95, $1b, $89
	.byte $00, $95, $1d, $89, $00, $b9, $14, $ad, $00, $89, $12, $ad, $00, $a1
	.byte $41, $1e
	.word @song9ref143
	.byte $20, $ad, $00, $89, $1e, $ad, $00, $a1, $20, $ad, $00, $95, $22, $ad, $00, $95, $23, $ad, $00, $89, $24, $ad, $00, $95
	.byte $24, $89, $25, $89, $00, $95, $27, $89, $00, $95, $29, $89, $00, $b9, $2c, $ad, $00, $89, $2a, $ad, $00, $a1, $2c, $89
	.byte $00, $b9, $2c, $89, $00, $ad, $2c, $ad, $2a, $89, $00, $95, $29, $89, $00, $95, $25, $89, $00, $95, $29, $89, $00, $ad
	.byte $2a, $89, $00, $a1, $29, $89, $00, $ff, $a5, $42
	.word @song9ch1loop
@song9ch2:
	.byte $9a, $14, $c5
@song9ch2loop:
	.byte $a4
@song9ref273:
	.byte $19, $a1, $25, $a1, $19, $a1, $25, $a1
	.byte $41, $08
	.word @song9ref273
	.byte $41, $08
	.word @song9ref273
	.byte $41, $08
	.word @song9ref273
	.byte $00
	.byte $41, $08
	.word @song9ref273
	.byte $41, $08
	.word @song9ref273
	.byte $41, $08
	.word @song9ref273
	.byte $1d, $a1, $29, $a1, $1d, $a1, $29, $9f
@song9ref308:
	.byte $0d, $a1, $19, $a1, $0d, $a1, $19, $a1
	.byte $41, $08
	.word @song9ref308
	.byte $41, $08
	.word @song9ref308
	.byte $11, $a1, $1d, $a1, $11, $a1, $1d, $a1, $12, $a1, $1e, $a1, $12, $a1, $1e, $a1, $14, $a1, $20, $a1, $14, $a1, $20, $a1
	.byte $0d, $a1, $00, $95, $0f, $a1, $00, $89, $0d, $a1, $00, $95, $0b, $89, $17, $a1, $0c, $a1, $18, $a1, $42
	.word @song9ch2loop
@song9ch3:
	.byte $c7
@song9ch3loop:
	.byte $75
@song9ref372:
	.byte $90, $14, $83, $00, $9b, $8e
@song9ref378:
	.byte $20, $95
@song9ref380:
	.byte $20, $89, $90, $20, $a1, $8e, $20, $95, $20, $89
	.byte $41, $0e
	.word @song9ref372
	.byte $41, $0e
	.word @song9ref372
	.byte $41, $0e
	.word @song9ref372
	.byte $41, $0e
	.word @song9ref372
	.byte $41, $0e
	.word @song9ref372
	.byte $41, $0e
	.word @song9ref372
	.byte $41, $0e
	.word @song9ref372
	.byte $41, $0e
	.word @song9ref372
	.byte $41, $0e
	.word @song9ref372
	.byte $41, $0e
	.word @song9ref372
	.byte $41, $0e
	.word @song9ref372
	.byte $41, $0e
	.word @song9ref372
	.byte $41, $0e
	.word @song9ref372
	.byte $90, $20, $a1, $8e, $20, $95, $90, $20, $a1, $8e
	.byte $41, $08
	.word @song9ref380
	.byte $41, $0a
	.word @song9ref378
	.byte $42
	.word @song9ch3loop
@song9ch4:
	.byte $c7
@song9ch4loop:
@song9ref450:
	.byte $ff, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $ff, $bf
	.byte $41, $0a
	.word @song9ref450
	.byte $42
	.word @song9ch4loop
@song9ch5:
	.byte $c7
@song9ch5loop:
	.byte $41, $0a
	.word @song9ref450
	.byte $41, $0a
	.word @song9ref450
	.byte $42
	.word @song9ch5loop
@song9ch6:
	.byte $c7
@song9ch6loop:
	.byte $41, $0a
	.word @song9ref450
	.byte $41, $0a
	.word @song9ref450
	.byte $42
	.word @song9ch6loop
@song10ch0:
	.byte $7c, $9a, $1d, $8f, $00, $a1, $19, $8f, $00, $a1, $14, $a1, $1e, $c5, $1b, $c5, $1d, $8f, $1b, $8f, $1d, $e9, $00, $ff
	.byte $ff, $ff, $83
@song10ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $c7, $42
	.word @song10ch0loop
@song10ch1:
	.byte $7c, $9a, $25, $8f, $00, $a1, $20, $8f, $00, $a1, $1d, $a1, $21, $95, $23, $95, $21, $95, $20, $95, $22, $95, $20, $95
	.byte $20, $ff, $ff, $ff, $ff, $93
@song10ch1loop:
	.byte $c7, $42
	.word @song10ch1loop
@song10ch2:
	.byte $9a, $0d, $a1, $19, $a1, $0d, $a1, $19, $a1, $15, $a1, $21, $a1, $17, $a1, $23, $a1, $25, $ff, $ff, $ff, $ff, $93
@song10ch2loop:
	.byte $c7, $42
	.word @song10ch2loop
@song10ch3:
	.byte $8e
@song10ref100:
	.byte $20, $a1, $20, $8f, $20, $a1, $20, $8f, $20, $a1, $7b, $a8, $1a, $89, $00, $89, $74, $1a, $95, $75, $19, $83, $74, $00
	.byte $8f, $19, $8f, $73, $17, $8f, $17, $8f, $74, $17, $8f, $7f, $8e, $20, $a1, $20, $8f, $20, $a1, $20, $8f, $20, $8f, $20
	.byte $8f
	.byte $41, $21
	.word @song10ref100
	.byte $ad
@song10ch3loop:
	.byte $c7, $42
	.word @song10ch3loop
@song10ch4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $b5
@song10ch4loop:
	.byte $c7, $42
	.word @song10ch4loop
@song10ch5:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $b5
@song10ch5loop:
	.byte $c7, $42
	.word @song10ch5loop
@song10ch6:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $b5
@song10ch6loop:
	.byte $c7, $42
	.word @song10ch6loop
@song11ch0:
	.byte $9a, $14, $85, $00, $85, $19, $85, $00, $85, $1d, $85, $00, $85, $20, $85, $00, $85, $25, $85, $00, $85, $29, $85, $00
	.byte $85, $2c, $a5, $00, $85, $29, $a5
@song11ref32:
	.byte $00, $85, $15, $85, $00, $85, $19, $85, $00, $85, $1c, $85, $00, $85, $21, $85, $00, $85, $25, $85, $00, $85, $28, $85
	.byte $00, $85, $2d, $a5, $00, $85, $28, $a5, $00, $85, $48
@song11ref67:
	.byte $17, $85, $00, $85, $1b, $85, $00, $85, $1e, $85, $00, $85, $23, $85, $00, $85, $27, $85, $00, $85, $2a, $85, $00, $85
	.byte $2f, $ad, $2f, $85, $00, $85, $2f, $85, $00, $85, $2f, $85, $00, $85, $29, $c5, $00, $f5
@song11ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $bf, $42
	.word @song11ch0loop
@song11ch1:
	.byte $8f, $9a, $11, $83, $00, $87, $14, $83, $00, $87, $19, $83, $00, $87, $1d, $83, $00, $87, $20, $83, $00, $87, $25, $a5
	.byte $00, $85, $20, $a5, $00, $95, $10, $85
	.byte $41, $13
	.word @song11ref32
	.byte $a5, $00, $85, $21, $a5, $00, $85, $8f, $12, $85, $00, $85
	.byte $41, $10
	.word @song11ref67
	.byte $2a, $ad, $2a, $85, $00, $85, $2a, $85, $00, $85, $2a, $85, $00, $85, $31, $c5, $00, $f5
@song11ch1loop:
	.byte $ff, $bf, $42
	.word @song11ch1loop
@song11ch2:
	.byte $a4, $0d, $ad, $19, $ad, $0d, $ad, $19, $ad, $09, $ad, $15, $ad, $09, $ad, $15, $ad, $0b, $ad, $17, $ad, $0b, $ad, $17
	.byte $ad, $9a, $0d, $dd, $00, $dd
@song11ch2loop:
	.byte $ff, $bf, $42
	.word @song11ch2loop
@song11ch3:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch3loop:
	.byte $ff, $bf, $42
	.word @song11ch3loop
@song11ch4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch4loop:
	.byte $ff, $bf, $42
	.word @song11ch4loop
@song11ch5:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch5loop:
	.byte $ff, $bf, $42
	.word @song11ch5loop
@song11ch6:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch6loop:
	.byte $ff, $bf, $42
	.word @song11ch6loop
@song12ch0:
	.byte $9a, $11, $83, $00, $83, $21, $89, $00, $89, $21, $89, $21, $89, $00, $89, $12, $89, $22, $89, $00, $89, $22, $89, $22
	.byte $89, $00, $89, $13, $89, $23, $89, $00, $89, $23, $89, $23, $89, $00, $89, $24, $89, $00, $89, $24, $dd
@song12ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $00, $89, $42
	.word @song12ch0loop
@song12ch1:
	.byte $9a, $1d, $89, $27, $95, $27, $89, $27, $95, $1e, $89, $28, $95, $28, $89, $28, $95, $1f, $89, $29, $95, $29, $89, $29
	.byte $95, $2a, $95, $2a, $dd
@song12ch1loop:
	.byte $00, $89, $42
	.word @song12ch1loop
@song12ch2:
	.byte $ae, $24, $89, $30, $95, $30, $89, $30, $95, $25, $89, $31, $95, $31, $89, $31, $95, $26, $89, $32, $95, $32, $89, $32
	.byte $95, $20, $95, $82, $20, $dd
@song12ch2loop:
	.byte $00, $89, $42
	.word @song12ch2loop
@song12ch3:
	.byte $ff, $ff, $cf
@song12ch3loop:
	.byte $8b, $42
	.word @song12ch3loop
@song12ch4:
	.byte $ff, $ff, $cf
@song12ch4loop:
	.byte $8b, $42
	.word @song12ch4loop
@song12ch5:
	.byte $ff, $ff, $cf
@song12ch5loop:
	.byte $8b, $42
	.word @song12ch5loop
@song12ch6:
	.byte $ff, $ff, $cf
@song12ch6loop:
	.byte $8b, $42
	.word @song12ch6loop
@song13ch0:
@song13ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song13ref5:
	.byte $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48
	.byte $ff, $ff, $bf, $48, $ff, $ff, $bf, $48
	.byte $41, $18
	.word @song13ref5
	.byte $42
	.word @song13ch0loop
@song13ch1:
@song13ch1loop:
@song13ref44:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $18
	.word @song13ref44
	.byte $42
	.word @song13ch1loop
@song13ch2:
@song13ch2loop:
	.byte $41, $18
	.word @song13ref44
	.byte $41, $18
	.word @song13ref44
	.byte $42
	.word @song13ch2loop
@song13ch3:
@song13ch3loop:
	.byte $41, $18
	.word @song13ref44
	.byte $41, $18
	.word @song13ref44
	.byte $42
	.word @song13ch3loop
@song13ch4:
@song13ch4loop:
	.byte $41, $18
	.word @song13ref44
	.byte $41, $18
	.word @song13ref44
	.byte $42
	.word @song13ch4loop
@song13ch5:
@song13ch5loop:
	.byte $41, $18
	.word @song13ref44
	.byte $41, $18
	.word @song13ref44
	.byte $42
	.word @song13ch5loop
@song13ch6:
@song13ch6loop:
	.byte $41, $18
	.word @song13ref44
	.byte $41, $18
	.word @song13ref44
	.byte $42
	.word @song13ch6loop
