; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_victory=music_data_victory
.endif

music_data_victory:
	.byte 1
	.word @instruments
	.word @samples-5
; 00 : Victory
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_victory
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env4,@env1,@env5,@env0 ; 00 : Long instrumental
	.word @env6,@env1,@env3,@env0 ; 01 : Death instrument

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$7f,$00,$01
@env2:
	.byte $7f,$00,$00
@env3:
	.byte $c2,$7f,$00,$00
@env4:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env5:
	.byte $c0,$c2,$00,$01
@env6:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c6,$c5,$c3,$c2,$c1,$c0,$00,$0c

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $80, $14, $85, $00, $85, $19, $85, $00, $85, $1d, $85, $00, $85, $20, $85, $00, $85, $25, $85, $00, $85, $29, $85, $00
	.byte $85, $2c, $a5, $00, $85, $29, $a5
@song0ref32:
	.byte $00, $85, $15, $85, $00, $85, $19, $85, $00, $85, $1c, $85, $00, $85, $21, $85, $00, $85, $25, $85, $00, $85, $28, $85
	.byte $00, $85, $2d, $a5, $00, $85, $28, $a5, $00, $85, $48
@song0ref67:
	.byte $17, $85, $00, $85, $1b, $85, $00, $85, $1e, $85, $00, $85, $23, $85, $00, $85, $27, $85, $00, $85, $2a, $85, $00, $85
	.byte $2f, $ad, $2f, $85, $00, $85, $2f, $85, $00, $85, $2f, $85, $00, $85, $29, $c5, $00, $f5
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $bf, $42
	.word @song0ch0loop
@song0ch1:
	.byte $8f, $80, $11, $83, $00, $87, $14, $83, $00, $87, $19, $83, $00, $87, $1d, $83, $00, $87, $20, $83, $00, $87, $25, $a5
	.byte $00, $85, $20, $a5, $00, $95, $10, $85
	.byte $41, $13
	.word @song0ref32
	.byte $a5, $00, $85, $21, $a5, $00, $85, $8f, $12, $85, $00, $85
	.byte $41, $10
	.word @song0ref67
	.byte $2a, $ad, $2a, $85, $00, $85, $2a, $85, $00, $85, $2a, $85, $00, $85, $31, $c5, $00, $f5
@song0ch1loop:
	.byte $ff, $bf, $42
	.word @song0ch1loop
@song0ch2:
	.byte $82, $0d, $ad, $19, $ad, $0d, $ad, $19, $ad, $09, $ad, $15, $ad, $09, $ad, $15, $ad, $0b, $ad, $17, $ad, $0b, $ad, $17
	.byte $ad, $80, $0d, $dd, $00, $dd
@song0ch2loop:
	.byte $ff, $bf, $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song0ch3loop:
	.byte $ff, $bf, $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song0ch4loop:
	.byte $ff, $bf, $42
	.word @song0ch4loop
@song0ch5:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song0ch5loop:
	.byte $ff, $bf, $42
	.word @song0ch5loop
@song0ch6:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song0ch6loop:
	.byte $ff, $bf, $42
	.word @song0ch6loop
