; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_death=music_data_death
.endif

music_data_death:
	.byte 1
	.word @instruments
	.word @samples-5
; 00 : Death
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_death
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env8,@env2,@env6,@env0 ; 00 : Death effect
	.word @env4,@env2,@env6,@env0 ; 01 : Death effect 2
	.word @env1,@env3,@env6,@env0 ; 02 : Instrumental 2
	.word @env10,@env3,@env6,@env0 ; 03 : Death instrument
	.word @env7,@env3,@env9,@env0 ; 04 : Long instrumental

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cc,$02,$ca,$c3,$c3,$c2,$c0,$00,$07
@env2:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$0a
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $00,$c8,$c4,$c0,$00,$03
@env5:
	.byte $7f,$00,$00
@env6:
	.byte $c2,$7f,$00,$00
@env7:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env8:
	.byte $00,$ce,$cc,$cb,$ca,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$0b
@env9:
	.byte $c0,$c2,$00,$01
@env10:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c6,$c5,$c3,$c2,$c1,$c0,$00,$0c

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $7a, $80, $22, $83, $23, $83, $24, $83, $82, $21, $b3, $48, $7b, $84, $1b, $8f, $22, $a1, $22, $8f, $22, $95, $20, $95
	.byte $1b, $95, $80, $1f, $8f, $1c, $a1, $1c, $8f, $18, $b3
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $c7, $42
	.word @song0ch0loop
@song0ch1:
	.byte $c7, $7b, $86, $24, $8f, $2a, $a1, $2a, $8f, $2a, $95, $29, $95, $27, $95, $25, $fb
@song0ch1loop:
	.byte $c7, $42
	.word @song0ch1loop
@song0ch2:
	.byte $c7, $88, $14, $a1, $20, $a1, $14, $a1, $20, $a1, $0d, $a1, $19, $a1, $0d, $a1, $00, $8f
@song0ch2loop:
	.byte $c7, $42
	.word @song0ch2loop
@song0ch3:
	.byte $c7, $ff, $ff, $8d
@song0ch3loop:
	.byte $c7, $42
	.word @song0ch3loop
@song0ch4:
	.byte $c7, $ff, $ff, $8d
@song0ch4loop:
	.byte $c7, $42
	.word @song0ch4loop
@song0ch5:
	.byte $c7, $ff, $ff, $8d
@song0ch5loop:
	.byte $c7, $42
	.word @song0ch5loop
@song0ch6:
	.byte $c7, $ff, $ff, $8d
@song0ch6loop:
	.byte $c7, $42
	.word @song0ch6loop
