; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_castleworld=music_data_castleworld
.endif

music_data_castleworld:
	.byte 1
	.word @instruments
	.word @samples-5
; 00 : Castleworld
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_castleworld
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env4,@env6,@env10,@env0 ; 00 : Closed Hat
	.word @env5,@env6,@env10,@env0 ; 01 : 12.5% Pulse
	.word @env5,@env21,@env2,@env3 ; 02 : Bass
	.word @env16,@env8,@env10,@env0 ; 03 : SS Noise snare(D3)
	.word @env20,@env6,@env10,@env0 ; 04 : Open Hat
	.word @env5,@env6,@env1,@env0 ; 05 : Overworld lead
	.word @env5,@env6,@env14,@env0 ; 06 : 25% Pulse
	.word @env19,@env6,@env10,@env0 ; 07 : 08 Crash
	.word @env18,@env6,@env9,@env0 ; 08 : Lead 2
	.word @env5,@env6,@env11,@env0 ; 09 : 50% Pulse
	.word @env12,@env6,@env11,@env0 ; 0a : Instrumental

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c2,$c1,$00,$01
@env2:
	.byte $c2,$c0,$00,$01
@env3:
	.byte $00,$bf,$7f,$00,$02
@env4:
	.byte $00,$cc,$c9,$c4,$c2,$c1,$06,$c0,$00,$07
@env5:
	.byte $00,$cf,$7f,$00,$02
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $00,$bd,$7f,$00,$02
@env8:
	.byte $c0,$c1,$c2,$00,$02
@env9:
	.byte $c3,$c2,$00,$01
@env10:
	.byte $7f,$00,$00
@env11:
	.byte $c2,$7f,$00,$00
@env12:
	.byte $00,$cf,$cf,$cd,$cb,$c9,$c9,$c8,$c6,$c0,$00,$09
@env13:
	.byte $00,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$00,$01
@env14:
	.byte $c1,$7f,$00,$00
@env15:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env16:
	.byte $00,$cf,$c9,$04,$c7,$04,$c5,$04,$c3,$00,$08
@env17:
	.byte $00,$ce,$7f,$00,$02
@env18:
	.byte $00,$cd,$7f,$00,$02
@env19:
	.byte $00,$cf,$ce,$03,$cd,$06,$cc,$cc,$cb,$04,$ca,$03,$c9,$c9,$c8,$02,$c7,$04,$c6,$04,$c5,$c5,$c4,$04,$c3,$02,$c2,$07,$c1,$00,$1c
@env20:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c5,$c4,$c4,$c3,$02,$c2,$06,$c1,$00,$0e
@env21:
	.byte $cc,$c0,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0d,$0d,$40,$01 ; 00 Punch Kick (Pitch:13)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48
	.byte $ff, $ff, $bf, $48, $4e, $fe, $90, $20, $87, $92, $50, $f8, $2c, $2d, $87, $21
@song0ref33:
	.byte $91, $49, .lobyte(@env15), .hibyte(@env15), $a7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $90, $27, $83, $28, $8b
	.byte $49, .lobyte(@env15), .hibyte(@env15), $a7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $90, $29, $87, $00, $9b, $28
	.byte $87, $00, $87, $26, $91, $29, $87, $00, $87, $28, $91, $26, $87, $00, $87, $21, $91, $24, $87, $00, $87, $48, $1e, $87
	.byte $92, $50, $f7, $2a, $2b, $87, $1f
	.byte $41, $0f
	.word @song0ref33
	.byte $2b, $91, $2d, $87, $00, $87, $27, $91, $26, $87, $00, $87, $24, $91, $26, $87, $00, $87, $48, $1c, $87, $92, $50, $f5
	.byte $28, $29, $87, $1d
	.byte $41, $26
	.word @song0ref33
	.byte $41, $11
	.word @song0ref33
	.byte $2c, $87, $00, $87, $28, $91, $26, $87, $00, $87, $24, $91, $21, $87, $00, $87, $48, $8a
@song0ref147:
	.byte $21, $a5, $24, $a5, $26, $91, $24, $87, $00, $87, $26, $87, $00, $87, $27, $83, $8c, $50, $fb, $33, $34, $87, $28, $81
	.byte $49, .lobyte(@env13), .hibyte(@env13), $a7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $27, $87, $00, $87, $26
	.byte $91, $49, .lobyte(@env13), .hibyte(@env13), $93, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $24, $87, $00, $87
	.byte $21, $91, $24, $87, $00, $87, $48, $1f, $a5, $24, $a5, $26, $91, $24, $87, $00, $87, $26, $87, $00, $87, $26, $83, $8c
	.byte $50, $fa, $32, $33, $87, $27, $81, $49, .lobyte(@env13), .hibyte(@env13), $a7, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8a, $26, $87, $00, $87, $24, $91, $49, .lobyte(@env13), .hibyte(@env13), $93, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8a, $21, $87, $00, $87, $1f, $91, $21, $87, $00, $87, $48, $1d, $a5, $24, $a5, $26, $91, $24, $87, $00, $87, $24
	.byte $87, $00, $87, $25, $83, $8c, $50, $fa, $31, $32, $87, $26, $81, $49, .lobyte(@env13), .hibyte(@env13), $a7, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $8a, $24, $87, $00, $87, $21, $91, $49, .lobyte(@env13), .hibyte(@env13), $93, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $8a, $20, $87, $00, $87, $1f, $91, $1d, $87, $00, $87, $48, $1f, $a5, $21, $a5, $23, $91, $24
	.byte $87, $00, $87, $23, $91, $21, $87, $00, $87, $20, $91, $1c, $87, $00, $87, $1c, $87, $00, $87, $27, $87, $28, $97, $8c
	.byte $50, $0c, $34, $31, $8b, $00, $87, $8a, $26, $91, $24, $87, $00, $87, $48
	.byte $41, $7c
	.word @song0ref147
	.byte $28, $91, $2d, $87, $00, $87, $2f, $91, $30, $87, $00, $87, $2d, $87, $00, $87, $26, $87, $27, $97, $8c, $50, $0c, $33
	.byte $30, $8b, $00, $87, $8a, $26, $a5, $48, $94
@song0ref406:
	.byte $28, $87, $21, $87, $27, $87, $21, $87, $26, $87, $21, $87, $27, $87, $21, $87, $28, $87, $21, $87, $29, $87, $21, $87
	.byte $28, $87, $21, $87, $27, $87, $21, $87
	.byte $41, $20
	.word @song0ref406
@song0ref441:
	.byte $48
@song0ref442:
	.byte $26, $87, $1f, $87, $25, $87, $1f, $87, $24, $87, $1f, $87, $25, $87, $1f, $87, $26, $87, $1f, $87, $27, $87, $1f, $87
	.byte $26, $87, $1f, $87, $25, $87, $1f, $87
	.byte $41, $20
	.word @song0ref442
	.byte $48
@song0ref478:
	.byte $26, $87, $1d, $87, $24, $87, $1d, $87, $23, $87, $1d, $87, $21, $87, $1d, $87, $23, $87, $1d, $87, $24, $87, $1d, $87
	.byte $26, $87, $1d, $87, $24, $87, $1d, $87
	.byte $41, $20
	.word @song0ref478
	.byte $41, $20
	.word @song0ref441
	.byte $27, $87, $20, $87, $26, $87, $20, $87, $25, $87, $20, $87, $26, $87, $20, $87, $27, $87, $20, $87, $28, $87, $20, $87
	.byte $27, $87, $20, $87, $26, $87, $20, $87, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref552:
	.byte $4e, $fb, $84, $09, $87, $00, $87, $09, $87, $00, $87, $82, $21, $81, $1c, $18, $21, $1c, $81, $18, $21, $1c, $84, $09
	.byte $87, $00, $9b, $07, $91, $82, $21, $81, $1c, $18, $21, $1c, $81, $18, $21, $1c, $84, $09, $87, $00, $9b, $0c, $87, $00
	.byte $87, $82, $21, $81, $1c, $18, $21, $1c, $81, $18, $21, $1c, $84, $0f, $87, $00, $87, $0e, $91, $0c, $87, $00, $87, $82
	.byte $21, $81, $1c, $18, $21, $1c, $81, $18, $21, $1c, $84, $06, $87, $00, $87, $07, $87, $00, $87, $07, $87, $00, $87, $82
	.byte $1f, $81, $1a, $17, $1f, $1a, $81, $17, $1f, $1a, $84, $07, $87, $00, $9b, $04, $91, $82, $1f, $81, $1a, $17, $1f, $1a
	.byte $81, $17, $1f, $1a, $84, $07, $a5, $04, $91, $82, $1f, $81, $1a, $17, $1f, $1a, $81, $17, $1f, $1a, $84, $09, $91, $03
	.byte $a5, $82, $1f, $81, $1a, $17, $1f, $1a, $81, $17, $1f, $1a, $84, $02, $87, $00, $87, $05, $87, $00, $87, $05, $87, $00
	.byte $87, $82, $21, $81, $1d, $18, $21, $1d, $81, $18, $21, $1d, $84, $05, $87, $00, $9b, $02, $91, $82, $21, $81, $1d, $18
	.byte $21, $1d, $81, $18, $21, $1d, $84, $05, $87, $00, $9b, $05, $87, $00, $87, $82, $21, $81, $1d, $18, $21, $1d, $81, $18
	.byte $21, $1d, $84, $07, $87, $00, $87, $08, $91, $07, $87, $00, $87, $82, $21, $81, $1d, $18, $21, $1d, $81, $18, $21, $1d
	.byte $84, $02, $87, $00, $87, $07, $87, $00, $87, $07, $87, $00, $87, $82, $1f, $81, $1c, $1a, $1f, $1c, $81, $1a, $1f, $1c
	.byte $84, $07, $87, $00, $9b, $07, $87, $00, $87, $82, $1f, $81, $1c, $1a, $1f, $1c
@song0ref832:
	.byte $81, $1a, $1f, $1c, $84, $08, $b9, $82, $20, $81, $1c, $1a, $20, $1c, $81, $1a, $20, $1c, $84, $09, $87, $82, $50, $c5
	.byte $15, $17, $87, $0b, $a5, $20, $81, $1c, $1a, $20, $1c, $81, $1a, $20, $1c, $00, $91
	.byte $41, $fa
	.word @song0ref552
	.byte $41, $22
	.word @song0ref832
	.byte $41, $fa
	.word @song0ref552
	.byte $41, $22
	.word @song0ref832
	.byte $41, $fa
	.word @song0ref552
	.byte $41, $22
	.word @song0ref832
	.byte $41, $fa
	.word @song0ref552
	.byte $41, $22
	.word @song0ref832
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref901:
	.byte $4e, $fc, $84, $09, $87, $00, $87, $09, $87, $00, $87, $21, $87, $00, $87, $09, $87, $00, $9b, $07, $91, $00, $91, $09
	.byte $87, $00, $9b, $0c, $87, $00, $87, $1a, $87, $00, $87, $0f, $87, $00, $87, $0e, $91, $0c, $87, $00, $87, $11, $91, $06
@song0ref949:
	.byte $87, $00, $87, $07, $87, $00, $87, $07, $87, $00, $87, $1f, $87, $00, $87, $07, $87, $00, $9b, $04, $91, $00, $91, $07
	.byte $a5, $04, $91, $1f, $87, $00, $87, $09, $91, $03, $a5, $00, $91, $02, $87, $00, $87, $05, $87, $00, $87, $05, $87, $00
	.byte $87, $1d, $87, $00, $87, $05, $87, $00, $9b, $02, $91, $00, $91, $05, $87, $00, $9b, $05, $87, $00, $9b, $07, $87, $00
	.byte $87, $08, $91, $07, $87, $00, $87, $4e, $fe, $1d, $91, $4e, $fc, $02
	.byte $41, $13
	.word @song0ref949
@song0ref1038:
	.byte $07, $87, $00, $9b, $08, $b9, $00, $91, $09, $87, $82, $50, $c5, $15, $17, $87, $0b, $a5, $00, $a5
	.byte $41, $7f
	.word @song0ref901
	.byte $41, $13
	.word @song0ref949
	.byte $41, $10
	.word @song0ref1038
	.byte $41, $7f
	.word @song0ref901
	.byte $41, $13
	.word @song0ref949
	.byte $41, $10
	.word @song0ref1038
	.byte $41, $7f
	.word @song0ref901
	.byte $41, $13
	.word @song0ref949
	.byte $41, $10
	.word @song0ref1038
	.byte $41, $7f
	.word @song0ref901
	.byte $41, $13
	.word @song0ref949
	.byte $41, $10
	.word @song0ref1038
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $7f, $8e, $31, $91, $31, $ff, $89, $00, $ff, $9d, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $9f
@song0ref1116:
	.byte $71, $82, $31, $8d, $72, $8d, $73, $91, $75, $8f, $77, $8d, $79, $8f, $7a, $8b, $7d, $8b, $70, $81, $7f, $83, $70, $85
	.byte $7f, $83, $70, $85, $7f, $83, $70, $85, $7f, $83, $70, $85, $7f
@song0ref1153:
	.byte $8e, $31, $a5
@song0ref1156:
	.byte $86, $1b, $91, $80, $31, $87, $31, $87, $88, $31, $91, $80, $31, $87, $31, $87, $86, $1b, $91, $80, $31, $87, $31, $87
	.byte $88, $31, $91, $80, $31, $87, $31, $87
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $12
	.word @song0ref1156
	.byte $8e, $31, $91, $31, $ff, $89
	.byte $41, $2c
	.word @song0ref1116
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $12
	.word @song0ref1156
	.byte $41, $1a
	.word @song0ref1153
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $12
	.word @song0ref1156
	.byte $41, $1a
	.word @song0ref1153
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $18
	.word @song0ref1156
	.byte $41, $12
	.word @song0ref1156
	.byte $8e, $31, $91, $31, $ff, $89
	.byte $41, $12
	.word @song0ref1116
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $01, $91, $01, $91, $00, $ff, $ff, $95, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
@song0ref1305:
	.byte $01, $a5, $01, $91, $01, $87, $01, $87, $01, $91, $01, $91, $01, $91, $01, $a5, $01, $91, $01, $91, $01, $87, $01, $87
	.byte $01, $91, $01, $91, $01, $a5
	.byte $41, $1e
	.word @song0ref1305
	.byte $41, $1e
	.word @song0ref1305
	.byte $01, $a5, $00, $ff, $c5
@song0ref1346:
	.byte $01, $81, $00, $83, $01, $81, $00, $83, $01, $81, $00, $83, $01, $81, $00, $83
	.byte $41, $10
	.word @song0ref1346
	.byte $41, $1e
	.word @song0ref1305
	.byte $41, $1e
	.word @song0ref1305
	.byte $41, $1e
	.word @song0ref1305
	.byte $41, $1e
	.word @song0ref1305
	.byte $41, $1e
	.word @song0ref1305
	.byte $41, $1e
	.word @song0ref1305
	.byte $41, $1e
	.word @song0ref1305
	.byte $41, $1e
	.word @song0ref1305
	.byte $41, $1e
	.word @song0ref1305
	.byte $41, $1e
	.word @song0ref1305
	.byte $41, $1e
	.word @song0ref1305
	.byte $01, $91, $01, $91, $00, $ff, $ff, $95, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
@song0ref1410:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0f
	.word @song0ref1410
	.byte $41, $0f
	.word @song0ref1410
	.byte $41, $0f
	.word @song0ref1410
	.byte $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $41, $0f
	.word @song0ref1410
	.byte $41, $0f
	.word @song0ref1410
	.byte $41, $0f
	.word @song0ref1410
	.byte $41, $0f
	.word @song0ref1410
	.byte $42
	.word @song0ch6loop
