; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_underworld=music_data_underworld
.endif

music_data_underworld:
	.byte 1
	.word @instruments
	.word @samples-5
; 00 : Underworld
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_underworld
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env5,@env9,@env0 ; 00 : Closed Hat
	.word @env13,@env7,@env9,@env0 ; 01 : SS Noise snare(D3)
	.word @env15,@env5,@env8,@env0 ; 02 : Lead 2
	.word @env4,@env5,@env10,@env0 ; 03 : 50% Pulse
	.word @env16,@env5,@env9,@env0 ; 04 : 08 Crash
	.word @env17,@env5,@env9,@env0 ; 05 : Open Hat
	.word @env14,@env18,@env2,@env6 ; 06 : DPCM
	.word @env1,@env11,@env9,@env0 ; 07 : Instrument 1
	.word @env4,@env5,@env9,@env0 ; 08 : 12.5% Pulse

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$04,$cb,$c6,$c2,$c0,$00,$06
@env2:
	.byte $c2,$c0,$00,$01
@env3:
	.byte $00,$cc,$c9,$c4,$c2,$c1,$06,$c0,$00,$07
@env4:
	.byte $00,$cf,$7f,$00,$02
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $00,$bd,$7f,$00,$02
@env7:
	.byte $c0,$c1,$c2,$00,$02
@env8:
	.byte $c3,$c2,$00,$01
@env9:
	.byte $7f,$00,$00
@env10:
	.byte $c2,$7f,$00,$00
@env11:
	.byte $c0,$bc,$b4,$a8,$00,$03
@env12:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env13:
	.byte $00,$cf,$c9,$04,$c7,$04,$c5,$04,$c3,$00,$08
@env14:
	.byte $00,$ce,$7f,$00,$02
@env15:
	.byte $00,$cd,$7f,$00,$02
@env16:
	.byte $00,$cf,$ce,$03,$cd,$06,$cc,$cc,$cb,$04,$ca,$03,$c9,$c9,$c8,$02,$c7,$04,$c6,$04,$c5,$c5,$c4,$04,$c3,$02,$c2,$07,$c1,$00,$1c
@env17:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c5,$c4,$c4,$c3,$02,$c2,$06,$c1,$00,$0e
@env18:
	.byte $cc,$c0,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e5,$09,$40,$00 ; 00 bass (Pitch:9)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e5,$0a,$40,$00 ; 01 bass (Pitch:10)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e5,$0c,$40,$00 ; 02 bass (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e5,$0e,$40,$00 ; 03 bass (Pitch:14)
	.byte $3a+.lobyte(FAMISTUDIO_DPCM_PTR),$da,$08,$40,$00 ; 04 bass 2 (Pitch:8)
	.byte $3a+.lobyte(FAMISTUDIO_DPCM_PTR),$da,$09,$40,$00 ; 05 bass 2 (Pitch:9)
	.byte $3a+.lobyte(FAMISTUDIO_DPCM_PTR),$da,$0b,$40,$00 ; 06 bass 2 (Pitch:11)
	.byte $3a+.lobyte(FAMISTUDIO_DPCM_PTR),$da,$0c,$40,$00 ; 07 bass 2 (Pitch:12)
	.byte $3a+.lobyte(FAMISTUDIO_DPCM_PTR),$da,$0d,$40,$00 ; 08 bass 2 (Pitch:13)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $99, $48, $ff, $ff, $99, $48, $ff, $ff, $99, $48
	.byte $ff, $ff, $99, $48, $7b, $4e, $01, $49, .lobyte(@env0), .hibyte(@env0), $4a, $84
@song0ref29:
	.byte $2c, $a1, $2a, $89, $00, $95, $2e, $87, $86, $50, $fb, $3a, $3b, $83, $2f, $8f, $84, $2c, $89, $00, $89, $32, $a1, $33
	.byte $89, $32, $93, $2f, $89, $2c, $89, $2a, $89, $2c, $89, $26, $95, $00, $87, $48, $24, $85, $86, $50, $fa, $30, $31, $87
	.byte $25, $8f, $84, $23, $89, $00, $95, $25, $93, $23, $89, $26, $95, $25, $a1, $23, $89, $20, $87, $00, $95, $1e, $89, $00
	.byte $95, $1f, $9f, $48, $20, $a1, $1e, $89, $00, $89, $20, $9f, $25, $89, $26, $89, $00, $95, $25, $a1, $28, $87, $00, $95
	.byte $2a, $a1, $2c, $89, $86, $50, $0c, $38, $32, $93, $48, $84, $26, $89, $00, $89, $26, $89, $25, $89, $00, $89, $26, $89
	.byte $20, $89, $1e, $87, $20, $89, $23, $89, $25, $89, $26, $89, $27, $89, $23, $89, $20, $89, $27, $87, $20, $89, $27, $89
	.byte $2a, $89, $00, $95, $2b, $89, $00, $93, $48, $4e, $01, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $41, $86
	.word @song0ref29
	.byte $48, $7d, $2c, $89, $00, $89, $72, $2c, $87, $00, $75, $2c, $89, $00, $db, $7d, $2f, $89, $00, $89, $72, $2f, $87, $00
	.byte $75, $2f, $87, $00, $db, $48, $7d, $2e, $89, $00, $89, $72, $2e, $87, $00, $75, $2e, $89, $00, $db, $7d, $2d, $89, $00
	.byte $89, $72, $2d, $87, $00, $75, $2d, $87, $00, $db, $48, $7f, $a3, $26, $89, $86, $50, $fd, $32, $33, $95, $27, $93, $49
	.byte .lobyte(@env12), .hibyte(@env12), $d3, $49, .lobyte(@env0), .hibyte(@env0), $4a, $84, $23, $87, $00, $95, $22, $a1
	.byte $20, $89, $00, $89, $22, $87, $48, $97, $23, $89, $20, $95, $49, .lobyte(@env12), .hibyte(@env12), $d1, $86, $50, $18
	.byte $2c, $1e, $bd, $7e, $81, $7d, $81, $7c, $81, $7f, $12, $89, $00, $89, $84, $13, $ab, $48, $7b, $4e, $01, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a
	.byte $41, $86
	.word @song0ref29
	.byte $48, $79, $4f, $02, $90
@song0ref329:
	.byte $2c, $89, $00, $89, $74, $2c, $89, $79, $38, $89, $00, $89, $74, $38, $89, $79, $4f, $02, $2c, $89, $00, $87, $74, $2c
	.byte $89, $79, $38, $89, $00, $89, $74, $38, $89, $79, $4f, $02, $2b, $89, $00, $89, $74, $2b, $89, $79, $37, $87, $00, $89
	.byte $74, $37, $89, $79, $4f, $02, $2b, $89, $00, $89, $74, $2b, $89, $79, $37, $89, $00, $89, $74, $37, $87, $48, $79, $4f
	.byte $02, $28, $89, $00, $89, $74, $28, $89, $79, $34, $89, $00, $89, $74, $34, $89, $79, $4f, $02, $28, $89, $00, $87, $74
	.byte $28, $89, $79, $34, $89, $00, $89, $74, $34, $89, $79, $4f, $02, $27, $89, $00, $89, $74, $27, $89, $79, $33, $87, $00
	.byte $89, $74, $33, $89, $79, $4f, $02, $2a, $89, $00, $89, $74, $2a, $89, $79, $37, $89, $00, $89, $74, $37, $87, $48, $79
	.byte $4f, $02
	.byte $41, $30
	.word @song0ref329
	.byte $48, $00, $ff, $ff, $97, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref487:
	.byte $ff
@song0ref488:
	.byte $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $ff, $d3, $7a, $8c
@song0ref512:
	.byte $06, $89, $00, $89, $07, $ab, $4e, $07
@song0ref520:
	.byte $08, $a1, $00, $95, $08, $89, $14, $89, $00, $93, $12, $95, $14, $89, $00, $95, $08, $89, $0e, $9f, $0d, $a1, $0b, $9f
	.byte $04, $a1, $00, $95, $0d, $9f, $0b, $83, $00, $83, $0d, $89, $00, $89, $0e, $ad, $0d, $87, $00, $89, $0b, $89, $06, $89
	.byte $00, $89, $07, $ab
	.byte $41, $17
	.word @song0ref520
@song0ref575:
	.byte $95, $0d, $87, $0e, $89, $00, $89, $0e, $89, $00, $95, $0e, $89, $00, $93, $08, $89, $0e, $89, $00, $89, $0d, $ad, $0b
	.byte $87, $00, $95, $06, $89, $00, $89, $07, $ab, $00, $ff, $ff, $97, $ff, $ff, $99, $ff, $ff, $99, $ff, $d3
	.byte $41, $3a
	.word @song0ref512
	.byte $41, $17
	.word @song0ref520
	.byte $41, $2c
	.word @song0ref575
	.byte $ff, $99, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $8e
@song0ref636:
	.byte $25, $89, $00, $b9, $25, $89, $00, $b7, $25, $89, $00, $b7, $25, $89, $00, $b7
	.byte $41, $10
	.word @song0ref636
	.byte $41, $10
	.word @song0ref636
	.byte $25, $89, $00, $b9, $25, $89, $00, $ab, $25, $89, $00, $db, $25, $89
@song0ref672:
	.byte $25, $89, $00, $89, $25, $87, $4e, $00
@song0ref680:
	.byte $25, $89, $00, $b9, $25, $89, $00, $b7, $25, $89, $00, $b7, $25, $89, $00, $95
	.byte $41, $16
	.word @song0ref672
	.byte $41, $16
	.word @song0ref672
	.byte $41, $16
	.word @song0ref672
	.byte $41, $16
	.word @song0ref672
	.byte $41, $16
	.word @song0ref672
	.byte $41, $16
	.word @song0ref672
	.byte $41, $16
	.word @song0ref672
	.byte $25, $89, $00, $89, $25, $87, $4e, $07, $8c
@song0ref726:
	.byte $14, $a1, $00, $95, $14, $89, $20, $89, $00, $93, $1e, $95, $20, $89, $00, $95, $14, $89, $1a, $9f, $19, $a1, $17, $9f
	.byte $10, $a1, $00, $95, $19, $9f, $17, $83, $00, $83, $19, $89, $00, $89, $1a, $ad, $19, $87, $00, $89, $17, $89, $12, $89
	.byte $00, $89, $13, $ab
	.byte $41, $17
	.word @song0ref726
	.byte $95, $19, $87, $1a, $89, $00, $89, $1a, $89, $00, $95, $1a, $89, $00, $93, $14, $89, $1a, $89, $00, $89, $19, $ad, $17
	.byte $87, $00, $95, $12, $89, $00, $89, $13, $ab, $4e, $00, $8e
	.byte $41, $10
	.word @song0ref680
	.byte $41, $16
	.word @song0ref672
	.byte $41, $16
	.word @song0ref672
	.byte $41, $16
	.word @song0ref672
	.byte $25, $89, $00, $89, $25, $87
	.byte $41, $10
	.word @song0ref636
	.byte $41, $10
	.word @song0ref636
	.byte $ff, $ff, $99, $ff, $eb, $25, $89, $25, $89, $00, $89, $25, $87, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref858:
	.byte $88, $31, $c5, $80, $31, $93, $00, $ad, $31, $95, $00, $ab, $31, $95, $00, $ab, $31, $95, $00, $ad, $31, $93, $00, $ad
	.byte $31, $95, $00, $ab, $31, $95, $00, $ab, $7b, $31, $89, $31, $89, $31, $89, $8a, $31, $a1, $80, $31, $89, $31, $87, $31
	.byte $89, $8a, $31, $a1, $80, $31, $89, $31, $89, $31, $89, $8a, $31, $9f, $80, $31, $89, $31, $89, $31, $89, $8a, $31, $9f
	.byte $80, $31, $89, $31, $89, $31, $89, $8a, $31, $a1, $80, $31, $89, $31, $87, $31, $89, $8a, $31, $95, $88, $31, $e7, $80
	.byte $31, $89, $82
@song0ref957:
	.byte $1b, $89, $00, $89, $1b, $87
@song0ref963:
	.byte $88, $31, $c5
@song0ref966:
	.byte $82, $1b, $89, $80, $31, $87, $31, $89, $2f, $89, $31, $89, $31, $89, $31, $89, $31, $89, $31, $89, $2f, $87, $31, $89
	.byte $31, $89, $82, $1b, $89, $80, $31, $89, $31, $89, $2f, $89, $31, $87, $82, $1b, $89, $80, $31, $89, $31, $89, $31, $89
	.byte $2f, $89, $31, $89, $31, $89
	.byte $41, $30
	.word @song0ref966
	.byte $41, $30
	.word @song0ref966
	.byte $41, $24
	.word @song0ref966
	.byte $41, $32
	.word @song0ref963
	.byte $41, $30
	.word @song0ref966
	.byte $41, $30
	.word @song0ref966
	.byte $41, $24
	.word @song0ref966
	.byte $88, $31, $c5, $82, $1b, $9f, $00, $e7, $1b, $a1, $00, $9f, $c7, $1b, $9f, $00, $e7, $1b, $a1, $00, $9f, $c7, $1b, $9f
	.byte $00, $e7, $1b, $a1, $00, $9f, $c7, $1b, $9f, $00, $e7, $1b, $85, $00, $81, $1b, $85, $00, $81, $1b, $85, $00, $81
	.byte $41, $38
	.word @song0ref957
	.byte $41, $30
	.word @song0ref966
	.byte $41, $30
	.word @song0ref966
	.byte $41, $24
	.word @song0ref966
	.byte $41, $1e
	.word @song0ref858
	.byte $ff, $ff, $99, $ff, $eb, $31, $89, $82, $1b, $89, $00, $89, $1b, $87, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref1121:
	.byte $02, $a1, $00, $95, $02, $89, $04, $89, $00, $93, $09, $95, $04, $89, $00, $95, $02, $89, $08, $9f, $03, $a1, $07, $9f
	.byte $05, $a1, $00, $95, $03, $9f, $07, $83, $00, $83, $03, $89, $00, $89, $08, $ad, $03, $87, $00, $89, $07, $89, $01, $89
	.byte $00, $89, $06, $ab
	.byte $41, $17
	.word @song0ref1121
@song0ref1176:
	.byte $95, $03, $87, $08, $89, $00, $89, $08, $89, $00, $95, $08, $89, $00, $93, $02, $89, $08, $89, $00, $89, $03, $ad, $07
	.byte $87, $00, $95, $01, $89, $00, $89, $06, $ab
	.byte $41, $34
	.word @song0ref1121
	.byte $41, $17
	.word @song0ref1121
	.byte $41, $21
	.word @song0ref1176
	.byte $41, $34
	.word @song0ref1121
	.byte $41, $17
	.word @song0ref1121
	.byte $41, $21
	.word @song0ref1176
	.byte $41, $34
	.word @song0ref1121
	.byte $41, $17
	.word @song0ref1121
	.byte $41, $21
	.word @song0ref1176
	.byte $41, $34
	.word @song0ref1121
	.byte $41, $17
	.word @song0ref1121
	.byte $41, $21
	.word @song0ref1176
	.byte $41, $34
	.word @song0ref1121
	.byte $41, $17
	.word @song0ref1121
	.byte $41, $21
	.word @song0ref1176
	.byte $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $41, $16
	.word @song0ref487
	.byte $41, $15
	.word @song0ref488
	.byte $41, $15
	.word @song0ref488
	.byte $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $41, $16
	.word @song0ref487
	.byte $41, $15
	.word @song0ref488
	.byte $41, $15
	.word @song0ref488
	.byte $ff, $99, $ff, $ff, $99, $ff, $ff, $99, $42
	.word @song0ch6loop
