; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Arpeggios are used, you must set FAMISTUDIO_USE_ARPEGGIO = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_overworld=music_data_overworld
.endif

music_data_overworld:
	.byte 1
	.word @instruments
	.word @samples-5
; 00 : Overworld
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_overworld
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env23,@env26,@env8,@env13 ; 00 : DPCM
	.word @env11,@env12,@env16,@env0 ; 01 : 12.5% Pulse
	.word @env25,@env12,@env16,@env0 ; 02 : Open Hat
	.word @env10,@env12,@env16,@env0 ; 03 : Closed Hat
	.word @env22,@env15,@env16,@env0 ; 04 : SS Noise snare(D3)
	.word @env11,@env12,@env7,@env0 ; 05 : Overworld lead
	.word @env11,@env12,@env17,@env0 ; 06 : 25% Pulse
	.word @env14,@env12,@env16,@env0 ; 07 : 09 Layered Crash
	.word @env24,@env12,@env16,@env0 ; 08 : 08 Crash

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$bd,$b6,$00,$00
@env2:
	.byte $00,$c0,$b5,$b5,$c0,$cb,$cb,$00,$01
@env3:
	.byte $00,$c0,$ba,$b7,$ba,$c0,$c6,$c9,$c6,$00,$01
@env4:
	.byte $c0,$bd,$ba,$00,$00
@env5:
	.byte $c0,$bd,$b9,$00,$00
@env6:
	.byte $00,$c0,$bd,$bd,$c0,$c3,$c3,$00,$01
@env7:
	.byte $c2,$c1,$00,$01
@env8:
	.byte $c2,$c0,$00,$01
@env9:
	.byte $c0,$bb,$b7,$00,$00
@env10:
	.byte $00,$cc,$c9,$c4,$c2,$c1,$06,$c0,$00,$07
@env11:
	.byte $00,$cf,$7f,$00,$02
@env12:
	.byte $c0,$7f,$00,$01
@env13:
	.byte $00,$bd,$7f,$00,$02
@env14:
	.byte $00,$cf,$cd,$cc,$03,$cb,$02,$ca,$c9,$02,$c8,$c8,$cf,$ce,$cc,$cb,$c9,$03,$c8,$03,$c7,$02,$ce,$cb,$c6,$05,$c5,$c5,$c4,$04,$c3,$02,$c2,$07,$c1,$00,$22
@env15:
	.byte $c0,$c1,$c2,$00,$02
@env16:
	.byte $7f,$00,$00
@env17:
	.byte $c1,$7f,$00,$00
@env18:
	.byte $c0,$bc,$b9,$00,$00
@env19:
	.byte $c0,$bc,$b7,$00,$00
@env20:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env21:
	.byte $00,$c0,$b8,$b8,$c0,$c8,$c8,$00,$01
@env22:
	.byte $00,$cf,$c9,$04,$c7,$04,$c5,$04,$c3,$00,$08
@env23:
	.byte $00,$ce,$7f,$00,$02
@env24:
	.byte $00,$cf,$ce,$03,$cd,$06,$cc,$cc,$cb,$04,$ca,$03,$c9,$c9,$c8,$02,$c7,$04,$c6,$04,$c5,$c5,$c4,$04,$c3,$02,$c2,$07,$c1,$00,$1c
@env25:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c5,$c4,$c4,$c3,$02,$c2,$06,$c1,$00,$0e
@env26:
	.byte $cc,$c0,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0d,$0d,$40,$01 ; 00 Punch Kick (Pitch:13)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48
	.byte $41, $0a
	.word @song0ref5
	.byte $48
	.byte $41, $0a
	.word @song0ref5
	.byte $48
	.byte $41, $0a
	.word @song0ref5
	.byte $48
	.byte $41, $0a
	.word @song0ref5
	.byte $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref48:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $41, $0a
	.word @song0ref48
	.byte $41, $0a
	.word @song0ref48
	.byte $41, $0a
	.word @song0ref48
	.byte $41, $0a
	.word @song0ref48
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $4e, $fc, $80
@song0ref83:
	.byte $0f, $9b, $00, $8d, $1b, $8b, $00, $9b, $0f, $9b, $00, $9b, $0f, $8d, $00, $8b, $1b, $8d, $0f, $8b, $00, $8d, $0f, $85
	.byte $00, $83, $4e, $fc
	.byte $41, $1a
	.word @song0ref83
@song0ref114:
	.byte $08, $9b, $00, $8d, $14, $8b, $00, $9b, $08, $9b, $00, $9b, $08, $8d, $00, $8b, $14, $8d, $08, $8b, $00, $8d, $08, $85
	.byte $00, $83, $0d, $9b, $00, $8d, $19, $8b, $00, $9b, $0d, $9b, $00, $9b, $0d, $8d, $00, $8b, $19, $8d, $0d, $8b, $00, $8d
	.byte $0d, $85, $00, $83, $07, $9b, $00, $8d, $13, $8b, $00, $9b, $07, $9b, $00, $9b, $07, $8d, $00, $8b, $13, $8d, $07, $8b
	.byte $00, $8d, $07, $85, $00, $83, $0c, $9b, $00, $8d, $18, $8b, $00, $9b, $0c, $9b, $00, $9b, $0c, $8d, $00, $8b, $18, $8d
	.byte $0c, $8b, $00, $8d, $0c, $85, $00, $83
@song0ref218:
	.byte $11, $9b, $00, $8d, $1d, $8b, $00, $9b, $11, $9b, $00, $9b, $11, $8d, $00, $8b, $1d, $8d, $11, $8b, $00, $8d, $11, $85
	.byte $00, $83, $0a, $9b, $00, $8d, $16, $8b, $00, $9b, $0a, $9b, $00, $9b, $0a, $8d, $00, $8b, $16, $8d, $0a, $8b, $00, $8d
	.byte $0a, $85, $00, $83, $4e, $fc
	.byte $41, $1a
	.word @song0ref83
	.byte $4e, $fc
	.byte $41, $1a
	.word @song0ref83
	.byte $41, $9c
	.word @song0ref114
	.byte $4e, $fc
	.byte $41, $1a
	.word @song0ref83
	.byte $4e, $fc
	.byte $41, $1a
	.word @song0ref83
	.byte $41, $9c
	.word @song0ref114
	.byte $41, $34
	.word @song0ref114
	.byte $41, $1a
	.word @song0ref218
@song0ref302:
	.byte $ff, $d1, $0d, $89, $00, $81, $0e, $87, $00, $81, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $8e, $31, $d7
@song0ref319:
	.byte $84, $31, $9b
@song0ref322:
	.byte $86, $31, $9b, $84, $31, $9b, $86, $31, $9b, $84, $31, $9b, $86, $31, $9b
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $41, $0c
	.word @song0ref319
	.byte $84, $31, $9b
@song0ref367:
	.byte $8e, $31, $b9
@song0ref370:
	.byte $88, $1b, $9b, $84, $31, $9b, $86, $31, $9b, $84, $31, $9b, $88, $1b, $9b, $84, $31, $9b, $86, $31, $9b, $84, $31, $9b
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $0c
	.word @song0ref370
	.byte $41, $12
	.word @song0ref367
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $10
	.word @song0ref370
	.byte $41, $0c
	.word @song0ref370
	.byte $90, $31, $ff, $b1, $00, $b9, $ff, $ef
	.byte $41, $0a
	.word @song0ref322
	.byte $84, $31, $9b, $86, $31, $9b, $84, $31, $9b, $90, $31, $ff, $b1, $00, $8d, $88, $1b, $81, $00, $81, $1b, $00, $81, $1b
	.byte $85, $00, $85, $1b, $85, $00, $83, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref485:
	.byte $01, $9b, $00, $9b, $01, $9b, $00, $9b, $01, $9b, $00, $9b
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
	.byte $41, $0c
	.word @song0ref485
@song0ref590:
	.byte $01, $9b, $00, $b9, $01, $9b, $00, $b9, $01, $9b, $00, $9b
	.byte $41, $0c
	.word @song0ref590
	.byte $41, $0c
	.word @song0ref485
	.byte $01, $9b, $00, $9b, $01, $9b, $00, $ff, $a3, $01, $81, $00, $81, $01, $00, $81, $01, $8d, $01, $8b, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $4c
	.byte $41, $0a
	.word @song0ref48
	.byte $ff, $ef, $ff, $ef, $ff, $ef
@song0ref642:
	.byte $7e, $4e, $fd, $80
@song0ref646:
	.byte $0f, $9b, $4b, .lobyte(@env9), .hibyte(@env9), $82, $2b, $8d, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80, $1b
	.byte $8b, $00, $8d, $4b, .lobyte(@env9), .hibyte(@env9), $82, $2b, $8b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80
	.byte $0f, $9b, $4b, .lobyte(@env9), .hibyte(@env9), $82, $2b, $9b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80, $0f
	.byte $8d, $4b, .lobyte(@env9), .hibyte(@env9), $82, $2b, $8b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80, $1b, $8d
	.byte $0f, $8b, $4b, .lobyte(@env9), .hibyte(@env9), $82, $2b, $8d, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80, $0f
	.byte $85, $00, $83, $0f, $9b, $4b, .lobyte(@env19), .hibyte(@env19), $82, $29, $8d, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $4c, $80, $1b, $8b, $00, $8d, $4b, .lobyte(@env19), .hibyte(@env19), $82, $29, $8b, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $4c, $80, $0f, $9b, $4b, .lobyte(@env19), .hibyte(@env19), $82, $29, $9b, $4b, .lobyte(@env12), .hibyte(@env12), $4c
	.byte $80, $0f, $8d, $4b, .lobyte(@env19), .hibyte(@env19), $82, $29, $8b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80
	.byte $1b, $8d, $0f, $8b, $4b, .lobyte(@env19), .hibyte(@env19), $82, $29, $8d, $4b, .lobyte(@env12), .hibyte(@env12), $4c
	.byte $80, $0f, $85, $00, $83
@song0ref792:
	.byte $08, $9b, $4b, .lobyte(@env18), .hibyte(@env18), $82, $2b, $8d, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80, $14
	.byte $8b, $00, $8d, $4b, .lobyte(@env18), .hibyte(@env18), $82, $2b, $8b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80
	.byte $08, $9b, $4b, .lobyte(@env18), .hibyte(@env18), $82, $2b, $9b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80, $08
	.byte $8d, $4b, .lobyte(@env18), .hibyte(@env18), $82, $2b, $8b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80, $14, $8d
	.byte $08, $8b, $4b, .lobyte(@env18), .hibyte(@env18), $82, $2b, $8d, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80, $08
	.byte $85, $00, $83, $0d, $9b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $2a, $8d, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $4c, $80, $19, $8b, $00, $8d, $4b, .lobyte(@env5), .hibyte(@env5), $82, $2a, $8b, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $4c, $80, $0d, $9b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $2a, $9b, $4b, .lobyte(@env12), .hibyte(@env12), $4c
	.byte $80, $0d, $8d, $4b, .lobyte(@env5), .hibyte(@env5), $82, $2a, $8b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80
	.byte $19, $8d, $0d, $8b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $2a, $8d, $4b, .lobyte(@env12), .hibyte(@env12), $4c
	.byte $80, $0d, $85, $00, $83, $07, $9b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $29, $8d, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $4c, $80, $13, $8b, $00, $8d, $4b, .lobyte(@env5), .hibyte(@env5), $82, $29, $8b, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $4c, $80, $07, $9b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $29, $9b, $4b, .lobyte(@env12), .hibyte(@env12), $4c
	.byte $80, $07, $8d, $4b, .lobyte(@env5), .hibyte(@env5), $82, $29, $8b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80
	.byte $13, $8d, $07, $8b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $29, $8d, $4b, .lobyte(@env12), .hibyte(@env12), $4c
	.byte $80, $07, $85, $00, $83, $0c, $9b, $4b, .lobyte(@env4), .hibyte(@env4), $82, $28, $8d, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $4c, $80, $18, $8b, $00, $8d, $4b, .lobyte(@env4), .hibyte(@env4), $82, $28, $8b, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $4c, $80, $0c, $9b, $4b, .lobyte(@env4), .hibyte(@env4), $82, $28, $9b, $4b, .lobyte(@env12), .hibyte(@env12), $4c
	.byte $80, $0c, $8d, $4b, .lobyte(@env4), .hibyte(@env4), $82, $28, $8b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80
	.byte $18, $8d, $0c, $8b, $4b, .lobyte(@env4), .hibyte(@env4), $82, $28, $8d, $4b, .lobyte(@env12), .hibyte(@env12), $4c
	.byte $80, $0c, $85, $00, $83, $11, $9b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $27, $8d, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $4c, $80, $1d, $8b, $00, $8d, $4b, .lobyte(@env5), .hibyte(@env5), $82, $27, $8b, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $4c, $80, $11, $9b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $27, $9b, $4b, .lobyte(@env12), .hibyte(@env12), $4c
	.byte $80, $11, $8d, $4b, .lobyte(@env5), .hibyte(@env5), $82, $27, $8b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80
	.byte $1d, $8d, $11, $8b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $27, $8d, $4b, .lobyte(@env12), .hibyte(@env12), $4c
	.byte $80, $11, $85, $00, $83, $0a, $9b, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $8d, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $4c, $80, $16, $8b, $00, $8d, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $8b, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $4c, $80, $0a, $9b, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $9b, $4b, .lobyte(@env12), .hibyte(@env12), $4c
	.byte $80, $0a, $8d, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $8b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80
	.byte $16, $8d, $0a, $8b, $4b, .lobyte(@env1), .hibyte(@env1), $82, $29, $8d, $4b, .lobyte(@env12), .hibyte(@env12), $4c
	.byte $80, $0a, $85, $00, $83, $4e, $fd
	.byte $41, $e0
	.word @song0ref646
	.byte $41, $38
	.word @song0ref792
	.byte $11, $9b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $29, $8d, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80, $1d
	.byte $8b, $00, $8d, $4b, .lobyte(@env5), .hibyte(@env5), $82, $29, $8b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80
	.byte $11, $9b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $29, $9b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80, $11
	.byte $8d, $4b, .lobyte(@env5), .hibyte(@env5), $82, $29, $8b, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80, $1d, $8d
	.byte $11, $8b, $4b, .lobyte(@env5), .hibyte(@env5), $82, $29, $8d, $4b, .lobyte(@env12), .hibyte(@env12), $4c, $80, $11
	.byte $85, $00, $83
	.byte $41, $0a
	.word @song0ref302
	.byte $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $4c
	.byte $41, $e0
	.word @song0ref642
	.byte $4e, $fd, $9d, $8a, $26, $83, $8c, $50, $f4, $32, $33, $83, $27, $9f, $8a, $24, $8b, $22, $9b, $20, $8d, $00, $8b, $1f
	.byte $9b, $1b, $8d, $00, $8b, $1d, $85, $00, $85, $1e, $85, $49, .lobyte(@env2), .hibyte(@env2), $85, $8f, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $8a, $27, $8b, $29, $8d, $27, $8b, $2a, $8d, $00, $8b, $29, $9b, $27, $8d, $00, $8b, $23, $8d
	.byte $22, $8b, $49, .lobyte(@env21), .hibyte(@env21), $9d, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $20, $8d, $00
	.byte $8b, $1b, $9b, $18, $8d, $00, $8b, $1b, $8d, $1d, $8b, $00, $8d, $1e, $85, $8c, $50, $f4, $2a, $2b, $83, $49, .lobyte(@env6)
	.byte .hibyte(@env6), $1f, $9b, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $1d, $8d, $00, $8b, $1b, $8b, $00, $8d, $18
	.byte $85, $00, $85, $1b, $83, $00, $85, $17, $9b, $1b, $8d, $00, $8b, $1d, $8d, $1b, $8b, $00, $8d, $1d, $85, $8c, $50, $f3
	.byte $29, $2a, $83, $49, .lobyte(@env6), .hibyte(@env6), $1e, $9b, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $1d, $8d
	.byte $00, $8b, $17, $95, $00, $83, $16, $85, $00, $85, $17, $83, $00, $85
@song0ref1492:
	.byte $18, $9b, $1b, $8d, $00, $8b, $1f, $9b, $20, $85, $00, $85, $1f, $8b, $49, .lobyte(@env21), .hibyte(@env21), $9d, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $8a, $20, $85, $00, $85, $1f, $8b, $22, $85, $00, $85, $1f, $8b, $20, $85, $00
	.byte $85, $1f, $8b, $00, $8d, $18, $83, $00, $85, $24, $9b, $18, $85, $00, $85, $22, $9b, $18, $83, $00, $85, $20, $9b, $18
	.byte $85, $00, $85, $1f, $9b, $49, .lobyte(@env20), .hibyte(@env20), $9d, $8a, $1e, $83, $1d, $85, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $1b, $ff, $93, $1d, $c9, $1c, $83, $1b, $85, $1a, $9b, $00, $b9, $16, $9b, $1a, $9b, $1d, $8d, $00, $8b, $16, $b9
@song0ref1595:
	.byte $50, $f9, $28, $29, $8d, $8c, $1d, $8b, $49, .lobyte(@env20), .hibyte(@env20), $bb, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8a, $1b, $9b, $49, .lobyte(@env20), .hibyte(@env20), $bb, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $16
	.byte $9b, $00, $9b
	.byte $41, $0c
	.word @song0ref1595
	.byte $1d, $8d, $8c, $50, $f3, $29, $2b, $8b, $1f, $9b, $00, $9b, $8a, $50, $0d, $2b, $29, $8d, $8c, $1d, $8b, $49, .lobyte(@env3)
	.byte .hibyte(@env3), $f7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $d7, $8a, $1b, $8d, $00, $8b, $1a, $8d, $00, $8b
	.byte $16, $8d, $00, $8b, $13, $8d, $00, $8b, $17, $85, $8c, $50, $ee, $23, $24, $85, $18, $8b, $d9, $8a, $1b, $85, $00, $83
	.byte $1d, $85, $00, $85, $1f, $85, $00, $83, $20, $85, $00, $85, $21, $85, $00, $85, $22, $a9, $1b, $8d, $00, $8b, $1d, $85
	.byte $1e, $85, $22, $85, $23, $83, $24, $9b, $27, $85, $00, $85, $24, $85, $00, $83, $1e, $9b, $1d, $9b, $18, $85, $00, $85
	.byte $1a, $81, $1b, $a5, $1d, $8d, $00, $8b, $13, $9b, $14, $8d, $00, $8b, $16, $9b, $18, $85, $00, $85, $16, $99, $1a, $85
	.byte $00, $85, $1b, $9b, $1d, $9b, $1f, $8d, $20, $83, $21, $85, $22, $9b, $27, $85, $00, $85, $26, $9b, $00, $8b, $1f, $9b
	.byte $49, .lobyte(@env21), .hibyte(@env21), $bb, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $1d, $8d, $00, $8b, $16
	.byte $8d, $00, $8b
	.byte $41, $0c
	.word @song0ref1595
	.byte $50, $f6, $22, $23, $8d, $8c, $17, $8b, $49, .lobyte(@env20), .hibyte(@env20), $bb, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8a, $16, $9b, $49, .lobyte(@env20), .hibyte(@env20), $bb, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $14
	.byte $8d, $00, $8b, $16, $8d, $17, $8b
	.byte $41, $3b
	.word @song0ref1492
	.byte $49, .lobyte(@env20), .hibyte(@env20), $a9, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $42
	.word @song0ch6loop
