
.scope piece00
	.include "panicuncut_0_params.inc"
	bits_bank := $00
	slopes_bank := $21
	.segment "BANK_00"
	bits:
		.incbin "panicuncut_0_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panicuncut_0_slopes.bin"
.endscope

.scope piece01
	.include "panicuncut_1_params.inc"
	bits_bank := $01
	slopes_bank := $21
	.segment "BANK_01"
	bits:
		.incbin "panicuncut_1_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panicuncut_1_slopes.bin"
.endscope

.scope piece02
	.include "panicuncut_2_params.inc"
	bits_bank := $02
	slopes_bank := $21
	.segment "BANK_02"
	bits:
		.incbin "panicuncut_2_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panicuncut_2_slopes.bin"
.endscope

.scope piece03
	.include "panicuncut_3_params.inc"
	bits_bank := $03
	slopes_bank := $21
	.segment "BANK_03"
	bits:
		.incbin "panicuncut_3_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panicuncut_3_slopes.bin"
.endscope

.scope piece04
	.include "panicuncut_4_params.inc"
	bits_bank := $04
	slopes_bank := $21
	.segment "BANK_04"
	bits:
		.incbin "panicuncut_4_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panicuncut_4_slopes.bin"
.endscope

.scope piece05
	.include "panicuncut_5_params.inc"
	bits_bank := $05
	slopes_bank := $21
	.segment "BANK_05"
	bits:
		.incbin "panicuncut_5_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panicuncut_5_slopes.bin"
.endscope

.scope piece06
	.include "panicuncut_6_params.inc"
	bits_bank := $06
	slopes_bank := $21
	.segment "BANK_06"
	bits:
		.incbin "panicuncut_6_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panicuncut_6_slopes.bin"
.endscope

.scope piece07
	.include "panicuncut_7_params.inc"
	bits_bank := $07
	slopes_bank := $21
	.segment "BANK_07"
	bits:
		.incbin "panicuncut_7_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panicuncut_7_slopes.bin"
.endscope

.scope piece08
	.include "panicuncut_8_params.inc"
	bits_bank := $08
	slopes_bank := $21
	.segment "BANK_08"
	bits:
		.incbin "panicuncut_8_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panicuncut_8_slopes.bin"
.endscope

.scope piece09
	.include "panicuncut_9_params.inc"
	bits_bank := $09
	slopes_bank := $21
	.segment "BANK_09"
	bits:
		.incbin "panicuncut_9_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panicuncut_9_slopes.bin"
.endscope

.scope piece0a
	.include "panicuncut_10_params.inc"
	bits_bank := $0a
	slopes_bank := $21
	.segment "BANK_0a"
	bits:
		.incbin "panicuncut_10_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panicuncut_10_slopes.bin"
.endscope

.scope piece0b
	.include "panicuncut_11_params.inc"
	bits_bank := $0b
	slopes_bank := $21
	.segment "BANK_0b"
	bits:
		.incbin "panicuncut_11_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panicuncut_11_slopes.bin"
.endscope

.scope piece0c
	.include "panicuncut_12_params.inc"
	bits_bank := $0c
	slopes_bank := $22
	.segment "BANK_0c"
	bits:
		.incbin "panicuncut_12_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_12_slopes.bin"
.endscope

.scope piece0d
	.include "panicuncut_13_params.inc"
	bits_bank := $0d
	slopes_bank := $22
	.segment "BANK_0d"
	bits:
		.incbin "panicuncut_13_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_13_slopes.bin"
.endscope

.scope piece0e
	.include "panicuncut_14_params.inc"
	bits_bank := $0e
	slopes_bank := $22
	.segment "BANK_0e"
	bits:
		.incbin "panicuncut_14_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_14_slopes.bin"
.endscope

.scope piece0f
	.include "panicuncut_15_params.inc"
	bits_bank := $0f
	slopes_bank := $22
	.segment "BANK_0f"
	bits:
		.incbin "panicuncut_15_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_15_slopes.bin"
.endscope

.scope piece10
	.include "panicuncut_16_params.inc"
	bits_bank := $10
	slopes_bank := $22
	.segment "BANK_10"
	bits:
		.incbin "panicuncut_16_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_16_slopes.bin"
.endscope

.scope piece11
	.include "panicuncut_17_params.inc"
	bits_bank := $11
	slopes_bank := $22
	.segment "BANK_11"
	bits:
		.incbin "panicuncut_17_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_17_slopes.bin"
.endscope

.scope piece12
	.include "panicuncut_18_params.inc"
	bits_bank := $12
	slopes_bank := $22
	.segment "BANK_12"
	bits:
		.incbin "panicuncut_18_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_18_slopes.bin"
.endscope

.scope piece13
	.include "panicuncut_19_params.inc"
	bits_bank := $13
	slopes_bank := $22
	.segment "BANK_13"
	bits:
		.incbin "panicuncut_19_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_19_slopes.bin"
.endscope

.scope piece14
	.include "panicuncut_20_params.inc"
	bits_bank := $14
	slopes_bank := $22
	.segment "BANK_14"
	bits:
		.incbin "panicuncut_20_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_20_slopes.bin"
.endscope

.scope piece15
	.include "panicuncut_21_params.inc"
	bits_bank := $15
	slopes_bank := $22
	.segment "BANK_15"
	bits:
		.incbin "panicuncut_21_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_21_slopes.bin"
.endscope

.scope piece16
	.include "panicuncut_22_params.inc"
	bits_bank := $16
	slopes_bank := $22
	.segment "BANK_16"
	bits:
		.incbin "panicuncut_22_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_22_slopes.bin"
.endscope

.scope piece17
	.include "panicuncut_23_params.inc"
	bits_bank := $17
	slopes_bank := $22
	.segment "BANK_17"
	bits:
		.incbin "panicuncut_23_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_23_slopes.bin"
.endscope

.scope piece18
	.include "panicuncut_24_params.inc"
	bits_bank := $18
	slopes_bank := $22
	.segment "BANK_18"
	bits:
		.incbin "panicuncut_24_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_24_slopes.bin"
.endscope

.scope piece19
	.include "panicuncut_25_params.inc"
	bits_bank := $19
	slopes_bank := $22
	.segment "BANK_19"
	bits:
		.incbin "panicuncut_25_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_25_slopes.bin"
.endscope

.scope piece1a
	.include "panicuncut_26_params.inc"
	bits_bank := $1a
	slopes_bank := $22
	.segment "BANK_1a"
	bits:
		.incbin "panicuncut_26_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_26_slopes.bin"
.endscope

.scope piece1b
	.include "panicuncut_27_params.inc"
	bits_bank := $1b
	slopes_bank := $22
	.segment "BANK_1b"
	bits:
		.incbin "panicuncut_27_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panicuncut_27_slopes.bin"
.endscope

.scope piece1c
	.include "panicuncut_28_params.inc"
	bits_bank := $1c
	slopes_bank := $23
	.segment "BANK_1c"
	bits:
		.incbin "panicuncut_28_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "panicuncut_28_slopes.bin"
.endscope

.scope piece1d
	.include "panicuncut_29_params.inc"
	bits_bank := $1d
	slopes_bank := $23
	.segment "BANK_1d"
	bits:
		.incbin "panicuncut_29_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "panicuncut_29_slopes.bin"
.endscope

.scope piece1e
	.include "panicuncut_30_params.inc"
	bits_bank := $1e
	slopes_bank := $23
	.segment "BANK_1e"
	bits:
		.incbin "panicuncut_30_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "panicuncut_30_slopes.bin"
.endscope

.scope piece1f
	.include "panicuncut_31_params.inc"
	bits_bank := $1f
	slopes_bank := $23
	.segment "BANK_1f"
	bits:
		.incbin "panicuncut_31_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "panicuncut_31_slopes.bin"
.endscope

.scope piece20
	.include "panicuncut_32_params.inc"
	bits_bank := $20
	slopes_bank := $23
	.segment "BANK_20"
	bits:
		.incbin "panicuncut_32_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "panicuncut_32_slopes.bin"
.endscope

.scope piece21
	.include "panicuncut_33_params.inc"
	bits_bank := $21
	slopes_bank := $23
	.segment "BANK_21"
	bits:
		.incbin "panicuncut_33_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "panicuncut_33_slopes.bin"
.endscope
