
.scope piece00
	.include "panic_0_params.inc"
	bits_bank := $00
	slopes_bank := $21
	.segment "BANK_00"
	bits:
		.incbin "panic_0_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_0_slopes.bin"
.endscope

.scope piece01
	.include "panic_1_params.inc"
	bits_bank := $01
	slopes_bank := $21
	.segment "BANK_01"
	bits:
		.incbin "panic_1_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_1_slopes.bin"
.endscope

.scope piece02
	.include "panic_2_params.inc"
	bits_bank := $02
	slopes_bank := $21
	.segment "BANK_02"
	bits:
		.incbin "panic_2_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_2_slopes.bin"
.endscope

.scope piece03
	.include "panic_3_params.inc"
	bits_bank := $03
	slopes_bank := $21
	.segment "BANK_03"
	bits:
		.incbin "panic_3_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_3_slopes.bin"
.endscope

.scope piece04
	.include "panic_4_params.inc"
	bits_bank := $04
	slopes_bank := $21
	.segment "BANK_04"
	bits:
		.incbin "panic_4_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_4_slopes.bin"
.endscope

.scope piece05
	.include "panic_5_params.inc"
	bits_bank := $05
	slopes_bank := $21
	.segment "BANK_05"
	bits:
		.incbin "panic_5_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_5_slopes.bin"
.endscope

.scope piece06
	.include "panic_6_params.inc"
	bits_bank := $06
	slopes_bank := $21
	.segment "BANK_06"
	bits:
		.incbin "panic_6_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_6_slopes.bin"
.endscope

.scope piece07
	.include "panic_7_params.inc"
	bits_bank := $07
	slopes_bank := $21
	.segment "BANK_07"
	bits:
		.incbin "panic_7_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_7_slopes.bin"
.endscope

.scope piece08
	.include "panic_8_params.inc"
	bits_bank := $08
	slopes_bank := $21
	.segment "BANK_08"
	bits:
		.incbin "panic_8_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_8_slopes.bin"
.endscope

.scope piece09
	.include "panic_9_params.inc"
	bits_bank := $09
	slopes_bank := $21
	.segment "BANK_09"
	bits:
		.incbin "panic_9_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_9_slopes.bin"
.endscope

.scope piece0a
	.include "panic_10_params.inc"
	bits_bank := $0a
	slopes_bank := $21
	.segment "BANK_0a"
	bits:
		.incbin "panic_10_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_10_slopes.bin"
.endscope

.scope piece0b
	.include "panic_11_params.inc"
	bits_bank := $0b
	slopes_bank := $21
	.segment "BANK_0b"
	bits:
		.incbin "panic_11_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_11_slopes.bin"
.endscope

.scope piece0c
	.include "panic_12_params.inc"
	bits_bank := $0c
	slopes_bank := $22
	.segment "BANK_0c"
	bits:
		.incbin "panic_12_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_12_slopes.bin"
.endscope

.scope piece0d
	.include "panic_13_params.inc"
	bits_bank := $0d
	slopes_bank := $22
	.segment "BANK_0d"
	bits:
		.incbin "panic_13_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_13_slopes.bin"
.endscope

.scope piece0e
	.include "panic_14_params.inc"
	bits_bank := $0e
	slopes_bank := $22
	.segment "BANK_0e"
	bits:
		.incbin "panic_14_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_14_slopes.bin"
.endscope

.scope piece0f
	.include "panic_15_params.inc"
	bits_bank := $0f
	slopes_bank := $22
	.segment "BANK_0f"
	bits:
		.incbin "panic_15_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_15_slopes.bin"
.endscope

.scope piece10
	.include "panic_16_params.inc"
	bits_bank := $10
	slopes_bank := $22
	.segment "BANK_10"
	bits:
		.incbin "panic_16_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_16_slopes.bin"
.endscope

.scope piece11
	.include "panic_17_params.inc"
	bits_bank := $11
	slopes_bank := $22
	.segment "BANK_11"
	bits:
		.incbin "panic_17_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_17_slopes.bin"
.endscope

.scope piece12
	.include "panic_18_params.inc"
	bits_bank := $12
	slopes_bank := $22
	.segment "BANK_12"
	bits:
		.incbin "panic_18_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_18_slopes.bin"
.endscope

.scope piece13
	.include "panic_19_params.inc"
	bits_bank := $13
	slopes_bank := $22
	.segment "BANK_13"
	bits:
		.incbin "panic_19_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_19_slopes.bin"
.endscope

.scope piece14
	.include "panic_20_params.inc"
	bits_bank := $14
	slopes_bank := $22
	.segment "BANK_14"
	bits:
		.incbin "panic_20_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_20_slopes.bin"
.endscope

.scope piece15
	.include "panic_21_params.inc"
	bits_bank := $15
	slopes_bank := $22
	.segment "BANK_15"
	bits:
		.incbin "panic_21_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_21_slopes.bin"
.endscope

.scope piece16
	.include "panic_22_params.inc"
	bits_bank := $16
	slopes_bank := $22
	.segment "BANK_16"
	bits:
		.incbin "panic_22_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_22_slopes.bin"
.endscope

.scope piece17
	.include "panic_23_params.inc"
	bits_bank := $17
	slopes_bank := $22
	.segment "BANK_17"
	bits:
		.incbin "panic_23_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_23_slopes.bin"
.endscope

.scope piece18
	.include "panic_24_params.inc"
	bits_bank := $18
	slopes_bank := $22
	.segment "BANK_18"
	bits:
		.incbin "panic_24_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_24_slopes.bin"
.endscope

.scope piece19
	.include "panic_25_params.inc"
	bits_bank := $19
	slopes_bank := $22
	.segment "BANK_19"
	bits:
		.incbin "panic_25_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_25_slopes.bin"
.endscope

.scope piece1a
	.include "panic_26_params.inc"
	bits_bank := $1a
	slopes_bank := $22
	.segment "BANK_1a"
	bits:
		.incbin "panic_26_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_26_slopes.bin"
.endscope

.scope piece1b
	.include "panic_27_params.inc"
	bits_bank := $1b
	slopes_bank := $22
	.segment "BANK_1b"
	bits:
		.incbin "panic_27_bits.bin"

	.segment "BANK_22"
	slopes:
		.incbin "panic_27_slopes.bin"
.endscope

.scope piece1c
	.include "panic_28_params.inc"
	bits_bank := $1c
	slopes_bank := $23
	.segment "BANK_1c"
	bits:
		.incbin "panic_28_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "panic_28_slopes.bin"
.endscope

.scope piece1d
	.include "panic_29_params.inc"
	bits_bank := $1d
	slopes_bank := $23
	.segment "BANK_1d"
	bits:
		.incbin "panic_29_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "panic_29_slopes.bin"
.endscope

.scope piece1e
	.include "panic_30_params.inc"
	bits_bank := $1e
	slopes_bank := $23
	.segment "BANK_1e"
	bits:
		.incbin "panic_30_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "panic_30_slopes.bin"
.endscope

.scope piece1f
	.include "panic_31_params.inc"
	bits_bank := $1f
	slopes_bank := $23
	.segment "BANK_1f"
	bits:
		.incbin "panic_31_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "panic_31_slopes.bin"
.endscope

.scope piece20
	.include "panic_32_params.inc"
	bits_bank := $20
	slopes_bank := $23
	.segment "BANK_20"
	bits:
		.incbin "panic_32_bits.bin"

	.segment "BANK_23"
	slopes:
		.incbin "panic_32_slopes.bin"
.endscope

.scope piece21
	.include "panic_33_params.inc"
	bits_bank := $21
	slopes_bank := $21
	.segment "BANK_21"
	bits:
		.incbin "panic_33_bits.bin"

	.segment "BANK_21"
	slopes:
		.incbin "panic_33_slopes.bin"
.endscope
